# FlightCtl OpenTelemetry Collector Configuration
# This file is mounted into the container at /root/.flightctl/config.yaml

service:
  logLevel: info

otelCollector:
  otlp:
    endpoint: "0.0.0.0:4317"
    tls:
      certFile: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
      keyFile: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
      clientCAFile: "/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem"
    auth:
      authenticator: "cnauthenticator"
  
  prometheus:
    endpoint: "0.0.0.0:9464"
  
  extensions:
    cnauthenticator:
      printCN: true
      logLevel: "info"
  
  pipelines:
    metrics:
      receivers: ["otlp"]
      processors: ["deviceid", "transform"]
      exporters: ["prometheus"] 