# FlightCtl OpenTelemetry Collector Configuration
# This file is mounted into the container at /root/.flightctl/config.yaml

service:
  logLevel: info

otelCollector:
  otlp:
    endpoint: "0.0.0.0:4317"
    tls:
      certFile: "/etc/otel-collector/certs/server.crt"
      keyFile: "/etc/otel-collector/certs/server.key"
      clientCAFile: "/etc/otel-collector/certs/ca.crt"
    auth:
      authenticator: "cnauthenticator"
  
  prometheus:
    endpoint: "0.0.0.0:9464"
  
  extensions:
    cnauthenticator:
      printCN: true
      logLevel: "info"
  
  pipelines:
    metrics:
      receivers: ["otlp"]
      processors: ["deviceid", "transform"]
      exporters: ["prometheus"] 