apiVersion: v2
name: flightctl
description: A helm chart for flightctl
home: https://github.com/flightctl/flightctl
type: application
version: 0.1.0
appVersion: "latest" # this is replaced at packaging with the hash of the image release
dependencies:
  - name: keycloak
    version: "0.0.1"
    condition: keycloak.enabled
  - name: ui
    condition: ui.enabled
    version: "0.0.1"
  - name: cert-manager
    version: "v1.15.1"
    condition: certManager.enabled
