global:
  auth:
    type: "none"
    oidc:
      oidcAuthority: http://keycloak.flightctl-external.svc.cluster.local:8081/realms/flightctl
  tracing:
    enabled: true
    endpoint: jaeger-collector.flightctl-e2e.svc.cluster.local:4318
    insecure: true
  internalNamespace: flightctl-internal
  storageClassName: standard
  exposeServicesMethod: "nodePort"
  nodePorts:
    api: 3443
    agent: 7443
    db: 5432
    kv: 6379
    alertmanager: 9093
    alertmanagerProxy: 8443
    keycloak: 8081
    prometheus: 9090
    otelCollector: 9464
    gitserver: 3222
    registry: 5000

api:
  image:
    image:  localhost/flightctl-api
    tag: latest
  baseUIUrl: "http://localhost:9000"
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
cliArtifacts:
  enabled: true
  image:
    image: localhost/flightctl-cli-artifacts
    tag: latest
worker:
  image:
    image: localhost/flightctl-worker
    tag: latest
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
periodic:
  image:
    image: localhost/flightctl-periodic
    tag: latest
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
alertExporter:
  image:
    image: localhost/flightctl-alert-exporter
    tag: latest
  env:
    GORM_TRACE_ENFORCE_FATAL: "true"
    GORM_TRACE_INCLUDE_QUERY_VARIABLES: "true"
alertmanagerProxy:
  image:
    image: localhost/flightctl-alertmanager-proxy
    tag: latest
certManager:
  enabled: true
ui:
  enabled: false

dbSetup:
  image:
    image: localhost/flightctl-db-setup
    tag: latest

otelCollector:
  enabled: true
  image:
    image: localhost/flightctl-otel-collector
    tag: latest
  service:
    logLevel: info
  config:
    otlp:
      endpoint: "0.0.0.0:4317"
      tls:
        certFile: "/etc/otel-collector/certs/server.crt"
        keyFile: "/etc/otel-collector/certs/server.key"
        clientCAFile: "/etc/otel-collector/certs/ca.crt"
      auth:
        authenticator: "cnauthenticator"
    prometheus:
      endpoint: "0.0.0.0:9464"
    extensions:
      cnauthenticator:
        printCN: true
        logLevel: "info"
    pipelines:
      metrics:
        receivers: ["otlp"]
        processors: ["deviceid", "transform"]
        exporters: ["prometheus"]
  prometheus:
    enabled: true
    image:
      image: quay.io/prometheus/prometheus
      tag: "v2.54.1"
    config:
      scrape_interval: 15s
      evaluation_interval: 15s
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "500m"
        memory: "512Mi"

keycloak:
  realm:
    redirectUris:
      - /realms/flightctl/account/*
      - http://127.0.0.1/callback
      - http://localhost:9000
      - http://localhost:9000/callback
    webOrigins:
      - http://localhost:9000
