// Code generated by oapi-codegen; DO NOT EDIT.

package imagebuilder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"strings"
	"sync"
	"time"

	ext_66c3f5a7 "github.com/flightctl/flightctl/api/core/v1beta1"
)

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
type APIVersion = string

// #/components/schemas/ResourceKind
// Resource types exposed via the ImageBuilder API.
type ResourceKind string

const (
	ResourceKindImageBuild  ResourceKind = "ImageBuild"
	ResourceKindImageExport ResourceKind = "ImageExport"
)

// #/components/schemas/ImageBuild
// ImageBuild represents a build request for a container image.
type ImageBuild struct {
	APIVersion           string                  `form:"apiVersion" json:"apiVersion"`
	Kind                 string                  `form:"kind" json:"kind"`
	Metadata             ext_66c3f5a7.ObjectMeta `form:"metadata" json:"metadata"`
	Spec                 ImageBuildSpec          `form:"spec" json:"spec"`
	Status               *ImageBuildStatus       `form:"status,omitempty" json:"status,omitempty"`
	Imageexports         []ImageExport           `form:"imageexports,omitempty" json:"imageexports,omitempty"`
	AdditionalProperties map[string]any          `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a ImageBuild) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *ImageBuild) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *ImageBuild) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apiVersion"]; found {
		if err := json.Unmarshal(raw, &a.APIVersion); err != nil {
			return fmt.Errorf("error reading 'apiVersion': %w", err)
		}
		delete(object, "apiVersion")
	}

	if raw, found := object["kind"]; found {
		if err := json.Unmarshal(raw, &a.Kind); err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["metadata"]; found {
		if err := json.Unmarshal(raw, &a.Metadata); err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["spec"]; found {
		if err := json.Unmarshal(raw, &a.Spec); err != nil {
			return fmt.Errorf("error reading 'spec': %w", err)
		}
		delete(object, "spec")
	}

	if raw, found := object["status"]; found {
		var val ImageBuildStatus
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		a.Status = &val
		delete(object, "status")
	}

	if raw, found := object["imageexports"]; found {
		if err := json.Unmarshal(raw, &a.Imageexports); err != nil {
			return fmt.Errorf("error reading 'imageexports': %w", err)
		}
		delete(object, "imageexports")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a ImageBuild) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["apiVersion"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'apiVersion': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	object["spec"], err = json.Marshal(a.Spec)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'spec': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	object["imageexports"], err = json.Marshal(a.Imageexports)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'imageexports': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuild) ApplyDefaults() {
	if s.Status != nil {
		s.Status.ApplyDefaults()
	}
}

// #/components/schemas/ImageBuild/properties/imageexports
// Array of ImageExport resources that reference this ImageBuild. Only populated when withExports query parameter is true.
type ImageBuildImageexports = []ImageExport

// #/components/schemas/ImageBuildList
// ImageBuildList is a list of ImageBuild resources.
type ImageBuildList struct {
	APIVersion string `form:"apiVersion" json:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind     string                `form:"kind" json:"kind"`
	Metadata ext_66c3f5a7.ListMeta `form:"metadata" json:"metadata"`
	// List of ImageBuild resources.
	Items []ImageBuild `form:"items" json:"items"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildList) ApplyDefaults() {
}

// #/components/schemas/ImageBuildList/properties/items
// List of ImageBuild resources.
type ImageBuildListItem = []ImageBuild

// #/components/schemas/ImageBuildSpec
// ImageBuildSpec describes the specification for an image build.
type ImageBuildSpec struct {
	Source               ImageBuildSource             `form:"source" json:"source"`
	Destination          ImageBuildDestination        `form:"destination" json:"destination"`
	Binding              ImageBuildBinding            `form:"binding" json:"binding"`
	UserConfiguration    *ImageBuildUserConfiguration `form:"userConfiguration,omitempty" json:"userConfiguration,omitempty"`
	AdditionalProperties map[string]any               `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a ImageBuildSpec) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *ImageBuildSpec) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *ImageBuildSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["source"]; found {
		if err := json.Unmarshal(raw, &a.Source); err != nil {
			return fmt.Errorf("error reading 'source': %w", err)
		}
		delete(object, "source")
	}

	if raw, found := object["destination"]; found {
		if err := json.Unmarshal(raw, &a.Destination); err != nil {
			return fmt.Errorf("error reading 'destination': %w", err)
		}
		delete(object, "destination")
	}

	if raw, found := object["binding"]; found {
		if err := json.Unmarshal(raw, &a.Binding); err != nil {
			return fmt.Errorf("error reading 'binding': %w", err)
		}
		delete(object, "binding")
	}

	if raw, found := object["userConfiguration"]; found {
		var val ImageBuildUserConfiguration
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'userConfiguration': %w", err)
		}
		a.UserConfiguration = &val
		delete(object, "userConfiguration")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a ImageBuildSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["source"], err = json.Marshal(a.Source)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'source': %w", err)
	}

	object["destination"], err = json.Marshal(a.Destination)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'destination': %w", err)
	}

	object["binding"], err = json.Marshal(a.Binding)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'binding': %w", err)
	}

	if a.UserConfiguration != nil {
		object["userConfiguration"], err = json.Marshal(a.UserConfiguration)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'userConfiguration': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildSpec) ApplyDefaults() {
	if s.UserConfiguration != nil {
		s.UserConfiguration.ApplyDefaults()
	}
}

// #/components/schemas/ImageBuildSource
// ImageBuildSource specifies the source image for the build.
type ImageBuildSource struct {
	// The name of the Repository resource of type OCI containing the source image.
	Repository string `form:"repository" json:"repository"`
	// The name of the source image.
	ImageName string `form:"imageName" json:"imageName"`
	// The tag of the source image.
	ImageTag string `form:"imageTag" json:"imageTag"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildSource) ApplyDefaults() {
}

// #/components/schemas/ImageBuildDestination
// ImageBuildDestination specifies the destination for the built image.
type ImageBuildDestination struct {
	// The name of the Repository resource of type OCI to push the built image to.
	Repository string `form:"repository" json:"repository"`
	// The name of the output image.
	ImageName string `form:"imageName" json:"imageName"`
	// The tag of the output image.
	ImageTag string `form:"imageTag" json:"imageTag"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildDestination) ApplyDefaults() {
}

// #/components/schemas/ImageBuildBinding

// ImageBuildBinding specifies binding configuration for the build.
type ImageBuildBinding struct {
	union json.RawMessage
}

// AsEarlyBinding returns the union data inside the ImageBuildBinding as a EarlyBinding.
func (t ImageBuildBinding) AsEarlyBinding() (EarlyBinding, error) {
	var body EarlyBinding
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromEarlyBinding overwrites any union data inside the ImageBuildBinding as the provided EarlyBinding.
func (t *ImageBuildBinding) FromEarlyBinding(v EarlyBinding) error {
	v.Type = "early"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeEarlyBinding performs a merge with any union data inside the ImageBuildBinding, using the provided EarlyBinding.
func (t *ImageBuildBinding) MergeEarlyBinding(v EarlyBinding) error {
	v.Type = "early"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLateBinding returns the union data inside the ImageBuildBinding as a LateBinding.
func (t ImageBuildBinding) AsLateBinding() (LateBinding, error) {
	var body LateBinding
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLateBinding overwrites any union data inside the ImageBuildBinding as the provided LateBinding.
func (t *ImageBuildBinding) FromLateBinding(v LateBinding) error {
	v.Type = "late"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLateBinding performs a merge with any union data inside the ImageBuildBinding, using the provided LateBinding.
func (t *ImageBuildBinding) MergeLateBinding(v LateBinding) error {
	v.Type = "late"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t ImageBuildBinding) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t ImageBuildBinding) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "early":
		return t.AsEarlyBinding()
	case "late":
		return t.AsLateBinding()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ImageBuildBinding) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ImageBuildBinding) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ImageBuildBinding) ApplyDefaults() {
}

// #/components/schemas/ImageBuildUserConfiguration
// ImageBuildUserConfiguration specifies user configuration for the build.
type ImageBuildUserConfiguration struct {
	// The username for the user configuration.
	Username string `form:"username" json:"username"`
	// The public key for the user configuration.
	Publickey string `form:"publickey" json:"publickey"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildUserConfiguration) ApplyDefaults() {
}

// #/components/schemas/EarlyBinding
// Early binding configuration - embeds certificate in the image.
type EarlyBinding struct {
	// The type of binding.
	Type string `form:"type" json:"type"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *EarlyBinding) ApplyDefaults() {
}

// #/components/schemas/EarlyBinding/properties/type
// The type of binding.
type EarlyBindingType string

const (
	Early EarlyBindingType = "early"
)

// #/components/schemas/LateBinding
// Late binding configuration - device binds at first boot.
type LateBinding struct {
	// The type of binding.
	Type string `form:"type" json:"type"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *LateBinding) ApplyDefaults() {
}

// #/components/schemas/LateBinding/properties/type
// The type of binding.
type LateBindingType string

const (
	Late LateBindingType = "late"
)

// #/components/schemas/BindingType
// The type of binding for the image build.
type BindingType string

const (
	BindingTypeEarly BindingType = "early"
	BindingTypeLate  BindingType = "late"
)

// #/components/schemas/ImageBuildStatus
// ImageBuildStatus represents the current status of an ImageBuild.
type ImageBuildStatus struct {
	// Current conditions of the ImageBuild.
	Conditions []ImageBuildCondition `form:"conditions,omitempty" json:"conditions,omitempty"`
	// The full image reference of the built image (e.g., quay.io/org/imagename:tag).
	ImageReference *string `form:"imageReference,omitempty" json:"imageReference,omitempty"`
	// The architecture of the built image.
	Architecture *string `form:"architecture,omitempty" json:"architecture,omitempty"`
	// The digest of the built image manifest.
	ManifestDigest *string `form:"manifestDigest,omitempty" json:"manifestDigest,omitempty"`
	// The last time the build was seen (heartbeat).
	LastSeen *time.Time `form:"lastSeen,omitempty" json:"lastSeen,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildStatus) ApplyDefaults() {
}

// #/components/schemas/ImageBuildStatus/properties/conditions
// Current conditions of the ImageBuild.
type ImageBuildStatusConditions = []ImageBuildCondition

// #/components/schemas/ImageBuildCondition
// Condition for ImageBuild resources.
type ImageBuildCondition struct {
	Type   ImageBuildConditionType      `form:"type" json:"type"`
	Status ext_66c3f5a7.ConditionStatus `form:"status" json:"status"`
	// The .metadata.generation that the condition was set based upon.
	ObservedGeneration *int64 `form:"observedGeneration,omitempty" json:"observedGeneration,omitempty"`
	// The last time the condition transitioned from one status to another.
	LastTransitionTime time.Time `form:"lastTransitionTime" json:"lastTransitionTime"`
	// Human readable message indicating details about last transition.
	Message string `form:"message" json:"message"`
	// A (brief) reason for the condition's last transition.
	Reason string `form:"reason" json:"reason"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildCondition) ApplyDefaults() {
}

// #/components/schemas/ImageBuildConditionType
// Type of ImageBuild condition.
type ImageBuildConditionType string

const (
	ImageBuildConditionTypeReady ImageBuildConditionType = "Ready"
)

// #/components/schemas/ImageBuildConditionReason
// Reason for the ImageBuild Ready condition.
type ImageBuildConditionReason string

const (
	ImageBuildConditionReasonPending   ImageBuildConditionReason = "Pending"
	ImageBuildConditionReasonBuilding  ImageBuildConditionReason = "Building"
	ImageBuildConditionReasonPushing   ImageBuildConditionReason = "Pushing"
	ImageBuildConditionReasonCompleted ImageBuildConditionReason = "Completed"
	ImageBuildConditionReasonFailed    ImageBuildConditionReason = "Failed"
	ImageBuildConditionReasonCanceling ImageBuildConditionReason = "Canceling"
	ImageBuildConditionReasonCanceled  ImageBuildConditionReason = "Canceled"
)

// #/components/schemas/ImageExport
// ImageExport represents an export request to convert and push images to different formats.
type ImageExport struct {
	APIVersion           string                  `form:"apiVersion" json:"apiVersion"`
	Kind                 string                  `form:"kind" json:"kind"`
	Metadata             ext_66c3f5a7.ObjectMeta `form:"metadata" json:"metadata"`
	Spec                 ImageExportSpec         `form:"spec" json:"spec"`
	Status               *ImageExportStatus      `form:"status,omitempty" json:"status,omitempty"`
	AdditionalProperties map[string]any          `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a ImageExport) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *ImageExport) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *ImageExport) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apiVersion"]; found {
		if err := json.Unmarshal(raw, &a.APIVersion); err != nil {
			return fmt.Errorf("error reading 'apiVersion': %w", err)
		}
		delete(object, "apiVersion")
	}

	if raw, found := object["kind"]; found {
		if err := json.Unmarshal(raw, &a.Kind); err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["metadata"]; found {
		if err := json.Unmarshal(raw, &a.Metadata); err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["spec"]; found {
		if err := json.Unmarshal(raw, &a.Spec); err != nil {
			return fmt.Errorf("error reading 'spec': %w", err)
		}
		delete(object, "spec")
	}

	if raw, found := object["status"]; found {
		var val ImageExportStatus
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		a.Status = &val
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a ImageExport) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["apiVersion"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'apiVersion': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	object["spec"], err = json.Marshal(a.Spec)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'spec': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageExport) ApplyDefaults() {
	if s.Status != nil {
		s.Status.ApplyDefaults()
	}
}

// #/components/schemas/ImageExportList
// ImageExportList is a list of ImageExport resources.
type ImageExportList struct {
	APIVersion string `form:"apiVersion" json:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind     string                `form:"kind" json:"kind"`
	Metadata ext_66c3f5a7.ListMeta `form:"metadata" json:"metadata"`
	// List of ImageExport resources.
	Items []ImageExport `form:"items" json:"items"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageExportList) ApplyDefaults() {
}

// #/components/schemas/ImageExportList/properties/items
// List of ImageExport resources.
type ImageExportListItem = []ImageExport

// #/components/schemas/ImageExportSpec
// ImageExportSpec describes the specification for an image export.
type ImageExportSpec struct {
	Source               ImageExportSource `form:"source" json:"source"`
	Format               ExportFormatType  `form:"format" json:"format"`
	AdditionalProperties map[string]any    `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a ImageExportSpec) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *ImageExportSpec) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *ImageExportSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["source"]; found {
		if err := json.Unmarshal(raw, &a.Source); err != nil {
			return fmt.Errorf("error reading 'source': %w", err)
		}
		delete(object, "source")
	}

	if raw, found := object["format"]; found {
		if err := json.Unmarshal(raw, &a.Format); err != nil {
			return fmt.Errorf("error reading 'format': %w", err)
		}
		delete(object, "format")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a ImageExportSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["source"], err = json.Marshal(a.Source)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'source': %w", err)
	}

	object["format"], err = json.Marshal(a.Format)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'format': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageExportSpec) ApplyDefaults() {
}

// #/components/schemas/ImageExportSource

// ImageExportSource specifies the source image for the export.
type ImageExportSource struct {
	union json.RawMessage
}

// AsImageBuildRefSource returns the union data inside the ImageExportSource as a ImageBuildRefSource.
func (t ImageExportSource) AsImageBuildRefSource() (ImageBuildRefSource, error) {
	var body ImageBuildRefSource
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromImageBuildRefSource overwrites any union data inside the ImageExportSource as the provided ImageBuildRefSource.
func (t *ImageExportSource) FromImageBuildRefSource(v ImageBuildRefSource) error {
	v.Type = "imageBuild"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeImageBuildRefSource performs a merge with any union data inside the ImageExportSource, using the provided ImageBuildRefSource.
func (t *ImageExportSource) MergeImageBuildRefSource(v ImageBuildRefSource) error {
	v.Type = "imageBuild"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}
	merged, err := JSONMerge(t.union, b)
	t.union = merged
	return err
}

// Discriminator extracts the discriminator property value from the union data.
func (t ImageExportSource) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

// ValueByDiscriminator returns the union member based on the discriminator value.
func (t ImageExportSource) ValueByDiscriminator() (any, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "imageBuild":
		return t.AsImageBuildRefSource()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t ImageExportSource) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ImageExportSource) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// ApplyDefaults sets default values for fields that are nil.
func (t *ImageExportSource) ApplyDefaults() {
}

// #/components/schemas/ImageBuildRefSource
// ImageBuildRefSource specifies a source image from an ImageBuild resource.
type ImageBuildRefSource struct {
	// The type of source.
	Type string `form:"type" json:"type"`
	// The name of the ImageBuild resource to use as source.
	ImageBuildRef string `form:"imageBuildRef" json:"imageBuildRef"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageBuildRefSource) ApplyDefaults() {
}

// #/components/schemas/ImageBuildRefSource/properties/type
// The type of source.
type ImageBuildRefSourceType string

const (
	ImageBuildRefSourceTypeImageBuild ImageBuildRefSourceType = "imageBuild"
)

// #/components/schemas/ImageExportSourceType
// The type of source for the image export.
type ImageExportSourceType string

const (
	ImageExportSourceTypeImageBuild ImageExportSourceType = "imageBuild"
)

// #/components/schemas/ExportFormatType
// The type of format to export the image to.
type ExportFormatType string

const (
	ExportFormatTypeVMDK               ExportFormatType = "vmdk"
	ExportFormatTypeQCOW2              ExportFormatType = "qcow2"
	ExportFormatTypeISO                ExportFormatType = "iso"
	ExportFormatTypeQCOW2DiskContainer ExportFormatType = "qcow2-disk-container"
)

// #/components/schemas/ImageExportStatus
// ImageExportStatus represents the current status of an ImageExport.
type ImageExportStatus struct {
	// Current conditions of the ImageExport.
	Conditions []ImageExportCondition `form:"conditions,omitempty" json:"conditions,omitempty"`
	// The digest of the exported image manifest for this format.
	ManifestDigest *string `form:"manifestDigest,omitempty" json:"manifestDigest,omitempty"`
	// The last time the export was seen (heartbeat).
	LastSeen *time.Time `form:"lastSeen,omitempty" json:"lastSeen,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageExportStatus) ApplyDefaults() {
}

// #/components/schemas/ImageExportStatus/properties/conditions
// Current conditions of the ImageExport.
type ImageExportStatusConditions = []ImageExportCondition

// #/components/schemas/ImageExportCondition
// Condition for ImageExport resources.
type ImageExportCondition struct {
	Type   ImageExportConditionType     `form:"type" json:"type"`
	Status ext_66c3f5a7.ConditionStatus `form:"status" json:"status"`
	// The .metadata.generation that the condition was set based upon.
	ObservedGeneration *int64 `form:"observedGeneration,omitempty" json:"observedGeneration,omitempty"`
	// The last time the condition transitioned from one status to another.
	LastTransitionTime time.Time `form:"lastTransitionTime" json:"lastTransitionTime"`
	// Human readable message indicating details about last transition.
	Message string `form:"message" json:"message"`
	// A (brief) reason for the condition's last transition.
	Reason string `form:"reason" json:"reason"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *ImageExportCondition) ApplyDefaults() {
}

// #/components/schemas/ImageExportConditionType
// Type of ImageExport condition.
type ImageExportConditionType string

const (
	ImageExportConditionTypeReady ImageExportConditionType = "Ready"
)

// #/components/schemas/ImageExportConditionReason
// Reason for the ImageExport Ready condition.
type ImageExportConditionReason string

const (
	ImageExportConditionReasonPending    ImageExportConditionReason = "Pending"
	ImageExportConditionReasonConverting ImageExportConditionReason = "Converting"
	ImageExportConditionReasonPushing    ImageExportConditionReason = "Pushing"
	ImageExportConditionReasonCompleted  ImageExportConditionReason = "Completed"
	ImageExportConditionReasonFailed     ImageExportConditionReason = "Failed"
	ImageExportConditionReasonCanceling  ImageExportConditionReason = "Canceling"
	ImageExportConditionReasonCanceled   ImageExportConditionReason = "Canceled"
)

// #/components/schemas/ImageExportFormatPhase
// The phase of a single format conversion.
type ImageExportFormatPhase string

const (
	ImageExportFormatPhaseQueued     ImageExportFormatPhase = "queued"
	ImageExportFormatPhaseConverting ImageExportFormatPhase = "converting"
	ImageExportFormatPhasePushing    ImageExportFormatPhase = "pushing"
	ImageExportFormatPhaseComplete   ImageExportFormatPhase = "complete"
	ImageExportFormatPhaseFailed     ImageExportFormatPhase = "failed"
)

// #/components/schemas/Status
// Status is a return value for calls that don't return other objects.
type Status struct {
	APIVersion string `form:"apiVersion" json:"apiVersion"`
	// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind string `form:"kind" json:"kind"`
	// Suggested HTTP return code for this status, 0 if not set.
	Code int32 `form:"code" json:"code"`
	// A human-readable description of the status of this operation.
	Message string `form:"message" json:"message"`
	// A machine-readable description of why this operation is in the "Failure" status. If this value is empty there is no information available. A Reason clarifies an HTTP status code but does not override it.
	Reason string `form:"reason" json:"reason"`
	// Status of the operation. One of: "Success" or "Failure". More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#spec-and-status.
	Status string `form:"status" json:"status"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Status) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+w9XW/cOJLv/hWFZAAnQFpte2Zudxo44BwnmTXG+VjbmXuYnQPYUnU31xKpkJSdvr39",
	"7wd+SKI+W922EzuRH4K0SBaLVcWqIqtI8hQZSekMfgwOgsM9yhZ8tgegqIpxBm9iulwpOOFMCR7DaUKW",
	"CC8zGkco4PjD6R7ANQpJOZvB9SGJ0xU53AOIUIaCpsp8/789AKg1lSiuaYiw4KLWR2BqX66oLColhJEl",
	"SqAGxFyDAIGSZyJEaUCYb5QtgbAI0kyu9P9DzhShDIVtKDVk8y1UM9MJIwnO4HKF9WFeIklMjUzEM1gp",
	"lcrZdLowlUIVB5SbUkwIjWegkCT/VSuMaYhMot/PcUrCFcJRcNAEfXNzExBTHnCxnLrWcnp2evL63cXr",
	"yVFwEKxUEu9pkqCQGu7EgpjuKbJ0H2xHZrSGIqajCi/epyiI/q8EzixPXlbpGdQh4eeUCzUI1GtT1Yf1",
	"FN5xhTO4wDATVK2BSlgRFsUYwXwNJysKCY2iGG+IQHhGMrUKTgQShceZWr17W5Q9fwGMK90pO/5wCtck",
	"ppHpfe+p4aB0HVyEK0xQggYX4YIyjIAyCHmScoZMWXmJeJglyJSBAGkmUi5R7qVErQwppySl0+vDaUlK",
	"aVn5eZIPzqezNGVLdHIFkLPE/k3qLKlR8oxK1ckL/cdzUp9GM4ipVGVl6aqkRJAElZONvF/LxpjMMb7A",
	"GEPFRVEKQNkMPmUo1t63CmLHIF0rUFyjpQQNFagVGiyAL0CgyoQmMp//E0MlNVfVCqmwvRZD0H9S84bM",
	"vC8Aap3iDDRgtmwgvqAYR18ccdPr7RCPaULVNghrEU7IZ5pkCbAsmaOwOMosVrLElbJyDAJlypnEYYhS",
	"pnCJolKy4CIhypT9eFQpSSjTqMzgoPrZYjiDw4ODg8agtW6lLMOtGMWAm/+SuBRhzTPTChIusKDCQvDE",
	"DN8qwVsx6IaqldVWcht0TxegRIYvgLIwziLUrImJwqhd/2l+IQlX/uR2LNyOe3POYySsUhLhgmSxmsGC",
	"xDIneg7W0wJPjg4Onsy6RvT+N69EcxCZqmJA0jSmoVE/039Kzqql7Vjrvx8ELmaw/3Ra6t6prSunJT20",
	"7tsvcf2pD9eXJIJz/JShVF8D6QtFVCYryB52I/uRaWPGBf1fjB4Itj92Y/uGizmNImQPA9WjX7pRveQc",
	"3hK2zkVBPgiUf+6j7oVzZD8yck1oTOYxfm2kUy539Fasewak1X1s9VhC06KsXegqw7+XPFqXvbcQo58U",
	"7YQYpnxK/mlcqMBoZvR7rzLtmfOWNNHX1aj7XruYsitZBfQret5jvY8K25Z+zVrFNncz/7MWdv+HwsTN",
	"ebR+Ok1QkYgoMtXl+5VWrzBGX0B60Ypqle8Vswq1zvhyOMHO+PJeMTshLMR4IM3CWuX7xayc7tYh6ket",
	"XrtWuVVLlDOJ/p5vP/gr8Km3F1H9u6IsmkF3dwD5yJq97UIMM59TDNuguYVkS0nhtXdxzPmrRfG50Qxb",
	"4lWuAD6F/OZo9MJGL6yKao8XdsLZIqahGv3F78FfbNkPm/5LK5V/3+O22K+otvEy29yVvl0x/W9t7Z8S",
	"terbodFNgC/MAr4HrU6H8oFvVYz7Em1e9GBrGIzm8Ns2hz91o/qOK3jDMxaN9vD72D+xq9DdDJtd7m5j",
	"2zrWvI/XvD0Se9CiBEZbMNqC0RaMtmDA2mga5xuGHesjXeH2a6SYL21WQ4dB0XMHSKjotUuekS+0MkaS",
	"SNs2pteulh6otjRRUdGGniXERCr4+eAAYso6EhM6tj+/hTXYgscxv9lp+WUpbQntIuQ8k/EansX0CuEq",
	"m2OoYls+WTxv5dYVYmpaMwxNxgpPkW3iGIkdVMIiCGMuUT78RZ3Cz2qaxoQOnqStfGvt/YwvgWcqzRQQ",
	"CaYT0x88u1khczz+TzNA4MLMqDp1nzeRxWtkamK5fN84X5jEh8kFMgWvr002kxOvyhC04FmF4IvR89GL",
	"Gb2Y0YsZvZhtvRgbPOx3ZGyd22YWGCBAQGSMUbb07HsA71m8dpoMKIMPyCLKli9sRrH5HxfwwaX+SkUU",
	"QkgYzNEFPzFqz01oj4x+WacFFHeIfIdr7FvtuY4GajRQjydYChOrrkwqO2VuzmvlbzXWaGq/O1NrT1d0",
	"nS5AL+63aY8A/XSWjvMFzQMafQcMqlHH8YTBeMJgPGHwDflcdnqPCfij4zX6AA8wAb/bntcy8GtGfVMK",
	"fiXt9avm4FtMvrUk/PqoerPwByRILytVv1Qe/gDEonrtL5KJ76zWwFT8ovaXysUfkvFer32/POU3LOYk",
	"GszVZv17w2/0NkZvY0w0H/2i/r2R/kzzu9ki8XPNh/hTrUb5voMGHYh9b7GCuoM1hrNHMzKGs0c7snWC",
	"drc5qGVoD7EIXauh0SiMSdqjPRjtwWgPHui6oj+/Ka+7TYJTz85ta4aTVeEuxcl1WMlxOuHsGoW6kyyn",
	"r2mcxjynndcuo6kaTdWjSnRyU3/MdBqtbqvVzeMMG+xuXu2W+3t5FKS+pCNC0QUJVZn6IXBJpRLr9kVe",
	"Z3Dk+1rmwQSOc8rNYz7PhWsbceOhwjs9OJMnG80pI14+0JMfD4767EDGIpjAOUZUYKhsNpcVATu0j+dn",
	"XuMVkqgR+Trjdky3GsaTHw/+0qOOMEm5IGJdYvogkB79l9F/GZfa9230e+bYKVMoGInd4UB4LUQlk3X0",
	"VW7vq3Sf484rDj3I3R+BbJzkrlt9/3Cw63rAWe6i5g6HuesJNI/Yz/nqx7kLPgw6z93g2nig+y4PdDvy",
	"Ps4T3Q3kx5jH6IiNjtjo0ZRIl0W6fe15HAtyjkSgOM7UKu/CAQ6CaRBMQy5wen04R0UOp+6ZqGBNkrja",
	"bxXytARqCcfF8jS6Q/gGngbtBmxBH5cXQe91auTPkyWftHyvsHH/+MOpA+UeEJLGO3HPXGHkOrZeC5Ug",
	"MBUoi8eE+EJ7b/bIV+D0uwS54lkcaSm4RuPehHzJtILLh6GX8ObgFVEolTlMZbz6axJrt0Ob/ISsQaCG",
	"CxnzIJgqMoC3XCCY97uKd6WWVAVXf5UB5ZqkScaoWk+1KAo6zxQXchrhNcZTSZcTIsIVVRiqTKB2hicG",
	"WWZeeAqS6Gl5aDCfEciyxPcCG5duT3ov5f480QAm10Ror6ziT5bs/L0Jsyx8k0M/5ZV65w7V3yiLeuTB",
	"4A9/lAfQX/g+6J9t0nFeRLLWKUpjh6VmASW1s/32ebSgfPqsckm7RcYKSVs3lTsCnHhJIMXbZ0YnWoeg",
	"/sxZbuBTof15RX3CksYs2aRNSlqXavDKo2qP71OdVZoVQPUYbEUrteXo9CdNwfPXF5devFBPMEsmjxDl",
	"tNJTgrIFCluz2MRFFqWcMnseM4ypdq9kNk+oOepoLQooHsAJYYwrmCNkaUQURgGcMjghCcYnROK9Tyoj",
	"RhNN0XJatV9Bv4vqdEx8bwj4FhUpu6jfST/shoaLFEMPhjE1O0Cp2dXmQWhfsIgQpPt0py7UOrf9UmO1",
	"IvrnAgWyXJwal4qkPM3szcjG5fbuW3ZnRMtjo1SaZaDvRFOFSW1ndcsocLGu9XRcOVO9j1pMvJ+5lHif",
	"NFdz5faZ6KVO6+Tf8FaC90ZC9e2BNrl0J3ORKS4nc85V6JZOv0zmlcZ1iWt7/UBgyiVVXKz1epysJ+6l",
	"xYqkvGv0OPV/NBtckuXMLat+qQqSoqxlD9zHIllP8p31LkyS9SSTKCpITMJMKp504HJ9GBwE/sHnOTWZ",
	"Hm2L97iMlpIoovYk84dSubsFfM3QnFEvR2WwsTEXBRglnZ9h73uVcLQwo4VxTNSCU7UvDbU4QJnvn/VJ",
	"3f4tlW7liqE71LkGl/r8u/CU3fD5p1u5srlbdmitSRdukZjvDXsP4fZNxqaGHWifTbuS3h2KchiwV2Xj",
	"EmKLvhsG7aVtWELSmveEswVdZmJHDD/WQfQJiaWp98EjjvfVDXB7xX1R4dkWomPVmROXXHjsRysuWnb0",
	"x41i45m/zTo4oewM2VKtZnA4dKP/vOig1MO6aJ0ivD85zVc0ucL2RxHsNQ3wzkgm5HP++ejnn4di34OO",
	"Nu53gc3h0V/3/PO2SqHQ+vF//vjHzZ9//OMmmPz5r4MXh0d/+fcP+31oK7Lsw7pNvkvm10NX7/zozqQY",
	"cF2AXzWVxXAp9hrXRNmbZhVJVptXvV9dnhU3b5LXcdbuwdcXZxeLeGTi3Ib1vYjzy6ql6pBbV8uTWWcA",
	"tC4rDUu7DuYM3y98pPvM1msi4nXDCva3OSMKa00iqseR6BnFRdm3mz5ru7DRDC89RpKmNZONGpftEAWz",
	"nhmEaI0RH7sM/XDt0gDh8Uv7EUOY1aZgdFs2bOo2ZDpvW/TWRKSclWk2j2l4hetderKN4QrXA/pqm0s5",
	"qt6nAiHLLZ/nQ9lj2nRMlwlgMsdIQqhJbrxgzG8o2zj1PeltY5rBazMZ3R6xEfU/e5WT1vZ8kY/EYGbq",
	"e0I9lCa6SSdJIjRhJl0sgShYUCEVzDlXX4waeg5vRwxT2VHh0utrUzSmBVghvS2roHpEwrDN++1tpvRE",
	"Hzw8X9cAeEWaSQ3vvbIjuoX3btr5e/1mWyETwuwr2FIbWfK2L3v4GXJmlxzbrsFPXJ8lgOa9xcFdrMRP",
	"8g5q+8Dn+W7tLjpukcWxk4ty19fh73tezzBYBi/MFmNA+ZSLpc37MlpckeXzcoj+/souKPntW1AJPAPL",
	"6AKlekWXKNUuXUWmZdt4c9hlbzGR6gKRDegnz6uOiMKJopUcrwYOJrVMVypNJ9wQCRKRwbMVEqHmSNTz",
	"oD51CnlodbWKUjP7+3YlWybdBn1olvVmilU0hVSXgjBper2kFbMnkMjKcj9BKclyGwW75STRCmdA4GWX",
	"vbuij3pYhs/NNZjRr8iwubfSdemnd+Xnf/zUJylBvpcWLIsObMDG6L6C4VZ6FMyJxAiy1HeImly6X3ku",
	"sVJFrxjZXWHOMNfUigNhXK38K0SdiGw7r/+WJYRpgYvM4SkHBbQZConZ045QERpLIHOeKYdvgVzgrYKJ",
	"5Gzb7o/h2VxQXDx37QvjW1BiX7b32SHEgw2/M/reVC+67LL250ii9Wbz3oFZ2bqlwnmFepuQP6/SyhuD",
	"6WTzSNzJX9/xcM8c+JXsMWDvy0me3eh9e0NoXPlgzyDXGrrDwzsRz462iXJn1ZaxdINtDLKzatvoOys3",
	"yNINtoVeGyo7wE8rUWmnb0sJq17GN8hZLALcZU4Ic8mgRVaI4kWaEWGR3XkyXoDRSxFdGL9IOTU4RvPG",
	"aN695ItYUb11wogDU3FNHnLCRO3GzO6MiWQ9wWiJEzt7J1oUd0iYcF5YM1WjWE+Zz+eaygNyNErn6FPI",
	"b462Cl+V14nvoNI6Mg+63isYldWorO4x9aAhdvsPNeGrnnxQat0dJuF26QdWcd1x/oFDpJaA4JTSQEAW",
	"xhvTxl83Dwrn2652UHzVwH0niQeH6avk3SpGdOrr/Sot7yTuU9qVrTCora2Kku23S4umHiFJjYxaW/a/",
	"sD5gW6hiQe9s+7yEOmgTvX4SsmrW7yek3fFIXSYRiCwwap8Du+7vu26q2/vVaVBfJzccn00r1zqeXpKr",
	"jWDVdMcu47AqRJPLrczK0ZQR/8bZiSS68n767pcZqOT10klE5dWkyP7fTID62H5/++q3nuK/n7z/76Oe",
	"8tOL95tav6Ly6qRAsCEt2wdL/IbDoyWvN1qq+wqXVHu+nffQEjC565CBlVeMalEDNyWpdKL9paMIbhpt",
	"CiPUyDQ0jtC1xvhWAgk1soyRhDGS8AgjCS1SvFMowc32O40ltOBWCybUatw+muCGsXM4obxR9EEEFFrp",
	"0xFRaK3bOp4e0O1RhQ7QHWGF1trtcYV2wF2BhZ7aGDUMnvW5PqyI3MpbTXUD4yWBpGwZY+632uCB7BGn",
	"TxlmlTGGbdRPGzTOL9/wl9s+uYZJiTfev9cRaa+2STi8qr2CUQHZGEp7RU8eNvq7467m493VDHmEWzo1",
	"lRdRq1dJZEvtlmMEf7u8/OAuADJdlK64dRBewAHQhbllVaK6tY9wDCvtJUwKL8ErLU4SFOsry+r81qjb",
	"OwgJCVeUYWfvN6t1rU8tni4f9ImeaZnAJw7BwNzZpGtbsaUSMEmVeYJXmJ+MGynR/NCgils7AjjObW4Y",
	"E+G2l5jlhRu94cU8UxBxlIb8/BqFoBEC9djQdK8HzbwLj8ToURjeM62yZ/DkIgtDlPIJcFGO/N5FX6YY",
	"TgiLJo7E+23GxSFvFIeTXMsBc/8SiWN3LDvibF/lNYyLmz+UHNxyn7yxBtPcGrLq+v8AAAD//xj88qgM",
	"rwAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------

// JSONMerge merges two JSON-encoded objects. Fields from patch override
// fields in base. Both arguments must be valid JSON objects (or nil/null).
func JSONMerge(base, patch json.RawMessage) (json.RawMessage, error) {
	if len(base) == 0 || string(base) == "null" {
		return patch, nil
	}
	if len(patch) == 0 || string(patch) == "null" {
		return base, nil
	}

	var baseMap map[string]json.RawMessage
	if err := json.Unmarshal(base, &baseMap); err != nil {
		return nil, fmt.Errorf("JSONMerge: unmarshaling base: %w", err)
	}

	var patchMap map[string]json.RawMessage
	if err := json.Unmarshal(patch, &patchMap); err != nil {
		return nil, fmt.Errorf("JSONMerge: unmarshaling patch: %w", err)
	}

	for k, v := range patchMap {
		baseMap[k] = v
	}

	return json.Marshal(baseMap)
}
