// Code generated by oapi-codegen; DO NOT EDIT.

package pam_issuer

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"strings"
	"sync"
)

// #/components/schemas/TokenRequest
// OAuth2 token request
type TokenRequest struct {
	GrantType            string           `form:"grant_type" json:"grant_type"`
	Username             Nullable[string] `form:"username,omitempty" json:"username,omitempty"`
	Password             Nullable[string] `form:"password,omitempty" json:"password,omitempty"`
	RefreshToken         Nullable[string] `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
	Code                 Nullable[string] `form:"code,omitempty" json:"code,omitempty"`
	ClientID             Nullable[string] `form:"client_id,omitempty" json:"client_id,omitempty"`
	ClientSecret         Nullable[string] `form:"client_secret,omitempty" json:"client_secret,omitempty"`
	Scope                Nullable[string] `form:"scope,omitempty" json:"scope,omitempty"`
	CodeVerifier         Nullable[string] `form:"code_verifier,omitempty" json:"code_verifier,omitempty"`
	RedirectURI          Nullable[string] `form:"redirect_uri,omitempty" json:"redirect_uri,omitempty"`
	AdditionalProperties map[string]any   `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a TokenRequest) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *TokenRequest) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *TokenRequest) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["grant_type"]; found {
		if err := json.Unmarshal(raw, &a.GrantType); err != nil {
			return fmt.Errorf("error reading 'grant_type': %w", err)
		}
		delete(object, "grant_type")
	}

	if raw, found := object["username"]; found {
		if err := json.Unmarshal(raw, &a.Username); err != nil {
			return fmt.Errorf("error reading 'username': %w", err)
		}
		delete(object, "username")
	}

	if raw, found := object["password"]; found {
		if err := json.Unmarshal(raw, &a.Password); err != nil {
			return fmt.Errorf("error reading 'password': %w", err)
		}
		delete(object, "password")
	}

	if raw, found := object["refresh_token"]; found {
		if err := json.Unmarshal(raw, &a.RefreshToken); err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		delete(object, "refresh_token")
	}

	if raw, found := object["code"]; found {
		if err := json.Unmarshal(raw, &a.Code); err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["client_id"]; found {
		if err := json.Unmarshal(raw, &a.ClientID); err != nil {
			return fmt.Errorf("error reading 'client_id': %w", err)
		}
		delete(object, "client_id")
	}

	if raw, found := object["client_secret"]; found {
		if err := json.Unmarshal(raw, &a.ClientSecret); err != nil {
			return fmt.Errorf("error reading 'client_secret': %w", err)
		}
		delete(object, "client_secret")
	}

	if raw, found := object["scope"]; found {
		if err := json.Unmarshal(raw, &a.Scope); err != nil {
			return fmt.Errorf("error reading 'scope': %w", err)
		}
		delete(object, "scope")
	}

	if raw, found := object["code_verifier"]; found {
		if err := json.Unmarshal(raw, &a.CodeVerifier); err != nil {
			return fmt.Errorf("error reading 'code_verifier': %w", err)
		}
		delete(object, "code_verifier")
	}

	if raw, found := object["redirect_uri"]; found {
		if err := json.Unmarshal(raw, &a.RedirectURI); err != nil {
			return fmt.Errorf("error reading 'redirect_uri': %w", err)
		}
		delete(object, "redirect_uri")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a TokenRequest) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["grant_type"], err = json.Marshal(a.GrantType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'grant_type': %w", err)
	}

	object["username"], err = json.Marshal(a.Username)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'username': %w", err)
	}

	object["password"], err = json.Marshal(a.Password)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'password': %w", err)
	}

	object["refresh_token"], err = json.Marshal(a.RefreshToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
	}

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["client_id"], err = json.Marshal(a.ClientID)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'client_id': %w", err)
	}

	object["client_secret"], err = json.Marshal(a.ClientSecret)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'client_secret': %w", err)
	}

	object["scope"], err = json.Marshal(a.Scope)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'scope': %w", err)
	}

	object["code_verifier"], err = json.Marshal(a.CodeVerifier)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code_verifier': %w", err)
	}

	object["redirect_uri"], err = json.Marshal(a.RedirectURI)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'redirect_uri': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TokenRequest) ApplyDefaults() {
}

// #/components/schemas/TokenRequest/properties/grant_type
// OAuth2 grant type.
type TokenRequestGrantType string

const (
	RefreshToken      TokenRequestGrantType = "refresh_token"
	AuthorizationCode TokenRequestGrantType = "authorization_code"
	Password          TokenRequestGrantType = "password"
)

// #/components/schemas/TokenResponse
// OAuth2 successful token response
type TokenResponse struct {
	AccessToken          string         `form:"access_token" json:"access_token"`
	TokenType            string         `form:"token_type" json:"token_type"`
	IDToken              *string        `form:"id_token,omitempty" json:"id_token,omitempty"`
	RefreshToken         *string        `form:"refresh_token,omitempty" json:"refresh_token,omitempty"`
	ExpiresIn            *int           `form:"expires_in,omitempty" json:"expires_in,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a TokenResponse) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *TokenResponse) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *TokenResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["access_token"]; found {
		if err := json.Unmarshal(raw, &a.AccessToken); err != nil {
			return fmt.Errorf("error reading 'access_token': %w", err)
		}
		delete(object, "access_token")
	}

	if raw, found := object["token_type"]; found {
		if err := json.Unmarshal(raw, &a.TokenType); err != nil {
			return fmt.Errorf("error reading 'token_type': %w", err)
		}
		delete(object, "token_type")
	}

	if raw, found := object["id_token"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'id_token': %w", err)
		}
		a.IDToken = &val
		delete(object, "id_token")
	}

	if raw, found := object["refresh_token"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'refresh_token': %w", err)
		}
		a.RefreshToken = &val
		delete(object, "refresh_token")
	}

	if raw, found := object["expires_in"]; found {
		var val int
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'expires_in': %w", err)
		}
		a.ExpiresIn = &val
		delete(object, "expires_in")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a TokenResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["access_token"], err = json.Marshal(a.AccessToken)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'access_token': %w", err)
	}

	object["token_type"], err = json.Marshal(a.TokenType)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'token_type': %w", err)
	}

	if a.IDToken != nil {
		object["id_token"], err = json.Marshal(a.IDToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'id_token': %w", err)
		}
	}

	if a.RefreshToken != nil {
		object["refresh_token"], err = json.Marshal(a.RefreshToken)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'refresh_token': %w", err)
		}
	}

	if a.ExpiresIn != nil {
		object["expires_in"], err = json.Marshal(a.ExpiresIn)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'expires_in': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *TokenResponse) ApplyDefaults() {
}

// #/components/schemas/TokenResponse/properties/token_type
// Token type.
type TokenResponseTokenType string

const (
	Bearer TokenResponseTokenType = "Bearer"
)

// #/components/schemas/OAuth2Error
// OAuth2 error response (RFC 6749 Section 5.2)
type OAuth2Error struct {
	// OAuth2 error code (RFC 6749 Section 5.2).
	Code string `form:"error" json:"error"`
	// Human-readable ASCII text providing additional information.
	ErrorDescription *string `form:"error_description,omitempty" json:"error_description,omitempty"`
	// URI identifying a human-readable web page with information about the error.
	ErrorURI *string `form:"error_uri,omitempty" json:"error_uri,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OAuth2Error) ApplyDefaults() {
}

// #/components/schemas/OAuth2Error/properties/error
// OAuth2 error code (RFC 6749 Section 5.2).
type OAuth2ErrorError string

const (
	InvalidRequest         OAuth2ErrorError = "invalid_request"
	InvalidClient          OAuth2ErrorError = "invalid_client"
	InvalidGrant           OAuth2ErrorError = "invalid_grant"
	UnauthorizedClient     OAuth2ErrorError = "unauthorized_client"
	UnsupportedGrantType   OAuth2ErrorError = "unsupported_grant_type"
	InvalidScope           OAuth2ErrorError = "invalid_scope"
	ServerError            OAuth2ErrorError = "server_error"
	TemporarilyUnavailable OAuth2ErrorError = "temporarily_unavailable"
)

// #/components/schemas/UserInfoResponse
// OIDC UserInfo response
type UserInfoResponse struct {
	Sub                  string         `form:"sub" json:"sub"`
	PreferredUsername    *string        `form:"preferred_username,omitempty" json:"preferred_username,omitempty"`
	Name                 *string        `form:"name,omitempty" json:"name,omitempty"`
	Email                *string        `form:"email,omitempty" json:"email,omitempty"`
	EmailVerified        *bool          `form:"email_verified,omitempty" json:"email_verified,omitempty"`
	Roles                []string       `form:"roles,omitempty" json:"roles,omitempty"`
	Organizations        []string       `form:"organizations,omitempty" json:"organizations,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a UserInfoResponse) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *UserInfoResponse) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *UserInfoResponse) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["sub"]; found {
		if err := json.Unmarshal(raw, &a.Sub); err != nil {
			return fmt.Errorf("error reading 'sub': %w", err)
		}
		delete(object, "sub")
	}

	if raw, found := object["preferred_username"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'preferred_username': %w", err)
		}
		a.PreferredUsername = &val
		delete(object, "preferred_username")
	}

	if raw, found := object["name"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		a.Name = &val
		delete(object, "name")
	}

	if raw, found := object["email"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'email': %w", err)
		}
		a.Email = &val
		delete(object, "email")
	}

	if raw, found := object["email_verified"]; found {
		var val bool
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'email_verified': %w", err)
		}
		a.EmailVerified = &val
		delete(object, "email_verified")
	}

	if raw, found := object["roles"]; found {
		if err := json.Unmarshal(raw, &a.Roles); err != nil {
			return fmt.Errorf("error reading 'roles': %w", err)
		}
		delete(object, "roles")
	}

	if raw, found := object["organizations"]; found {
		if err := json.Unmarshal(raw, &a.Organizations); err != nil {
			return fmt.Errorf("error reading 'organizations': %w", err)
		}
		delete(object, "organizations")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a UserInfoResponse) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["sub"], err = json.Marshal(a.Sub)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'sub': %w", err)
	}

	if a.PreferredUsername != nil {
		object["preferred_username"], err = json.Marshal(a.PreferredUsername)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'preferred_username': %w", err)
		}
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	if a.Email != nil {
		object["email"], err = json.Marshal(a.Email)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email': %w", err)
		}
	}

	if a.EmailVerified != nil {
		object["email_verified"], err = json.Marshal(a.EmailVerified)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'email_verified': %w", err)
		}
	}

	object["roles"], err = json.Marshal(a.Roles)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'roles': %w", err)
	}

	object["organizations"], err = json.Marshal(a.Organizations)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'organizations': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *UserInfoResponse) ApplyDefaults() {
}

// #/components/schemas/JWKSResponse
// JSON Web Key Set
type JWKSResponse struct {
	Keys []JWKSResponseKeysItem `form:"keys,omitempty" json:"keys,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *JWKSResponse) ApplyDefaults() {
}

// #/components/schemas/JWKSResponse/properties/keys
type JWKSResponseKeys = []JWKSResponseKeysItem

// #/components/schemas/JWKSResponse/properties/keys/items
type JWKSResponseKeysItem struct {
	// Key type.
	Kty *string `form:"kty,omitempty" json:"kty,omitempty"`
	// Key use.
	Use *string `form:"use,omitempty" json:"use,omitempty"`
	// Key ID.
	Kid *string `form:"kid,omitempty" json:"kid,omitempty"`
	// Algorithm.
	Alg *string `form:"alg,omitempty" json:"alg,omitempty"`
	// RSA modulus (for RSA keys).
	N *string `form:"n,omitempty" json:"n,omitempty"`
	// RSA exponent (for RSA keys).
	E *string `form:"e,omitempty" json:"e,omitempty"`
	// Elliptic curve name (for EC keys, e.g., "P-256").
	Crv *string `form:"crv,omitempty" json:"crv,omitempty"`
	// EC x-coordinate (for EC keys).
	X *string `form:"x,omitempty" json:"x,omitempty"`
	// EC y-coordinate (for EC keys).
	Y *string `form:"y,omitempty" json:"y,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *JWKSResponseKeysItem) ApplyDefaults() {
}

// #/components/schemas/OpenIDConfiguration
// OpenID Connect configuration
type OpenIDConfiguration struct {
	// OIDC issuer.
	Issuer *string `form:"issuer,omitempty" json:"issuer,omitempty"`
	// Authorization endpoint.
	AuthorizationEndpoint *string `form:"authorization_endpoint,omitempty" json:"authorization_endpoint,omitempty"`
	// Token endpoint.
	TokenEndpoint *string `form:"token_endpoint,omitempty" json:"token_endpoint,omitempty"`
	// UserInfo endpoint.
	UserinfoEndpoint *string `form:"userinfo_endpoint,omitempty" json:"userinfo_endpoint,omitempty"`
	// OIDC RP-Initiated Logout endpoint (end session at the issuer).
	EndSessionEndpoint *string `form:"end_session_endpoint,omitempty" json:"end_session_endpoint,omitempty"`
	// JWKS endpoint.
	JwksURI *string `form:"jwks_uri,omitempty" json:"jwks_uri,omitempty"`
	// Supported subject identifier types.
	SubjectTypesSupported []OpenIDConfigurationSubjectTypesSupportedItem `form:"subject_types_supported,omitempty" json:"subject_types_supported,omitempty"`
	// Supported response types.
	ResponseTypesSupported []string `form:"response_types_supported,omitempty" json:"response_types_supported,omitempty"`
	// Supported grant types.
	GrantTypesSupported []string `form:"grant_types_supported,omitempty" json:"grant_types_supported,omitempty"`
	// Supported scopes.
	ScopesSupported []string `form:"scopes_supported,omitempty" json:"scopes_supported,omitempty"`
	// Supported claims.
	ClaimsSupported []string `form:"claims_supported,omitempty" json:"claims_supported,omitempty"`
	// Supported signing algorithms.
	IDTokenSigningAlgValuesSupported []string `form:"id_token_signing_alg_values_supported,omitempty" json:"id_token_signing_alg_values_supported,omitempty"`
	// Supported authentication methods.
	TokenEndpointAuthMethodsSupported []string `form:"token_endpoint_auth_methods_supported,omitempty" json:"token_endpoint_auth_methods_supported,omitempty"`
	// Supported PKCE code challenge methods.
	CodeChallengeMethodsSupported []OpenIDConfigurationCodeChallengeMethodsSupportedItem `form:"code_challenge_methods_supported,omitempty" json:"code_challenge_methods_supported,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *OpenIDConfiguration) ApplyDefaults() {
}

// #/components/schemas/OpenIDConfiguration/properties/subject_types_supported
// Supported subject identifier types.
type OpenIDConfigurationSubjectTypesSupported = []OpenIDConfigurationSubjectTypesSupportedItem

// #/components/schemas/OpenIDConfiguration/properties/subject_types_supported/items
type OpenIDConfigurationSubjectTypesSupportedItem string

const (
	Public   OpenIDConfigurationSubjectTypesSupportedItem = "public"
	Pairwise OpenIDConfigurationSubjectTypesSupportedItem = "pairwise"
)

// #/components/schemas/OpenIDConfiguration/properties/code_challenge_methods_supported
// Supported PKCE code challenge methods.
type OpenIDConfigurationCodeChallengeMethodsSupported = []OpenIDConfigurationCodeChallengeMethodsSupportedItem

// #/components/schemas/OpenIDConfiguration/properties/code_challenge_methods_supported/items
type OpenIDConfigurationCodeChallengeMethodsSupportedItem string

const (
	OpenIDConfigurationCodeChallengeMethodsSupportedItemS256 OpenIDConfigurationCodeChallengeMethodsSupportedItem = "S256"
)

// #/paths//api/v1/auth/authorize/get/parameters/0/schema
type GetAPIV1AuthAuthorizeParameter0 string

const (
	Code  GetAPIV1AuthAuthorizeParameter0 = "code"
	Token GetAPIV1AuthAuthorizeParameter0 = "token"
)

// #/paths//api/v1/auth/authorize/get/parameters/6/schema
type GetAPIV1AuthAuthorizeParameter6 string

const (
	GetAPIV1AuthAuthorizeParameter6S256 GetAPIV1AuthAuthorizeParameter6 = "S256"
)

// #/paths//api/v1/auth/login/get/parameters/5/schema
type GetAPIV1AuthLoginParameter string

const (
	GetAPIV1AuthLoginParameterS256 GetAPIV1AuthLoginParameter = "S256"
)

// #/paths//api/v1/auth/login/post/requestBody/content/application/x-www-form-urlencoded/schema
type AuthLoginPostFormRequest struct {
	// Username for authentication
	Username string `form:"username" json:"username"`
	// Password for authentication
	Password string `form:"password" json:"password"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *AuthLoginPostFormRequest) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+wcXY/bNvJ9f8UgPSBeYG0n26Z3dV/OdRLUTdIs4g3yUAQGLY1lZilSJSl7feiPP5DU",
	"ByVL/lh7N2mx+1A0EjkzHM73jCwS5CShA/i+96z3/IzyuRicAWiqGQ7gNaPRQsNIcC0Fg6vhO3g/fjmC",
	"KymWNEQJw6vxGcASpaKCD2D5fIaaPD8DCFEFkibaPv7rDADM7u6MKAwdDJLqBXJNA2IWgUK5pAHCXMga",
	"2p7dfb2gqliUOPwK3g9TvbjsNwFMFeURqLXSGFvKO1csjSIyYwjD6tJ3IkwZqnODKRBck0APLFJOYhzA",
	"9QLrnLhGEtsVqWQDWGidqEG/P7eLAs16VNi3GBPKBqCRxP+tvWQ0QK7QxzNMSLBAuOw92wS9Wq16xL7v",
	"CRn1s92q/3Y8evX75FX3svest9AxOzMsQqkM3K4D0T/TJMoeOERVTllklfvawlWRoLT/p3pnCdELC7dP",
	"EtpfPu+btf3eChnr3nCx4n0jXTTsBoLPaZS6je7EEWYsBsipc3/dJurq9CXIxy/NZXAMNIRUBWKJcg3I",
	"w0RQrnvZroLacehO7XaOfHqypRJVIgxLS1KeXD579qT853YiggaY5s/IE3LtgwEgScKy8/W/qJwn5Z8K",
	"FhiT+lOAf0mcD+Dpd/1AxIngyLXqu7Wq33C0p+VRfrj8qf0o10JATPgaJP6ZotIKuiCJRmA0phrwNkAM",
	"Mfwqp7Ki+EpKIZ/WJc38R0j6PzyFSFk8kIN0wp6LkzVK1VeBCBHmTKxaRW2YU5ctSIgkMepMN3PKnELm",
	"wjfV6wQ9/lA+gD9TlGvvmbkjKjEcgJapv7iJvQbeAJSWlEeVF8jTeAB/mGNcgBY3yD+3CrpjTU6jhdnb",
	"OELAKHI9peEDkN9EnsMP45e9Bu6GVGKgp6mkD8LcuZAx0QOo4mtmqiMNPn4YbxKuArFTHI5km0XRgFkT",
	"fd+YDYpSKxokSoQ4DRaEMeTRCYkBiCl/izzSiwH88H31DbnN3zy//E/bCa7ejF45C1CQt4v8aYx6IcJT",
	"niJT4cnlix8/H0ApOEqgIzhbg9kNKk0SITWG5727esO3IqLcCj78ev3uLXToHFKFErjQvvnF8HyXG9F4",
	"q/smltnXfzRy6Mn3zy7byf2Q650WNcOekAhBSJiR4Ma8dXbFc6TbuPALCXMfCh3Kl4TRcJo9uADUQe/8",
	"G3CixUmet5/kIy+8a/gNkfzPiGKy07zYJkpjrlFywsAF9IBm87cWgTGj9SeIvjzrUYm5GqOyrVGXhbRH",
	"xPUYrtxDuPINBA1fL2R6DFf+vuHKA4Uk+8YOjw735KdJhDrCP11JEaBSwEqxUekspkpRwXswrEWQuduB",
	"TuFmLipm/cIZsiwkBCIRlBYSQ6AcCAfkgVwnGkMIhLihCAo1rBbIQS/Qp2JFFIRUJYysMdzuFK9EIVjZ",
	"ff0iwnXJhxZf0nBl/oXddlerVdfQ0k0lQ26UN6zeVfP9OQ0Rsy8Y6NqrRJoTaOqrc/5ncgprsDbebDE9",
	"TfFtBqco7WwIgEcPUWolZHgszqsMzj44AVaSanzP2XrDuVdua2Nnt+BRw6v8KHe1m5M0MIowT1kmhV2Q",
	"qFPJlR8bvN1Mq/Kwbi9LmzBC+VGmdnvSl1HYXEyEFdULIIx5inyX9M9aBx4VNwVziixUJrfMMkNQaA3I",
	"+ddkirWREKNSxItatieHtfbJnFCGYZHwQiAxNK8JU9/k0f6BpXBbwR2cwNNlMa6Ft1n/9i6d8DBbJXEu",
	"US1avc+1WXV6z7PJ1mambmOpJe2Do+npqT3coYiPMcb5TTgIX0M6sxM5Ap6epF6WP4gk4foCUl4E/u6R",
	"7Zb8HQtq5VldfHgOXRi5ggBpMq2P+cB92k4TLuVzD8d2EccvRza0HPO5qJpPiVpSXJqIwNbFDUYZW0it",
	"ljOHlL1XGKSS6rVP0wyJRGlON4A/Pt/VknysUfQ1rig/bKMNOVixrEE8f1Sc+1ScL6sbdQKl+W3y/nf4",
	"hDN4g2uYoIbOb5/eTM6r6uMcnL3b7Tpj9t5VDeqUfA2GG/qbVOAfKD9MRCLVJ5Cgv4rV1gB/uOqOOdWU",
	"aAzhrUUCndq4zsSlXvCOcBJhbJxwD0YMiVS2xkKVSlHmGZoXk9pyjAl+hUVOGFsXqa8yWaWJv6fuaFO/",
	"5uPqN1RDTHSwQAUEJEZUaZTe1WR9Ab/QDh1FYgSZMrNJ1RLrCooZUXi+rQwkUr1Hc6TtCHt3I+aEqfts",
	"R3xaoETD7IJP5s6sXyVzjRJYdutxqjQQRiPu0vqS4xUWq/PNgnjuRKaLatni3k5emy5z0gXjl5ntM2RA",
	"hwQB2sLg3NYRNNpaGZlRRvX6Z9ttLwsOImfE+SnmdU52tFoH7Gegc1CoL8DellUPe5/5SB2G2eK7tZzu",
	"8XJEQv5MMetKdRKiFIagF1Kk0WKrLSDKkenU0JmGfAHl0dbGxt6DDe3YrY4ExtrZGdmakduRdWaW027H",
	"0MhcqUsdLkBIwDjR61b8D1UUOjz3vDvJf5Mss9B6CAUqay626Ntj+HzS05TvDZA8m5uYpbmCe+ncmS/Z",
	"C62TM48MHGRLs4fuH68zz/nbp+vGQPvTNfxiF2YupSGyEubZZRW5e5Y9mjOx8qxRJRgZibDSmKm8/Ghn",
	"0RtL7t4WS9jmUu3VEB0TRFJvD7lh843B7PpEgO0vzSnDAQxt/cyYShs6ZM9bEuFimr+2yz6trJOCodpY",
	"Z59WCZ7PGeU4JXahsd22kJpfjn1a8WP29TbmGBaMw+zktUv0X5URYvlsE+6uSf49RvM3JCxTDEebXwWt",
	"Uev3BTd7XV0oC4Bn7U3DcpEvKS0ePptPyLjsYr+LqghP3bh03kTbNTFt0dfGpZv6ly0E8ZQxMjNyWuv/",
	"tTcyc8oy1B1j31Pl2so2NbLa60WDTa3No8ip9DgPJqe961m5lpNRW9U4V6bz8Di6e172F57u4oYN3xPU",
	"PzOwArdBRe7DT0ZK+0xahkthIFHfEz4HHDp5Qu1EJ50xGmRL9hMRa+hPTWNt2MtOSS1R0jlFeQyutpmu",
	"Qye6clp6nqaUYeupuVEtS1QSzTa5Nckd5QFLw2y6pVa9sMa/uN/2XmR1NIqEIXXSclXafS+/q3SjDnQt",
	"zvFOqyFH15Gxy+P4e/dgfuMnSHnYcIO8vNUS+/6uzMV6n9vDZsPXqnvKix4H0151+0XRouOmQzB0Ka6L",
	"IpxSAVX5pXqTfIdb+mY59ex6CRpvEypRTWkDXMo1Rii3M8sCcJKraWwiRWO9BA/VNgFWO/q0zcJs1BHg",
	"OxgyJlbeGus5s8Qinylh9AYdVy/ybH5alka8JORAVfCHzpvEHX2YuwWytcPrzHxDx7fMZos1zW3gcm/B",
	"BrlEObUUXoDGOBGSSMrW05STJaHW6O2K4OxuZ2g7H16P4Md///ATTDCwEvCid1nxS7fdSHRdWcokQlUm",
	"TX3wBwr1r2lMeFciCd3Hy5PReGxrJNl30JRHvnw0dBZzIvZzCXsUYI39p3bIZ7626GFRJXKFM/cpjS27",
	"eiQBmYnU1WstTdsUx7G/+PCw+Qrs/nrz8EA5V+lsi5SrdHbolU1SizLnUcVBJxLnKCWG0wOSgdo4agah",
	"SCdK6HeB9zplDKpgXK57IJxXZpMRRYlK1WDlUVND1DoTgiHh26G67fmPBWiiUw+Dy7g3ABMpiV8Jphpj",
	"dXi592ORvpcYhYwIz6KYe8ZcQdXbPXZwF+8iZ1RLItcOVMAIjW2vKUEJKsGgYL0F6vcot2haky7d4PoY",
	"djXMC7dPC9/4oxKHjw++wXUtOipS+GPBpmoD6g0Nj4XqJ27Z3bPoGKBDFglJ9SKuw+VHjeFOhhCLMGWp",
	"go5JHcwDIxfndTR4LBq8dQXXHXgCuTxqzpQx878BBKlcojWkDuGrkcV3AdiLehfw5Kp7+eLHJxvob49C",
	"PoLbbiCEDCm3XSgP8Qam9ZGY1jsx7Z6naPidigNtiOvNH5waGMvmtvaay9fTfOLkUNDDxlH3evJ2V+jX",
	"lVncainRBFZ3BrwxqOa5bB5O80TiruBbZzGKwZ4O8mIIHoj2Bi88yf2yulF7Bq61bsebScPJlIvMbNKg",
	"pkUqcUoXXuQ7roh1AQmhckVVe7oxycnIyfMCR4vFj3X83wq5pxO0EFf5CRCPpDINe1h6ygK7R4xrDT0o",
	"HQ6lXzU18dODkuBQbhZypopGnPJoSlg0XRKWPjRrHHoTibhQQrWZxamxxdl3pw9LY23mOiOhVvStfxp7",
	"37Zj63eyJe3tX8y2pArbfrXq7P8BAAD//2SFt1wOTgAA",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

const (
	emailRegexString = "^(?:(?:(?:(?:[a-zA-Z]|\\d|[!#\\$%&'\\*\\+\\-\\/=\\?\\^_`{\\|}~]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])+(?:\\.([a-zA-Z]|\\d|[!#\\$%&'\\*\\+\\-\\/=\\?\\^_`{\\|}~]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])+)*)|(?:(?:\\x22)(?:(?:(?:(?:\\x20|\\x09)*(?:\\x0d\\x0a))?(?:\\x20|\\x09)+)?(?:(?:[\\x01-\\x08\\x0b\\x0c\\x0e-\\x1f\\x7f]|\\x21|[\\x23-\\x5b]|[\\x5d-\\x7e]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])|(?:(?:[\\x01-\\x09\\x0b\\x0c\\x0d-\\x7f]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}]))))*(?:(?:(?:\\x20|\\x09)*(?:\\x0d\\x0a))?(\\x20|\\x09)+)?(?:\\x22))))@(?:(?:(?:[a-zA-Z]|\\d|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])|(?:(?:[a-zA-Z]|\\d|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])(?:[a-zA-Z]|\\d|-|\\.|~|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])*(?:[a-zA-Z]|\\d|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])))\\.)+(?:(?:[a-zA-Z]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])|(?:(?:[a-zA-Z]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])(?:[a-zA-Z]|\\d|-|\\.|~|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])*(?:[a-zA-Z]|[\\x{00A0}-\\x{D7FF}\\x{F900}-\\x{FDCF}\\x{FDF0}-\\x{FFEF}])))\\.?$"
)

var (
	emailRegex = regexp.MustCompile(emailRegexString)
)

// ErrValidationEmail is the sentinel error returned when an email fails validation
var ErrValidationEmail = errors.New("email: failed to pass regex validation")

// Email represents an email address.
// It is a string type that must pass regex validation before being marshalled
// to JSON or unmarshalled from JSON.
type Email string

func (e Email) MarshalJSON() ([]byte, error) {
	if !emailRegex.MatchString(string(e)) {
		return nil, ErrValidationEmail
	}

	return json.Marshal(string(e))
}

func (e *Email) UnmarshalJSON(data []byte) error {
	if e == nil {
		return nil
	}

	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}

	*e = Email(s)
	if !emailRegex.MatchString(s) {
		return ErrValidationEmail
	}

	return nil
}

// Nullable is a generic type that can distinguish between:
// - Field not provided (unspecified)
// - Field explicitly set to null
// - Field has a value
//
// This is implemented as a map[bool]T where:
// - Empty map: unspecified
// - map[false]T: explicitly null
// - map[true]T: has a value
type Nullable[T any] map[bool]T

// Get returns the value if set, or an error if null or unspecified.
func (n Nullable[T]) Get() (T, error) {
	if v, ok := n[true]; ok {
		return v, nil
	}
	var zero T
	if n.IsNull() {
		return zero, ErrNullableIsNull
	}
	return zero, ErrNullableNotSpecified
}

// MustGet returns the value or panics if null or unspecified.
func (n Nullable[T]) MustGet() T {
	v, err := n.Get()
	if err != nil {
		panic(err)
	}
	return v
}

// Set assigns a value.
func (n *Nullable[T]) Set(value T) {
	*n = Nullable[T]{true: value}
}

// SetNull marks the field as explicitly null.
func (n *Nullable[T]) SetNull() {
	*n = Nullable[T]{false: *new(T)}
}

// SetUnspecified clears the field (as if it was never set).
func (n *Nullable[T]) SetUnspecified() {
	*n = nil
}

// IsNull returns true if the field is explicitly null.
func (n Nullable[T]) IsNull() bool {
	if n == nil {
		return false
	}
	_, ok := n[false]
	return ok
}

// IsSpecified returns true if the field was provided (either null or a value).
func (n Nullable[T]) IsSpecified() bool {
	return len(n) > 0
}

// MarshalJSON implements json.Marshaler.
func (n Nullable[T]) MarshalJSON() ([]byte, error) {
	if n.IsNull() {
		return []byte("null"), nil
	}
	if v, ok := n[true]; ok {
		return json.Marshal(v)
	}
	// Unspecified - this shouldn't be called if omitempty is used correctly
	return []byte("null"), nil
}

// UnmarshalJSON implements json.Unmarshaler.
func (n *Nullable[T]) UnmarshalJSON(data []byte) error {
	if string(data) == "null" {
		n.SetNull()
		return nil
	}
	var v T
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	n.Set(v)
	return nil
}

// ErrNullableIsNull is returned when trying to get a value from a null Nullable.
var ErrNullableIsNull = errors.New("nullable value is null")

// ErrNullableNotSpecified is returned when trying to get a value from an unspecified Nullable.
var ErrNullableNotSpecified = errors.New("nullable value is not specified")

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------
