// Code generated by oapi-codegen; DO NOT EDIT.

package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"time"

	ext_66c3f5a7 "github.com/flightctl/flightctl/api/core/v1beta1"
)

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
type APIVersion = string

// Semantic version identifier (e.g., 1.2.3, 2.0.0-rc1)
type SemVer = string

// Semver range constraint (e.g., >=1.0.0 <2.0.0). Space-separated terms, each with optional operator (>=, <=, >, <, =, ~, ^) followed by a version.
type SemVerRange = string

// #/components/schemas/Catalog
type Catalog struct {
	APIVersion           string                  `form:"apiVersion" json:"apiVersion"`
	Kind                 string                  `form:"kind" json:"kind"`
	Metadata             ext_66c3f5a7.ObjectMeta `form:"metadata" json:"metadata"`
	Spec                 CatalogSpec             `form:"spec" json:"spec"`
	Status               *CatalogStatus          `form:"status,omitempty" json:"status,omitempty"`
	AdditionalProperties map[string]any          `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a Catalog) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *Catalog) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *Catalog) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apiVersion"]; found {
		if err := json.Unmarshal(raw, &a.APIVersion); err != nil {
			return fmt.Errorf("error reading 'apiVersion': %w", err)
		}
		delete(object, "apiVersion")
	}

	if raw, found := object["kind"]; found {
		if err := json.Unmarshal(raw, &a.Kind); err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["metadata"]; found {
		if err := json.Unmarshal(raw, &a.Metadata); err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["spec"]; found {
		if err := json.Unmarshal(raw, &a.Spec); err != nil {
			return fmt.Errorf("error reading 'spec': %w", err)
		}
		delete(object, "spec")
	}

	if raw, found := object["status"]; found {
		var val CatalogStatus
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		a.Status = &val
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a Catalog) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["apiVersion"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'apiVersion': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	object["spec"], err = json.Marshal(a.Spec)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'spec': %w", err)
	}

	if a.Status != nil {
		object["status"], err = json.Marshal(a.Status)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'status': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Catalog) ApplyDefaults() {
	if s.Status != nil {
		s.Status.ApplyDefaults()
	}
}

// #/components/schemas/CatalogSpec
// CatalogSpec describes the configuration of a catalog. Catalogs are containers for locally-managed CatalogItems.
type CatalogSpec struct {
	DisplayName          *string        `form:"displayName,omitempty" json:"displayName,omitempty"`
	ShortDescription     *string        `form:"shortDescription,omitempty" json:"shortDescription,omitempty"`
	Icon                 *string        `form:"icon,omitempty" json:"icon,omitempty"`
	Provider             *string        `form:"provider,omitempty" json:"provider,omitempty"`
	Support              *string        `form:"support,omitempty" json:"support,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogSpec) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogSpec) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["displayName"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'displayName': %w", err)
		}
		a.DisplayName = &val
		delete(object, "displayName")
	}

	if raw, found := object["shortDescription"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'shortDescription': %w", err)
		}
		a.ShortDescription = &val
		delete(object, "shortDescription")
	}

	if raw, found := object["icon"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'icon': %w", err)
		}
		a.Icon = &val
		delete(object, "icon")
	}

	if raw, found := object["provider"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		a.Provider = &val
		delete(object, "provider")
	}

	if raw, found := object["support"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'support': %w", err)
		}
		a.Support = &val
		delete(object, "support")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.DisplayName != nil {
		object["displayName"], err = json.Marshal(a.DisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'displayName': %w", err)
		}
	}

	if a.ShortDescription != nil {
		object["shortDescription"], err = json.Marshal(a.ShortDescription)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'shortDescription': %w", err)
		}
	}

	if a.Icon != nil {
		object["icon"], err = json.Marshal(a.Icon)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'icon': %w", err)
		}
	}

	if a.Provider != nil {
		object["provider"], err = json.Marshal(a.Provider)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider': %w", err)
		}
	}

	if a.Support != nil {
		object["support"], err = json.Marshal(a.Support)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'support': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogSpec) ApplyDefaults() {
}

// #/components/schemas/CatalogStatus
// CatalogStatus represents the current status of a catalog source.
type CatalogStatus struct {
	Conditions           []ext_66c3f5a7.Condition `form:"conditions" json:"conditions"`
	AdditionalProperties map[string]any           `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogStatus) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogStatus) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogStatus) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["conditions"]; found {
		if err := json.Unmarshal(raw, &a.Conditions); err != nil {
			return fmt.Errorf("error reading 'conditions': %w", err)
		}
		delete(object, "conditions")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogStatus) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["conditions"], err = json.Marshal(a.Conditions)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'conditions': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogStatus) ApplyDefaults() {
}

// #/components/schemas/CatalogList
// CatalogList is a list of Catalogs.
type CatalogList struct {
	APIVersion           string                `form:"apiVersion" json:"apiVersion"`
	Kind                 string                `form:"kind" json:"kind"`
	Metadata             ext_66c3f5a7.ListMeta `form:"metadata" json:"metadata"`
	Items                []Catalog             `form:"items" json:"items"`
	AdditionalProperties map[string]any        `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogList) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogList) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogList) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apiVersion"]; found {
		if err := json.Unmarshal(raw, &a.APIVersion); err != nil {
			return fmt.Errorf("error reading 'apiVersion': %w", err)
		}
		delete(object, "apiVersion")
	}

	if raw, found := object["kind"]; found {
		if err := json.Unmarshal(raw, &a.Kind); err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["metadata"]; found {
		if err := json.Unmarshal(raw, &a.Metadata); err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["items"]; found {
		if err := json.Unmarshal(raw, &a.Items); err != nil {
			return fmt.Errorf("error reading 'items': %w", err)
		}
		delete(object, "items")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogList) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["apiVersion"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'apiVersion': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	object["items"], err = json.Marshal(a.Items)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'items': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogList) ApplyDefaults() {
}

// #/components/schemas/CatalogList/properties/items
// List of Catalogs.
type CatalogListItem = []Catalog

// #/components/schemas/CatalogItemMeta
// Metadata for CatalogItem resources. Extends ObjectMeta with catalog scoping.
type CatalogItemMeta struct {
	CreationTimestamp    *time.Time        `form:"creationTimestamp,omitempty" json:"creationTimestamp,omitempty"`
	DeletionTimestamp    *time.Time        `form:"deletionTimestamp,omitempty" json:"deletionTimestamp,omitempty"`
	Name                 string            `form:"name" json:"name"`
	Labels               map[string]string `form:"labels,omitempty" json:"labels,omitempty"`
	Generation           *int64            `form:"generation,omitempty" json:"generation,omitempty"`
	Owner                *string           `form:"owner,omitempty" json:"owner,omitempty"`
	Annotations          map[string]string `form:"annotations,omitempty" json:"annotations,omitempty"`
	ResourceVersion      *string           `form:"resourceVersion,omitempty" json:"resourceVersion,omitempty"`
	Catalog              string            `form:"catalog" json:"catalog"`
	AdditionalProperties map[string]any    `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogItemMeta) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogItemMeta) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogItemMeta) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["creationTimestamp"]; found {
		var val time.Time
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'creationTimestamp': %w", err)
		}
		a.CreationTimestamp = &val
		delete(object, "creationTimestamp")
	}

	if raw, found := object["deletionTimestamp"]; found {
		var val time.Time
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'deletionTimestamp': %w", err)
		}
		a.DeletionTimestamp = &val
		delete(object, "deletionTimestamp")
	}

	if raw, found := object["name"]; found {
		if err := json.Unmarshal(raw, &a.Name); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		delete(object, "name")
	}

	if raw, found := object["labels"]; found {
		if err := json.Unmarshal(raw, &a.Labels); err != nil {
			return fmt.Errorf("error reading 'labels': %w", err)
		}
		delete(object, "labels")
	}

	if raw, found := object["generation"]; found {
		var val int64
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'generation': %w", err)
		}
		a.Generation = &val
		delete(object, "generation")
	}

	if raw, found := object["owner"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'owner': %w", err)
		}
		a.Owner = &val
		delete(object, "owner")
	}

	if raw, found := object["annotations"]; found {
		if err := json.Unmarshal(raw, &a.Annotations); err != nil {
			return fmt.Errorf("error reading 'annotations': %w", err)
		}
		delete(object, "annotations")
	}

	if raw, found := object["resourceVersion"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'resourceVersion': %w", err)
		}
		a.ResourceVersion = &val
		delete(object, "resourceVersion")
	}

	if raw, found := object["catalog"]; found {
		if err := json.Unmarshal(raw, &a.Catalog); err != nil {
			return fmt.Errorf("error reading 'catalog': %w", err)
		}
		delete(object, "catalog")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogItemMeta) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.CreationTimestamp != nil {
		object["creationTimestamp"], err = json.Marshal(a.CreationTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'creationTimestamp': %w", err)
		}
	}

	if a.DeletionTimestamp != nil {
		object["deletionTimestamp"], err = json.Marshal(a.DeletionTimestamp)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deletionTimestamp': %w", err)
		}
	}

	object["name"], err = json.Marshal(a.Name)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'name': %w", err)
	}

	object["labels"], err = json.Marshal(a.Labels)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'labels': %w", err)
	}

	if a.Generation != nil {
		object["generation"], err = json.Marshal(a.Generation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'generation': %w", err)
		}
	}

	if a.Owner != nil {
		object["owner"], err = json.Marshal(a.Owner)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'owner': %w", err)
		}
	}

	object["annotations"], err = json.Marshal(a.Annotations)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'annotations': %w", err)
	}

	if a.ResourceVersion != nil {
		object["resourceVersion"], err = json.Marshal(a.ResourceVersion)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'resourceVersion': %w", err)
		}
	}

	object["catalog"], err = json.Marshal(a.Catalog)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'catalog': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItemMeta) ApplyDefaults() {
}

// #/components/schemas/CatalogItemMeta/properties/labels
// Map of string keys and values that can be used to organize and categorize (scope and select) objects.
type CatalogItemMetaLabels = map[string]string

// #/components/schemas/CatalogItemMeta/properties/annotations
// Properties set by the service.
type CatalogItemMetaAnnotations = map[string]string

// #/components/schemas/CatalogItem
// CatalogItem represents an application template from a catalog. It provides default configuration values that can be customized when adding the application to a fleet.
type CatalogItem struct {
	APIVersion           string          `form:"apiVersion" json:"apiVersion"`
	Kind                 string          `form:"kind" json:"kind"`
	Metadata             CatalogItemMeta `form:"metadata" json:"metadata"`
	Spec                 CatalogItemSpec `form:"spec" json:"spec"`
	AdditionalProperties map[string]any  `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogItem) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogItem) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogItem) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apiVersion"]; found {
		if err := json.Unmarshal(raw, &a.APIVersion); err != nil {
			return fmt.Errorf("error reading 'apiVersion': %w", err)
		}
		delete(object, "apiVersion")
	}

	if raw, found := object["kind"]; found {
		if err := json.Unmarshal(raw, &a.Kind); err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["metadata"]; found {
		if err := json.Unmarshal(raw, &a.Metadata); err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["spec"]; found {
		if err := json.Unmarshal(raw, &a.Spec); err != nil {
			return fmt.Errorf("error reading 'spec': %w", err)
		}
		delete(object, "spec")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogItem) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["apiVersion"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'apiVersion': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	object["spec"], err = json.Marshal(a.Spec)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'spec': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItem) ApplyDefaults() {
}

// #/components/schemas/CatalogItemArtifact
// An artifact reference. The type field is the discriminator and must be unique within the artifacts list.
type CatalogItemArtifact struct {
	Type                 CatalogItemArtifactType `form:"type" json:"type"`
	Name                 *string                 `form:"name,omitempty" json:"name,omitempty"`
	URI                  string                  `form:"uri" json:"uri"`
	AdditionalProperties map[string]any          `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogItemArtifact) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogItemArtifact) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogItemArtifact) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["type"]; found {
		if err := json.Unmarshal(raw, &a.Type); err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["name"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'name': %w", err)
		}
		a.Name = &val
		delete(object, "name")
	}

	if raw, found := object["uri"]; found {
		if err := json.Unmarshal(raw, &a.URI); err != nil {
			return fmt.Errorf("error reading 'uri': %w", err)
		}
		delete(object, "uri")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogItemArtifact) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	if a.Name != nil {
		object["name"], err = json.Marshal(a.Name)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'name': %w", err)
		}
	}

	object["uri"], err = json.Marshal(a.URI)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'uri': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItemArtifact) ApplyDefaults() {
}

// #/components/schemas/CatalogItemArtifactType
// Artifact format discriminator. Must be unique within the artifacts list. Includes bootc-image-builder output formats.
type CatalogItemArtifactType string

const (
	CatalogItemArtifactTypeContainer   CatalogItemArtifactType = "container"
	CatalogItemArtifactTypeQcow2       CatalogItemArtifactType = "qcow2"
	CatalogItemArtifactTypeAmi         CatalogItemArtifactType = "ami"
	CatalogItemArtifactTypeIso         CatalogItemArtifactType = "iso"
	CatalogItemArtifactTypeAnacondaIso CatalogItemArtifactType = "anaconda-iso"
	CatalogItemArtifactTypeVmdk        CatalogItemArtifactType = "vmdk"
	CatalogItemArtifactTypeVhd         CatalogItemArtifactType = "vhd"
	CatalogItemArtifactTypeRaw         CatalogItemArtifactType = "raw"
	CatalogItemArtifactTypeGce         CatalogItemArtifactType = "gce"
)

// #/components/schemas/CatalogItemConfigurable
// Configuration fields that can be specified at item level (as defaults) and overridden at version level. Version-level values fully replace item-level values (not merged).
type CatalogItemConfigurable struct {
	// Configuration values (envVars, ports, volumes, resources, etc.).
	Config map[string]any `form:"config,omitempty" json:"config,omitempty"`
	// JSON Schema defining configurable parameters and their validation.
	ConfigSchema map[string]any `form:"configSchema,omitempty" json:"configSchema,omitempty"`
	// Detailed documentation, preferably in markdown format.
	Readme *string `form:"readme,omitempty" json:"readme,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItemConfigurable) ApplyDefaults() {
}

// #/components/schemas/CatalogItemConfigurable/properties/config
// Configuration values (envVars, ports, volumes, resources, etc.).
type CatalogItemConfigurableConfig = map[string]any

// #/components/schemas/CatalogItemConfigurable/properties/configSchema
// JSON Schema defining configurable parameters and their validation.
type CatalogItemConfigurableConfigSchema = map[string]any

// #/components/schemas/CatalogItemSpec
// CatalogItemSpec defines the configuration for a catalog item.
type CatalogItemSpec struct {
	Category             *CatalogItemCategory     `form:"category,omitempty" json:"category,omitempty"`
	Type                 CatalogItemType          `form:"type" json:"type"`
	Artifacts            []CatalogItemArtifact    `form:"artifacts" json:"artifacts"`
	Versions             []CatalogItemVersion     `form:"versions" json:"versions"`
	Defaults             *CatalogItemConfigurable `form:"defaults,omitempty" json:"defaults,omitempty"`
	DisplayName          *string                  `form:"displayName,omitempty" json:"displayName,omitempty"`
	ShortDescription     *string                  `form:"shortDescription,omitempty" json:"shortDescription,omitempty"`
	Icon                 *string                  `form:"icon,omitempty" json:"icon,omitempty"`
	Deprecation          *CatalogItemDeprecation  `form:"deprecation,omitempty" json:"deprecation,omitempty"`
	Provider             *string                  `form:"provider,omitempty" json:"provider,omitempty"`
	Support              *string                  `form:"support,omitempty" json:"support,omitempty"`
	Homepage             *string                  `form:"homepage,omitempty" json:"homepage,omitempty"`
	DocumentationURL     *string                  `form:"documentationUrl,omitempty" json:"documentationUrl,omitempty"`
	AdditionalProperties map[string]any           `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogItemSpec) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogItemSpec) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogItemSpec) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["category"]; found {
		var val CatalogItemCategory
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'category': %w", err)
		}
		a.Category = &val
		delete(object, "category")
	}

	if raw, found := object["type"]; found {
		if err := json.Unmarshal(raw, &a.Type); err != nil {
			return fmt.Errorf("error reading 'type': %w", err)
		}
		delete(object, "type")
	}

	if raw, found := object["artifacts"]; found {
		if err := json.Unmarshal(raw, &a.Artifacts); err != nil {
			return fmt.Errorf("error reading 'artifacts': %w", err)
		}
		delete(object, "artifacts")
	}

	if raw, found := object["versions"]; found {
		if err := json.Unmarshal(raw, &a.Versions); err != nil {
			return fmt.Errorf("error reading 'versions': %w", err)
		}
		delete(object, "versions")
	}

	if raw, found := object["defaults"]; found {
		var val CatalogItemConfigurable
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'defaults': %w", err)
		}
		a.Defaults = &val
		delete(object, "defaults")
	}

	if raw, found := object["displayName"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'displayName': %w", err)
		}
		a.DisplayName = &val
		delete(object, "displayName")
	}

	if raw, found := object["shortDescription"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'shortDescription': %w", err)
		}
		a.ShortDescription = &val
		delete(object, "shortDescription")
	}

	if raw, found := object["icon"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'icon': %w", err)
		}
		a.Icon = &val
		delete(object, "icon")
	}

	if raw, found := object["deprecation"]; found {
		var val CatalogItemDeprecation
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'deprecation': %w", err)
		}
		a.Deprecation = &val
		delete(object, "deprecation")
	}

	if raw, found := object["provider"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'provider': %w", err)
		}
		a.Provider = &val
		delete(object, "provider")
	}

	if raw, found := object["support"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'support': %w", err)
		}
		a.Support = &val
		delete(object, "support")
	}

	if raw, found := object["homepage"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'homepage': %w", err)
		}
		a.Homepage = &val
		delete(object, "homepage")
	}

	if raw, found := object["documentationUrl"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'documentationUrl': %w", err)
		}
		a.DocumentationURL = &val
		delete(object, "documentationUrl")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogItemSpec) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	if a.Category != nil {
		object["category"], err = json.Marshal(a.Category)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'category': %w", err)
		}
	}

	object["type"], err = json.Marshal(a.Type)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'type': %w", err)
	}

	object["artifacts"], err = json.Marshal(a.Artifacts)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'artifacts': %w", err)
	}

	object["versions"], err = json.Marshal(a.Versions)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'versions': %w", err)
	}

	if a.Defaults != nil {
		object["defaults"], err = json.Marshal(a.Defaults)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'defaults': %w", err)
		}
	}

	if a.DisplayName != nil {
		object["displayName"], err = json.Marshal(a.DisplayName)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'displayName': %w", err)
		}
	}

	if a.ShortDescription != nil {
		object["shortDescription"], err = json.Marshal(a.ShortDescription)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'shortDescription': %w", err)
		}
	}

	if a.Icon != nil {
		object["icon"], err = json.Marshal(a.Icon)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'icon': %w", err)
		}
	}

	if a.Deprecation != nil {
		object["deprecation"], err = json.Marshal(a.Deprecation)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'deprecation': %w", err)
		}
	}

	if a.Provider != nil {
		object["provider"], err = json.Marshal(a.Provider)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'provider': %w", err)
		}
	}

	if a.Support != nil {
		object["support"], err = json.Marshal(a.Support)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'support': %w", err)
		}
	}

	if a.Homepage != nil {
		object["homepage"], err = json.Marshal(a.Homepage)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'homepage': %w", err)
		}
	}

	if a.DocumentationURL != nil {
		object["documentationUrl"], err = json.Marshal(a.DocumentationURL)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'documentationUrl': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItemSpec) ApplyDefaults() {
	if s.Defaults != nil {
		s.Defaults.ApplyDefaults()
	}
	if s.Deprecation != nil {
		s.Deprecation.ApplyDefaults()
	}
}

// #/components/schemas/CatalogItemSpec/properties/artifacts
// Artifact definitions for this catalog item. Defined once; version references resolve each artifact independently. Type must be unique within the list.
type CatalogItemSpecArtifacts = []CatalogItemArtifact

// #/components/schemas/CatalogItemSpec/properties/versions
// Available versions using Cincinnati model. Use replaces for primary edge, skips when stable channel skips intermediate versions.
type CatalogItemSpecVersions = []CatalogItemVersion

// #/components/schemas/CatalogItemVersion
// A version of a catalog item following the Cincinnati model where versions
// are nodes in an upgrade graph and channels are labels on those nodes.
// Upgrade edges are defined by replaces (single), skips (multiple), or
// skipRange (semver range). Includes CatalogItemConfigurable fields that
// override item-level defaults.
type CatalogItemVersion struct {
	// Configuration values (envVars, ports, volumes, resources, etc.).
	Config map[string]any `form:"config,omitempty" json:"config,omitempty"`
	// JSON Schema defining configurable parameters and their validation.
	ConfigSchema map[string]any `form:"configSchema,omitempty" json:"configSchema,omitempty"`
	// Detailed documentation, preferably in markdown format.
	Readme *string `form:"readme,omitempty" json:"readme,omitempty"`
	// Semantic version identifier (e.g., 1.2.3, 2.0.0-rc1). Required for version ordering and upgrade graph.
	Version string `form:"version" json:"version"`
	// Map of artifact type to image tag or digest. Keys must match a type in spec.artifacts. Only keyed artifacts are available for this version.
	References map[string]string `form:"references" json:"references"`
	// Channels this version belongs to.
	Channels []string `form:"channels" json:"channels"`
	// The single version this one replaces, defining the primary upgrade edge.
	Replaces string `form:"replaces,omitempty" json:"replaces,omitempty"`
	// Additional versions that can upgrade directly to this one. Use when stable channel skips intermediate fast-only versions.
	Skips []SemVer `form:"skips,omitempty" json:"skips,omitempty"`
	// Semver range of versions that can upgrade directly to this one. Use for z-stream updates or hotfixes.
	SkipRange   string                  `form:"skipRange,omitempty" json:"skipRange,omitempty"`
	Deprecation *CatalogItemDeprecation `form:"deprecation,omitempty" json:"deprecation,omitempty"`
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItemVersion) ApplyDefaults() {
	if s.Deprecation != nil {
		s.Deprecation.ApplyDefaults()
	}
}

// #/components/schemas/CatalogItemVersion/allOf/1/properties/version
// Semantic version identifier (e.g., 1.2.3, 2.0.0-rc1). Required for version ordering and upgrade graph.
type CatalogItemVersionAllOf1Version = string

// #/components/schemas/CatalogItemVersion/allOf/1/properties/references
// Map of artifact type to image tag or digest. Keys must match a type in spec.artifacts. Only keyed artifacts are available for this version.
type CatalogItemVersionAllOf1References = map[string]string

// #/components/schemas/CatalogItemVersion/allOf/1/properties/replaces
// The single version this one replaces, defining the primary upgrade edge.
type CatalogItemVersionAllOf1Replaces = string

// #/components/schemas/CatalogItemVersion/allOf/1/properties/skipRange
// Semver range of versions that can upgrade directly to this one. Use for z-stream updates or hotfixes.
type CatalogItemVersionAllOf1SkipRange = string

// #/components/schemas/CatalogItemList
// CatalogItemList is a list of CatalogItems.
type CatalogItemList struct {
	APIVersion           string                `form:"apiVersion" json:"apiVersion"`
	Kind                 string                `form:"kind" json:"kind"`
	Metadata             ext_66c3f5a7.ListMeta `form:"metadata" json:"metadata"`
	Items                []CatalogItem         `form:"items" json:"items"`
	AdditionalProperties map[string]any        `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogItemList) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogItemList) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogItemList) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apiVersion"]; found {
		if err := json.Unmarshal(raw, &a.APIVersion); err != nil {
			return fmt.Errorf("error reading 'apiVersion': %w", err)
		}
		delete(object, "apiVersion")
	}

	if raw, found := object["kind"]; found {
		if err := json.Unmarshal(raw, &a.Kind); err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["metadata"]; found {
		if err := json.Unmarshal(raw, &a.Metadata); err != nil {
			return fmt.Errorf("error reading 'metadata': %w", err)
		}
		delete(object, "metadata")
	}

	if raw, found := object["items"]; found {
		if err := json.Unmarshal(raw, &a.Items); err != nil {
			return fmt.Errorf("error reading 'items': %w", err)
		}
		delete(object, "items")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogItemList) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["apiVersion"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'apiVersion': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["metadata"], err = json.Marshal(a.Metadata)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'metadata': %w", err)
	}

	object["items"], err = json.Marshal(a.Items)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'items': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItemList) ApplyDefaults() {
}

// #/components/schemas/CatalogItemList/properties/items
// List of CatalogItems.
type CatalogItemListItem = []CatalogItem

// #/components/schemas/CatalogItemCategory
// Category of a catalog item.
type CatalogItemCategory string

const (
	CatalogItemCategorySystem      CatalogItemCategory = "system"
	CatalogItemCategoryApplication CatalogItemCategory = "application"
)

// #/components/schemas/CatalogItemType
// Type of catalog item within its category.
type CatalogItemType string

const (
	CatalogItemTypeOS        CatalogItemType = "os"
	CatalogItemTypeFirmware  CatalogItemType = "firmware"
	CatalogItemTypeDriver    CatalogItemType = "driver"
	CatalogItemTypeContainer CatalogItemType = "container"
	CatalogItemTypeHelm      CatalogItemType = "helm"
	CatalogItemTypeQuadlet   CatalogItemType = "quadlet"
	CatalogItemTypeCompose   CatalogItemType = "compose"
	CatalogItemTypeData      CatalogItemType = "data"
)

// #/components/schemas/CatalogItemDeprecation
// Deprecation information for a catalog item or version. Presence indicates deprecated status.
type CatalogItemDeprecation struct {
	Message              string         `form:"message" json:"message"`
	Replacement          *string        `form:"replacement,omitempty" json:"replacement,omitempty"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a CatalogItemDeprecation) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *CatalogItemDeprecation) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *CatalogItemDeprecation) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["message"]; found {
		if err := json.Unmarshal(raw, &a.Message); err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if raw, found := object["replacement"]; found {
		var val string
		if err := json.Unmarshal(raw, &val); err != nil {
			return fmt.Errorf("error reading 'replacement': %w", err)
		}
		a.Replacement = &val
		delete(object, "replacement")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a CatalogItemDeprecation) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["message"], err = json.Marshal(a.Message)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'message': %w", err)
	}

	if a.Replacement != nil {
		object["replacement"], err = json.Marshal(a.Replacement)
		if err != nil {
			return nil, fmt.Errorf("error marshaling 'replacement': %w", err)
		}
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *CatalogItemDeprecation) ApplyDefaults() {
}

// #/components/schemas/Status
// Status is a return value for calls that don't return other objects.
type Status struct {
	APIVersion           string         `form:"apiVersion" json:"apiVersion"`
	Kind                 string         `form:"kind" json:"kind"`
	Code                 int32          `form:"code" json:"code"`
	Message              string         `form:"message" json:"message"`
	Reason               string         `form:"reason" json:"reason"`
	Status               string         `form:"status" json:"status"`
	AdditionalProperties map[string]any `json:"-"`
}

// Get returns the specified additional property value and whether it was found.
func (a Status) Get(fieldName string) (value any, found bool) {
	if a.AdditionalProperties != nil {
		value, found = a.AdditionalProperties[fieldName]
	}
	return
}

// Set sets an additional property value.
func (a *Status) Set(fieldName string, value any) {
	if a.AdditionalProperties == nil {
		a.AdditionalProperties = make(map[string]any)
	}
	a.AdditionalProperties[fieldName] = value
}

func (a *Status) UnmarshalJSON(b []byte) error {
	object := make(map[string]json.RawMessage)
	err := json.Unmarshal(b, &object)
	if err != nil {
		return err
	}

	if raw, found := object["apiVersion"]; found {
		if err := json.Unmarshal(raw, &a.APIVersion); err != nil {
			return fmt.Errorf("error reading 'apiVersion': %w", err)
		}
		delete(object, "apiVersion")
	}

	if raw, found := object["kind"]; found {
		if err := json.Unmarshal(raw, &a.Kind); err != nil {
			return fmt.Errorf("error reading 'kind': %w", err)
		}
		delete(object, "kind")
	}

	if raw, found := object["code"]; found {
		if err := json.Unmarshal(raw, &a.Code); err != nil {
			return fmt.Errorf("error reading 'code': %w", err)
		}
		delete(object, "code")
	}

	if raw, found := object["message"]; found {
		if err := json.Unmarshal(raw, &a.Message); err != nil {
			return fmt.Errorf("error reading 'message': %w", err)
		}
		delete(object, "message")
	}

	if raw, found := object["reason"]; found {
		if err := json.Unmarshal(raw, &a.Reason); err != nil {
			return fmt.Errorf("error reading 'reason': %w", err)
		}
		delete(object, "reason")
	}

	if raw, found := object["status"]; found {
		if err := json.Unmarshal(raw, &a.Status); err != nil {
			return fmt.Errorf("error reading 'status': %w", err)
		}
		delete(object, "status")
	}

	if len(object) != 0 {
		a.AdditionalProperties = make(map[string]any)
		for fieldName, fieldBuf := range object {
			var fieldVal any
			err := json.Unmarshal(fieldBuf, &fieldVal)
			if err != nil {
				return fmt.Errorf("error unmarshaling field %s: %w", fieldName, err)
			}
			a.AdditionalProperties[fieldName] = fieldVal
		}
	}
	return nil
}

func (a Status) MarshalJSON() ([]byte, error) {
	var err error
	object := make(map[string]json.RawMessage)

	object["apiVersion"], err = json.Marshal(a.APIVersion)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'apiVersion': %w", err)
	}

	object["kind"], err = json.Marshal(a.Kind)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'kind': %w", err)
	}

	object["code"], err = json.Marshal(a.Code)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'code': %w", err)
	}

	object["message"], err = json.Marshal(a.Message)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'message': %w", err)
	}

	object["reason"], err = json.Marshal(a.Reason)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'reason': %w", err)
	}

	object["status"], err = json.Marshal(a.Status)
	if err != nil {
		return nil, fmt.Errorf("error marshaling 'status': %w", err)
	}

	for fieldName, field := range a.AdditionalProperties {
		object[fieldName], err = json.Marshal(field)
		if err != nil {
			return nil, fmt.Errorf("error marshaling '%s': %w", fieldName, err)
		}
	}
	return json.Marshal(object)
}

// ApplyDefaults sets default values for fields that are nil.
func (s *Status) ApplyDefaults() {
}

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+xde3fbNrL/359i1tlzZLcW/cjjNrpNe71O0vU2abKxkz3npukeiBxJWIMAA4By1Nvd",
	"z34PAIIEKUqWZTuJE+aPHIvEYzAYzPxmMABFhpxkdAB3o71of4PykRhsAGiqGQ7gKaPjiYYjwbUUDA5f",
	"Hm8ATFEqKvgApvuEZROyvwGQoIolzbR9/scGAMDbeuV3WxOtMzXY3R3Z57FmERXbQBUQUCinNEYYCQkJ",
	"xoxIoukUISWcjDFFrkGMYMQQtTJ/YTJGSNDUUUB4AnqCVMK5kGdMkERFG5aE0wlVhmhPMmx5krchFlwT",
	"yhXYB32lyRhBohK5NI3qCdFAJILKh//CWIMWEE8IH2O0Aa5yrAe2F05SHMDpBJvsOkWS2hK5ZANoG759",
	"iymhbAAaSfo/jZeMxsgVhv0cZiSeIBxEe/NNn5+fR8S+j4Qc7xa11e6z46Mnv5w86R9Ee9FEp2zD8Bul",
	"Mu32XRO7JKO70/0NTcbFY9ddTDRhYmz7qk3yiwzNJAmuQHA4csUqBkYbGdET29Ru0QbVmCo3lA99X7Ds",
	"wb61L8dYMBbAU+P+9WvUNOh5RpX2ZBybtoDEUigzv8w/V1FRU3jij5MBMKr0IWNh3aJYRiRJURec8kQU",
	"jBFcU55j+QKA8gG8z1HOgmc1Gg85CPsnYVXbRrJsLUiFtCKYM61gJEVqxBrcXEVWwKaE5WgWgHlRtZDm",
	"SkNKdDyxL2qlep7QHowosgQod7UlTqnIlR2+6TUTXGEUkC7xfU4lJgMYEabCgap4gikZBE8A9CzDASgt",
	"KR/PMYuRIbITZBhrIS/FMVBFLcMmiaZ9sxgn6OgWI5Coc8kxAWEXqoLhrFAHtlcVwWMcEctTLQCnKGd6",
	"Qvk4usqALCs/+oBsr2oHVJ5lQmrKx4UkC2nm8Qyh96i3A71H5n+jFnt/etSDLYzG0Q5snuFs/5GVjf2d",
	"M5wd/Mn9ONjcvhIrGE2pvgwLjCCn5ANN8xR4ng5RulE7uS9HX8hpXTxtZbci4JwyBgr1UjGvVQc6qi8y",
	"/ECVdo36+sXqSYllOochgsowpiOKCRAVrDrKjeXKhwrf58ZC2UFfdQFRrnGMsvZmJGRKtH1396D2JqXc",
	"sHEAe/XHjrsD2N/b8288DwJVtnmwt7c5WDRNL34O3hjuINd1ikmWMRpbPbr7LyV4/W37KM2/P0scDaB3",
	"ZzcWaSY4cq12XVm1G2hho9F7FbH3lhH7F5LAKzMPSn8Kqk800bmqEbu/mNjXnOR6IiT9HZPPhNq7i6l9",
	"KuSQJgnyz4PUg4eLST0VAp4TPvOioD4Lku8v4+5JgXxfczIllJEhw09LtEdri5HadaG0ECwugGVHYY+3",
	"Ao91cKyDYx0c6+DYlwXHOijWQbEOin18ojOh1kFZRxKJRiBzSKsVaMW29FGtOelm7S8imVV9trBgOQPa",
	"h7+CvqmmrFLaWpbgrl15LlnmjiHJJ9SgvaASo/xM1Vv5CT3WbbZem6pxWaxRqg0Z+38OF/T+XFrtoUhm",
	"d3ZT1CQhmuya971arcfIsJSIpQQlYckbpelZ5Q4cV4HkBWSxRuFLUFYsq8sRdxQuIdPjUuriZumbJu8V",
	"ZozEK02orBW90RmtZN6pvBUl3xW+Ucrq/FqBOtlS4cYo7OBXB78sqUvg15HgI0Zj3QHFrypmt/t/RlX8",
	"+0ZCdz+hXhVRzsGUZYE7838jXpERPVkWrjBVfECtSRBoYfpvd/wDDHmJ4Mrt8tU7Q9EZigap9xaT+ovQ",
	"8FTkPOksxVcSUsjXUf6vs+QSEYVWJ+Ij24DcUny9ZuD2xURugZG6NYGbzpx25vSWmdPORewMvyfahWrX",
	"sP0uGryq7W+LCH9k0+9I+Ao9wBYF0FmszmJ1FquzWLfSVSU6nqxhsF7a1LsV7ZXt5JOaK0vB5+Co9i0l",
	"317SZ42i3en+EDXZ3y0Ok0UzkrLW2bUzU6yJL9Wf7WxuZ3M7m9vZ3C9hI3FXBbkPN7Cf6Jo3xvHSO4u1",
	"JIuPaLG7jcXOxnU2rttY7CzHdW4sXtoQLMm4u7XGoNte7ExVZ6o6d6xzxzqjei0h0Etb1TAY+jXb1C4S",
	"2pnezvR2XmJn0G4svlj89e/d5dfCqd3rvxjOXuVRWsSLLh9Z+UK4uSNzn5MlNP/wA0kzhgN7fWKfZJn6",
	"5LeofIH3m9yayzu6qzGuA+90N5V1uKfDPR3u+Tg3eRht4246WoZeFl0w8IXCl1Yvf47UkINh+pVjVrRx",
	"AakfLxJvKOzd3ptOQvLhottOLrwrY1wruu5FGVY+IiPMUTx/H4v7d8VrUi4cSdIs/XkNpn7nxYWjkXPF",
	"P5/hdACsA2Ddnk+Hu5bEmy68KOPKYafadRkWdKwQdmq1dl980Ol6NpBqwO7rzdKrw6/OFHam8HaZwq8j",
	"7a1A25d17Bei7s5GfGobcZUQRDGttyoGcUvs360KlnTWurPWnePa4Qq4zus6VvU9F8UnO2jRuZ/rqYbO",
	"lnW2rPM8P/frMVbzPMPM8M44XMk4dHd+fBmZ7p3v1tm7znfrLHOd6OqVqa8wziXVsxNTyuu1IRKJ8jDX",
	"lfW2Cn2idbYRUICDomjx0P14WuTY/u0fp/a5kOPjpN4QyejP6HOGmznEzq4JOf4nTTYWmLDXr48fexMm",
	"5Jhw+rvllvssvjjnyr4q7TI8J5n9niPhtfIKfIpGZLo1Bq/glyP4MKNv3Kf56wOombYP/bHotzyvUd07",
	"fHlcNAUJjihHR2Lx5X9Mio7dqKgCiZlEhVy7gYmRpd3mdEdWplAqUBORs8QI0RSlBomxGHOjFv0wzJht",
	"ZjXRqLTNiZacMPfVQvfRx5TMQKJpF3IetGCLqAieC4lA+UhU3/EfUx2dfaciKoykpTmnerZrJFnSYa6F",
	"VLsJTpHtKjruExlPqMZY5xJ3SUb7llhuuR+lyZ3qI6t+QSHP0xCtTfcJyyZkP3g0YnQ80bFmhoTG+w99",
	"00B/SqSZ0hruq6bzzXyb1cunvvVjUSt3gukblFeWhBNMCdc09nMPNDH8GFGU/uOb+9FBdHcHDqK9aK8v",
	"4/3tXolntZnBAfR+29r74+1+/+G7X5Nvtn+NFv/a+nHQ39r6cVA9+uPX5Ju3pP/7Yf9/++/e7vUf+r9t",
	"4V+jVQtvf7O9/aOp8e1W+OJb20jtiS3553KCPazdtOPcDJj7ivAxXgeHpyhBmsbM4lBaEsq15+4Pj/YN",
	"Y+F7y9/tCE4yEmNfofEWNCagUaZqB5DEEzinelKdH/HfT4WtHx7twPePduCHHfh+Bx7twH924LdtGAnG",
	"xDkmMJwB8TMctUzf2x8eff+f3959Y/j07lvHr3ffbvk/tn/c6lcsjPr2ya/fzj2C62ln+5uW2anzyU3T",
	"He8y9IvPnMalqtlSEyIN92YZKohFii6sVyBxmFIC+KFQQBJHatu22Pjql5tcp+g816Rhu6bhYiZzmvki",
	"A1it78pyn1GehPUX+GF16fqZ8gSoAlIULD4BWyps88jo3FdPTk4Dp8oodTesqqiqVLlRw5SPULqS5UEk",
	"5EkmjPCaHzGjyDWofJhSe37GZbyDFhEcEc6FhiEWnxZIIjjmcERSZEdE4Y0rcjvtfcPRSpVDaV9bZuky",
	"TtoLy7jnqEnVtBHAVSffnxnPMA4amPtw2ipN1MBf6SYGhqQSzeCh4Uvw07MleGSGU/wkSUKdwnlZiX7t",
	"6JNfpG3rYal1LGQemh/Qa5snh8TmYw9NxidUZYzMfrHFnyRjhMMKwKpwkZ8ENVsWeh3hV1WKF8MCM8WC",
	"j+g4lxUy8rGcyNdSQKT7SDOh3CyvkZDAREwYm/VTwskYk9qhy2iJrgnHd0ll8dc8JbwvkSQG9/uWXAhG",
	"TcQ5B8o98fb4G+Xj4IiemgipHwcNXrL7QxhKiiMQHPuMcgzfevwc16NqADS+fEevXz0DIcFIELx+ddxo",
	"2zZpp8AzgHJ4fVx1mUkxpUmFrVbt9mVRz/Sd5UNG1cSdMAw73zKLmfCZKaSRpJb7wUfMi8+jX7bvZ5Sf",
	"GXhdVC81vbKMEHGeluDdjHyM2lqGCbIsWnGdt37gcdV14+7WqEyN40kupbUgwc0bnk/1GGbbQogFdwSr",
	"eWYRKcnCY6BHQbfYnJ/52Cmd/4DqGjbjyFO7TFlXQ7rcnDyjwXmp1WbEHvS2uMGf1fXKKuqATgd03OQZ",
	"IanDnLnFsMJ66z1rSlhvpeW1ysUp1wh5aHB1wYrrzhhrw59V117vedGtVcJt2x0qgicfNPJEQYUyndtX",
	"aqhYZJSPo6WKpAGo+uHWTKsylWitwylNUWmSZpddn6cTBE1TdFEwt+DOiSoODCahQvXn3s1y6Zs6QQ4g",
	"w+ungjJm1qdL2ViREr4avErJh2fIx3oygIP7d1fd5yoCZ2VxdxfCfHc1QZpr9TnJTIOFNjzDmbIRNBcp",
	"c7HHmHCrmZRxhIUPNqItFxONY7ttAVtGpNxTd6PDtr+vIWRW65pYZeOwxqYHFZfGyIs90/mhz9+XMHf1",
	"xPsceYz+IoeaHSBQxgOqTjz3E1RmuTjzH8FLkeXMBlrc3RSgZkpjGsErJElfcDZrkxjK9YN75XNxzi8P",
	"Fw9DK1UFim201T3fMch002gue2Zvs+i9osfaHrIAA81Jz9oT2ES5RV1QqEumuX2FMCnXjaEFLqzEHA4i",
	"I+9z9PJtWVTGJlVwLUpPBZHkIohZC1BvNE9SXhZ6nAb40E6QMRUwRCb42KGAE5pSRuw9KDbOm5HYGH34",
	"OR+i5KixbvMWbqVfwu5cEu8VVqbE34SHGzugMc3MKvC5b6ULe6y9P6QgwRHJmW64vC0KJ86VFqkN3J9P",
	"kNthFfCs1qkAAiOG1QeIv2TMuRI6u2gL/cpBJ9NIGHj6NDGjgJhDqemIxCv7L71DDqSoAxJHKI0ZiJzp",
	"n2UII4rMzppV9tRUTSm3cXK7w5QrB9c5NerFQKviwh/fqrIuURUmb5FJS+TlGe/HejrLghPYfI1QTu+F",
	"3wSYLAnqGJRppdEPrV0L/f3oxT8O4DFVZ3CcknGFgnJJVwFBlHvrvr+QXj90G5AxTBe5LtX1+5wwu+Xk",
	"ptE/LmcXtjQZ20gGHaPS23ZNGkWCCRAX7GC5Uyk0xfZBvs/JzHhcEpMJ0btygqw/FELH/fexOD9YshzM",
	"sIOfuaTrS/lpIDgX79J6njm7XxfmCJ6vKslwzGOWGw3uBkzNJPeHOWU2WpXrLPd9BBufnnFl3HLBjmjz",
	"vXkWstRqlJSGnpYS4TtOYsET0q8/nqbJWfhzEmofSc6DX+MYL95uXTAZRy3ULyj698agFhQ7rI11QaHj",
	"2lgXtVRwZqXCb+r8WlSqxsYFhV7VuLug0E/xnJAfeVwwZLiyOj+qgQmrvOtgooDybqlb5MVwigy2SIlI",
	"1LZV7WKKUtrsJlPUaxFbOoLCovVd5QK0jHLGZv5EmW28/n6LCw0pyjEm20sNgoNE64LwZhrjMg55ypBP",
	"3xCpdiATUqsdmAqWp6h2qlDCDqCOo+1WdViD/UVTzRSeZy9++uezJ2+ePBvY+FXtre20WaEPmw/3Hu4N",
	"zH+bDdaczGUJXR+D/nby4hdwHbh0FoPL4kAYg8xbKyjuCsIpYTSxTI3CVEuSrGGOH6MmlGFSj7XvQGZt",
	"GBkyu8uQEnmWiHPuHTnf7R34RWgcwC9imU2BCUqEIcYkVwXKLNJ0qHI+PuVAGHsxAgtDVC2UfMcnHAQL",
	"tlgT2walSwShJyjLHXSSeEYZiiuhj+DE7R6UDS+j+dzmBGUSp+ijqRVtzts4F/LMzJjrwvvbDby6hrtT",
	"bNZV6U11v8WAo2q/waz9pbsNLlwyWwP1HRVVe1eFj3XYWBr5i8Ox68VYQ43fq+M9u0u5Etxz69Glt5Vw",
	"tMZ0eGynKAHBY/zvefDn4iFsii4FpsT+lCeYIU+QazaLwDBnCbivQfqFmrBfMHAe01SAuESSmRQp6gnm",
	"KvizrFCM40ZnZ87LnZsGn+RZkgO5MmvtiPKYck40hVQkxj6+VugNoZupTNKUyJmNUeyAOqOZct680rbF",
	"eEI4R1a8sSGYFBNKdNXZKgyf+kSBzYPo3v0oMBxeIXs5aLkay0/TADbVhBzcfzAgdzF5eD8mONw7GI3w",
	"wXdxkjwcJd/du7f34MF3ewQf3k0e3L0bD/cf3Ds4SPb28DvyX/HBwcP794f3HiT3mt0Xo1QDeOvGvQMj",
	"ovS7OSod59ww7s0Pw3JpAG/N67vR3ua7ZWy4tz4bpu3Vg2FcTP7dsL6HWOsovsAE976uBIaaPbmZLAZ7",
	"EumCVIYEM4nxXIx9xfl7XNXufZzsCDuozzdFAmAiUszIGNfZmPJ17cw6W9gYeSZFPWJdI+u1ZOuOucx0",
	"rDUYrR70KMHGxpzKWiN23ZrGvhjT/VF2eliL8NeZ55JdfUi2aeAKiNugGWxmFhcJKgueOeTZWJIEYSxJ",
	"NnEbZYXqtEXdVh3Y5H6hiqrVfL0uahub6SokBbgZzirrumVMMMNtb1W30pxpmtknwRXs5qVNQYYtFeQQ",
	"bwfxnAXKNnSjq00q5x3X3Fyv3MscIOM9hGJwJU3fX+TjZQv2n6bzcf4WqlajzqVwN2/HvHrye2SPptkd",
	"RLOGS3mUCdotAiMyNSGKmjRUOc1tiGexoV/AzAKSh4tuv8nAC3f+lm7fLgnytqQ4uG3pEqbbmLwWYIOO",
	"UIvjRvAzzpQD7WlxztYWp9xGfaJS60TwgrMZnOEMkyC6aRZYeY6pci+aie5LEehHwpHgYqIFQpub9RKf",
	"tc5502NY7IUt8CcumN5GvMkrvJCZ4XZnb6MVO36sVWtsqdOgJXFuy41XHsxOFQgy1sD7MnmgnxvDcAB9",
	"ZfYvYPJVx3ZYrtTKYyuDoZ76hEqMNZu581Ru5M6BW9E/My6ATW1o99RqSurtpj13sbkDm/vR/pznUhqp",
	"a5x+296Fmrs6VCNGazHL6Ivf+0pLgzFd9p7FghOhR/QDLuFJdRhlP7rbXMoLMPdVcXcbTKvhsMZTr1Ea",
	"jyvz0gRlaySR+mqtiaQXZrJ3yaRdMumVk0mdlPWuJZz2+SSVHjWizRduFfsK837RwpOsLs+tNsQyNWej",
	"FvsZtLxabafVk3XS7KulzGGjj0bge2VW2ECwGNWdwyISbFacj+QvYMwdcMSW5dwRwoB2Ef4YUZmeExn6",
	"yomk0yByfCc8gLS41bZt9AmykGnvc5Iw1LVKaSZUrfNK/labIsOuFyeL3z2dH2CjxOP6eOfeX7DFbor8",
	"tT7Qxtu/z417rocmG5okeq60W9mVN6uDOlYNy3TRXhJUvmEEL62psCmBiREEm0vnWioSUXO1dHs5RaXW",
	"iDr1Sle1aADwQ8aIw8Xnk1mRzVijxviv5wZEaQGJAMqVRpK059RsnpbZkLVGHL7iY8o/9DOWq7KVzY2G",
	"15A2rpu4XO5TmFQdNNgIJwbxDoN52zfEA2qXWIGCjSsq9AuPSnWo6PaiolgkuEre+qKv/NWvZcnHY1Rm",
	"+f319PRl8SlC20UV1XBqYgf2gI7AMERhECleU0MczuUPzm9pVMfz3FT7m87CZG+i1tlOSUk8oRwX9l6q",
	"qLJPI57Fju7mU0JZLnHTK1A4Lih0YksVYJppm58u7U8uakq7jBxFcAiv7BAgZkS6BHPC3VwUo7dzMcw1",
	"JAKVZX8QT42WnOJeaeWdBCzGgMPwghsFN4DNkzyOUalNY1fKkd+46KsM4z7hSb9ho+rC64i3iqOQXDcD",
	"RnRjwljhlSeC97Qv4XJNGsdM1gXeKvz6usNFSYgGnHyupcf/PwAA//++OTBw88cAAA==",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------
