receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: ./certs/otel-collector.crt
          key_file: ./certs/otel-collector.key
          client_ca_file: ./certs/ca.crt

exporters:
  debug:

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [debug] 