receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        tls:
          cert_file: ./certs/otel-collector.crt
          key_file: ./certs/otel-collector.key
          client_ca_file: ./certs/ca.crt
        auth:
          authenticator: cnauthenticator

processors:
  deviceid: {}
  transform:
    metric_statements:
      - context: datapoint
        statements:
          - set(attributes["device_id"], resource.attributes["device_id"])
          - set(attributes["org_id"], resource.attributes["org_id"])

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"

extensions:
  cnauthenticator:
    print_cn: true
    log_level: info

service:
  extensions: [cnauthenticator]
  pipelines:
    metrics:
      receivers: [otlp]
      processors: [deviceid, transform]
      exporters: [prometheus] 