// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNpYw+irY3q2yPdtq2U5mKqOq1Kwi2Yk2tqUryZnajXwnEInuxogNcgBQcifl",
	"qvsO9w2/J/kK5wAkSII/LbUkx+Fu1cRq4vfg4OD8n98mUbrKUsGEVpO93yYqWrIVhX/uX6o0yTU7oXpp",
	"/o6ZiiTPNE/FZG9yyjLJlOlGqCDUtiVznjCSUb2cTaaTTKYZk5ozGC8LjnO+ZGVv04TolFAcJxVELxlR",
	"a6XZakbepZoRvaSaULEm7CNXmosFNr3hSUIuGUmvmbyRXGsmzArYR7rKEjbZm+xeU7mbpItdmmWzJF1M",
	"phO9zswXpSUXi8mnT8Uv6eU/WaQnn6aT/Sw7h99CyzatSTqHNdIsS3hEzVeYV+Sryd7PCFzFJh/qs00n",
	"H3dMo51rKgVdGQj97GY7cJ1wAW7cg1RoJrRZC02S4/lk7+ffJv8h2XyyN/n33fIYd+0Z7r7mCXOdPk27",
	"256yhGp+jYdtGkv2r5xLFpt1wcl9aICntr5X4vonKvGoKwfPyg80jrlpS5OTSpPaUUxr0H4lrrlMxYoJ",
	"Ta6p5PQyYeSKrXeuaZIbtOFSTQkXZl0sJnFuhiEyF5qv2IyYw7pia0JFTLAHo9GSrHKlDc5cMn3DmCAv",
	"oMHLP39FoiWVNNJMqtmkse0WPHFgOJHpNY+ZPMtYNPysAnA0p1AFJC2xsWcsaPZpOjGo1XLnygmJaVVA",
	"48X/+f/+/yoMSJKKxZQoTaUmN1wvCSUJ05pJkkoi8tUlk1OAXZQKTbkgIiU3S66ZymjEZoOu2m+TVLAB",
	"gDpa0QVrA3cflh+JhIv23h8+feg+2zNNda7CFAG/GXpAieJikVRhbGlZzK45gsSRiBPJMmppwpkBMf7z",
	"NBcC//VKylROppP34kqkN2IynRgCkTDN4uF0pboDf87GR28RjW/lqhqf3DIbH8p1Nz55G6kC+qc0yRFz",
	"y+tTBfchm3PBFKGAvTG5hh4kVywml2t4k6okuXqVwhfjveD/yhneB0vY/XEN7nMRovdN/PbpJ0z24Y44",
	"jyBpIGwIbnUSVN067kg1d/+GKw3466GtbWz2yDVbqQG0p3aG5V2nUtJ1L/3Ebogf3bdsK0f+rnHWgfM0",
	"xzlnkomIhTgh+8lwLnjHsyRds5gcHxztGBglnApNuDlFQzHN9ZrTSJNLGl2Zh6pz7hAu+evpIVnqLF+t",
	"qFwPJF1J4gNRtZOtHxhN9HI9mU4O2ULSmMUBUrUxeaqutpyjtYk3eWubAGWqNiiWa0CX6+VBKuZ80YST",
	"+WbeuDlfNNGL5np5LBdU8F9xinKUzgvT0u3TFEYMHxgsxEA2iKum3/vTNy3d3p++6ceyYupytGnrDoMY",
	"2A6NwJqk4T5ZTFK/h4V0LlvuMxOGDYxxyDnNEz3Zm9NEsTr3eDQnWuZsSlSeZanUZJ5KchSfkAzpZH1e",
	"rogd2wPUZZomjIoGpNwqQkD4juooIPLAz2YWKghLGHC1XJBL+Fmxf+XmXjf3m/AV12FmbkU/8lW+sryY",
	"oTEZkxETGijO3F5fZQhUnsVUM2KfMZjTTDXsITopRoXXa8WFmXay96LYPBeaLZhE4UCxhEU6lX134A29",
	"ZMmZa2w65lHElDpfSqaWaRL3DeCv61PbQZxZyLYciPtMYstZGPgk9kkEOCEALxlhH1mUG3zlouO8VOt8",
	"+9VxcUaQi4Y/tIhbn6bmEI6ww4v6Szs115tqtlj3jXaaJkma6zPXvI7lxTghND8we54bysrO+MLwh6dm",
	"6yqArK1NifT0CUTaH81FNdz0QrCYRGVfMpfpCg7oYD9AiTP+E5MKZmyA/uTIfquc8zX+xmKCEEGOgKty",
	"WZaLn5tLi1ufkTMmTUeilmmegPRzzaTZSpQuBP+1GE05zsBQOWUuu2ZS0ASFURSdVnRNJDPjklx4I0AT",
	"NSNvU2lu7TzdI0utM7W3u7vgenb1jZrx1BzpKhdcr3eNCCb5Za5TqXZjds2SXcUXO1RGRiCLdC7ZLs34",
	"DixWIM6t4n+XTKW5jJgKvihXXMRNWP7IRQxkjGBLK1sXIHOszemrs3PiJkCwIgS9Qy+BaQDBxZxJbFmc",
	"NBNxlnKh4Y8o4YZqqvxyxbVy+GLgPCMHVIgURFmkdfGMHAlyQFcsOaCK3TsoDfTUjgFZGJgrpmlMNe27",
	"k8cAo7dMU7jJlpfv6tF6u6xwPFEFV327YbB7g1ko75tFFW+TduUb0Q0jiGxAO0BuATx0ZLW16Ugs7p9Y",
	"FM9XWLrsPJtBT1/7e/Op+QKOpOsRSJc5ayRcm5EKPP6NaIXTcVTP9++SZhkzonaai5hQkismdyLJQMw4",
	"ODudklUas8Tw/oJc5ZdMCqaZIjwFYNKMzzx+Q82uX8w6lxAQTz5mHEWXMxalIlYhzQH0R411QTOuacJj",
	"rtfA/QDGlBObaeapXFGNvPZXLydN1ns6YR+1pF369uKeNY64fn9qingzMKEakYsppzkx4EXTjIMxMGcG",
	"zlma5SjdXa7h1/2TI6LgxhjYQ3uzc0PX+GqVayNPBdTuiEhBrvIcJBnF/vL1DhNRaiS6k1dvy3//eHD2",
	"7y+em+XMyFvHyS8ZMS/TrOA1OUuAo6c+PnQxrEgVKkdyudYsdHGAhZXvghqoIxEjksGaZIET2AcJPpCq",
	"f+U04XPOYlBQBi9ozgPE7v3R4QOck7cIRRch/eJ7+B2gbrYB1JfBm3DF1gR7efu3IipXKq9y/5WHoheB",
	"zZb7VX8PAJgaKXTYXEGOzUhfi460RCiaZTK9psluzASnye6c8iSXjKhC4Vfs0jPfqBa4Ez4vLa+qSfG8",
	"puE7aodsynPTEnAkNTJ4AfNBt8uQVxSfA1xj8Q0Vm+ZkU/+mzciPIr0RJPIaSkb2AXQsnpJDJrj5r4HQ",
	"a8qtWmgYp+LGDGrBfWzwthDEgWKg9g2WxxczTXmi4AFJBSPUXDntjjvKpQQORJszdbyrQepTj6TVdE9U",
	"6XNJhYKZznmbVdG0I5qvGM5ULE0XfVmMfJFZl0VDnRIqUr1ksnLahgHaMWOFORFl6EVzFT/kKyqIZDQG",
	"bLLtCMc7Yfg6Bx16mebarrhYXpCgpZdw3ePvmWD4Tod3P3OszGxRtESiUoXGDVVA+cybFZM8w2n9d/0v",
	"XwffdcmoCgoq5Oml5Gz+jGCLknVwcz5Rg3Y6UEB0ozqB0I00sBtap2s3QKO62a5gGkK5AgDl+Xdeln4j",
	"UgVGU0DKdE7OQVv8GnTJxBoHfNuH+T6ZTqDBxtaO2ursWLVf3dC1n31DRRWaTXy0zikl1nFfkvB24ygd",
	"WkjcP5HqwS4NyTMfQSfLLxNW/8PRjRMqFTQ9W4sI/vGT4WVNC9QvHokTmS4kU+aA3xsRx9q9Mxa5pm/z",
	"RPMsYcc3gkkFK7nmETtkRrrhysgOptMwYL8SMk2SFRPavpneDlvf1SFtCvC0tijgdsqyVHGdynUQaAZW",
	"rR8akPU/FlB+nTCmHfzgjxC8EY4e1PEHH/b4y9ATQCSc80Xd3jzMmPA914HufS4cPxa8+RmLJNO38P+4",
	"xaw/aJ2FugEMstydyttUmINuuv5UX9MVNuv3LCs1DymxnfoZS3/0oNNBtx9Ycye4S5mKVx8zg0thNkSm",
	"grCiAcHXDB4iM3acJ6BT4SumZhfCbNK24Ir88idi//+XPbJD3nJhZMs98suffiErK6893/nzX2dkh/yQ",
	"5rLx6eVX5tMhXRugvU2FXlZbvNj56oVpEfz04qXX+e+MXdVH/8vsQpyh6ZDFxBwk1alZxI5puFeIlIY3",
	"Rj3SUzZbzKYwDBdkaZZcjMeumVzDb8/MvL/s/LJHTqlYlL2e73zzCwDuxUuy/9ac/Tdk/y22nv6yR0CT",
	"5hq/mL54aVsrDTzqi5d6SVYAQ+yz+8seOdMsK5e16/rgYuo9ztB9qbqXb0qQmFfzG6/LhXiFfpYGcuT5",
	"zjfTF3/ZefmVPdIgo3GQK52ukLAciXnapayo8zqgy0GFbEwiGIjYC2YPIDhlXRj1BuECkRHEOGALq04P",
	"DRYDF95cHP5eNWZly7XiEU288UYV9GivGu1VuyUDMlz2sH1uYYn60HqPG36JTae5sAapJmz6foPdDoIg",
	"ycTr8OvvvDjmTqI3aHaz5NESNBPQkwzyQzTTgNtugI6+K2ZxbYiTcwvxMTy6J5AOO7OwB+2nabsrYimh",
	"2SaFlx9cstq6bueZWBdeWzQzhcOdOS8PoMXmB+FV1eEs9KopbODwZwm+bzV3zIA/XhVNuX1KO9HUf+1Q",
	"GeIoH6gIfPfPragLur0Rm64mPVBFPrwNkAeedquU8RFerb57komYSRa3PsOntoF7eFvH7dP5Vufp3KRK",
	"k1YOw372GQ2ryoCfo1QIFlmpvzjskIsSMOtHh2FCZD+To0NfoVSbIYwY2POt93TU8L3g9YpZHKF2pM2s",
	"2xoHvq3EeURUwGupUJcLrlM04b+i0rGIymFyxQVNpsWa0XnLdJsSpqO246LxsUjWkz3wGayiZm1XUw+A",
	"7Ufpy81NQLjBLN9JHUrFVWm70FY3zlBTuWB62LPpL+Uc+oVVcTjksC154zTJeGHqwcuizAyNra2YXqZx",
	"9Ur5Cqr3goEaB5RRkU7l+pSpyvq6VEBdK/ZG7mpWnbWAwpF5ByXX64Mli67aCFJ72/rtrZIs7nqQyHQh",
	"GZPmRqDF+pZvwE7wDSglnvqcuKI7kP72zd+O9reO1KPj3QCYJda5sJX3Qjnp39eH/sQkWGM3wsPQBsqZ",
	"utr4a2hvV6yuvUm57iZYWzXmljlpQ9HG3c1qEjzMEhupQ69vjzTgXrQpi1OiN7A35aJ7mBvTuoBV833k",
	"K8MJrjK399rg19Cz5FGHmbVudats2BYekWOtdba6C5xvfTGbixl8NVsfgOIUvNsXvp63uoq1a9Gypbab",
	"1XOHm9e3vHZv+JxF6yhhP6TplYOV2/R3bJ5KX12/P9dMen9jg1N2maZ+i/KHTYBRWUpj6kCb+mpah/EX",
	"2DaOt+YmcG7F6Seu9xZkpLpGsBx8Ww9kba+3extDg7TdPT90PQSx5iOIljR7AaqGoOovG97C2qrr96j2",
	"ubKKwPfQ0nqa1W5kyL+s/FZ1M8bf1ajRfXSnYu8kBimDrP5+9Bf+3PyFpxOrBxt2go7R2J6jccgEfsg0",
	"JJY4RM+hpnYYtWj99lxsB8qUmJtGKy6oTiXJcpmlChHY0d6ulTRJrIE21dGSiwV4AHRclrn5Dspqhd5J",
	"0LHGew11sKzB3YNEY0FDwX3KVJpcd4CbKnQhhOZhiOMeXUNCFUlNY/JU5ElC+JyIFH95ZjZrfjTPvlP6",
	"BGyHD3TAbu/BA84ku+Zprt5uctD2jF3fZG3NuPEtDxxU4GmSt7se/ZDeOF3hPOGRBn83aTfmAwDtzLCb",
	"yXTyLnX/gn0dspYUF50oV1tbO8odq3DkgP+V4KdL+0SjWowcnxXa0FYVzCrom3heGQTzAaDNSA4Ly8Zx",
	"Ozd1G2b5+GzwFn6q6r/dNsJvtvlyyBetPvsxfKuPhR4HRC3pyz//ZY8+n81mz4aCpjppB6Dgsi15drCk",
	"YvE4lL2+huCVF+ymg8oJdmPpGtK7grpJtkqvWTyMuDnS0DGRaxKeTaSCDZmq/eK2n1Th8LYRYhfMZJ9m",
	"KsryYZxGdR1OyxJzdXWX/iu2SofyOqER6l7kWT4pBrWrGwrabhxXFXc0BHYVqctkHX+n0gpfB5JrHtHk",
	"1qlBQgv1M480v5aTh756Cwp9dosMffN9bz3HhZYHpPZ80A7nn9I4Oiwlj81aIW+VlKfm9dh426OWNB1u",
	"Ifj9FmsIOl2GpldpEvIIOPeyMdBI8+vSFmmNcJtKf87EGgx6q6oRNjauQdTAwHVYTsQyVkC1AloDs7TK",
	"HbRuntUsKcNhUHP0DEEB8y7GLbZh/AiBUC63iOeiWnN4NYzdCdWaSaG68mGgJJLZlpXNNPwl0EnRrcPI",
	"scBMTTFFXSrhv2luROf5nH+cEkwmsWRJsqP0OmFkkaSXbjJYP8xOF5QLpV2cTLImSUpjhlPAmlb04xsm",
	"Fno52Xv5579MJ3aIyd7k//35+c5f6c6v+zv/u3dxsfOP2QX8388XFx/+7eJi5+LiTxcXf/vwn0//a1i7",
	"Z397enEx+xkbhj7/R4jv6k+3hdqCkzTh0cDH573XA9H1U+u70m0Jbdo+w7pW5WX6ssST2L4rCsYbnqCT",
	"UqRzmpThTHeltZYp9kluqebdgL40vcoCd4w2fWM2Hr3mWzQ8IK44A4Ajen85PyMDx2C0GA3JjLcMgvPf",
	"m0EEu3T8AUugtbHcyl7mTHxnjIkhwWwWLTB2iwkXDGrp33ATX6Fnv5VpYMOHpehTeVo25TU3Vss1EBKp",
	"tHP0HjBA2b4gV/EmlCpuMWR6N6OyqupNnIQvpg9GH/0KNIazKddbQs1DNR8D2nnz27sLeri6pDK+oZKB",
	"eh/jFrhY2CeTVBTu23cjtGtwMZ7bcCQMgOZ2prKNciKGbdLHEEoUTn/omzxP0hsmWXw8n1eM1n+n3DR4",
	"ncqDwpPOmkKVTqUZ+ITmakNjWmVf3gob37xFB75WxaDKp6Y1t/K5stvA97p5r/JxAExCU1owlYdboTXD",
	"gkqOM+eMiHfDy3DBPmapKoP/6YIJPbsQr2i0hLwFUSolU1kqYoxkLhlyvCTW0BbRjF7yhOv17EL0h6fg",
	"Jip3LEqTBPNbF4aiVkbHLLLVAmnetv0F5NLGJuEskp7tp2UMr4XhJTA+ysKpETxTjmwwKORy+l2aanJ0",
	"uMlQGP0z5F1pBByZh9SRRIR2eJfHBd08c3Rz4PLqJikfoAUUmquYVo+vnYo1ePIe/8sMWoKOckUFXWAw",
	"PFBpfLEgh3qU5LH5crNkwv3u7MuXjMTpjbDykHlVbE6FgMuXbXeGwX+93A5upmhdvPq37f+pB2zxrTTl",
	"uKat+pT4j6VNzrnFx7Ky2ds9ls0hNvAqKQFWuJRk5+khhUQex7k+ntt/e65Et1ERVhbpTRH46s8a7Fzz",
	"aap+bWgBfbGth0lzaVidgzto0SXTuRQsxgs3Z2jaK5PIgzGsU5YtMbntsRuQWqJIoftb4y3aJ5eS0Stz",
	"ozt3crkmF/66LiZN/6gSuVSdw/0MFm/X1L1wnWqatGjKzScvfis008BUH5b6fU7QsWJNF3TqgQQAqmkA",
	"WevnX9twkBpxddUbaL9xbPv0MwvODz7gVg0FLzcOAG83V1eYNmuTYjsxl5BneV1U23GaZGu89Mbs3ktH",
	"WZhDrmQOs36XxzY8paYMrLWopl1m1yyx+ejTGxabZdnWSCYl5rcgHPA0s0kummBYyDTPvlu3K/sSeskS",
	"w8cD827DAgh0g9pCztBfzn8Jy61ovzz979Of93f+l+78+nznrx9+3in+/Y/d2Yc/Pfub93GA5hYUze8F",
	"vabcWlWDub8xCbdHddwZkaJncaldZRwEH+iyO3J4w9f9nulrqcfnJBfNeYtz3Gj+IA+X+xmYLGGbPDcU",
	"pH1xRXpFt44iwBWD5HRKIluKBKsFFR1KxtelrQNnIkogpwu/tv7rzNweO/blmlBUG+aC6xkpU0cUP0KK",
	"sT3yi8IsDAoTRE7JLyv8ARMrmB+W+AOkkAD09lDtb3s/v9j564eLi/hPz/52cRH/rFbLMF69ElFqmPoh",
	"UVrMtkU6B0F2QBiopjVfVJ+ryxLKjViLaRgHZ+fBqU5sZ/f3d3aQT1MvgU9ZQKBeBsC12LG62D7OuBzz",
	"zHZoJvVvjBl6kRrZhZqwbTTpSHRuk/UZbMQFdJoyRg/jMWfEHzBnRONCbZY+otl9uznNWxKOhQSG1qZl",
	"IsewxqAgFJ41jpQkqz1UmLrEZh0pQ2+WTC+Z9DNkkiVV5JIxQdwAoboo0wnwUncp87fv8sHiSKBOzbJk",
	"XRZWaknI0zg8u8+NTsiTtQaJE+1H3eTjeybtO3HPFn7Xs99v8cUE3oRqm2fEP/0bqioHP8zM6Xp815bk",
	"pJorxbQdID55o079LQWkkOmGR3ALh4QA4IsDmgVxLRxfFGxWDTVqNBlZgkcPOgqeySCXiCbjOEYifamV",
	"C8IMSz8NAA9Sjq6jRUOkPo22T5SLKwA3nYCbs2px7A7lyfdTfivMaeq/K4FHvOr1NTx9133wDC7dshXc",
	"sDK0x0ZwVbjyLJkgBpM9Ms5ViMlp4TMMVIcdeYutqaXhZm/RoKehZEJvxdJ4rmV9Sd59jGpmep9tnL+9",
	"ma2c3YHybi0je1OJ0HG6tkkXm7dMb6wayhBCuHu21PLrhC+WmhwYwpgmPrJ6vmfNWpSGOEaFqmwjfch+",
	"DkXAfTVIznfcWxA+9venb9zpvD8qbyGYskmu0EE4k+4t+X9OiUER4AESLq4wGynM516wDrP/bRU9bfqe",
	"GrzKCVphMAglAI79aOHKipa1F+xLW11WBWmwMt4tUAOH3vGu5E44Q9cBNPTSWx9STctl+tccdIPAM1C3",
	"dDM+VuY3Kz1/cxa++LiYK7buXMSPbL3R5Fds3Td3/bK3QKW5xEEHP5wkDKAMLtWauRbpLQ/d25dBqlRy",
	"3Qrysu2+a9oOfZ9XKEYmldJJbRc4FGuG/Kh5hYF4xLFkqvDB6N04eepYy2WqtJEw97JU6gHRgx0AKhYb",
	"PHnDgwaO+RpFQk/Ta6357BrdrakmaQS+1UWhG3Q9CxBzV0K1W4iGCjZgTEBYIAmWfLGAxIXAzZvJ0cCB",
	"UgPwRpcQ3jfnH9F2wTjof8xwe+QpGB/AjcX8oJ55M9ivNNfpCsrjuFCQZ2F/slE83bJ4GpdBq52voBnR",
	"BbiC2/w1RGKj7nWYhraocT4KplsXTFsK2ezjvStT9tXEwHrGQAPHjMn2VMC308m3l5xRy1TqKVnRaMkF",
	"K9dpjx/oTzWAvlacBsmRZ0R0DhoHWILLK3dxYItseUU18MP7wtW++kujoUsnUPvFH7MZxtfyc63Hwcn7",
	"Rlzpwcn7eiTqwcn7d+ZpLxu9hUDdRl/8ud4df62NcMjVVaO/+bHe2/xW6+tFEFUdvr0PDT9x71s9DveQ",
	"K8uq+GnSAh7j1mPbS3Vb62ReeCZ0w43P/t504Cs6BF33iuPqqgbTKvrWDrslH0t3JpOOYivmlyNxbX87",
	"sm/QOVVX/QVk3M9HglY/WGIdl03Ke9IsFlNO79eOKS+h/+uZprL5a7HUygDWo6L+O1QuP+QqwzQkta8W",
	"KixxcG109cf1y+EcmPupvRMZVGGnAbvyU7DojvmRi0WDvlQK8tR/tK1DCR6w4aA3/AybetW22p3TPHbv",
	"GIta4e2fEksZfLpbEAZHNT7022G6taFVFiNQt2ta1PvCTU0tm9vKZHsZOgK89o71zolcdbepeYZyeJVj",
	"W2ctFY77XmcgI1USdWCYcpbZcO/Oy96p2+xOHdVDJzYYuZ4lqS21SU+MYEsilM571zJie4+OUT1CMHTY",
	"skt43I0W2rPGGjkaMGC1R3hUSw8GjIYtw6M4WjxgGNu0HCfw0LTWzKq3LEfpemlanXBbu/jjVsh692kG",
	"GzfH6l1XpZknL7nSQli9189a82k6sNRZ6+CDwnhbruiw3t3k6DZj1AlPf9G1NgQaWowseLL9nXsRrW+I",
	"jhu0SdfNNt1JnDbp3EIrNx7iTosIU8NPHzbKBAVPfIvrhPtUc5e4BjXC6CPx6D4SxUEMc4wAferoDPHF",
	"OkN4ckxQfilWgfojuGYqSwXIZ03NUc3M4Tr3a8s3nKfHelDMG9rza544BUXbnuEjWvPnPJSzPOrqD773",
	"RLOPmjx9f/565xvQ0qMnfmmoKSeBsC6etNriTTvnit9vYvUiC4IBG2b77XWAzNei8k9L/E5LhleesCcK",
	"Q3WmXnSGtV9AkIZLrinyFZM8IkeHM3KIQSNAeC8mMk31xSR8S9KYdU6dMWkVgsS0nZH/SXMgHrgYjA5f",
	"mas+pyuecCpJGmmaOMN+wigEWvzKZOrKbD7/y9dfw/FR9PyJ+Mp2wOpAoT5fv3z+zFAvnfN4VzG9MP/R",
	"PLpak0sba0KK8gMzcjQnhjoVEJticHh1M3AFzD4ViT2AmeWFK8HlqjUVL0ILMkfew0G14dxx5tVqd5qO",
	"qFBq2QyZXraWYTErlaE9HZn/82kxduVnJ4F8sCvcLHrRJyO9HJh/5/oa719Cylx2QsHr47dmjF9BFVqi",
	"/YDhC9xtG9/sW0GZl2Jr5M/GsJYxrMWTmTYLZcEu2w1fgTHDklbxqSppYQ7y8SY/uqRVHsQgSQtp9ihp",
	"famSVr8apxFJewnp94M8HHwCNrSau6SM436YkgkdRomQcW1uNdvdVZaxVT3xBWx5YLIOlYMN8YTJyFCp",
	"ttz/tpnhtW07J47dYrJ5nvRtrGx5l81ptsoMzezMJ+bL1ufVDs4ZmCuLRoaiWz9f8GdPg/ij+YrFx7nu",
	"2yS0g4Hussdb53QZPktX2Yo6jKf2MoZQa1qkVfEwocB1D3CDyEJTQfxF0AXPrBgiDI+C07dBgL4z7Kfq",
	"9w7vbhK8RUhXcMtA3OXsgAwVdwR4H6DDhoyHh3bNIB189UxztFb2ARtBWkRr2MAog9UMMsUyl3EyCN/t",
	"nW7H1DolWDZ9wwMuobD5YVctdg9/yB3+Qvd2nywXdP83qWZJfXjoOr+JEHilayKpZotA7Lodw4hB0KLw",
	"JiqdqSDp7nf3/vpUn5w7vzf1nQ84xmBMY7PNZuGMDQ6iZgnBeMDv+ngSy7CVRRyQrGD50BrAOhNOlZqZ",
	"8FY74nRhK72xuXarw6oxnFYaQyRNwlyASKeESS9ZcuYae0jYcsns11qps2Yqw1ryvHtTkHkldxoZTMPa",
	"rHouQrffVsTuxOhbo/LgqhXQekoYWEhokqwJL6UN72os6TUDCw4EZOEbCbnOBF2wSjgUF4SSm2WbRXGz",
	"mNvixO9e9CFuJE7dpNJnQaoGqbiq1GrDIN/vmWCSR6csSwtjTTBMfU4Txeogdl663V5KOLTzJ8tlixj6",
	"NEvBSXkNtd00ewZ5qNGtaVjxQDO0bRPcK9eBGk2N13nB9anZTmiN0rlcYaDi91xXqxMRjKTbJFuly1Hp",
	"6knyhaNApVdXkDMtodP/vJZDFarLMLcLdPyUXfP2Z1var2bRuWKlTrNzvbWj8hbfmHXalndzOhGDeP5a",
	"Ca/+1Qhkou3JhyaGQu6RM7aW9sxakux5ZzUaLEWbK1DnrpgOJGm8ZIR9ZFGuMTvDIEpk1tZJjTRfsbRN",
	"z/RZZ5AkT9STagLJJ6sn1QSSVMTkyfLJ3ZNIfgolqx3m/Vpix2kuJp8+gM24+mMgq+P1T1TeJTHIK3HN",
	"ZSrgQbymkkNs2hVb76DlIqNcQr77f6KY6TKT5sLAOJj4Weai1WlpZQBdxVA/mT4Va0LlIl8B55ArkHA1",
	"FTGVMZYkI2otNP1okMeIZpwlsXPaUGRlHXDdTIpkPAPZeAHZ2qYGozhc7zW5YbJcBMmN6EwouaRqSXYi",
	"9AP6GFbN3aTy6pC3uHGYj5h12OUPxu1ChlBMypsL4exAdqEDSF0uWklKeW33NsG1otsJ1cvjrNcBotLn",
	"1UfD4GENv951eY2bRk5BWPHZI27M4B9k+U+JljkzR1ewIWGaZ9MSszh4aqEtN+5T2uJFVYSMPlXPiJkf",
	"XH6oBg8ylthKzvgKmy0oqrmyrk3wa7H04ZbHinNOgCC3cwPUuqoUbAH6yxFQARRoWYAaOOUIvebvCOZQ",
	"6uupgWoQR7TOynS1nRxj4zX0uCWzyB/Oz0+wHoShBAE2ns4iGXi7MIUucd5/Mk01OdgP4k9GlbpJZdzG",
	"gOFXYmP9UdsfWFdh/yjGC0W7XfEMjb8/MVkkNg/kgbjimWV0LdNIrr0O4fyTOlGDgHH+5gzzkzifw0FL",
	"N6NfsfXw0a/Yevjg6VVbFTr4tB3o54rJdh7Rfe2da4ADXnkDuqWJpdbZQHFC4EqGCRSGKpwEyYj51YkQ",
	"KIc+UUhEbOknnXo5MJ3XbFGkw9b8gaUoZvCy5O9uJNeaiTuLI7IpjjhpgiqbKkREpENQwYqnoc3LwgP4",
	"/ekbJJVRujIkf65t1tdLquDrjBxpElFh2RhG/pUzqBog6YppcLnJoyWhao9cTHYNRdzV6a5z3fgbtP4W",
	"Wrf5bbaKPMXxPbyU4zCyja7fUhewrDwJndxI2dKL9N2KDgGwFs49JRFNEvNuRkkqUEoNYhJEhmPhjhac",
	"MuMhviErmIoEa0y5rob9Rb8HK8eXRz0j7xX4AUFiH4PgDjORAQY5Cd4uu2rHb16u3QG7Ou/mLAxTDSth",
	"yvLRkOBmyZIMaZnGzDd2R0XtRK2zwuVoIz3K1D/XEMYcreiCtZXfHuz66w3wU5rkK1Yro90QtFdBF5RT",
	"n5466ka5YJJAj5Ir8quN0+hqUDUQnDSYiDcMlpM8SUqld1nL4Wj+LtUnqGVtVHVwhfqq7uFP/D5PZuTv",
	"RhxRTMO3/eSGrtUTdHPHjXJFshwMAYaEr0GsrvV6Z75UOgFLSRPJaLwm7CO43YmW6pA452Ra3wyMOtDT",
	"3MCnGMf8URvL/GTHcyANYMdeK3J0xmyWo7msAwOPu7KStkifw0paGPvEoVvn8cHRDmhSOBXaQt7wI1Lz",
	"OY0CHHBWQaPeTXlYBztyeY26b0v/wlDZLtmCK20IG5CfFV0bkkUbN810FCkmWrfmzOODo2IwkOeT1FBO",
	"RawWNZWrgoKatjiQ8gsEDXll3X6DJwcVQx+eXGGh0o6y8D5BsizZYHHTW00ZPtGd+tMuaCAtg8ZDmN3+",
	"faL0bV5nCCxp0pfBArZzJa/L1vfLPLUCLpRw4GEdAAIJD0KmeSZlKt+25eQys0MLYvOYuARXTu01pzzJ",
	"ZZgpTyVfcEGTImfgoEBYybRcH6R5KPjvXcUJEomppuqqLNhgevOKQmOQO2IFCvWVh073x/ySScE0U2cs",
	"kkx3X4RtIeF0omC2oQapcpUEOwYM2AbSt5QcK9UTcAJPOoSRW1R4wwBSrjk4gMpo1DEKfO4dKnyvy+Gn",
	"HoR6Te62d3lIIdQBx4RwyElJGGOuNBeRtlm+p+RmCVpuGi0Jh0LJiqAKRKOq72Jyxdbfgqr/YoIVl9lH",
	"usoShvWdCtvAt5lM4zyyeX/N+52Kb3O1w6jSOy/AnZbJby9pdMUEkIyCBPdWb6u6XIR2B8XnnAeHjauB",
	"31DUTq9BdW+D5sroEIK4rfIEPqyojpZvMP05RrHoaFmqptFUtP/ukMUz8mqV6fWuyJOkNrvCbsRwJTY9",
	"VO1m1Ebto2Bv6+2hnl2x0julfF/RzGz8tyu2nsIZf0J7TjhlexPlXLRFMJjGfPESFzqXFqv/Xgu9ZJpH",
	"5XGUumbf4mMwF4/jmkqe5qrwDIFlqBnZL7U7hk8EZTUIzykm7PqtdJKZErewT+HYcC7ywNV/i+ynwR/u",
	"JYk1f1OS8BUvJJjSvR3Qu9B3oQGRF9WBKtn1mYSHBiKcAUJF3T8/xyzkpaT/ylkRYeWEeJ0SrhR8QFbY",
	"1VCxXK4XBUTRqQVcXbhCsgCOoeZ5u0a1gWAftbsrZQXCAtwHCCasrRulQnEFqj0YyyzLBhJZPwvmQGZ3",
	"WtU7mn07wwIU5ZSQcNeIAHN248yveKYZVcpcPXtp4cSdIx+qOaolgNE6CPt0R1tL18tjzAqeOEhZSFvX",
	"LC6hzBykM2BTkouEKUXWaY7rkSxivAClVS9D/mxRZW5aFJkrygUXiyPNVi18ST0K5VKZgzVSEyCXXScA",
	"Hh9MQ6AM+K2m0aZEdgfttgKh60VPhyxOtIotQYO4dbCeOsoGQnwdz4t9uEUpkmNtZ8BTBKQZxgE9YXNN",
	"cgGXR8QkXXHt2Y0Vk5wm/FeUwyoL9RzVyVMb9H7JIporZmQ7rtCZa5kLsK+m5VcAgc2FDWXCodGzcj+S",
	"WdAhBtb3hBspzMm32okL1UuTGPTDVJDrF7MXfyZximkEmPbmQCw3PKYwx2g2USi163hjdvYnpjRfgZLw",
	"T3jb+K/WHS5KE3N+sAhMA1/EeJp5JQNK2TY26gqBGsjCLm/1B0MidRpvRu05azK1QdvQOZycLTHrU0/7",
	"5GP5fNUWA4XW2bbs34XttiyUBgQEXtlaiscjw928SzX899VH8zhNppPDlKl3qYa/g+IQBr627MvyZtgG",
	"Cgm7WKihPFKNXzQg9Db9oQl21cUkIgNTGt2HB8PWDxcr3x5h1xdNzg5z8fYWo/6sCktvXBnbgN/z020s",
	"ufxmbnKVTaJJQjLzxilDWYKsElJ+S/GhQrB7qzHVPLZFRUggvFyIFMPB78JJlo2BVFjjnldGoUEGIpuI",
	"+twI3Jquso5qemYsG/x8Y/gFTBYyvIRebBNUbzqXJfMxZrwePt+CCSZbDPL7BN/wqHhDK6HftFBEknKU",
	"sqK8gnLU6P9OTtIsT6BggIM3Fj4gp4zGO4YDHhi0eefaUW9RjLAR7VAEHBl2JGhgHKXC51dTuaDCPFGm",
	"nWGJF6k0fz5VUZrhr0jbnxWM5+TWJkyb4SD4MNwIFhQpvdB7qkl6A36VmN0KfjciihGOuYh3zVwXEys3",
	"tzB7FXY16ORkmXs/6zvyp0VFaeSgnygv5YJlfyuZHIZ5FtTrEQRhUNH6+C69tSd7THWwvVQHw3C6OJu4",
	"89grXAFmPYDxQwqkY7yTBeEa85CMGYXGjEK7/rUIhk11phbpu2hhhW29RTVVkP91zBj0+BmDGucxSFaq",
	"kNsxf9CXmj+oQT46LzsEwZY6c3PZvK/Nux5zlSV0HU5S8APUGyvqCQH7oJbpjYupkmFYsY94PY8C6PfK",
	"fiNHhwV3XVvgAN7zhOpo6So27/1W3pcNHAF7HfGhTiZ6ovsKHBpj1sosQTMc5q8MKm3C/vP75L/Pjt+R",
	"kxTIGHjQt3n85S2MHN5Zw1THoPa2q5k1sC7NusLU6hSjK21S+c0pQi39QKmlSkC8vErYKrjBAYnhH8Yl",
	"oat6woft+RCDSHZDVUHiNssU4M0aOsxTllDNr1u8rU/95J/SNkWjuUPAIZGg+4G+TvnrtAfvUm2lXiqs",
	"fx7giWnvVCLpNZOel3ZhEZ4oGe1yEbOPs3+qYbSg4nQb2nfx1SGuX5pHVoJBHUIsuLYupcHzP+04/0oI",
	"qwfz77n2cQH8ztAP2Hd4HRmxUWQaRabd8hJtlonV67fddKzlwGF5q/q9Km0V3/iYaPkzELZk7TgGyVoe",
	"xR8lrS9V0qpRnY5LXpeyak4pVaZiWLx0PcNJb6y0HwLV1/hMLcu2PVtvyb1Tb7FZAp4qRO6YAKc62F2z",
	"4GyWiMYZaPcTJvVpnrCQiOLt4DbFhKkZO5yyM28zCx463HM8Ll8hl+15wtJrJo1IlisrxaWX1pfrks3N",
	"pYeJjbRGXsN57nWnxuhPetGV8OLiIv7PthwX00nWk8G3mrkXd+QXWldBSKLFFP2Vr5nkuj/Nl3/eZ7ZT",
	"UWOlkvzKjegdU2UfVaNnL3JVJgvU58evDZxxIkxZd9grS3wk5unAoKfWtZQDtzbxZmxtg0vxNv1j8BE9",
	"Ld5F82wQ9tEI7zG55hS2vX9y5G/6wOAvBOGwM74wy3RKokBd4aJQp6vmWCnlWyt+OJlOzlvTK/qSYcV/",
	"w2rYWoubHpy8b6VYWR5yBplODrm6as3QxdVVuBc6yrS63bS60TTLLvr+LYPrLrbspu/d6lpXT66yFkjU",
	"C95VvHWaBxhmBM78WC+keNgcPTDa7dzUvRoh9ynzHMFrmQBfblrNyLHzQ8ZfM/AatlefK5cEaQM+tv58",
	"BdhZRVdZwsUCInWuQ+m4i9fmkukbxoTbP4GuZt0P8IAU6ZI6MiW1HfXUP4rAjruoM5CDVkJlvlY1PxUv",
	"CHApt37KGGRmwxVLLWGKWQXAq9oSP5D++GiuG7VEo5YoXJV2Uz2R13PbmqKOUrkNWQFDF3qjCrEZ+G1B",
	"kJRz2eOKVOgOYkC4LlwEVfl/oCqg1je/Ok4S/duh8cOVDQjXmW6NC+0FGLRSkAooN9Rnc4B1WWI8UE4r",
	"R1hZXh92OE3iSM0fWR9oO69FtDEfBbzAqBH8cjWCtRemk+2raQVddden6lnB1GF4V6c6rCcFb1Gbtppr",
	"j4tGRp8j07JogQlUyg7ltdeUC4x3DPGbmK9HpAZ1XG9u7vQrGi1t1HV1KPQ0dwOYBftMb/ddfdjsXEPS",
	"CDuf+SKdcBPS95VFOMCldOPfLRSzfv87qmbp7UhpZ0pgp6E8gBe3LayrYFjI0jAyhZ+FWUdLoL8b+PuO",
	"UIticC+SIjD2pvWmBmqYH8kTpjJ5kAMT7OY4HPUAN5TdYIVh8pQX+WIuE/bMTCPyBIKBJ3ta5iyk9jXX",
	"LM1VxwSuyR1msc/ca86SuIMzgEBKG34CuXxtv5IElLSlQHUHSQwMKWJjrMSA/5kVtSLs34GSCAMj9Sp8",
	"aXVfQeRq1i4KmxOKV2yZ3sDrBW2LKggGm7zKIF06TigQcmZjltqIQLVRU+noirwM1zjWRuwAhp/6LFBg",
	"Bj87u4or0pPhr/WSDPUrCpnR8DKdl9nNOxWXeZmPN24e04CSJPXD/QTnI3PY13d5vGD9i6i3L6sdni8l",
	"U8s0ifvG8JwJw35bfQV+ztHHEIv7gBCc8ghz49kaVcrt0dzI6sn4RK2KCqErdqaWW0oTfHb2Q1eW4Ezy",
	"a6rZj2x9QpXKlpIq1p7uF7+jilQtT4q+n0eW38qSerPx2p0DgIYn5A0hjm/M3szlV/nH3GMvv6fMn2b7",
	"NVdAlwe0K/9nV+bLclchItfGOFpmkaOGWudSWGnUYFtEk8Q+fHEqnri0uwSzg3gBlaPu4n51F+buBM4u",
	"XywYBHSDA6k9HNPWZg7lLsnNlDwnfO7yQ9S51a9eBjWFo/Jiq8qLlhR2QzxBSkkN4ehCE1pkZ6rCLicr",
	"Gi25YK1T3SzXtQnMQVsu92LyGnPpXUzsemxWFa7KxEJslem1TYQCeVSqomeZjmifnMIySZRQiZHJzg/a",
	"bhbQ+DI3lIdhRpb0mknJY0ZaNNKqm8S5MJMCeOQY8jrtkYvJGTI1FxOSSn+n9442hu3foSLesSDtJfkh",
	"HZbduCUTBQaUSBd6EM57ax7WahxWjJl+wHhRm258CUab5GiThB61y7OZWbLeebuWydroYUf2QKOqN3ut",
	"wcgFPr4FK3Qkg1Sv9adgNGR9qYasEFnqu/sNJ/fK229VMO0sAOjEwkIwlk+9WabKq29r7/scfHcHVO3H",
	"8YdstqC9w7Km+wVuGynSN3ZW3zBleKc1xGL1vu7IP1XJfVwA94YqNGV4oadDclFtYrr4MO3Bp1uYp4oN",
	"WNybwfnyFfvf1CVwd9Uq3qTocVxbg4HJr6lgZS4kqawTIsx2tP9u38Uw75++2t99c3ywf350/M6lNjY/",
	"VnlgTAZqTjqVJI0YFfiGuJ5FfUkoLkml5lGeUEkUNyfB9ZJbOxKVjE5BZLcBsGR/xSSP6O47dvOP/0nl",
	"1ZS8yg3+7Z5QyZ07aC7o6pIv8jRX5KudaEkljaBmkNsrJhpWRbHKpxeT79+eX0ym5GLy/vzgYvIsSJ5Q",
	"T30WLVlsAxvqRoHyxVa2latRlZpjjEic3ogkpbbUYmzRTfn5eDVfua+prSFCbOXPAC/Rq6o+kNVSgcBr",
	"Sf29pBE79MIlhurctYdcnW+na9eg0WGi5LFE1S1et/FK33Ptk9xwQryWi+oG/fAJc7Pnkuu1OdkVTnrJ",
	"qGRyP0dXA/zrtaMH//33c8NHQuvJnv1aTglh0ZBGf3HUUqvu/ftweodKMjTPgEbIW5opW9/D71CmM5wJ",
	"itVAuZkE0nK7XFR7Zin/4J76mGb8R7aefDK7N0TGZWemEeATW1GeTPYmmtHVf80TvljqSCcznpYjml28",
	"hi+Qr1imCTlndDWxqt2JYx8qvRt57X6uDvHhaajbM8tJ2VrhaN+IEioxzt4rJ57O8ekE4sjiRVkM3mbK",
	"5RKqg5obqDDXesIjJtDGYHe2n9FoycjL2fPGZm5ubmYUPs9Sudi1fdXum6ODV+/OXu28nD2fLfUqwXui",
	"IWC/BqT9k6PJtMTpyfULmmRL+sImURU045O9yVez57MX1vUB8NFwU7vXL3Zprpe7UaGjX4Q4iO+Zhqp4",
	"mHrZlSIp7TCzInUpT4XB0InBc6sih1R6kMQY5n35/LnDDVsLwqtwsvtPq0/DO99b36ScBRCvlqTlRwOC",
	"r198s7X5CvGwmZc9B5edsug3i9GUQhcQ21OFHhKJygnY0lys9Qx+sg3Mfa2dBeSxDp+B6wUn74rXAT8W",
	"qDAaGNUQCLe0ghQsGY2BPDn8zvUylS4v0tQDZp1kfrhHZGg/nHPYCWwDMOJBJv2OxsSFPcGkLx5sp1yU",
	"e3087J9O/vwggHbVbaxQS15JmcrBly8q49cUxq85+bb1JoISoDXurepuV72RpmdrR9V3RyHhqGXfiobm",
	"gmLFDOfrB4XhCkneVgn1ihJYJgFGMANArmHMH63rjZ64LPxPbB51a6EoPIKqSepbeIWiSkMXaZiG0u7a",
	"VOEYmKMlj3SZWx4ciW3xAJc9GbPqcmlrpVQr5UG9u6LCR2ihSaVqycOtFt2epk5+gFT4NhO4AfEVI0++",
	"fTIlT741/wtl7f/t2yfkKZstZlMs9/IC6728mF6x9ct/wz9eWqkjtFOY8XY7NZi0oh/5Kl9Vagog4hWb",
	"9CsdlFUMzsuqEpCYCFPotyNapTvh8yqWQ6YjHLRWLmJF11gp4LKoE4fFccqLA1FgXoEGgFArZvAVJCgq",
	"4dRr1b3Xx66VioCOuZ0Z+nKfvveCWjaE2Vf+qweY9XUqL3kcMxBkv3751wd541Pyloo1Kd4NeGofYrdn",
	"VmB6Lwr7cuWhbX1MIdA3S0PmjwMs90cHvKjNBxU7d8Wg2wV8l8br+798CLNSK6Blzj41qMCLh1pICNDx",
	"SAbunQw8fwgyYOTehKOmayQ8HYRnELO/+5t56D8heUqYDuhi8fcqoSL22pGS4FQJ1CF06iJQvWK5H4DT",
	"TyMN94krLVgZiHYpOBlbmLBKpD4/md3xK38YmvH1A0z5LtXkdZqLeCQavdxKUPSXjGJ9tFKmiDrudpUW",
	"fM/0AxOCBTqg3p0KTCe54P/KmS0LBXzN48g3I60YacXnJ9lQHYWrJkfLW0o20PeByUVW1LDbFtswVPba",
	"gan/c7PTrKSkHyR5PTJ9GoWuL4sojnLeZ0aG8yDLBoUaalzbwWCu7RT7PzApLrPkPDgtfjA92KNS41EN",
	"N74I44swav6c5m+XZplMberN4EOyDw0wCRAT6y6+vsnOo6Nna4d9N/nWHhMsi+0veHxMRtZ+JOQjIf99",
	"E3LrftvtnIXxJH2eWId2qNHtanS7Gt2uvhi3qwCO2BQ6ZJ7QhcETDI1hmILRrGa1onJdjR9TM/J3sxMA",
	"VUqAK3IhFAgWgGQlmyPcfDuYF2llg4gA4JCk7AliUwXvn5QwqgcT3Zh1PLEDm6GeQG4smbdefa9tCMuK",
	"lEL3asNB+jo6pI0OaY/GVOBVHuJ9VmMZ2lzNivIl9yEC2cEf2InMn3VUVY0eY38wytCULQb4gh06X7Be",
	"soEtC7KxkXanNvjo2jWqL0Z3jU3f/faA1v7L+z3TW7u5W/PFegimfby247V9ZHa926Wq9+pCw61d3tEz",
	"aosEZJQkRlvJKLxsi06GTNVobR5CJq1309YI5e/Cb2kTPcvDEcZRpzNS4pESf3FqpN2YQaUkVeQiC1Hs",
	"IrlbaYBCdY/Xt6laKj9uUcFUDvq7IOM+FEZed6Swo4T+yPROMhEzuH4d2eTQkI4NvYStDfXbqW2zTTVc",
	"aHLnrVAWmN8W8Zu21ri7EumNKBbyk0u3GrboQ+PTatvJ56okfIk3s36RIGWhmXykUiMf+Ieji2VBgk6q",
	"6OdiHm6gOHN1SUYzxWimGJmgz8NMsfF19owWW7vQo+liFOdGSjZSsrsYEjYmZBWzwtZI2WhcGEnXSLpG",
	"Ge8zkvGYkGmSrJjQA0oolI0r0SEhqe5V0bSoojCYetKBOSYwfg2qyQjClcqr2cyg5mgm02ses3jqF0Ox",
	"kS9LFl0R3heIbANkVHgSCISBoCOuSEQVK2JzuNPT2cCmOkSg0BhNElsh2fSd2tplBZT9iTC+CVZ+ybB6",
	"amvgnJKPplprHPxI0kdu9A9CYMubGwz9bXzuiQIur9LA0gyNDmNs8BgbPMYGjyUZNny5x1IMY+Tr5/iW",
	"9gXBio4nsy0gttHjnmJjm/M8cJhsywJG78oxYnbkzoPc+QZxtJtRHuwVojwbaZjbpxwjbUeZfVTD/q44",
	"m/Yw381oS0X3ei+E5XfiYTOI3xkJzKgUfBxBpjM8eLMrD53u+dKPXjj3Q3hGGWtkp0Z26h7oa1dY8Wbk",
	"1foC3TOB/V34Bt1SifUotHXUnY10faTrfzx13S0KIQTeg+YzYHvdwzPwuyt10NhCUf7hsZ8Dt5B+leJI",
	"oEc1w0gubxXWd3eF5O086ke15EgvRnrxeGrJO5GBsJLyPgjBqKocVZUjBRxF2i9BVXknktumuLwPojuq",
	"L0fmb2T+vhRh8drM0yoSnjItObtmitAiEAG7zC5EODAFB+wLRvnDxDucpVKTVMZMQviircoF8QdmQ3zF",
	"lKarrBpr8sSM8YQ8FezGUN85l0q3Lg4GrywqxqEme7CWyXTCRL4yyEDhL/jxw/S2sRp4/nhu5ohcsEVf",
	"HM92CqR90VFM96qNMMc2xnmMcR6P9xQZDKw+P/OEsb7YyNemTV885GscaIyBHGMgxxjIL7c+6pHNuNBW",
	"CNVtGuhK20pobHO0qjMc5PHqjgLZGh/l8VF+tEcZbsqQqqPVZ7gtxhJa3VNcJY79wLGU3qSjD9gYP/nH",
	"IgoNTn33N/jvp13NVllCtWEIFU9FOwsP7IdrTYrmIR7+3Lb6qWzUq7aGGuWOCWhM06KknntE6paZ0UdJ",
	"YpQkRklizKZi6GyNbo3s/MjO/45e7gGpD2JXQrz+wLakO6hdiDu/4/f3jNct3wNnHnMqjObl0bxcVR8E",
	"uX/JaIysb/Hu99KQ75keCchDEpA6tEdKMlKSz4pzGZybqVdJiQ2dknIjp7jq0GPapfFijxd7GywCJD7q",
	"vbjfM72lW7vF4KE/hnlyJBsj2Xhcw2RnAqVe0gHttkQ8xoCj7dGOUQ86BhmNZtotkciuHEi9FNJGD22J",
	"Rv4u4oM28CV5MJI4uq2MJHgkwV+W1qov5wYoyMuwz6qq3BHksCh8u9jOexWIR1l0lEX/wLJovfbscMl0",
	"W3d5lE9H+XQkYiMRu4W0KFEI3JAZ8UXHbRGxUYAceaCRfPwOJB107B6UPCLmSnMR6cIBG/sWORFKOlNS",
	"gnXG2rJMvMGZB5AaM4r1iS4IjLQLKxYh01WbNe6Ki7iT3rjcCras/ZC8CvtkzhMbL1BfSyqSNUYMFBHP",
	"RC+pHxWw4NdMYPvC0f1evOi3sEp0IO9b5dY94Et0w/U+SLKK20m/7CNdZQn2wNW+wl/gUlsL8N7E/lj6",
	"35ubk7hrAI72mO7lmstUrJjQ32YyjfNIowOdZAueim9ztcOo0jsvzAY4k99e0uiKiRgv9jAaApdv9HIf",
	"vdwf7S0CvK++RalcUMF/hXVsls+o0nNGyLGhbUgtVPUjkjhDPnLFJFlSRWgUMWXoSzgtxXFlVffIGfoT",
	"jVdzvJoPfjXLlwqStqQ1xHc31/+9eoEly1LFdSo560kIc+parvuywpz6Y465YcaIzjGic4zoHED+Sgoz",
	"vqXjW/pobG7xJK6HJGgJPIttWVrKpveUqsWb4IHztdRnHr1fxqQtf0Bq0cJYbxJLNYieYOsKPdnI+hOY",
	"ZAytGm0yo03mNgxCR3zVoMv8PdNbv8m/E++ybrZhvMrjVX5gXr875mnQdbbeVVu+0KOL2ZaJyiiGjE74",
	"o+SzTdrZGQw1iHRat7atE8/fhWvbpsqbhyWYo7JopNIjlf6i9FPWhrsWUa/lF5uerUXUb/st247G39H4",
	"Oxp/R+PvQKagJByj+Xc0/z7ig1k+jMMMwIHXsd0EXDa+NyOwN8WDm4Hrc4+8/WgI/kPSjTZWezNb8CDS",
	"4qzBFdKyod4kMNFoER7F+tGMdDueodMmPOhSg1X4Hm7078Yy3M1JjJd6vNQPLgj0WYcHXWxrGr2Hqz3a",
	"iLdOXkYZZbQ/jGLRdqloj514EBEtLMX3QEZ/J9biTbU8D008R73SSLNHmv1FqbJspaI2Y7GRb5Ud2ivE",
	"1JBry/pS90aiBhRVGi0rD41WDn8+QF80muJLnctksjfZnZjX0rauI9exwyLMXmQoIRPabmHm1fGofJg0",
	"rb3eQKkgB0xqPjet2RlfCC4WFm5VRwdn9y9bK2wti0egex7MUxQcFKuU9I7wSsg0SVZM6K4VsqLVoJUZ",
	"UNosQ1wsCLs2R+0PZ37oXVo1mZzfH9NXbbIEmzqIRjJVisR8PmeSifDomJBkk9H9hB3BISuZEvr23ZYS",
	"wY7lud70j9TmYlOM5ZHkATuOGIcNB+ixHdHdxk8fPv3fAAAA//9LoWxU6FwCAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
