// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNrIw+irYOV+V7T2jke3sbu2qKrWfIjmJNrGtK8lJfSfydSASM4MVB5wFQMmT",
	"lKvuO9w3vE9yC90ACZIAyZFHcuLwnKqNNcRvo9Ho//51kuSrdS6Y0Gpy8OtEJUu2ovDPwyuVZ4Vmp1Qv",
	"zd8pU4nka81zMTmYnLG1ZMp0I1QQatuSOc8YWVO9nE2mk7XM10xqzmC8dXCciyWrepsmROeE4ji5IHrJ",
	"iNoozVYz8irXjOgl1YSKDWHvudJcLLDpLc8ycsVIfsPkreRaM2FWwN7T1Tpjk4PJ/g2V+1m+2Kfr9SzL",
	"F5PpRG/W5ovSkovF5MOH8pf86t8s0ZMP08nhen0Bv4WWbVqTfA5rpOt1xhNqvsK8olhNDn5C4Co2educ",
	"bTp5v2ca7d1QKejKQOgnN9uR64QLcOMe5UIzoc1aaJa9nk8Ofvp18r8km08OJv+1Xx3jvj3D/a95xlyn",
	"D9Putmcso5rf4GGbxpL9p+CSpWZdcHJvW+BprO+FuPmBSjzq2sGz6gNNU27a0uy01qRxFNMGtF+IGy5z",
	"sWJCkxsqOb3KGLlmm70bmhUGbbhUU8KFWRdLSVqYYYgshOYrNiPmsK7ZhlCREuzBaLIkq0JpgzNXTN8y",
	"JsgzaPD8r1+QZEklTTSTajZpbTuCJw4MpzK/4SmT52uWDD+rABzNKdQBSSts7BkLmn2YTgxqRe5cNSEx",
	"rUpoPPv//p//tw4DkuViMSVKU6nJLddLQknGtGaS5JKIYnXF5BRgl+RCUy6IyMntkmum1jRhs0FX7ddJ",
	"LtgAQJ2s6ILFwN2H5Sci4yLe++2Ht91ne66pLlSYIuA3Qw8oUVwssjqMLS1L2Q1HkDgScSrZmlqacG5A",
	"jP88K4TAf72QMpeT6eSNuBb5rZhMJ4ZAZEyzdDhdqe/An7P10VtE61u1qtYnt8zWh2rdrU/eRuqA/iHP",
	"CsTc6vrUwX3M5lwwRShgb0puoAcpFEvJ1QbepDpJrl+l8MV4I/h/Cob3wRJ2f1yD+1yE6H0bv336CZO9",
	"/UicR5C0EDYEtyYJqm8dd6Tau/+eKw3466GtbWz2yDVbqQG0p3GG1V2nUtJNL/3Ebogf3bdsJ0f+qnXW",
	"gfM0xzlnkomEhTgh+8lwLnjH11m+YSl5fXSyZ2CUcSo04eYUDcU012tOE02uaHJtHqrOuUO45K+nh2Sp",
	"82K1onIzkHRlmQ9EFSdb3zKa6eVmMp0cs4WkKUsDpGpr8lRfbTVHtIk3ebRNgDLVG5TLNaAr9PIoF3O+",
	"aN+clM1pkWl3vbqRyTYmtNBLJrS7UGvXOYBkuVxQwX/BFb4QhstJ25P8uGR6CW+v15pQyQjDLmRukKw2",
	"bTXbVZ5njAoznVtKFykw+HBDeQYcV2QrajBxKPTSAe9EzPOBtKHZq7Va08LwHnO+aF97s+g3Mgv38nbz",
	"5ux7AJw5u65DSjLOhD4JHMyxPXFsQU6OYbzXJ8dHNVC1eV2u1hndvArSp2+LFRV7ktEUjsC2JZYMtMbi",
	"yq7Cw9fJwZxmik0jeKSXXBGuakjbBoCHN9ywCJon209BDROpeVKOTx7PZb6yZ/fEEMd0I+iKJ/ZDSjW9",
	"ooo9iSxEFaFrCCDHj3Csj9vn8CQEvE6mgKcGWeacyUFoosNioxUZ40TB0decp8lkOrn+u0EZStdtWtp8",
	"GcyYQN+niPNn39t/vfYJhaVtoVfjK6qTgIQOP8PpCcIyBkIYF+QKflbsP4V5htr3LuMrrsOyx4q+56ti",
	"ZUUHc+prJhMmNDyQc/vaKPOeFuuUakYs1wVzmqmG8U2n5ajAbK24MNNODp6Vm+dCswWTKMsqlrFE57KP",
	"jH1Pr1h27hqbjkWSMKUulpKpZZ6lfQP46/oQO4hzC9nIgbjP5soCI2zgk1myDXBCAF4xwt6zpDByMRcd",
	"56Wi8x3Wx8UZQYwfzhcibn2YmkM4wQ7PmsR/ajCbarbY9I12lmdZXuhz17x5FcpxQmh+ZPY8N1ePnfOF",
	"EWfOzNZVAFmjTYn01F9E2h/h3SWKLwRLSVL1JUDLzAEdHQYeqDX/gUkFM7ZAf3piv9XO+QZ/YylBiCDP",
	"wVW1LCt0zs2lxa3PyDmTpiNRy7zIQFi/YdJsJckXgv9SjqYcI5tRbbZlLokUNEPdCUr6K7ohkplxSSG8",
	"EaCJmpGXuTS3dp4fkKXWa3Wwv7/genb9dzXjuTnSVSG43uwnudCSXxU6l2o/ZTcs21d8sUdlsuSaJbqQ",
	"bJ+u+R4sViDOrdL/kkzlhUyYCjLr11wEnufvuEjdIwT6IVQFlSBznPjZi/ML4iZAsCIEvUOvgGkAwcXc",
	"PXLlSTORrnMuNPxhOQJVXK24Vg5fDJxn5IgKkYPmBWldOiMnghzRFcuOqGL3DkoDPbVnQBYG5oppap7h",
	"vjv5GmD0kmkKN9mKnl09orfL6nImqhQC7zYMdm+9k9V9s6jibdKufCu6YZjlLWgH8NaAh46sRpuOxOL+",
	"iUX5fIUloM6zGfT0xd+bD+0XcCRdn4B0mbNGwrUdqcDj34pWOJVcQ06SdL1mklCZFyIllBSKyb1EMgNU",
	"cnR+NiWrPGVGts8FuS6umBRMM0V4DsCkaz7z+A01u3k261xCm7Cw92suUTXLklykKqTogv5oYClpxg3N",
	"eMr1ppSKvIWYaea5XFGNvPYXzydt1ns6Ye+1pF3mofKeRcSs6v407EZmYEI1IhdTTjdjwIuWRAdjYM4M",
	"nNf5usjgp6sN/Hp4ekIU3BgDe2hvdm7oGl+tCm3E8oCVCBEpyFVegCSj2N/+ssdEkqcsJacvXlb//u7o",
	"/L+ePTXLmZGXjpNfMmJeplnJa3KWAUdPfXzoYliRKtSO5Gqjg1oEYGFlWCFxIlJEMliTLHEC+yDBB1L1",
	"n4JmRl5OQVkRvKAFDxC7NyfHD3BO3iIUXYTU4W/gd4C62QZQXwZvwjXbEOzl7d+KqKB2SJuXYDgCmy33",
	"a6ofADANUuiwuYYc25G+iEq/Qii6Xsv8hmb7KROcZvtzyrNCMqJK/XS5S8/aqCJwJ3xeOQqoNsXzmobv",
	"qB2yLc9NK8CR3MjgJcwH3S5DXlF8DnCN5TfUw5uTzf2bNiPfifxWkMRrKBk5BNCxdEqOmeDmvwZCX1Oe",
	"4aKGcSpuzKBi1scGbwtBHCgHim+wOr6UacozBQ9ILhih5sppd9xJISVwINqcqeNdDVKfeSStoXuiSl9I",
	"KhTMdMFjRnDTjmi+YjhTuTRd9mUp8kVmXRYNdU6oyPWSydppGwZoz4wV5kSUoRcR9S4p1bu2HeF4Jwxf",
	"56BDr/JC2xWXywsStPwKrnv6DRMM3+nw7meOlZktypZIVOrQuKUKKJ95s1JSrHFa/13/21+C77pkVAUF",
	"FfL4SnI2f0KwRcU6uDkfqUE7HSggulGdQFhpZwd1Q2eKxg3QqGm1K5iGUK4EQHX+nZel3+ZZg9EUkDKf",
	"kwtpBK2vQQFPrC3LN9WZ75PpBBpsbZxrrM6O1fjVDd342ber1aEZVYxXWMd9ScLbjaN0k+nk4vTlD0wC",
	"j4HmPfcBaSDs2RDAdlPQ1/KrjDX/cDTllEoFTc83IoF//GD4XNMCdY8n4lTmC8mUOfw3RvyxLhxrlrim",
	"L4tM83XGXt8KNP0cg2L7mBnJhysjV5hOww7ihZB5lq2Y0PY99fbb+lbfbvRJ9oaItilhGW1RAjnaor6c",
	"M7bOFde53ARBbyAe/dA6H/9jeVZfZ4xpdwrwR+jU8DS8s8Mf/BPEX4aeI6L5nC+aDhjDzBXfcB3o3ufT",
	"9F3J/Z+zRDJ9B4eoO8z6rdbrUDeAwbpwp/IyF+ag275w9fd6hc36XS0r3UZObKd+1tUfPeiF0+0Y2d4J",
	"7lLm4sX7tcGlMKMjc0FY2YDgewlPnRk7LTLQ2vAVU7NLYTZpW3BFfv4zsf//8wHZIy+5MNLrAfn5zz+T",
	"lZUIn+799R8zske+zQvZ+vT8C/PpmG4M0F7mQi/rLZ7tffHMtAh+evbc6/wjY9fN0f82uxTnxXqdSyNm",
	"mIOkOjeL2DMND0qh1XDfqKl6zGaL2RSG4YIszZLL8dgNkxv47YmZ9+e9nw/IGRWLqtfTvb//DIB79pwc",
	"vjRn/3dy+BJbT38+IKCrc42fTZ89t62VBi742XO9JCuAIfbZ//mAnGu2rpa17/rgYpo9ztGfr76Xv1cg",
	"Me/y370ul+IFOh4byJGne3+fPvvb3vMv7JEGWZmjQul8hYTFeTnE1CFNbgq0RajyTUkCAxF7wewBBKds",
	"irveIFwgMoKgCIxn3QuoxcTgwkM+Eeb3urlsvdwontDMG29Uco8WsdEitl8xIMOlG9vnDraut9F73HLU",
	"bfvCibi3UiXO+o603R6zICulm/Dr7/xE5k5nYNDsdsmTJeg+oCcZ5JhrpgE/9gAdfVXO4toQJ0mXAmp4",
	"dE/kHXZmYZfyD9O4b24lA9ompdsrXLLGuu7mqtsUjyO6n9ID1ZyXB9By84Pwqu6BGXrVFDZw+LMEZ9CG",
	"f3LAQbWOpjzoMNhAU/+1Q3WLo3yghPD9oXeikOh2z207s/RAFfnwGCCPPP1ZpUVAeEWdJiUTKZMsjT7D",
	"Z7aBe3ij4/ZplevzdG5S5VmUw7CffUbDKkvg5yQXgiVWr1AedsgJCpj1k+MwIbKfnWtneIYwYmDPl97T",
	"0cD3ktcrZ3GE2pE2s25rfviyFviUUAGvpUJtMThn0Yz/gmrNMkyNyRUXNJuWa0b3MNNtSphOYsdF09ci",
	"20wOtCxYAzUbu5p6AIwfpS83twHhBrN8J3Uoldal7VIf3jpDTeWC6WHPpr+UC+gXVvbhkMO25I3TJuOl",
	"MQkvizIztLa2YnqZp/Ur5avA3ggGCh9QcCU6l5szpmrr61Ikda3YG7mrWX3WEgon5h2UXG+Oliy5jhGk",
	"eNvm7a2TLO56kMR0IWsmzY1Am/gd34C94BtQSTzNOXFFH0H645u/G+2PjtSjRd4CmBXWuTiuN0I56d/X",
	"sZYqvm3wMLSBaqauNv4a4u3K1cWbVOtugzWqk7fMSQxFW3e3GUkCs4BLud7cHWnAgWlbFqdCb2BvqkX3",
	"MDemdQmr9vvIV4YTXK3d3huD30DPikcdZji7062ycYx4RI611uvVx8D5zhezvZjBVzP6AHjK9BK/w9fz",
	"TlexcS0iW4rdrJ473L6+1bX7nip9zpiIPRrue/OhAFRT5oP2sZBG718WnahtFrb8B1pBmXBuFUYy5A1/",
	"mg5UbuBPuYA4Bn3P5yzZJBn7Ns+vHeI4DPiKzXPp2y4O55pJ729scMau8txvUf2wDWbUltKaOtCmuZro",
	"MP4CY+N4a24D505iT+Z670BgbKpHq8F3xS009no3RiE0SIwQ+YktQhBrcwRogLTUoG4Vq/+yJUlqrLpJ",
	"VBqfa6sIfA8tradZnTwFHb2rb3WvbvxdjertT+7D7Z3EIM2YNWaM7tm/Nffs6cQqBYedoOO6dufXHfIH",
	"OGYa0s4co6NWKGzcfOg3bmM70Cyl3DRacUF1Lsm6kOtcIQI72tu1kkCs6HQCtkouFuAO0XFZ5uY7aO4V",
	"OoNBxwYjOtSftQF3DxKtBQ0F9xlTeXbTAW6q0GMTmochjnt0DQlVJDeNyWNRZBnhcyJy/OWJ2az50Tz7",
	"TgMWMKQ+0AG7vQcPeC3ZDc8L9XKbg7Zn7PpmG2vTTu944GAPyLMi7un1bX7rFKfzjCcaGGtpN+YDAI3u",
	"sJvJdPIqd/+CfR2zSAKcTpRrrC2Ocq9VOFDD/0rw05V9olFHSF6fl6rhqD5qFXQFvagNgtlC0IAGUez9",
	"ynQct3NTd2GWX58P3sIPdWOA20b4zTZfjvkiGiKRwrfmWOh+QdSSPv/r3w7o09ls9mQoaOqTdgAKLtuS",
	"r4+WVCw+DWVvriF45QW77aBygt1auob0rqRukq3yG5YOI26ONHRM5JqEZxO5YEOmil/c+EmV3n9bIXbJ",
	"TPap6ZJ1MYzTqK/DqZxSrq4/pv+KrfKhvE5ohKbT/rqYlIPa1Q0FbTeOq5pvHgK7jtRVKp8fqbTC15Hk",
	"mic0u3PioNBC/bxE7a/V5KGv3oJCn90iQ998V+fye7FiXmqBsDeXzZtCxcZ6Rta1RH6mibfNvIwQA+Z9",
	"fjsNR+wZ8U7CcsrUGujLnwsCUxCX+sKIevu5tNFl7tcZOdQkY9RQY8Gqxi5loE1fktYybv7aWP3BhFVZ",
	"HL9cyzwtwFw61ZzJL+cSElWmNi+Rdwfrmwz5Cbjl4C61NEyFnw3DSydioYAqPG73qWbkjXIxdubBtY6Y",
	"VJHKubYBEuXcAC9LwWFm8PJLnOzZ1Op+1kuq2J++PGUi5WJxOXkS0azXILXbPcLgw/ZYRwZvj9ds8wxt",
	"zs+m12zz/E/4x/Pwhj50ERW4FGqdC8V6b0UTm7EbisKwTQyQKaV7D/kQCqkVBCcHX3xo+zjUW8T9gUrg",
	"Glb5lklGbMaXeZFlGwvwNOQQ1HJ3qE0ZJ75d3GeD96QdbpSVm8mwbH9leqS7OBE1/MdbgkFSZlULLwS/",
	"32ENQff10PQqz0IHfeHdI5poflN5dVh3hm1VR85ZJRigXNdBbu2mABFeA9dhxRgrlQHLE6AuZmm1B9w6",
	"zNsTsbHew2HQcJkPQQFTOqcRLxv86CwsquHs3wgdMFLhKdWaSaG6chehGmNtW9Y206K26O7t1lEIjgqR",
	"KWa/zSX8Ny80UcV8zt9PCSb+WbIs21N6kzGyyPIrNxmsH2anC8qF0i6mMduQLKcpwylgTSv6/nsmFno5",
	"OXj+179NJ3aIycHk//7p6d4/6N4vh3v/c3B5ufdudgn/99Pl5ds/XV7uXV7++fLyn2//+/H/HtbuyT8f",
	"X17OfsKGoc//K57VrCtbH6oaT/OMJwM51zdeD0TX+PvR7VPS9iIJG2qUl0TUEk9i+64omMF5hu6eiS5o",
	"VoWefiyttRK1T3IrG9EW9KXtnxu4Y7TtZbj16A0vzeHBy+UZABzRj9Z5bBo4BiN7aUjhdMeAZf+9GUSw",
	"KxdK8Kmw1uo7eR44Z4ndWJjJ41evL14coBWgDOvgiohcE8l0IUUt2P/JQJO0EakW+d6/VS72+ELk0grm",
	"ZvHOIHYnA+WWL1TZp/ZGbSvxbm0caGE2knsXezNggKp9SffSbUheGvEt8a5YbVX1Kz0J33AfjD4el/cB",
	"zqZabwU1/9g7ONM7u217mL6kMr2lkoFlEePHDCePeyU1W9/u3bntGlw0/y4cugOguZuVfqtkzWHfoNcQ",
	"0hnOy+x7W5zmRpJJX8/nNeehw1vKNUTuWo9mDOsGVf0pLdSWBvzahryltb55qw18rateap/aHiS1z7Vt",
	"Br43XQpqH0PACDRrwqc6zhpJGRbO93rt3MDxNnjZi9j7da4qWk8XTOjZpXhBkyXkpElyKUFGTjFLRcXA",
	"47WwVv2ErukVz7jezC5Ff2AgbqJ2q5I8y7DURmmVjjJGZpFRdwfzFh4uoKwHNgleQt/QHBnDa2F4D4xM",
	"tXBqhS1WIxvUCTn7f5XnkMB5i6Ew7nLI89EK9TTvpSOCCO3wLl+XlPLcUcqBy2vav32AllBor2JaP744",
	"3Wrx8D2e72toCQaRFRV0UelxrK8ClHNJsiI1X26XTLjfnTPLFSNpfius/GTeEZsvJ+Bsa9udY9h1L1OD",
	"mylbl4/7Xft/6AFbeiezHK5ppw5s/vNoEy/v8HmsbfZuz2N7iC1c2CqAlf5r64v8mEKSpteFfj23//b8",
	"Fu9ij6gt0psi8NWfNdi54UBZ/9oyOfhiXg9b5lSaLrQITHalMAEXbs7Qj6CqZwOW907Zt8Lk2GM3IG1Q",
	"mVP+19ZbdEiuJKPX5kZ37uRqQy79dV1O2s6YFXKpJk/7G1i8XVP3wnWuaRYxy5lPXuRsaKaBaZws9fst",
	"QcdKL13QaYZwAaimAWRtnn9jw0FqxNV1b4qTrbOKTH9jaVGCD7hVW8HLjQPA283VNaZE3KbuX8olGJo2",
	"ZeE/p3m2nhLemN176ahQd8yVLGDWr4rUBgY2lIeNFvWU+uyGZbYUSn7LUrMs2xrJpMTMQoQDnq5teqE2",
	"GBYyL9ZfbeLKQTS+XbMNMO82IItANyhz6LyKqvmvYLk1bZmnL3780+He/9C9X57u/ePtT3vlv9/tz97+",
	"+ck/vY8DNL2gmH4jylIwkboOWGDBozrujLwiMu5SuyJ9CD7QfXfUZ4Cvhz3TN8pKzEkh2vOW57jV/EEe",
	"rvCz61nCNnlqKEh8cWXqXLeOMrUAhifrnCS2KhoWLiw7VIyvS0kKnouUQDYtfmMjh6A+iR37akMoqhkL",
	"wfWMVEl7yh8hfeQB+Vlh/huFyX+n5OcV/oApbcwPS/wBkvcAenuo9s+Dn57t/ePt5WX65yf/vLxMf1Kr",
	"ZRivXogkN0z9kPhYZtsinYPwZiAMVNOG47vP1a0zyo1Yiyl2B2dXw6lObWf391d2kA9+krVYfShWttiz",
	"uts+zrga89x2aFK2wJihF6mVAa4N21aTjiIWNhGrwUZcQKfpYwxnGLP1/AGz9bQu1HaJe9rdd1uvIpIw",
	"MiQwRJtWSXrDGoOSUHjWO1KRrHiSBuoyT3akg74tq4eV2Y/JkipyxZggboBZsDIY+jx9RMXhQ5frG0cC",
	"dep6nW2qGo+RVGitw7P73OqEPFlrkDgRP+o2H98zad+Je7bzjz37w4jjN/AmVNsMT/7p31JVO/hhMeSu",
	"x1ex9FL1LFWm7QDxyRt16m8pIIVMtzyCOzgwBABfHtAsiGvhYMZgs3pcY6vJyBJ88gjH4JkMcqFoM45j",
	"2OPnWpUmzLD00wDwOOXoalo2ROrTavtIuSAmcOsJxFSoSBRJqAaKX85BYUpp/10JPOJ1L7HhiROnE9Cm",
	"n/UlPruA56gz+RlWLsXcTrN/q1yQx7k16na4f++UW3FJ/J0L0S23hZ0tA8NV6XS0ZIKYO+Q9IFyF2KsI",
	"h2POcxiyRaxckYbbvYKDHqWK/b0TM+U5wfWVDvFxuV0/ZLZ1VZB2DQz2ETR/Z3U+2uqLjtO1TboYzGV+",
	"axVghgTDrQePW0q+zvhiqcmRIcl55iOrl4elXfjZq4C9rSbmsNBQsNRTwBR8z71C4WN/c/a9O503J9Ut",
	"BCM6KRS6Mq+le8X+rzNiUAS4j4yLa8xADfO5t7PD4eCuKqaYpqlVMdxNEIXBIJQAOPajhavhXVX0sW98",
	"o1SyjzRYb/UOqIFD73lXci+clfEIGnp1DY6pptUy/WsOWkkg/dQt3YxP5jyDaBty8f35LF5QfO+abToX",
	"8R3bbDX5Ndv0zd287BGotJc46OCHk4QBlMGl1zTXIr/joXv7MkiVS66jIK/aHrqmcej7XEo5MqkV5Itd",
	"4FBILXLCriQ7TVPJVOn90btx8tgxtctcaSPbHqxzqQcESXcAqFxs8OQN9xs45hsURj0ds/UjYDfoGE41",
	"yRPwAi/Lp6HTW4CYhyPjmuI71EUDMwbCAkmw5IsF8GsgR5jJ0bSC8grwRhDFyOb8PVpNGAfNkxnuAMvH",
	"L8GBxvygnngz2K+00PkKiq65oJUwpzcKxrsWjNMqNr/zFTQjujh+cPC/gYQTqPUdphs+Y3MmoUT6KBLv",
	"WiSOlEc7xHtXpWltCKDNLLEGjmtbymyH1oB4ITO1zKWekhVNllywap32+IH+1POENEqeITnyzJfONeQI",
	"Czt6JY6ObOnGMvGi+/Cm9OWv/9Jq6LKmNH7xx2wHHEZ+bvQ4On3TCp8/On3TDLg/On3zyjztVaOXkI+g",
	"1Rd/bnbHXxsjHHN13epvfmz2Nr81+nqxTnUfc+9DyzXd+9ZMN3DMlWVV/NSYASf1hs948+cy04/3oTHq",
	"EUTM65aHof297VtYdgh6FZbnuVWhMScbN7AhkpeqO6NTRwUu88uJuLG/ndhH6oKq63Ji/8dTJldUQISl",
	"dwciVcfczyeC1j9Yap9WTaqL1q4wVi3PLzhW3WL/13NNZfvXcqm1AawzSPP3r6hOlsdcrTFdU+OrhRrL",
	"HNxbXf1x/RpqR+aCa+/EBpVla8Gu+hSs1GZ+5GLRIlC1Km7NH8vW6J1+xpTOZSQzDvYcxBWcY1OvKmTc",
	"0c5jIF9j8UWkJ1NiaY1PyUtS4+jQ236bUrdmt860BOpLTsu6lLipqWWco2y7l9oowL3vWU+jxFUhnZqH",
	"rYB3Pq1yiFh+frMGqauW4QhDtNdrG+reSR069bTdOfd6CMsWIzfTy8VyQvWENUYySHVexMiI8R4do3qU",
	"YeiwVZfwuFsttGeNDfo0YMB6j/ColkAMGA1bhkdxxHnAMLZpNU7gZYpWXmy2DI/SfsoGDNjqVI3d9axF",
	"nZWjXfxxa29IN6YEG7fH6l1XrZkn3bkoaaxg76cS+zAdWIwzOvigqObI9R/Wu5vU3WWMJlHrLwsaQ85t",
	"ekaxcGjNzSB69Hfuxda+ITqu+DZdt9t0J/XcpnOEmG89xEctIkyuP7zdKscf8CARPxX3qeGbcgOak9Eh",
	"5ZM7pJQHMcwLBVTIo+fJZ+t54glaQQGrXAWqzOCaQbY3I1G2lWUNy47r3G8g2HKeHoNJOW9oz1/zzKlc",
	"YnuGj+jAMOehahRJV38IdCCavdfk8ZuLr/f+DoYJDHuobFPVJBBDZ6cJuR+Ydi7uod+q7IVxBKNjzPbj",
	"5e7M17LAXSRYKpK7m2fskcK4qKkXCmNNNhAR49Imi2LFJE/IyfGMHGOEDhDey4nMc305Cd+SPGWdU6+Z",
	"tDpQYtrOyP/JCyAeuBgMxV+Zqz6nK55xKkmeaJo5X4aMUYhq+YXJ3KVYfPq3v/wFjo+im1XCV7YDFsEL",
	"9fnL86dPDPXSBU/3FdML8x/Nk+sNubKBPaSssjMjJ3PIGFRCbIqR+PXNwBUw+1Qk9QBmlhcueFqoaJJ1",
	"hBbkBL6Hg4rh3Gun//fL5SSlGs7mPvYy4AwLEKoN7Wn1/J/PyrFrPzsx5q1d4Xahoj4Z6eXA/DvX1/jw",
	"CpKhs1MKji6/tgMqS6oQCa0Ehi9wt20wuW/4ZX6W0pE/G2OIxhiiSmbaLm4Iu+w2VgjGDEta5ae6pIXV",
	"Jcab/MklreogBklaSLNHSetzlbT61TitsOUrKKwS5OHgE7Ch9UQxVdD8wxTD6bCahKx/c6spD0qDZXYA",
	"bNXMMgJbHpgZxaYBP2UyMVQqVtXFNjO8tm3nxLE7TDYvsr6NVS0/ZnOardaGZnaGQviy9UW9g/N/5sqi",
	"kaHo1rUZXPjzIP5ovmLp60L3bRLawUAfs8c7J9AZPktXQaImjKf2MoZQa1rmsPEwocR1D3CDyEJbQfxZ",
	"0AXP7hkiDJ8Ep++CAH1n2E/V7x3e3SR4h5Cu4ZaBuEuQAulAPhLgfYAOGzIeHtoNi3nw1TPN0eTZB2wE",
	"aRmgYmPBDFYzSMTLXHrPIHx3d7odU0MlE5GybQ+4gsL2h1232D38IVsL/4PeJ8sF3f9NalhSHx66zrEj",
	"BF7pmkiq2SKQKMCOYcQgaFG6O1XeXpDa+Kt7f33qT85HvzfNnQ84xmAYZ7vNdhGcLQ6iYQnBEMiv+ngS",
	"y7BVFTaQrGBh6AbAOrN7VZqZ8FY7gqJhK72B0Harw0plnNUaQ/BQVS2qU8KslZbykDByyezXRhHLdt7I",
	"RqbCe1OQefWQWuliw9qsZuJHt98oYndi9J1ReXBJEWg9JQwsJDTLNoRX0oZ3NZb0hoEFB2LQ8I2ExHKC",
	"LlgtAowLQsntMmZR3C7MuDzxj6/Ikbay1G5Tw7kkVYNUXHVqtWVc8zdMMMmTM7bOS2NNV52ydSBYv89L",
	"CYd2TmmFjIihj9c5uFVvoGqnZk8g6Te6NQ0rC2uGtm2Ce+U6UECr9TovuD4z2wnnQ7AuVxib+Q3X9dJR",
	"BIMHt0kN6hKCukrBfOEoUOXVFeRMK+j0P6/VUKXqMsztAh0/Yze8KycEfjWLLlyNut71turDlYtvzTqN",
	"JTmdTsQgnr9RX61/NQKZaHvyoYm/zfPrw8QZWyt7ZiMj+byzVBAWGbelJFdMBzJiXjHC3rOk0JiQYhAl",
	"MmvrpEaar1ge0zP9ptN1kkfqUT1b56PVo3q2TipS8mj56OMzdn4IZQYe5kJbYcdZISYf3oLNuP5jIIXm",
	"zQ9UfkwulBdVlVFyQyWHcLxrttlDy8WacgnFBf6NYqZLA1sIA+Nglm1ZiKjT0soAuo6hfuUCKjaEykWx",
	"As6hUCDhaipSKlOsF0fURmj63iAPL4uM4rkrsrJevG4mRdZ8DbLxAlLjTQ1GcbjeGyxM6RZBCiM6E0qu",
	"qFqSvQT9gN6HVXO3ubw+5hE3DvMRUzy7ZM24XUjHihmQCyGcHcgudACpK0SUpFTX9mAbXCu7nVK9fL3u",
	"dYCo9Xnx3jB4WGCxd11e47aRUxBWfvaIGzP4ByUVcqJlwczRlWxImObZHNAsDZ5aaMut+5RHvKjKKNnH",
	"6gkx84PLD9XgQcYyW6MfX2GzBUU1V9a1CX4tlz7c8lhzzgkQ5Dg3QK2rSskWoL8cARVAiZYlqIFTTtD1",
	"/iPBHMozPjVQDeKI1usqN/AWlW2PatySWeS3FxenWHzDUIIAG09niQy8XZivmDjvP5nnmhwdBvFnTZW6",
	"zWUaY8DwK7HpDVDbH1hXaf8oxwuF413zNRp/f2CyzCIfSH1xzdeW0bVMI7nxOoSTfepMDQLGxffnmJLF",
	"+RwOWroZ/Zptho9+zTbDB8+vYyUC4dNuoF8oJuM8ovvaO9cAB7zqBnRLE0ut1wPFCYErGSZQGKpwGiQj",
	"5lcnQqAc+kghEbF1tnTuJRx1XrPN8oqwFMUMXlb83a3kWjPx0eKIbIsjTpqgtnL3RiSkQ1DBcrShzcvS",
	"A/jN2fdIKpN8ZUj+XNsUu1dUwdcZOdEkocKyMYz8p2BQokHSFdPgclMkS0LVAbmc7BuKuK/zfee68U9o",
	"/SW0jvltRkWe8vgeXspxGBmj63fUBSxrT0InN1K19EKRd6JDAKyFc89JQrPMvJtJlguUUoOYBLHsWCUl",
	"glNmPMQ3ZAVzkWFBL9fVsL/o92Dl+OqooRi9VGQFuYwMgjvMRAYY5CR4u+yqHb95tXEHbD2miDkLw1TD",
	"SpiyfDTk9FmybI20TGOyH7ujsjSl1uvS5WgrPcrUP9cQxpys6ILFaqMPdv31Bvghz4oVa9Q4bwnaq6AL",
	"yplPTx11o1wwSaBHxRX5peBpcj2o9ApOGsx6HAbLaZFlldK7KpxxMn+V61PUsrZKaLiqiHX38Ed+n0cz",
	"8qMRRxTT8O0wu6Ub9Qjd3HGjXJF1AYYAQ8I3IFY3er0yX2qdgKWkmWQ03RD2HtzuRKT4Js45mTY3A6MO",
	"9DQ38CnHMX80xjI/2fEcSAPYcRBFjs7wzWo0lxZh4HHXVhKL9DmuZcKxTxy6db4+OtkDTQqnQlvIG35E",
	"aj6nSYADXtfQqHdTHtbBjlwqp+7b0r8wVLZLtuBKG8IG5GdFN4Zk0dZNMx1FjlntrTnz9dFJORjI81lu",
	"KKciVouay1VJQU1bHEj51ZiGvLJuv8GTg7qsD0+usBxsR81+nyBZlmywuOmtpgqf6M52ahc0kJZB4yHM",
	"bv8+Ufo2rzMElrTpy2AB27mSN2Xr+2WeooALZUR4WAeAQEaGkGmeSZnLl7E0ZGZ2aEFsohWX08upveaU",
	"Z4UMM+W55AsuaFamSRwUCCuZlpujvAgF/72qOUEiMdVUXVfVMUxvXlNoDHJHrEGhufK+042G+z/8QbeT",
	"ZtzDma/dJL+V07+lyh08uWLzXDLr/LCi8ho1YesKMNbx5yNRxFvoEHz514/fnZ9hwG0A5P86f/2K/Miu",
	"yHdsQ86Zbr3512yDFLUsd1ePPckWASqbLXLJ9XIVOp3Q+39+CIW2BXJbgcCqUJgE2xCooNxurjfh5laQ",
	"aHUQ4SWt8rTIoDplSL0TnsJ8GKS2ab2KrRbfFVdMCqaZOmeJZLr7xdvVazOdKJhtqOW5WiXBjgFPFYOr",
	"d1QR1WrS4ASeGghGjujqhwGkWnNwALWmScco8Ll3qPADXg0/9SDU61tje1eHFLrz4IEUji2rOKCUK81F",
	"om0Fgym5XYI5iyZLwqH8vCKo69RIyS4NMfgSbHqXE6xjz97T1TpjWDWvNAJ+uZZ5WiQ2p7lh1HPxZaH2",
	"GFV67xn4zTP55RVNrpmAd6IkLr01Meu+VaHdQUlP56plA+jgN9Sp5Tdgo7PRsVUYGEHcVkUGH1ZUJ8vv",
	"sbQDhqvpZFnZoNAmfPjqmKUz8mK11pt9UWRZY3aF3YgRP2yiusbNaIza91i9bLaHKqHlSj+qnMWKrs3G",
	"f71mmymc8Qc03IbLUbRRzoVVBaPmzBcvKavzXbOGro3QS6Z5Uh1HZVTyTbsGc/E4bqjkeaFKFzBYhpqR",
	"w0qNawRCsEqBlizH1IG/Vt5wU+IW9iGcBIKLInD1X6KcafCHewmwzd+UZHzFS1VFFccC6F0qttFTgJc1",
	"12qVQ5gEjhJSGQCEymqqfv5syLlL/1OwMpTSaet0TrhS8AFlXleZyoqzXrgfRe818GnjCskCeIAbduYG",
	"9YOCvdfurlR1XUtwHyGYsGJ5kgvFFejwYSyzLBsxaB2qmAOZ3WndwGD27SyIUOpYQjJxI+vP2a3zs8Az",
	"XVOlzNWzlxZO3Hnsoj6zXlgd3QBgn+5oG6nIeYoVDzIHKQtp64PJJRTvRDZqSgqRMaXIJi9wPZIljJeg",
	"tHYkqA0g6hxtxGKxolxwsTjRbBVhQZvhZlfKHKzQFrnsOgHw+GAaAmXAb00KNt27O2i3FchRUfZ0yOJ0",
	"KKklaJCgAtwkHGUDbV0Tz8t9uEUpUmDFfMBTBKQZxgE9Y3NNCgGXR6QkX3HtOYgoJjnN+C+ocKkt1ItI",
	"IY9tdosrltBCMcLhM3htLgsBjhR59RVAYPP8Z1TZRk+q/UhmQYcY2NwTbqT0G7nTTlxMbp6lYAiigtw8",
	"mz37K0lzzBfCtDcHYrmRFIQ5RrOJ0nrVxBuzsz8zpfkKrAF/xtvGf7F+r0memfODRWCJizKY28wrGVDK",
	"2NhoFABqIEsHHKsoHBKS13ozGs9Zm6kNGoEv4ORs4W6fetonHzRYoNsJS4fgDxGrbFA6aVTlJ4GAwCvb",
	"SDZ7YribV7mG/754bx6nyXRynDP1Ktfwd1AGxgj3yL4sb4ZtoDy7C3ocyiM1+EUDQm/Tb9tgV11MIjIw",
	"lXfN8Kj35uFiPfET7PqszdlhnvHeEv+/qXL9QzIq+jsBd7zXJ8dHxxtBVzx5LRdUWLJwqBRfAPvc3klv",
	"F0LhnwqrZZhN5l47VeUNNiORf/14QZKM8pUK1emhfHUadQsCfUHNU9i0d89PObq1dnulhfz12Md2zpl0",
	"iZUuMf+Umj29nBjycjlJCqXz1SyXi8vJk7CapxrxFV2xl1XO45BzKXwk1h8TnUgxfUW1C3zyG8BDcbFc",
	"Zi4Xe78if4wr/bfhVC8n5W9P4qX9uxC0NiWtcKEiNykiQH9Ka6vmqE4yDquQ8GgOcRvEjGCkSzeyzG8t",
	"Vlr/bK4QT5wSAp5b3DEysDXU7Utv7aASi37pvWzTyZrJN5BSKz7EKTaJDmHkkO5FnEOLyADt/Ll6q8y5",
	"AyboH6AbTENG6IbShxiydXcL4lxnF2vSwSRYayrBvONfL6j5RpMl4GWbBDYvyylUKapbzk3PPUMLWmZz",
	"8OSDHqWRHxqXed07iEs56kCS5zuKuJUFF2S9RrZe0F6c/O6CpLmbN4ykRfHHEpIIqjgy42dHE+T1momT",
	"Y2JrfFTEqCaTjrmWxqxpY9a0ir7XnQsGJk+r9dxtDjV/6LC6u9minlGtxoeMmdU+fWa19oEMkjVrr8CY",
	"aO1zTbTWokGd1x2yBVQ2ByoaYkfPS49HdBKJ1YCh7CmGrdD4EU23/WOgPS9oLxf0qsysZpk8LYtWQMuP",
	"S4ZObm0BiyviRgkFc4DBQHasERuAY7DlDB3e0STJC4P+izxfZGyW5KtexrXO2/dd67jEJBkGIr2RPGap",
	"xgbkzdkJsL6wmVbN5bYBPMnXrI9IYSM0mMDlvbuKzsJ/WqFcA3vqe41Cs/fKRJIutNtslXuhca92kP+g",
	"Nd7H50HIqNJHS5Zch3IUfk+Vxnjf1uwNG9UtVc6rHS5TqfY2P+yZIQZksO/Mg9ArygePr6tHqRukWdaj",
	"iQGPDlsxGFUaNSGuX1Tud7ioCYXocVCty1lTnDbovuROq64Zqklr7TJ4cBVL3T6i8puhxXXrt9n92jyH",
	"SrM0bAFHg5415OE5WhOshRu0Ra1HgIk17AQt798dHQSqxmABssFZXuXvFkASWzv1gq+Y0nQVCYst753l",
	"qcwVs7njZwNvmFkr1lTddi6LbykWaR0+34IJL+V9q0ItmGaT0jRa4yhp6UhOqlHc7UiZMrhn8xeR03xd",
	"ZFDj2sEba3WTM0bTvVxkm4FJN7OP9Q95id4hllG+Zhvnh4F2KlD3U+G7IdhLgy4KCdVskUvz52N4OeFX",
	"NNk9Kf0JJncOQbNyVJD1uBUs6CnkcfRUk/wWDBVYnQR+nxIuyCUwqPtmrsuJdYeK2PBrXgjBIHXrs+EX",
	"Ki4tIcpzjHikPMHOypg1eXGYi2GzhHYQBjVnPj8lS8MSO0pQu5OghuF0eTZp57HXjL0oTInoGwVKz1ro",
	"e+CxqmtGawxQ+3Ep9NLca/j6zp1QANX8duVJhuUmylfqXVlFJRCxXuZowbaTbRwIF5IK/Q5OaNgc0AF4",
	"i+0m4uk78AN6Z/gPLhbvaLZ4h/Ry2MS2H6HOm3rL+SNSnSfRhcD/79tr9a4IiVT/+vG7886Tcz5F20DX",
	"9bkDgFECGwhLFOm2GR4PL47RF+Dk1QWP+gjvzFV5t2J6macDV10XVYntu9UuDH9oCF3HRt4oJk/EPO/Y",
	"S/B18ZjiQFzAqDkd7SR/SDuJdy2CKTQ7tZ9vey5axMjRaNEwcjTdKcab+mltHM3zGGbi8MntaOL4bE0c",
	"TfLRednbJo5udV3K1Tqjm7Cm7ttiRQWRjKbg5A+iiFrmty6/pgzDir3H6xmylLyw38jJcUj/N1COPaU6",
	"WZ5ZLbsfirhFUpjepGxmkzYrme/jS1OsYLjOMFILaxlCVu+Ie284pdohek6e5kDNwIMylgSmiMiGpXci",
	"TSFAwi5q1kK+fN2VubRJOLoq6VTfnMu8JSOoCKnTEa/UDrYKbnBArfCHCV7uqsr/dndppUDLc0tVSem2",
	"Sx7vzRo6zDOWUc1vIgm4zvx6kNI2xfBKh4BDkgMfBvq6MAGnkHyVa6tIo8KmbAE8Me2dljW/YdJL3FXG",
	"Dk6UTPa5SNn72b/VMJJQy8MU2nf51SGuw5FGViQPIRZc2yxDwfM/6zj/WlZjD+bfcO3jAqQiwdRQfg6k",
	"kR8bJadRctqvLtF2/mVev916l1UDh8Wu+ve60FV+42Pt3d+AzCUbxzFI5PIo/ihwfa4CV4PqdFzyprDV",
	"cA2pMxXD4jaaRS9602f7WTH7Gp+rZdW2Z+sRz6Bmi+1qstQh8pE+QfXBPtYhaDufHBfKd5gxqc+KjIVE",
	"FG8HbQZ6aWTrvVK2bpQvgkSQZuxwFceope7Y4Z7jcfkKuWwvZwq9YdKIZIWyUlx+ZaP+bb4imNhIa+Rr",
	"OM+D7moJ/XUQumogXF6m/x0rewCBWJ1FXevFXHFHGP8r+WIBgY8BSKITBma2uWGS6/7KT/55n9tOmPK1",
	"WQ/JjegdU20fdT+KXuSqTda2DNmvLZxxIsyPVApMcnkkOWQzmEwnJ2KeD8yDGV1LNXC0iTdjtA0uxdv0",
	"d8FH9Kx8F82zAamhlGE0OIVtH56e+Js+MvgLeRnZOZpMz0qPzBdC5lm2YkJXv2GRo4mtRDWpSXbVys43",
	"IplMJxet4m01X/OwoFgL/LV6t2gA49HpmygBWxehKOLp5Jir62gNJ66uw70wwjoarx2Nv25HJ/qB0YOD",
	"FCO76XvGutbVU80qAgnzGEbDvNsHGOYLzv1soEgAsTn6eMU9aah7REJx9+Z1gsczAzbdtJqR1y6BDf66",
	"hnQzlhJw5crkbMHWNl+zkHGdrtYZFwtI8XcTKthcPj5XTN8yJtz+CXQ1636A96QsqNNRSyd21FP/KAI7",
	"7iLWQB2idMt8rSuCan5WkIvIJrjBNKQ2oW2lNMwx7zx4l1taCMIgH414o9JoVBq1iZm5ctuqjbyeu1Yc",
	"VUP3Vw3HnFe9mUexGXiGQnY95xTMFanRHcSAWdAN2Bw0199SFdDym18dY4mJkaDxwxWWD0ItnkW2F2DQ",
	"SkGxmMJQn+0B1mWY8UA5rR1hbXl92OEUiyM1/8TqQdt5I5Kt+SjgBUYF4eerIGy8MJ1sX0NJiCnvMvZY",
	"PSmZOswL2Kkd6ynSihWKW9XYuGjVfDkxLcsWWGKj6lBde025wESZIX4TK7qI3KCO683NnX5Bk6VN11sf",
	"CmNZ3AAQlOUxvd139WHrNw0pNOuicsqCs21I31ed2QCX0o1/d9DT+v0/UlNL70ZKO0M3ncLyCF7cWD7A",
	"kmEhS8PIlG4XZh2RDNFu4G86grnKwb1YrcDYQ9If3kHh/IkcY2qTBzkwwW5fh+Oq4IayWwJhV+QxLyuK",
	"XGXsiZlGFBlkkXVR7G0tsLlmeaE6JnBNPmIW+8x9zVmWdnAGkIHTBrhBtVfbryIBFW0pUd1BEkPPyug7",
	"KzHgf2YuX6X7O1A0f2D8eI0vre8riFxYpt1W+Wc2IWhX5aBlfguvF7Qt6+QbbLLl4fuStH1FdbI8t1GR",
	"MSJQb9RWOiotqWaLzXCNY2PEDmD4xbFqpNX/7MwsdtNkjb82i/Y3ryjkbMDLdFHVv+5UXBZVxda0fUyd",
	"TGn4cD/A+cgC9vVVkS5Y/yKa7aHYIVSXu1hKppZ5lvaN4fkWht24cLXn7mSDl92dOwrBOU+wehoCxiKl",
	"fZTrJ+MTtToqhK7YuVruqJDs+fm3XXVk15LfUM2+Y5tTqtR6Kali8YKw+B1VpGp5Wvb9bdSBrS2pt16r",
	"3TkAaHjJ1hDi+Lbt7RyBlX/MPebze6oNabbf8Ax0lSK7KkR21UasdhUicjHG0TKLHDXUupDCSqMG2xKa",
	"ZfbhS3PxyBVmJZhW3gvZHnUX96u7MHcnFCW4WDBIGQH+pPZwTFub5ZG76ghT8pTwuUss3uRWv3ge1BSO",
	"youdKi8iBa+GOIZUkhrC0QUsRGRnqsIeKCuaLLlg0alul5vGBOagLZd7Ofka621dTux6bDp+rqqKFGy1",
	"1hubQR8S8NdFz6qOxSE5g2WSJKMScx84t2i7WUDjq8JQHoap/PMbJiVPGYlopFU3iXPBJyXwyGsoCHJA",
	"LifnyNS4vNPlTu8dbQzbv0dFumdB2kvyQzosu3FLJkoMqJAu9CA0vRraz1S9Qd2Y6aekIE5sGV+C0SY5",
	"2iShR+PybGeWbHberWWyMXrYrz3QqO7c3mgwcoGf3oIVOpJBqtfmUzAasj5XQ1aILPXd/ZbPe+3ttyqY",
	"OAsAOrGwEAyfyO0yV9UA7r7PsYZJP0OE4w/ZbEl7h9XVtvqzcBHtrX3Xtywq3WkNsVh9qDsy3NWKZpbA",
	"vaUKTRleJOqu81e+nfbg0x3MU+UGLO7N4Hz5iv1P7kp8u9oH3+fogNxYg4HJL7lgXt0ZZZ0QYbaTw1eH",
	"LqT58OzF4f73r48OL05ev3I1Mc2PdR4Yq8iZk84lyRNGBb4hrqdL8geXZk2l5kmRUUkUNyfB9ZJbOxKV",
	"jE6xIgXGw5LDFZM8ofuv2O27/5PL6yl5URj82z+lkjt30ELQ1RVfFHmhyBd7yZJKmmhDNd1esUJlmWaI",
	"PL6cfPPy4nIyJZeTNxdHl5MnQfIEWY28WPtG7oHDQi+f2/p2Vd7bUOLkd6Gavbb/gLzJ71QkcXJ9iHja",
	"5CrPV3SMKrOXX5Ki0kNKNpdMLTGNVyTW3zYOFLbFL3CyrhnOGJbb/akCFl747AoLQvC/1yE+LuS9igIA",
	"v4bLG8twkro39sugfTUoh3ckQZKNqBerVN3APdusxXiCLB+Dox0DG+FQk5h/WbQ31nO04na477vOcKDa",
	"OP6nYHaNNZdMveMimoHMtLCGaXP5uXC+1EHFXg+m2bVJH+Hiuc0iuXhhXY179RWjMlbppYUKaC07T5Ys",
	"tdFWTdNkJTco2wowkhY6X0He4jS/FVlOoW6sIcz46Cm/nKzmK/c1X6P5AEBoDZoNxOo1mB3JXNTr3SlN",
	"pf5G0oQdezFcQy1/2nviOjl4167FKYZZI5fvreOqnRwfkTItXPSusRXlARPHC/MzoWlqIBHEadPgHRqX",
	"QgnwcADf+ERKLVfbBBW5rC86b2mYuH1dZBmxBbY7U9irMGGsVy7bKk/fGrheydJ3cdp76tqQsk3oKcmD",
	"oSWwPvy2VZLF4ipke0ABrmKnhlntPJVAHZNuYrqCb7j2RY5wyunIc+MGffsBi9oXkuuNoSkrnPQKKJKh",
	"d9VfXzt++F8/XkzM82laG3xD6lVOCVlCDFJQQy7jD009gSO40ZWPpqE7NTqLz6g5n3mW31pHwIrBqMoS",
	"2Is3OXTvGNagxp+h2Kcw3Fczk6t77tcyn3NIvNIYwH7wefJJiVDNxvizewreSLMgIxDv3zzbN/vex7ej",
	"enIu3Itj/452mf5et+rhPOIFlpsVJ6ldV2+y3VZxilr3wMyzW5Zle1BjeR+B8a6ZsNctqbYQJGix6iZv",
	"3oQTdtVSZXvOT4S8pGuAVyMFWZXsfmboFYjAZhKoxe8yFR+YpRh5oSI/a/4d20w+GIiaE3Il2SmC0CGF",
	"ZnT1v+cZXyx1orMZz6sRzS6+hi9QpFzmGblgdDWxZvmJU/3Uereynv9UH+Lt41C3J1YLhnTJ+qYkGZWY",
	"MmlFBV0wKMSQz1HtAYItSxes9KWy5bG5JLe5vDZ8i5pdmsPLeMLsG213drimyZKR57Onrc3c3t7OKHye",
	"5XKxb/uq/e9Pjl68On+x93z2dLbUqwy5Cw33ogGkw9OTybSix5ObZzRbL+kzh8p0zScHky9mT2fPrNsq",
	"XNPtcPLg18mC9V+GlKskv2FyU8uWVNrwDPJCXulQVusqGzGs7/nTpw6HbA0N6y9oGu//29pMkaPqNQgE",
	"pgNM3SKNNpAKuoCg68adh+eqBk+XY5vFAVc9N+0k244x9j6hm0CW34YBelhOaI5Y0hXTTCpQmkWkBS+J",
	"c+SK15JDT/yXGh00K9g7icHxbhHp+8N0gHYhtJJKP9G1iqGz+UWGolvHJpBWu2vOUhuHDYcuwT12obnd",
	"t+03hhrM8vhj45tWneO/bVzFL54+Dyk4LBTNE1JD1TVke5DkiibX6CLFbf2nv+zwTpdmttY1/oqmpaZr",
	"q1ublF5mwSv7DWu+9u2CZO2baZ287pG6ebOEiNp3APlnf38AyJuVgO+HgwtLtzuBf99eqyj8IR3nj+yK",
	"fMc25Jxp8vhfP353/qRONZEttwWfoodiOt7nkZjxS2E9AKjmVraDUqkIWue9Kt/Wk+JhL7AwVjkH/H0Y",
	"WBeWxbd36qs83ewMUDXl9Ye6PGho7Yd7PKS69jJwShd1xeWOCVjv9HemY66CQJz5qGmLaigimZac3XCx",
	"QEHKk7bC2OGGuc/r1NJ/BaD1prFaPK5nD7sGUTJ+SPicDgMYMV978dNbiG0YeqKugF30RH+wDYw017jl",
	"cMPDZ+d69TGNRjQLjWped7e0UlBcMpoC8+GkH5852IrveP4g7MJF9WI8LI9Skr3dImrfTrmo9vrpuILp",
	"5K8PAugT5zWE7ioElMyDyWlSJaqytX2c50r0JoJ7TzTBVT2Qtn4jTc9oR9V3R6FYmTWJlA3NBQX2v4zi",
	"LTLt+ehg1MiMVMnKrQoJRjADQJ3CFdXWNaHW6BGa1Av2CIPunO9xGesH3mfuSsc0SW6Q7USeQ+Ki8WzK",
	"HS15gp4IWZkiQBdSlLW4lK3IxyXB6L4ZOUY3BFCDsRsmN3ppk6CHFgq9zr0YwAdaLQY0Tp1ngHmaEXFy",
	"aUB8zcijLx9NyaMvzf8anu7Rn7585Mr+Xk6u2ebZl3Buz6bXbPP8T/jHc+tPENopzHi3nRpMWtH3fFWs",
	"XC1FzNYAcC43aTGljiCAhjaQCTKQK6Y7Ea3WnfB5HcshpTkO6vpb/F1RgC0UP3ReHymhyrs4kN9JFVdY",
	"GFLjLYpiBl9BJvKAXiAWr3Gvj12UioD3aFxI/HyfvjpnZmb94gFm/TqXVzxN0abyl+f/eJA3PicvqdiQ",
	"8t2Ap/Yhdntu1elvRBk5Untoo48ppPALy7JHUFaW0AEvavtBxc5dySbvQ6SNzzdIvn32UAsJATodycC9",
	"k4GnD0EGjnIxzzhaDUfC00F4BjH7+7+ah/4DkqeM6YCnB/5eJ1TEXjtSEZw6gTqGTl0Eqlcs91Pr9NNI",
	"w33iSktWBvLYlJyMdVEZbmT5NDK741f+MDTjLw8w5atck6/zQqQj0ejlVoKiv2Q0RbG6lCmSjrtdpwXf",
	"MP3AhGCBoeUfTwWmk0Lw/xTsBH3UgK/5NPLNSCtGWvHbk2yoTpaheAOdLO8o2UDfByYXsI2dsg1DZa89",
	"mPq/tzvNWgnKB7Ys3ok+jULX50UURznvN0aGiyDLBhVZG1zb0WCu7Qz7PzAprvJfPzgtfjA92CelxqMa",
	"bnwRxhdh1Pw5zd8+Xa9lbovqBB+SQ2iA6b2Z2HTx9W12HoMnox0O3eQ7e0x0Tmh9weNjMrL2IyEfCfnv",
	"m5BjcBaF7MJqXzJVYFRu2Lh8Bt/LiK4rqlhKcoHuQZXHDhXpfm7dcMpfZwFRwIyGaWjUPdmWcXSc6RMR",
	"wPoS4r6wI+0bXUrunSzU7vvk7XTyfk9eUUwwbZOv2/RL6J4OEjRYa+GWOgrxoU1Dehw88Rb0eXNWxGB0",
	"3RxdN0fXzc/EdTOAIza7CZlndGHwBFPWMCzQZFazWlG5qWeXUzPyo9kJgConIFm5IH0EC0CyVusJbr4d",
	"zA/NwRRjAHAoYfIIsamG948qGDVTjd2adTyyA5uhHkHlDFlEr77XNoRlZbaXe7UDI30dnVpHDuQTcyBD",
	"PFgbLEPMXbWsdX5/8sNDO6L6s47q7tHr9A9GGdqyxQB/0mPnT9pLNrBlSTa20hA3Bh/dQ0cV6Ojyte27",
	"H08W0n95v2F6Zzd3Z/6cD8G0j9d2vLafmF3vdsvsvbrQcGeXd/Su3CEBGSWJ0d46Ci+7opMhdxf0WBlC",
	"Jq2H5M4I5e/C93EbPcvDEcZRpzNS4pESf3ZqpP2UJflqxVWZqT1EscuiC5UBCtU9Xt+2aqn6uEMFUzXo",
	"74KM+1AYed2Rwo4S+iemdxlVWjEmOjP1YuVIpYlpCUVilKardYQwdWjmvqdKnzPIgLoDDV10XXP0Kfx9",
	"aO9KmHTwmn9pn8urHLLWl9mgRzIykpFPR0YkEymTWM6ok4y4hl5VyBatOLNtdqnND03unJ5sGtYdUo2g",
	"PxhQKqgLUS7kB1fTMewYBI3P6m0nv1Vbw0ilRnFypIsNulhVPe+kin7B1+Hc1LkrCzdaO0dr58gE/Tas",
	"nVtfZ8/2ubMLPVpAR63QSMlGSvYx9sitCVnNOrkzUjbaKEfSNZKuUcb7Dcl4TMg8y1ZM6AFV7qrG3fWf",
	"vmH6Rdm0LHQ3mHrSgemuMAwWCpgJwpUq6olVZ+RkTtYyv+EpS6d+xWkbQLdkyTXhfTlRbJydCk8C8XQQ",
	"u8gVSahiZYgfd3o6Gx/ZhMiMnAhCs4zkeskk9MVFelD2J8IwSVj5FSNstdbR4MVEyU+mWmsd/EjSR270",
	"D0Jgq5sbzELS+tyTTKC6SgOrRLU6jCkGxhQDY4qBsTrUli/3WBVqDKD/Lb6lfbH0ouPJjMXVt3rcU4h9",
	"e54HjraPLGB00h4D70fuPMidbxGOvx3lwV4hyrOVhjk+5RiwP8rsoxr2d8XZxLMFbEdbarrXeyEsvxMP",
	"m0H8zkhgRqXgpxFkOrMMbHflodM9X/rRC+d+CM8oY43s1MhO3QN97cpOsB15tb5A90xgfxe+QXdUYn0S",
	"2jrqzka6PtL1P5667g41mQLvQfsZsL3u4Rn43VVdam2hrET1qZ8Dt5B+leJIoEc1w0gu7xTW9/EKybt5",
	"1I9qyZFejPTi06klP4oMhJWU90EIRlXlqKocKeAo0n4OqsqPIrkxxeV9EN1RfTkyfyPz97kIizdmnqhI",
	"eMa05OyGKULLQATsMrsU4cAUHLAvGOUPE+9wnktNcpkyCeGLtrgfxB+YDbnkf/VYk0dmjEfksWC3hvrO",
	"uVQ6ujgYvLaoFIeCKqcqmUwnTBQrgwwU/oIf307vGquB54/nZo7IBVv0xfHsps7iZx3FdK/aCHNsY5zH",
	"GOfx6Z4ig4H152eeMdYXG/m1adMXD/k1DjTGQI4xkGMM5OdbZvnEZlyI1VN2mwa6ElsJTW2OVnWOg3y6",
	"8sVAtsZHeXyUP9mjDDdlSPHi+jMci7GEVvcUV4ljP3AspTfp6AM2xk/+sYhCi1Pf/xX++2Ffs9U6o9ow",
	"hIrnIs7CA/vhWpOyeYiHv7Ctfqga9aqt81uB3JN59VvTRJTUc49I3TEz+ihJjJLEKEmM2VQMnW3QrZGd",
	"H9n539HLPSD1QWpTH7Qe2Ei6g8aF+Oh3/P6e8able+DMY06F0bw8mpfr6oMg9y8ZTZH1Ld/9XhryDdMj",
	"AXlIAtKE9khJRkrym+JcBudm6lVSYkOnpNzKKa4+9Jh2abzY48XeBYsAiY96L+43TO/o1u4weOiPYZ4c",
	"ycZINj6tYbIzgVIv6YB2OyIeY8DR7mjHqAcdg4xGM+2OSGRXDqReCmmjh3ZEI38X8UFb+JI8GEkc3VZG",
	"EjyS4M9La9WXcwMU5FXYZ11V7ghyWBS+W2znvQrEoyw6yqJ/YFm0WXt2uGS6q7s8yqejfDoSsZGI3UFa",
	"lCgEbsmM+KLjrojYKECOPNBIPn4Hkg46dg9KHpFypblIdOmAjX3LnAgVnakowWbNYlkmvseZB5AaM4r1",
	"iS4JjLQLKxch81XMGnfNRdpJb1xuBVvWfkhehUMy55mNF2iuJRfZBiMGyohnopfUjwpY8BsmsH3p6H4v",
	"XvQ7WCU6kPetcuce8BW64XofJFnF3aRf9p6u1hn2wNW+wF/gUlsL8MHE/lj535ubk7lrAI72mO7lhstc",
	"rJjQX65lnhaJRgc6yRY8F18Wao9RpfeemQ1wJr+8osk1Eyle7GE0BC7f6OU+erl/srcI8L7+FuU8TdYy",
	"v+EpvAVdCSVenxwfndqmfXkl/LZjeokxKGwMChuDwgYRN59wjG/l+FZ+srfSfxgHFdYOPo+xfA9+43tK",
	"+1Cb4oGzP7TnHq3p4zX+DVzjGOe7VSHrgTcdOzRu+lY63uBEYwjFqHsdda93e8O7SkgPvNXfMH0vV/p3",
	"4k7S97KPt3q81Q/OmXdXMh14sa1J9l4u9+/CNLu9wPDQZGUUUUYSOpLQ+5WK5IIK/gssZ7v6BrWeM0Je",
	"i2xjtaaq/hFNnoZgFopJsqSK0CRhShGdR8wJtVXdJx3yJhrVj6Pe4sFvaGW5Bptb3kD88gJ7v9cvsGTr",
	"XHGdS8567HlnruWmz5p35o85GvNGY95ozBuNeQPIX0Vhxrd0fEs/GbdbPombIQnbA89izIpXNb0nG543",
	"wQNb8Jozj8LxmMT9D0gtIoz1NrnVBtETbF2jJ1tpHgOTjHbCUR02qsPuwiB05FsbdJm/YXrnN/l3Yh7s",
	"ZhvGqzxe5Qfm9btzoA26zjbaescXegw53zFRGcWQMSnPKPnsknZ2JkcbRDqtT8XOiefvwp9iW+XNwxLM",
	"UVk0UumRSn9W+ilrw92IpNfyi03PNyLpt/1WbUfj72j8HY2/o/F3IFNQEY7R/Duafz/hg1k9jMMMwIHX",
	"MW4CrhrfmxHYm+LBzcDNuUfefjQE/yHpRozV3s4WPIi0OGtwjbRsqTcJTDRahEexfjQj3Y1n6LQJD7rU",
	"YBW+hxv9u7EMd3MS46UeL/WDCwJ91uFBF9uaRu/hao824p2Tl1FGGe0Po1i0WyraYyceRERLS/E9kNHf",
	"ibV4Wy3PQxPPUa800uyRZn9WqiwmFccVROVbZYe2bYNy7Q92nHskUW6KDtZutKw8NFo5/HkLfdFoii91",
	"IbPJwWR/Yl5L27qJXK8dFmE1A0MJmdB2CzOvrnftw6Rt7fUGygU5YlLzuWnNzvlCcLGwcKs7Oji7f9Va",
	"YWtZPgLd82DdguCgWLW8ewSzZWxHaIIpM5oD2N97V/JCyDzLVkzorp2ystWgHZr12eoFXCwIuzEo4w9n",
	"fuhdWr1Ijd8fy2JsswRbkoAmMleKpHw+Z5KJ8OiY6Hyb0f3EH8EhaxkX+vYdS61gx/JcePpHirnqlGN5",
	"pH3AjhPGYcMBum5HdLf6w9sP/38AAAD//1D5e3q/uQIA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
