// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+y9jXLcNrIw+irYOV+V7T2jke1kt3ZVldpPkexEG9vSleSkvhP5OhCJmUHEAbkAKHmS",
	"ctV9h/uG90luoRsgQRL8GXkkxQ7PqdpYQ/w2Go3+798nUbrKUsGEVpO93ycqWrIVhX/uX6o0yTU7oXpp",
	"/o6ZiiTPNE/FZG9yyjLJlOlGqCDUtiVznjCSUb2cTaaTTKYZk5ozGC8LjnO+ZGVv04TolFAcJxVELxlR",
	"a6XZakbepJoRvaSaULEm7ANXmosFNr3hSUIuGUmvmbyRXGsmzArYB7rKEjbZm+xeU7mbpItdmmWzJF1M",
	"phO9zswXpSUXi8nHj8Uv6eWvLNKTj9PJfpadw2+hZZvWJJ3DGmmWJTyi5ivMK/LVZO9nBK5ik3f12aaT",
	"Dzum0c41lYKuDIR+drMduE64ADfuQSo0E9qshSbJ8Xyy9/Pvk/8l2XyyN/mv3fIYd+0Z7r7kCXOdPk67",
	"256yhGp+jYdtGkv2n5xLFpt1wcm9a4Cntr4X4vpHKvGoKwfPyg80jrlpS5OTSpPaUUxr0H4hrrlMxYoJ",
	"Ta6p5PQyYeSKrXeuaZIbtOFSTQkXZl0sJnFuhiEyF5qv2IyYw7pia0JFTLAHo9GSrHKlDc5cMn3DmCDP",
	"oMHzv31FoiWVNNJMqtmkse0WPHFgOJHpNY+ZPMtYNPysAnA0p1AFJC2xsWcsaPZxOjGo1XLnygmJaVVA",
	"49n/9//8v1UYkCQViylRmkpNbrheEkoSpjWTJJVE5KtLJqcAuygVmnJBREpullwzldGIzQZdtd8nqWAD",
	"AHW0ogvWBu4+LD8SCRftvd99fNd9tmea6lyFKQJ+M/SAEsXFIqnC2NKymF1zBIkjESeSZdTShDMDYvzn",
	"aS4E/uuFlKmcTCdvxZVIb8RkOjEEImGaxcPpSnUH/pyNj94iGt/KVTU+uWU2PpTrbnzyNlIF9I9pkiPm",
	"ltenCu5DNueCKUIBe2NyDT1IrlhMLtfwJlVJcvUqhS/GW8H/kzO8D5aw++Ma3OciRO+b+O3TT5js3Sfi",
	"PIKkgbAhuNVJUHXruCPV3P0rrjTgr4e2trHZI9dspQbQntoZlnedSknXvfQTuyF+dN+yrRz5m8ZZB87T",
	"HOecSSYiFuKE7CfDueAdz5J0zWJyfHC0Y2CUcCo04eYUDcU012tOI00uaXRlHqrOuUO45K+nh2Sps3y1",
	"onI9kHQliQ9E1U62vmc00cv1ZDo5ZAtJYxYHSNXG5Km62nKO1ibe5K1tApSp2qBYrgFdrpcHqZjzRRNO",
	"5pt54+Z80UQvmuvlsVxQwX/DKcpROi9MS7ePUxgxfGCwEAPZIK6afm9PX7V0e3v6qh/LiqnL0aatOwxi",
	"YDs0AmuShvtkMUn9HhbSuWy5z0wYNjDGIec0T/Rkb04Txerc49GcaJmzKVF5lqVSk3kqyVF8QjKkk/V5",
	"uSJ2bA9Ql2maMCoakHKrCAHhW6qjgMgDP5tZqCAsYcDVckEu4WfF/pObe93cb8JXXIeZuRX9wFf5yvJi",
	"hsZkTEZMaKA4c3t9lSFQeRZTzYh9xmBOM9Wwh+ikGBVerxUXZtrJ3rNi81xotmAShQPFEhbpVPbdgVf0",
	"kiVnrrHpmEcRU+p8KZlapkncN4C/ro9tB3FmIdtyIO4ziS1nYeCT2CcR4IQAvGSEfWBRbvCVi47zUq3z",
	"7VfHxRlBLhr+0CJufZyaQzjCDs/qL+3UXG+q2WLdN9ppmiRprs9c8zqWF+OE0PzA7HluKCs74wvDH56a",
	"rasAsrY2JdLTJxBpfzQX1XDTC8FiEpV9yVymKzigg/0AJc74j0wqmLEB+pMj+61yztf4G4sJQgQ5Aq7K",
	"ZVkufm4uLW59Rs6YNB2JWqZ5AtLPNZNmK1G6EPy3YjTlOAND5ZS57JpJQRMURlF0WtE1kcyMS3LhjQBN",
	"1Iy8TqW5tfN0jyy1ztTe7u6C69nVP9SMp+ZIV7nger1rRDDJL3OdSrUbs2uW7Cq+2KEyMgJZpHPJdmnG",
	"d2CxAnFuFf+XZCrNZcRU8EW54iJuwvIHLmIgYwRbWtm6AJljbU5fnJ0TNwGCFSHoHXoJTAMILuZMYsvi",
	"pJmIs5QLDX9ECTdUU+WXK66VwxcD5xk5oEKkIMoirYtn5EiQA7piyQFV7M5BaaCndgzIwsBcMU1jqmnf",
	"nTwGGL1mmsJNtrx8V4/W22WF44kquOrbDYPdG8xCed8sqnibtCvfiG4YQWQD2gFyC+ChI6utTUdicffE",
	"oni+wtJl59kMevra35uPzRdwJF0PQLrMWSPh2oxU4PFvRCucjqN6vj9JmmXMiNppLmJCSa6Y3IkkAzHj",
	"4Ox0SlZpzBLD+wtylV8yKZhmivAUgEkzPvP4DTW7fjbrXEJAPPmQcRRdzliUiliFNAfQHzXWBc24pgmP",
	"uV4D9wMYU05sppmnckU18tpfPZ80We/phH3Qknbp24t71jji+v2pKeLNwIRqRC6mnObEgBdNMw7GwJwZ",
	"OGdplqN0d7mGX/dPjoiCG2NgD+3Nzg1d46tVro08FVC7IyIFucpzkGQU+/vXO0xEqZHoTl68Lv/9w8HZ",
	"fz17apYzI68dJ79kxLxMs4LX5CwBjp76+NDFsCJVqBzJ5Vqz0MUBFla+CWqgjkSMSAZrkgVOYB8k+ECq",
	"/pPThM85i0FBGbygOQ8Qu7dHh/dwTt4iFF2E9Itv4XeAutkGUF8Gb8IVWxPs5e3fiqhcqbzK/Vceil4E",
	"NlvuV/3dA2BqpNBhcwU5NiN9LTrSEqFolsn0mia7MROcJrtzypNcMqIKhV+xS898o1rgTvi8tLyqJsXz",
	"mobvqB2yKc9NS8CR1MjgBcwH3S5DXlF8DnCNxTdUbJqTTf2bNiM/iPRGkMhrKBnZB9CxeEoOmeDmvwZC",
	"Lym3aqFhnIobM6gF97HB20IQB4qB2jdYHl/MNOWJggckFYxQc+W0O+4olxI4EG3O1PGuBqlPPZJW0z1R",
	"pc8lFQpmOudtVkXTjmi+YjhTsTRd9GUx8kVmXRYNdUqoSPWSycppGwZox4wV5kSUoRfNVXyfr6ggktEY",
	"sMm2IxzvhOHrHHToZZpru+JieUGCll7CdY+/Y4LhOx3e/cyxMrNF0RKJShUaN1QB5TNvVkzyDKf13/W/",
	"fx181yWjKiiokMeXkrP5E4ItStbBzflIDdrpQAHRjeoEQjfSwG5ona7dAI3qZruCaQjlCgCU5995WfqN",
	"SBUYTQEp0zk5B23xS9AlE2sc8G0f5vtkOoEGG1s7aquzY9V+dUPXfvYNFVVoNvHROqeUWMd9ScLbjaN0",
	"k+nk/OT1j0wCj4H2EvcBaSDs2RDAZlPQ1/LLhNX/cDTlhEoFTc/WIoJ//Gj4XNMCdY9H4kSmC8mUOfy3",
	"RvyxNvGMRa7p6zzRPEvY8Y1gUsG6rnnEDpmRfLgycoXpNOwgXgiZJsmKCW3fU2+/jW/V7bY+yd4QrW0K",
	"WLa2KIDc2qK6nFOWpYrrVK6DoDcQb/3QOB//Y3FWLxPGtDsF+CN0anga3tnhD/4J4i9DzxHRfM4XdYv2",
	"MHPFd1wHuvc5ifxQcP9nLJJM38LD5Bazfq91FuoGMMhydyqvU2EOuulcVH2vV9is33et1G2kxHbqZ139",
	"0YNuDd2eZs2d4C5lKl58yAwuhRkdmQrCigYE30t46szYcZ6A1oavmJpdCLNJ24Ir8stfif3/X/bIDnnN",
	"hZFe98gvf/2FrKxE+HTnb/+ckR3yfZrLxqfnX5lPh3RtgPY6FXpZbfFs56tnpkXw07PnXuefGLuqj/73",
	"2YU4Q+Mki4k5SKpTs4gd03CvEFoN942aqsdstphNYRguyNIsuRiPXTO5ht+emHl/2fllj5xSsSh7Pd35",
	"xy8AuGfPyf5rc/b/IPuvsfX0lz0CujrX+Nn02XPbWmnggp8910uyAhhin91f9siZZlm5rF3XBxdT73GG",
	"DlLVvfyjBIl5l//hdbkQL9CT00COPN35x/TZ33eef2WPNMjKHORKpyskLEdinnapQ+rcFGiLUOUbkwgG",
	"IvaC2QMITlkXd71BuEBkBEERGM+qW0WDicGFNxeHv1fNZdlyrXhEE2+8Uck9WsRGi9huyYAMl25sn1vY",
	"ut613uOG52PTLS+so6qJs75nYrcLIshK8Tr8+js/kbnTGRg0u1nyaAm6D+hJBnk6mmnAMThAR98Us7g2",
	"xEnShYAaHt0TeYedWdhH9+O03dmxlAFtk8KPEC5ZbV23832si8ctup/Cpc+clwfQYvOD8Krq0hZ61RQ2",
	"cPizBO+6msNnwOOviqbcPqWdaOq/dqhucZQPlBC+g+lWFBLd/o5NZ5YeqCIf3gbIA09/VmoREF6t3oGS",
	"iZhJFrc+w6e2gXt4W8ft0ypX5+ncpEqTVg7DfvYZDassgZ+jVAgWWb1CcdghJyhg1o8Ow4TIfiZHh77K",
	"qjZDGDGw52vv6ajhe8HrFbM4Qu1Im1m3NT98U4kkiaiA11Khthics2jCf0O1ZhH3w+SKC5pMizWje5jp",
	"NiVMR23HReNjkawne+CVWEXN2q6mHgDbj9KXm5uAcINZvpM6lIqr0nahD2+coaZywfSwZ9Nfyjn0Cyv7",
	"cMhhW/LGaZLxwpiEl0WZGRpbWzG9TOPqlfJVYG8FA4UPKLgincr1KVOV9XUpkrpW7I3c1aw6awGFI/MO",
	"Sq7XB0sWXbURpPa29dtbJVnc9SCR6UIyJs2NQJv4Ld+AneAbUEo89TlxRZ9A+ts3fzva3zpSjxZ5A2CW",
	"WOcCY94K5aR/X8daqPg2wcPQBsqZutr4a2hvV6yuvUm57iZYW3XyljlpQ9HG3c1qEjzMEhupQ69vjzTg",
	"wLQpi1OiN7A35aJ7mBvTuoBV833kK8MJrjK399rg19Cz5FGHGc5udatsYBgekWOtdbb6FDjf+mI2FzP4",
	"arY+AJ4yvcDv8PW81VWsXYuWLbXdrJ473Ly+5bV7RZU+Y0y0PRrue/2hAFRT5oP2sZC23r+kdaKmWdjy",
	"H2gFZcK5VRjJkNf8aTpQuYY/xQLaMegVn7NoHSXs+zS9cojjMOBbNk+lb7vYn2smvb+xwSm7TFO/RfnD",
	"JphRWUpj6kCb+mpah/EX2DaOt+YmcG4l9iSu9xYExrp6tBx8W9xCba+3YxRCg7QRIj9TQAhiTY4ADZCW",
	"GlStYtVfNiRJtVXXiUrtc2UVge+hpfU0q5KnoKN3+a3q1Y2/q1G9/eA+3N5JDNKMWWPG6J79R3PPnk6s",
	"UnDYCTqua3t+3SF/gEOmIY/HITpqNVXlqFLsN25jO9Asxdw0WnFBdSpJlsssVYjAjvZ2raRJYg20qY6W",
	"XCzAHaLjsszNd9DcK3QGg441RnSoP2sN7h4kGgsaCu5TptLkugPcVKHHJjQPQxz36BoSqkhqGpPHIk8S",
	"wudEpPjLE7NZ86N59p0GLGBIvacDdnsPHnAm2TVPc/V6k4O2Z+z6Jmtr045veeBgD0iTvN3T6/v0xilO",
	"5wmPNDDW0m7MBwAa3WE3k+nkTer+Bfs6ZC0ZRTpRrra2dpQ7VuFADf8rwU+X9olGHSE5PitUw636qFXQ",
	"FfS8MgimX0ADmhwWBY/jdm7qNszy8dngLfxYNQa4bYTfbPPlkC9aQyRi+FYfC90viFrS53/7+x59OpvN",
	"ngwFTXXSDkDBZVvy7GBJxeJhKHt9DcErL9hNB5UT7MbSNaR3BXWTbJVes3gYcXOkoWMi1yQ8m0gFGzJV",
	"+8VtP6nC+28jxC6YyT41XZTlwziN6jqcyinm6upT+q/YKh3K64RGqDvtZ/mkGNSubihou3FcVXzzENhV",
	"pC5zo/xEpRW+DiTXPKLJrTOxhBbqJ3ppfi0nD331FhT67BYZ+ua7Ohff8xXzUguEvblsChAq1tYzsqol",
	"8jNNvKsnuoMYMO/zu2k4Ys+IdxKWU6TWQF/+VBCYgrjUF0bU202ljS5zv87IviYJo4YaC1Y2djnYXGKS",
	"SgrD32ur35uwMi3eN5lM4xzMpVPNmfxmLiHzX4wUx7+D1U2G/ATccnCXWhqmws+G4aUTsVBAFR63+1Qz",
	"8la5GDvz4FpHTKpI6VxbA4lyboAXheAwM3j5DU72bGp1P9mSKvaXb06YiLlYXEyetGjWK5Da7h5h8GF7",
	"rCKDt8crtn6GNudn0yu2fv4X/ON5eEMfu4gKXAqVpUKx3ltRx2bshqIwbBMDZArp3kM+hEJsBcHJ3lcf",
	"mz4O1Rbt/kAFcA2rfMMkIzbjyzxPkrUFeBxyCGq4O1SmbCe+XdxnjfekHW6UpZvJsPRp9iLLWyVQq/mP",
	"NwSDqCWlklsIfr/FGoLu66HpVZqEDvrcu0c00vy69Oqw7gybqo6cs0owQLmqg9zYTQEivAauw4oxVioD",
	"lidAXczSKg+4dZivZrQaDoOay3wICpgjN27xssGPzsKias7+tdABIxWeUK2ZFKordxGqMTLbsrKZBrVF",
	"d2+3jlxwVIhMMZ1oKuG/aa6Jyudz/mFKMPHPkiXJjtLrhJFFkl66yWD9MDtdUC6UdjGNyZokKY0ZTgFr",
	"WtEPr5hY6OVk7/nf/j6d2CEme5P/++enO/+kO7/t7/zP3sXFzvvZBfzfzxcX7/5ycbFzcfHXi4t/vfvv",
	"x/97WLsn/3p8cTH7GRuGPv+v0EPVnxoRVY0nacKjgZzrW68Homv7+9HtU9L0IgkbapSXldEST2L7riiY",
	"wXmC7p6RzmlShp5+Kq21ErVPcksb0Qb0pemfG7hjtOlluPHoNS/N4cHLxRkAHNGP1nlsGjgGI3tpSOF0",
	"y4Bl/70ZRLBLF0rwqbDW6lt5Hjhnie1YmMnjN8fnL/bQClCEdXBFRKqJZDqXohLs/2SgSdqIVIt051eV",
	"ih2+EKm0grlZvDOI3cpAueELVfSpvFGbSrwbGwcamI3k3sXeDBigbF/QvXgTkhe3+JZ4V6yyquqVnoRv",
	"uA9GH4+L+wBnU663hJp/7B2c6a3dtj1MX1IZ31DJwLKI8WOGk8e9koqtb/vu3HYNLpp/Gw7dAdDczkq/",
	"UfbbsG/QMYR0hhPd+t4WJ6mRZOLj+bziPLR/Q7mGyF3r0Yxh3aCqP6G52tCAX9mQt7TGN2+1ga9V1Uvl",
	"U9ODpPK5ss3A97pLQeVjCBiBZnX4lMdZISnDwvmOM+cGjrfBy17EPmSpKmk9XTChZxfiBY2WkJMmSqUE",
	"GTnGLBUlA4/Xwlr1I5rRS55wvZ5diP7AQNxE5VZFaZJg7YLCKt3KGJlFtro7mLdwfwF1ErBJOEOwZ2hu",
	"GcNrYXgPjEy1cGqELZYjG9QJOft/m6aaHB1uMhTGXQ55Phqhnua9dEQQoR3e5XFBKc8cpRy4vLr92wdo",
	"AYXmKqbV42unWw0evsfzPYOWYBBZUUEXpR7H+ipAfYwoyWPz5WbJhPvdObNcMhKnN8LKT+YdsflyAs62",
	"tt0Zhl33MjW4maJ18bjftv/HHrDFtzLL4Zq26sDmP4828fIWn8fKZm/3PDaH2MCFrQRY4b+WnaeHFJI0",
	"Hef6eG7/7fkt3sYeUVmkN0Xgqz9rsHPNgbL6tWFy8MW8HrbMqTRdaBGY7AphAi7cnKEfQVkgBCzvnbJv",
	"icltj92AtEFFevTfG2/RPrmUjF6ZG925k8s1ufDXdTFpOmOWyKXqPO0fYPF2Td0L16mmSYtZznzyImdD",
	"Mw1M42Sp3x8JOlZ66YJOPYQLQDUNIGv9/GsbDlIjrq56U5xsnFVk+gdLixJ8wK3aCl5uHADebq6uMCXi",
	"JoXUYi7B0LQuKqk5zbP1lPDG7N5LR8mvQ65kDrN+m8c2MLCmPKy1qKbUZ9cssbVG0hsWm2XZ1kgmJWYW",
	"IhzwNLPphZpgWMg0z75dtysH0fh2xdbAvNuALALdoG6c8yoq57+E5Va0ZZ6++PHP+zv/Q3d+e7rzz3c/",
	"7xT/fr87e/fXJ//yPg7Q9IJi+q2g15RbF45gXQcssOBRHXdGpOhZXGpX9QzBB7rvjvoM8HW/Z/paWYk5",
	"yUVz3uIcN5o/yMPlfnY9S9gmTw0FaV9ckTrXraNILYDhyTolkS0zhZXgig4l4+tSkoLnIiWQTYtf28gh",
	"Zm6PHftyTSiqGXPB9YyUSXuKHyF95B75RWH+G4XJf6fklxX+gCltzA9L/AGS9wB6e6j2r72fn+38893F",
	"RfzXJ/+6uIh/VqtlGK9eiCg1TP2Q+Fhm2yKdg/BmIAxU05rju8/VZQnlRqzFFLuDs6vhVCe2s/v7WzvI",
	"Rz/JWlkcpl7ixbXYsbrbPs64HPPMdmgWbGmMGXqRGhngmrBtNOkoYmETsRpsxAV0mj7GcIYxW8+fMFtP",
	"40Jtlrin2X279SpaEkaGBIbWpmWS3rDGoCAUnvWOlCSrPUkDdZknO9JB3yyZXjLpZz8mS6rIJWOCuAFC",
	"Na+sQ9WnlHDdd7m+cSRQp2ZZsi6L5rWkQmscnt3nRifkyVqDxIn2o27y8T2T9p24Zzv/1LPfb3H8Bt6E",
	"apvhyT/9G6oqBz8shtz1+LYtvVQ1S5VpO0B88kad+lsKSCHTDY/gFg4MAcAXBzQL4lo4mDHYrBrX2Ggy",
	"sgQPHuEYPJNBLhRNxnEMe/xSq9KEGZZ+GgAepxxdTYuGSH0abR8pF8QEbj2BmArVEkUSqoHil3NQmFLa",
	"f1cCj3jVS2x44sTpBLTpp32Jz87hOepMfgYoa3M7zX5VqSCPU2vU7XD/3iq34pL4OxeiG24r5VoGhqvC",
	"6WjJBDF3yHtAuAqxVy0cjjnPYcjWYuVqabjZKzjoUSrZ31sxU54TXF/pEB+Xm/VDZhtXBWnWwGCfQPO3",
	"Vuejqb7oOF3bpIvBXKY3VgFmSDDcelvA/2XCF0tNDgxJThMfWb08LM0Kx4YsR4WSbiNNzH6uoWCpp4DJ",
	"+Y57hcLH/vb0lTudt0flLQQjOskVujJn0r1i/9cpMSgC3EfCxRVmoIb53NvZ4XBwWxVTm6apBq9yglYY",
	"DEIJgGM/Wrhi1WVFH/vGV5dVQRqst3oL1MChd7wruRPOyngADb26BodU03KZ/jUHrSSQfuqWbsYnc55A",
	"tA05f3UWvvi4mCu27lzED2y90eRXbN03d/2yt0ClucRBBz+cJAygDC69prkW6S0P3duXQapUct0K8rLt",
	"vmvaDn2fSylGJpWCfG0XOBRSi5yweYWBeMSxZKrw/ujdOHnsmNplqrSRbfeyVOoBQdIdACoWGzx5w/0G",
	"jvkahVFPx2z9CNg1OoZTTdIIvMCL8mno9BYg5uHIuLr4DnXRwIyBsEASLPliAfwayBFmcjStoLwCvBFE",
	"MbI5/4BWE8ZB82SG2yOPwewBDjTmB/XEm8F+pblOV1B0zQWthDm9UTDetmAcl7H5na+gGdHF8YOD/zUk",
	"nECt7zDd8CmbMwkl0keReNsicUt5tH28d2Wa1poAWs8Sa+CY2VJmW7QGtBcyU8tU6ilZ0WjJBSvXaY8f",
	"6E81T0it5BmSI8986VxDDrCwo1fi6MCWbiwSL7oPbwtf/uovjYYua0rtF3/MZsBhy8+1Hgcnbxvh8wcn",
	"b+sB9wcnb9+Yp71s9BryETT64s/17vhrbYRDrq4a/c2P9d7mt1pfL9ap6mPufWi4pnvf6ukGDrmyrIqf",
	"GjPgpF7zGa//XGT68T7URj2AiHnd8DC0vzd9C4sOQa/C4jw3KjTmZOMaNrTkperO6NRRgcv8ciSu7W9H",
	"9pE6p+qqmNj/8YTJFRUQYendgZaqY+7nI0GrHyy1j8sm5UVrVhgrl+cXHCtvsf/rmaay+Wux1MoA1hmk",
	"/vu3VEfLQ64yTNdU+2qhxhIH90ZXf1y/htqBueDaO7FBZdkasCs/BSu1mR+5WDQIVKWKW/3HojV6p58y",
	"pVPZkhkHew7iCs6wqVcVst3RzmMgj7H4ItKTKbG0xqfkBalxdOhdv02pW7NbZVoC9SWnRV1K3NTUMs6t",
	"bLuX2ijAve9YT6PIVSGdmocth3c+LnOIWH5+nYHUVclwhCHaWWZD3TupQ6eetjvnXg9h2WDkenq5tpxQ",
	"PWGNLRmkOi9iy4jtPTpG9SjD0GHLLuFxN1pozxpr9GnAgNUe4VEtgRgwGrYMj+KI84BhbNNynMDL1Fp5",
	"sd4yPErzKRswYKNTOXbXs9bqrNzaxR+38oZ0Y0qwcXOs3nVVmnnSnYuSxgr2fiqxj9OBxThbBx8U1dxy",
	"/Yf17iZ1txmjTtT6y4K2IecmPVuxcGjNzSB69Hfuxda+ITqu+CZdN9t0J/XcpHMLMd94iE9aRJhcf3y3",
	"UY4/4EFa/FTcp5pvyjVoTkaHlAd3SCkOYpgXCqiQR8+TL9bzxBO0ggJWsQpUmcE1g2xvRqJsKstqlh3X",
	"ud9AsOE8PQaTYt7Qnl/yxKlc2vYMH9GBYc5D1Siirv4Q6EA0+6DJ47fnL3f+AYYJDHsobVPlJBBDZ6cJ",
	"uR+Ydi7uod+q7IVxBKNjzPbby92Zr0WBu5ZgqZbc3TxhjxTGRU29UBhrsoGIGJc2WeQrJnlEjg5n5BAj",
	"dIDwXkxkmuqLSfiWpDHrnDpj0upAiWk7I/8nzYF44GIwFH9lrvqcrnjCqSRppGnifBkSRiGq5TcmU5di",
	"8enfv/4ajo+im1XEV7YDFsEL9fn6+dMnhnrpnMe7iumF+Y/m0dWaXNrAHlJU2ZmRozlkDCogNsVI/Opm",
	"4AqYfSoSewAzywsXPM1Va5J1hBbkBL6Dg2rDuWOn//fL5USFGs7mPvYy4AwLEKoM7Wn1/J9Pi7ErPzsx",
	"5p1d4Wahoj4Z6eXA/DvX13j/EpKhsxMKji6/NwMqC6rQEloJDF/gbttgct/wy/wspSN/NsYQjTFEpcy0",
	"WdwQdtlurBCMGZa0ik9VSQurS4w3+cElrfIgBklaSLNHSetLlbT61TiNsOVLKKwS5OHgE7Ch1UQxZdD8",
	"/RTD6bCahKx/c6spD0qDRXYAbFXPMgJbHpgZxaYBP2EyMlSqraqLbWZ4bdvOiWO3mGyeJ30bK1t+yuY0",
	"W2WGZnaGQviy9Xm1g/N/5sqikaHo1rUZXPjTIP5ovmLxca77NgntYKBP2eOtE+gMn6WrIFEdxlN7GUOo",
	"NS1y2HiYUOC6B7hBZKGpIP4i6IJn9wwRhgfB6dsgQN8Z9lP1O4d3NwneIqQruGUg7hKkQDqQTwR4H6DD",
	"hoz7h3bNYh589UxzNHn2ARtBWgSo2Fgwg9UMEvEyl94zCN/tnW7H1FDJRMRs0wMuobD5YVctdvd/yNbC",
	"f6/3yXJBd3+TapbU+4euc+wIgVe6JpJqtggkCrBjGDEIWhTuTqW3F6Q2/vbOX5/qk/PJ70195wOOMRjG",
	"2WyzWQRng4OoWUIwBPLbPp7EMmxlhQ0kK1gYugawzuxepWYmvNWOoGjYSm8gtN3qsFIZp5XGEDxUVovq",
	"lDArpaU8JGy5ZPZrrYhlM29kLVPhnSnIvHpIjXSxYW1WPfGj228rYndi9K1ReXBJEWg9JQwsJDRJ1oSX",
	"0oZ3NZb0moEFB2LQ8I2ExHKCLlglAowLQsnNss2iuFmYcXHin16RI25kqd2khnNBqgapuKrUasO45u+Y",
	"YJJHpyxLC2NNV52yLBCs3+elhEM7p7Rctoihj7MU3KrXULVTsyeQ9BvdmoaVhTVD2zbBvXIdKKDVeJ0X",
	"XJ+a7YTzIViXK4zN/I7raukogsGDm6QGdQlBXaVgvnAUqPTqCnKmJXT6n9dyqEJ1GeZ2gY6fsmvelRMC",
	"v5pF565GXe96G/XhisU3Zp22JTmdTsQgnr9WX61/NQKZaHvyoYm/T9Or/cgZW0t7Zi0j+byzVBAWGbel",
	"JFdMBzJiXjLCPrAo15iQYhAlMmvrpEaar1japmf6Q6frJI/Uo2q2zkerR9VsnVTE5NHy0adn7PwYygw8",
	"zIW2xI7TXEw+vgObcfXHQArN6x+p/JRcKC/KKqPkmkoO4XhXbL2DlouMcgnFBX5FMdOlgc2FgXEwy7bM",
	"RavT0soAuoqhfuUCKtaEykW+As4hVyDhaipiKmOsF0fUWmj6wSAPL4qM4rkrsrJevG4mRTKegWy8gNR4",
	"U4NRHK73GgtTukWQ3IjOhJJLqpZkJ0I/oA9h1dxNKq8OeYsbh/mIKZ5dsmbcLqRjxQzIuRDODmQXOoDU",
	"5aKVpJTXdm8TXCu6nVC9PM56HSAqfV58MAweFljsXZfXuGnkFIQVnz3ixgz+QUmFlGiZM3N0BRsSpnk2",
	"BzSLg6cW2nLjPqUtXlRFlOxj9YSY+cHlh2rwIGOJrdGPr7DZgqKaK+vaBL8WSx9ueaw45wQIcjs3QK2r",
	"SsEWoL8cARVAgZYFqIFTjtD1/hPBHMozPjVQDeKI1lmZG3iDyrYHFW7JLPL78/MTLL5hKEGAjaezSAbe",
	"LsxXTJz3n0xTTQ72g/iTUaVuUhm3MWD4ldj0BqjtD6yrsH8U44XC8a54hsbfH5ksssgHUl9c8cwyupZp",
	"JNdeh3CyT52oQcA4f3WGKVmcz+GgpZvRr9h6+OhXbD188PSqrUQgfNoO9HPFZDuP6L72zjXAAa+8Ad3S",
	"xFLrbKA4IXAlwwQKQxVOgmTE/OpECJRDHykkIrbOlk69hKPOa7ZeXhGWopjBy5K/u5FcayY+WRyRTXHE",
	"SRPUVu5ei4h0CCpYjja0eVl4AL89fYWkMkpXhuTPtU2xe0kVfJ2RI00iKiwbw8h/cgYlGiRdMQ0uN3m0",
	"JFTtkYvJrqGIuzrdda4b/4LW30DrNr/NVpGnOL77l3IcRrbR9VvqApaVJ6GTGylbeqHIW9EhANbCuack",
	"okli3s0oSQVKqUFMglh2rJLSglNmPMQ3ZAVTkWBBL9fVsL/o92Dl+PKooRi9VGQFuYwMgjvMRAYY5CR4",
	"u+yqHb95uXYHbD2miDkLw1TDSpiyfDTk9FmyJENapjHZj91RUZpS66xwOdpIjzL1zzWEMUcrumBttdEH",
	"u/56A/yYJvmK1WqcNwTtVdAF5dSnp466US6YJNCj5Ir8UvA0uhpUegUnDWY9DoPlJE+SUuldFs44mr9J",
	"9QlqWRslNFxVxKp7+CO/z6MZ+cmII4pp+Laf3NC1eoRu7rhRrkiWgyHAkPA1iNW1Xm/Ml0onYClpIhmN",
	"14R9ALc70VJ8E+ecTOubgVEHepob+BTjmD9qY5mf7HgOpAHs2GtFjs7wzXI0lxZh4HFXVtIW6XNYyYRj",
	"nzh06zw+ONoBTQqnQlvIG35Eaj6nUYADzipo1LspD+tgRy6VU/dt6V8YKtslW3ClDWED8rOia0OyaOOm",
	"mY4ixaz21px5fHBUDAbyfJIayqmI1aKmclVQUNMWB1J+NaYhr6zbb/DkoC7r/ZMrLAfbUbPfJ0iWJRss",
	"bnqrKcMnurOd2gUNpGXQeAiz279PlL7N6wyBJU36MljAdq7kddn6bpmnVsCFMiLcrwNAICNDyDTPpEzl",
	"67Y0ZGZ2aEFsohWX08upveaUJ7kMM+Wp5AsuaFKkSRwUCCuZluuDNA8F/72pOEEiMdVUXZXVMUxvXlFo",
	"DHJHrEChvvK+020N97//g24mzbiDM8/cJH+U07+hyh08uWTzVDLr/LCi8go1YVkJGOv484ko4i10CL78",
	"+6cfzk4x4DYA8n+fHb8hP7FL8gNbkzOmG2/+FVsjRS3K3VVjT5JFgMomi1RyvVyFTif0/p/tQ6FtgdxW",
	"ILAqFCbB1gQqKDeb63W4uRUkGh1EeEmrNM4TqE4ZUu+EpzAfBqltGq9io8UP+SWTgmmmzlgkme5+8bb1",
	"2kwnCmYbankuV0mwY8BTxeDqLVVElZo0OIGnBoKRW3T1wwBSrjk4gMpo1DEKfO4dKvyAl8NPPQj1+tbY",
	"3uUhhe48eCCFY8tKDijmSnMRaVvBYEpulmDOotGScCg/rwjqOjVSsgtDDL4Bm97FBOvYsw90lSUMq+YV",
	"RsBvMpnGeWRzmhtGPRXf5GqHUaV3noHfPJPfXNLoigl4Jwri0lsTs+pbFdodlPR0rlo2gA5+Q51aeg02",
	"OhsdW4aBEcRtlSfwYUV1tHyFpR0wXE1Hy9IGhTbh/TeHLJ6RF6tMr3dFniS12RV2I0b8sInqajejNmrf",
	"Y/W63h6qhBYr/aRyFiuamY3/fsXWUzjjj2i4DZejaKKcC6sKRs2ZL15SVue7Zg1da6GXTPOoPI7SqOSb",
	"dg3m4nFcU8nTXBUuYLAMNSP7pRrXCIRglQItWYqpA38vveGmxC3sYzgJBBd54Oq/RjnT4A/3EmCbvylJ",
	"+IoXqooyjgXQu1Bso6cAL2quVSqHMAkcJaQyAAgV1VT9/NmQc5f+J2dFKKXT1umUcKXgA8q8rjKVFWe9",
	"cD+K3mvg08YVkgXwADfszDXqBwX7oN1dKeu6FuA+QDBhxfIoFYor0OHDWGZZNmLQOlQxBzK706qBwezb",
	"WRCh1LGEZOJG1p+zG+dngWeaUaXM1bOXFk7ceeyiPrNaWB3dAGCf7mhrqch5jBUPEgcpC2nrg8klFO9E",
	"NmpKcpEwpcg6zXE9kkWMF6C0diSoDSCqHG2LxWJFueBicaTZqoUFrYebXSpzsEJb5LLrBMDjg2kIlAG/",
	"NSnYdO/uoN1WIEdF0dMhi9OhxJagQYIKcJNwlA20dXU8L/bhFqVIjhXzAU8RkGYYB/SEzTXJBVweEZN0",
	"xbXnIKKY5DThv6HCpbJQLyKFPLbZLS5ZRHPFCIfP4LW5zAU4UqTlVwCBzfOfUGUbPSn3I5kFHWJgfU+4",
	"kcJv5FY7cTG5aRKDIYgKcv1s9uxvJE4xXwjT3hyI5UZSEOYYzSYK61Udb8zO/sqU5iuwBvwVbxv/zfq9",
	"Rmlizg8WgSUuimBuM69kQCnbxkajAFADWTjgWEXhkJC8xptRe86aTG3QCHwOJ2cLd/vU0z75oMEC3U5Y",
	"OgR/iLbKBoWTRll+EggIvLK1ZLNHhrt5k2r474sP5nGaTCeHKVNvUg1/B2VgjHBv2ZflzbANlGd3QY9D",
	"eaQav2hA6G36XRPsqotJRAam9K4ZHvVeP1ysJ36EXZ81OTvMM95b4v8PVa5/SEZFfyfgjuc55DeWXH4z",
	"N7nKJtEkIZl545ShLEFWCSm/pfhQd9291VhGA9uixjOQR0KIFPM+fAonWTYGUmGt+F6JmAYZiGyS/XO+",
	"YkrTVdZRo9SMZbMc3Bh+AbMCDS9MGtvk+5vOZcl8jNn8h8+3YILJFs+bfYJveFS8oZUcD7SwOJBylLLu",
	"HdS6s4Eu5CTN8gSKoTh4Y1EXcspovGM44IHR2Z9cF+81ihE2dcUVWzuGHQkaeEFQ4fOrqVxQYZ4o086w",
	"xItUmj8fqyjN8Fek7U8KxnNya18Fm8ok+DDcCBYUKb0cG1ST9AYcqDGNHfxuRBQjHHMR75q5LiZWbm5h",
	"9irsatCb0TL3fkUL5E+LOv3IQT9SXm6VsjBimbJlmC6qXmslCIOK1sf33a892WNOk+3lNBmG08XZxJ3H",
	"XuEKML0JjB9SIB1nTBwdVnwkA48VNCK2TEZVmguWBjT3Gr6+b6/pt++3K04yXMSN8pV6X6TbC7g2Fs78",
	"2HayiaZpIanQ7+GEhs0BHYDh2GwiHr8HgfG9rbb6niaL90gvh03sqrRSp3bfcH6l8hDhOz46PCD2YwD8",
	"v95cqfe55AGbwk8/nHWenBM+N4Gu63MLAMM7MhSW0Haj4fHwOqpUgjagCx7VEd6bq/J+xfQyjQeuulaw",
	"0fbdaBeGPzSErmMjbxWTR2Keduwl+Lrg+14QkTF52ZiGcExDuOtfi2CsdWc+snc9Fy1s/Km3qOYX9L+O",
	"aQYfPs1g4zwG6V0q5HZMOvilJh1skI/Oyw6ZM0r7m7ls3tfmXY+5yhK6Dmc2+h7qshZ1F0EUUcv0xgVi",
	"yzCs2Ae8nkcB9Hthv5Gjw0JSry1wAKdxQnW0tFXyKj4rG0QP9EbvQT1xDF/zlcE0xlTXWYImfUx6Delf",
	"WvTA4di7fQIuOScpUDOIvmuLFshbZEO8ukZOj8GSZhc1ayBfmnWFuNcJR1fKxfKbs61YMoKKkCod8XIy",
	"YqvgBgcUlbkfL7eu8k3vthd/BFqeG6oKSrdZliFv1tBhnrKEan7dEql16icOl7Yp+uE4BBySRWI/0NfZ",
	"k5xC8k2qrSKNCuvbD3hi2jsta3rNpBfhVTiZTJSMdrmI2YfZr2oYSagE7IT2XXx1iOvXHZSVRBIOIRZc",
	"23CU4Pmfdpx/Jf2FB/PvuPZxAXzWMYbID5YZ+bFRcholp93yEm2Wxd3rt91U7uXAYbGr+r0qdBXf+Fik",
	"4Q8gc8nacQwSuTyKPwpcX6rAVaM6HZe8LmzV/NyqTMWwXCv17Gi9eVb88Om+xmdqWbbt2XpL3r56i82S",
	"91Uh8onJ86qDfWoGvc2S2Dmfj/2ESX2aJywkong7aDLQSyNb7xSydS3PJUQMm7HD6b5bLXWHDvccj8tX",
	"yGV7zvX0mkkjkuXKSnHppXUPtYEtMLGR1shLOM+97rRa/QmzupJlXVzE/92WH2s6yXqy/1ez/uOO0FFM",
	"8sXCEMoQJNEJA0Mgrpnkuj9FqH/eZ7ZTUZ+tkjjTjegdU2UfVT+KXuSqTNa0DNmvDZxxIowrjz6dHEgO",
	"bq9QA3meDgyYbl1LOXBrE2/G1ja4FG/TPwQf0dPiXTTPBsQQKcNocArb3j858jd9YPAXAnjZGZpMna5o",
	"OnkhZJokKyZ0+Rtmw3SlqicVya5afXkynZy3pmb2JcOKS5hVtLVWbj84edtKsbI85F82nRxyddWa3ZOr",
	"q3Av9L1r9eRr9cxr1n32XeYGF35u2U3fu9W1rp48py2QqBfLrTgANg8wzAic+XHiSPGwOTp1tbvOUPdq",
	"hDwyzXMEr2UCfLlpNSPHLrQBf80gEMFefa5cAsUN+Nj68xWyptNVlnCxgODP61Apj+K1uWT6hjHh9k+g",
	"q1n3PTwgRarFjiyLbUc99Y8isOMu6gzkoJVQma9VzU/FsQqiVGzoAwao21QHpZYwxYxEEKhhiR9If3y0",
	"2o1aolFLFK5ov6meyOu5bU1RR5n9hqyA0VC9MenYDFxBIe7SeQFzRSp0BzEgXFPWHDTX31MVUOubXx0n",
	"iSEz0Pj+Sg4FodaeX6AXYNBKQRrB3FCfzQHWZYnxQDmtHGFleX3Y4TSJIzV/YH2g7bwW0cZ8FPACo0bw",
	"y9UI1l6YTravphV0leEfqycFU4cRo53qsJ70/UVd+2qeXi4a2QCPTMuiBSZfKzuU115TLjCEOsRvYq4/",
	"kRrUcb25udMvaLS0iRyqQ2HwihvALNhnervv6v1m9hxSgsCF4RSlCJqQvqsKBAEupRv/bqGY9ft/omqW",
	"3o6UdpYTcBrKA3hx2yJFC4aFLA0jU/hZmHW05A5xA3/XEb1VDO4FZwXG3rRW5UAN8wN5wlQmD3Jggt0c",
	"hwOp4IayGwJxVuQxL3LNXSbsiZlG5AnkF5jsaZmzkNrXXLM0Vx0TuCafMIt95l5ylsQdnAHEZtuINqgD",
	"YPuVJKCkLQWqO0hirFkRbmclBvzPrKgzZf8OlFMaGPxb4Uur+woiV7PuYdicULxiy/QGXi9oW1RQMtjk",
	"VRXr0nFCcbEzGwbZRgSqjZpKR1cgbrjGsTZiBzD8tKmB4nT42dlVXIG/DH+tl3OqX1HIqoqX6bysjNKp",
	"uMzLXP5x85gGlDOrH+5HOB+Zw76+zeMF619EvX1ZKfl8KZlapkncN4bnTBj22+orDniOPoZYGBCE4JRH",
	"mFfX1rdUbo/mRlZPxidqVVQIXbEztdxSiYGzs++7Kgxkkl9TzX5g6xOqVLaUVLH2UgH4HVWkanlS9P1j",
	"VAioLKk3k7/dOQBoeDL/EOL4xuzNPH+Vf8w99vI7yhputl9zBXQ5xLtyh3dlzS53FSJybYyjZRY5aqh1",
	"LoWVRg22RTRJ7MMXp+KRS9lPMOGQF6M96i7uVndh7k4oLHCxYJAjAhxI7eGYtjbrOHd5s6bkKeFzl3Km",
	"zq1+9TyoKRyVF1tVXrSkQh3iCVJKaghHF6HQIjtTFXY5WdFoyQVrnepmua5NYA7acrkXk5eYifViYtdj",
	"EzVxVeYqY6tMr21uJUjNVBU9ywxn++QUlkmihEpMduD8oO1mAY0vc0N5GCZ5Sq+ZlDxmpEUjrbpJnIs2",
	"KYBHjiFV3B65mJwhU3MxIan0d3rnaGPY/h0q4h0L0l6SH9Jh2Y1bMlFgQIl0oQfhvLdecq0+csWY6eeg",
	"KOraji/BaJMcbZLQo3Z5NjNL1jtv1zJZGz3syB5oVPVmrzUYucCHt2CFjmSQ6rX+FIyGrC/VkBUiS313",
	"v+HkXnn7rQqmnQUAnVhYCMbS6zfLVHm18e19n4PvbtrPEOH4QzZb0N5hFVf84viN8iobO6tvWG6k0xpi",
	"sXpfd6S0q6RTL4B7QxWaMrzQ0yHp7TYxXbyb9uDTLcxTxQYs7s3gfPmK/U/qir+4SlevUvQ4rq3BwOS3",
	"VLAyvZpU1gkRZjvaf7PvYpj3T1/s7746Ptg/Pzp+47Klmx+rPDDmFzYnnUqSRowKfENcz6I2NRSmplLz",
	"KE+oJIqbk+B6ya0diUpGpyCy2wBYsr9ikkd09w27ef9/Unk1JS9yg3+7J1Ry5w6aC7q65Is8zRX5aida",
	"UkkjqDfo9oq5y4u8QuTxxeS71+cXkym5mLw9P7iYPAmSJ0hj5AXX15IN7Od6+dxmPpaFC3XtegB1fh+q",
	"5mD7W/odrutgu2Pq+74hbKtQSsYisVfrGGUqL09R7OkhJZtLppaYt6sluL+t0uuJX+W1KPkKM4bldn+q",
	"UOks89krXVrp0D4uJLpqBQB+3aiu6Vu/pmnfvmqUwzuSIMlG1GurYVLDPduswXiCLN8GRztGUT3RNGrz",
	"L2vtjZm+rbgd7vu+M/6nMo7/KZhOI+OSqfdctKYcMy2sYdpcfi6cL3VQsdeDaXZt0ke49mRm4euF66rd",
	"q28ZlaFKfUH1PlrLzqIli214Vd00WcoNyrZyVXZT85hEJE5vRJJSWyw+to+e8gsNaL5yX1NbBRFAaA2a",
	"NcTqNZgdyGqxc5D4pP5O0ogdekFbQy1/2nviOjl4167BKYZZI5fgreOqHR0ekCIPXOtdYyvKAyaOF+Zn",
	"QuPYQCKI06bBezQuhTLe4QC+8YkUWq6mCarlsr7ovKVh4vYyTxJiS68E6k15eZrChJFU22ySmC8Drley",
	"+H077T1xbYrK0sGnJA2GlsD68NtGWRXzy5DtAQW4kp0aZrXzVAJVTLpu0xV8x7UvcoRzTLc8N27Qdx+x",
	"3FEuuV4bmrLCSS+BIhl6V/710vHD//7pfGKeT9Pa4BtSr2JKSAtikIIactn+0FQzNoIbXfFoGrpTobP4",
	"jJrzmSfpjXUELBkMm7SyvHiT/aIKMFQnwZ8hDbww3Fc9dat77jOZzjlkWqkNYD/4PPmkQKh6Y/zZPQVv",
	"pVmQEYh3r5/tmn3v4ttRPjnn7sWxf7d2mX6uW/VwHvECCxGIo9iuqze7bhVhJrXugZlnNyxJdqD6xi4C",
	"4309Q69bUmUhSNBCSbqMFPn2bThDVyU3tuf8RMhrmilb17VCBIvs9jNDr0AENpNAlSaXmnjPLMXICyX5",
	"yfgPbD35aCBqTsgV66EIQocUmtHV/54nfLHUkU5mPC1HNLt4CV+gfI1ME3LO6GpizfITp/qp9G6kOf+5",
	"OsS7x6FuT6wWDOmS9U2JEioxR9KKCrpgKxAV56j2AMGWxQtW+FLZwilckptUXhm+RWHprYRHzL7Rdmf7",
	"GY2WjDyfPW1s5ubmZkbh8yyVi13bV+2+Ojp48ebsxc7z2dPZUq8S5C403IsakPZPjibTkh5Prp/RJFvS",
	"Zw6VacYne5OvZk9nz6zbKlzTzXBy7/fJgvVfhpirKIVy0n56pMKGZ5AXEkmH0liX6Ydhfc+fPnU4ZKtF",
	"ehVwd3+1NlPkqHoNAoHpAFM3yJsNpIIuIMq6dufhuarA0yXVZu2AK5+bZlZtxxh7n9BNIElvwgDdLyY0",
	"RyzpimkmFSjNWqQFL2tzyxWvZIOe+C81OmiWsHcSg+PdWqTvj9MB2oXQSkr9RNcqhs4mGXrEk7enR61b",
	"xyaQR7trzkIbhw2HLsE9dqG53bfNN4YazOL428Y3rTrHf1e7il89fR5ScFgomiekgqqZre59SaMrdJHi",
	"tpTr11u804WZrXGNv6Vxoena6NZGhZdZ8Mp+x+qvfZVEhG+mdfK6Q+rmzRIiaj8A5J/94x4gb1aCBb4s",
	"XFi82Qn8enOlWuFfL4lLHv/7px/OnlSpJrLl1zThccehmI53eSSV2r4BQDWq+24EpUIRlKW9Kt/Gk+Jh",
	"L7AwVjkH/H0YWOeWxbd36ts0Xm8NUBXl9ceqPGho7cc7PKSq9jJwSudVxeWWCVjv9LemY65kQDvzUdEW",
	"VVDEVpnkYoGClCdthbHDDXOX16mh/wpA621ttXhcz+53DaJg/JDwOR0GMGK+9uLndxDbMPRELT1rZyd/",
	"tA2MNFe75XDDw2fnevUxjUY0C41qXne3tEJQXDIaA/PhpB+fOdiI73h+L+zCefli3C+PUpC97SJq3065",
	"KPf6cFzBdPK3ewH0kfMaQncVAkrmweQ0KjNT2WI+znOl9SaCe09rRqtqIG31RpqerR1V3x2F6mTWJFI0",
	"NBcUy2u7KN480Z6PDkaN+BWMrQoJRjADQGFCLDap640euZK9j2zRVet7XMT6VSvatgl3rqTzRiLPfllX",
	"FFPuaMkjXRaihRQBttKwK7WIJfi4tIXVZ+QQ3RBADcaumVwX5cBDC00qJc7vb7UY0Dh1ngFQN9eWDTUg",
	"vmLk0TePpuTRN+Z/DU/36C/fPCKP2Wwxm2Jt+GdYHP7Z9Iqtn/8F/3hu/QlCO4UZb7dTg0kr+oGv8lWl",
	"ADEiXrFJvyxyWfL4vCxBDSnHsd5uO6JVuhM+r2I55DDHQWu1pVd0jWWFL1nh9QGV9MuLA/mdvGrOAKFW",
	"zOArSD0e0Au0xWvc6WPXSkXAe7RdSPxyn74qZ2Zm/eoeZn2Zyksex2hT+fr5P+/ljU/JayrWpHg34Km9",
	"j92eWXX6W1FEjlQe2tbHFFL4hWXZA6gjS+iAF7X5oGLnruySdyHSts83SL59dl8LCQE6HsnAnZOBp/dB",
	"Bg5SMU84Wg1HwtNBeAYx+7u/m4f+I5KnhOmApwf+XiVUxF47UhKcKoE6hE5dBKpXLPdT6/TTSMN94koL",
	"Vgby2BScjHVRGW5keRiZ3fErfxqa8fU9TPkm1eRlmot4JBq93EpQ9JeMxihWFzJF1HG3q7TgO6bvmRAs",
	"MLT806nAdJIL/p+cHaGPGvA1DyPfjLRipBV/PMmG6mgZijfQ0fKWkg30vWdyAdvYKtswVPbagan/e7PT",
	"rNScvGfL4q3o0yh0fVlEcZTz/mBkOA+ybFCCtca1HQzm2k6x/z2T4jL/9b3T4nvTgz0oNR7VcOOLML4I",
	"o+bPaf52aZbJ1BbVCT4k+9AA03szse7i65vsPAZPtnbYd5Nv7THRKaHVBY+Pycjaj4R8JOSfNyHH4CwK",
	"2YXVrmQqx6jcsHH5FL4XEV2XVLGYpALdg0qPHSri3dS64RS/zgKigBkN09CoO7It4+g40wMRwOoS2n1h",
	"R9o3upTcOVmo3PfJu+nkw468pJhg2iZft+mX0D0dJGiw1sItdRTiY5OG9Dh44i3o8+YsicHoujm6bo6u",
	"m1+I62YAR2x2EzJP6MLgCaasYVigyaxmtaJyXc0up2bkJ7MTAFVKQLJyQfoIFoBkpdYT3Hw7mB+agynG",
	"AOBQwuQRYlMF7x+VMKqnGrsx63hkBzZDPYLKGTJvvfpe2xCWFdle7tQOjPR1dGodOZAH5kCGeLDWWIY2",
	"d9WiuPndyQ/37Yjqzzqqu0ev0z8ZZWjKFgP8SQ+dP2kv2cCWBdnYSENcG3x0Dx1VoKPL16bvfnuykP7L",
	"+x3TW7u5W/PnvA+mfby247V9YHa92y2z9+pCw61d3tG7cosEZJQkRnvrKLxsi06G3F3QY2UImbQeklsj",
	"lJ+F7+Mmepb7I4yjTmekxCMl/uLUSLsxi9LViqsiU3uIYhdFF0oDFKp7vL5N1VL5cYsKpnLQz4KM+1AY",
	"ed2Rwo4S+gPTu4QqrRgTnZl6sXKk0sS0hCIxStNV1kKYOjRzr6jSZwwyoG5BQ9e6rjn6FH4e2rsCJh28",
	"5tfNc3mTQtb6Ihv0SEZGMvJwZEQyETOJ5Yw6yYhr6FWFbNCKU9tmm9r80OTO6cmmYd0i1Qj6gwGlgroQ",
	"xUJ+dDUdw45B0Pi02nbyR7U1jFRqFCdHuliji2XV806q6Bd8Hc5NnbmycKO1c7R2jkzQH8PaufF19myf",
	"W7vQowV01AqNlGykZJ9ij9yYkFWsk1sjZaONciRdI+kaZbw/kIzHhEyTZMWEHlDlrmzcXf/pO6ZfFE2L",
	"QneDqScdmO4Kw2ChgJkgXKm8mlh1Ro7mJJPpNY9ZPPUrTtsAuiWLrgjvy4li4+xUeBKIp4PYRa5IRBUr",
	"Qvy409PZ+Mg6RGbkSBCaJCTVSyahLy7Sg7I/EYZJwsovGWGrTLcGL0ZKPphqrXHwI0kfudE/CYEtb24w",
	"C0njc08ygfIqDawS1egwphgYUwyMKQbG6lAbvtxjVagxgP6P+Jb2xdKLjiezLa6+0eOOQuyb89xztH3L",
	"AkYn7THwfuTOg9z5BuH4m1Ee7BWiPBtpmNunHAP2R5l9VMN+VpxNe7aAzWhLRfd6J4TlM/GwGcTvjARm",
	"VAo+jCDTmWVgsysPne740o9eOHdDeEYZa2SnRnbqDuhrV3aCzcir9QW6YwL7WfgG3VKJ9SC0ddSdjXR9",
	"pOt/PnXdLWoyBd6D5jNge93BM/DZVV1qbKGoRPXQz4FbSL9KcSTQo5phJJe3Cuv7dIXk7TzqR7XkSC9G",
	"evFwaslPIgNhJeVdEIJRVTmqKkcKOIq0X4Kq8pNIbpvi8i6I7qi+HJm/kfn7UoTFazNPq0h4yrTk7Jop",
	"QotABOwyuxDhwBQcsC8Y5U8T73CWSk1SGTMJ4Yu2uB/EH5gNueR/1ViTR2aMR+SxYDeG+s65VLp1cTB4",
	"ZVExDgVVTlU0mU6YyFcGGSj8BT++m942VgPPH8/NHJELtuiL49lOncUvOorpTrUR5tjGOI8xzuPhniKD",
	"gdXnZ54w1hcb+dK06YuHfIkDjTGQYwzkGAP55ZZZPrIZF9rqKbtNA11pWwmNbY5WdYaDPFz5YiBb46M8",
	"PsoP9ijDTRlSvLj6DLfFWEKrO4qrxLHvOZbSm3T0ARvjJ/9cRKHBqe/+Dv/9uKvZKkuoNgyh4qloZ+GB",
	"/XCtSdE8xMOf21Y/lo161dbpjUDuybz6jWlalNRzj0jdMjP6KEmMksQoSYzZVAydrdGtkZ0f2fnP6OUe",
	"kPogtqkPGg9sS7qD2oX45Hf87p7xuuV74MxjToXRvDyal6vqgyD3LxmNkfUt3v1eGvId0yMBuU8CUof2",
	"SElGSvKH4lwG52bqVVJiQ6ek3Mgprjr0mHZpvNjjxd4GiwCJj3ov7ndMb+nWbjF46M9hnhzJxkg2HtYw",
	"2ZlAqZd0QLstEY8x4Gh7tGPUg45BRqOZdksksisHUi+FtNFDW6KRn0V80Aa+JPdGEke3lZEEjyT4y9Ja",
	"9eXcAAV5GfZZVZU7ghwWhW8X23mnAvEoi46y6J9YFq3Xnh0umW7rLo/y6SifjkRsJGK3kBYlCoEbMiO+",
	"6LgtIjYKkCMPNJKPz0DSQcfuQckjYq40F5EuHLCxb5EToaQzJSVYZ6wty8QrnHkAqTGjWJ/ogsBIu7Bi",
	"ETJdtVnjrriIO+mNy61gy9oPyauwT+Y8sfEC9bWkIlljxEAR8Uz0kvpRAQt+zQS2Lxzd78SLfgurRAfy",
	"vlVu3QO+RDdc770kq7id9Ms+0FWWYA9c7Qv8BS61tQDvTeyPpf+9uTmJuwbgaI/pXq65TMWKCf1NJtM4",
	"jzQ60Em24Kn4Jlc7jCq988xsgDP5zSWNrpiI8WIPoyFw+UYv99HL/cHeIsD76luUygUV/DdYx2b5jCo9",
	"Z4QcG9qG1EJVPyKJM+QjV0ySJVWERhFThr6E01IcV1Z1h5yhP9F4Nceree9Xs3ypIGlLWkN8d3P936sX",
	"WLIsVVynkrOehDCnruW6LyvMqT/mmBtmjOgcIzrHiM4B5K+kMONbOr6lD8bmFk/iekiClsCz2JalpWx6",
	"R6lavAnuOV9LfebR+2VM2vInpBYtjPUmsVSD6Am2rtCTjaw/gUnG0KrRJjPaZG7DIHTEVw26zN8xvfWb",
	"/Jl4l3WzDeNVHq/yPfP63TFPg66z9a7a8oUeXcy2TFRGMWR0wh8ln23Szs5gqEGk07q1bZ14fhaubZsq",
	"b+6XYI7KopFKj1T6i9JPWRvuWkS9ll9serYWUb/tt2w7Gn9H4+9o/B2NvwOZgpJwjObf0fz7gA9m+TAO",
	"MwAHXsd2E3DZ+M6MwN4U924Grs898vajIfhPSTfaWO3NbMGDSIuzBldIy4Z6k8BEo0V4FOtHM9LteIZO",
	"m/CgSw1W4Tu40Z+NZbibkxgv9Xip710Q6LMOD7rY1jR6B1d7tBFvnbyMMspofxjFou1S0R478SAiWliK",
	"74CMfibW4k21PPdNPEe90kizR5r9RamybKWiNmOxkW+VHdorxNSQa8v6UndGogYUVRotK/eNVg5/3kFf",
	"NJriS53LZLI32Z2Y19K2riPXscMizF5kKCET2m5h5tXxqHyYNK293kCpIAdMaj43rdkZXwguFhZuVUcH",
	"Z/cvWytsLYtHoHsezFMUHBSrlHSPYLaM7QiNtCuyXBnA/t67khdCpkmyYkJ37ZQVrQbt0KzPZiviYkHY",
	"tUEZfzjzQ+/Sqknp/P6YBmuTJdgURDSSqVIk5vM5k0yER8fEJpuM7if+CA5ZybjQt++21Ap2LM+Fp3+k",
	"NledYiyPtA/YccQ4bDhA1+2I7lZ/fPfx/w8AAP//XsShyhqJAgA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
