apiVersion: v1
kind: Service
metadata:
  labels:
    flightctl.service: flightctl-remote-access
    {{- include "flightctl.standardLabels" . | nindent 4 }}
  name: flightctl-remote-access
  namespace: {{ .Release.Namespace }}
spec:
  {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.dev.nodePorts.consoleService }}
  type: NodePort
  {{- end }}
  ports:
    - name: "service-api"
      port: 3444
      targetPort: 3444
      {{- if and (eq (include "flightctl.getServiceExposeMethod" .) "nodePort") .Values.dev.nodePorts.consoleService }}
      nodePort: {{ .Values.dev.nodePorts.consoleService }}
      {{- end }}
  selector:
    flightctl.service: flightctl-remote-access
