// Code generated by oapi-codegen; DO NOT EDIT.

package v1beta1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"strings"
	"sync"
)

// Base64-encoded, gzip-compressed OpenAPI spec.
var openAPISpecJSON = []string{
	"H4sIAAAAAAAC/+yaTXPbNhPH7/oUO/Ez42SeihRlu53y1MSxO562ScYvvXR6WIErEg0J0AAoj5rGn70D",
	"kLQpWaRfk0guc8jIIHax/yXEH3YpmZPAnIew4428YMDFVIYDAMNNSiEcpjxODOxLYZRM4fWHowHAjJTm",
	"UoQwCyZkMBgARKSZ4rlxw/8MAAD+WLT982ViTK5D35+6cWZSj8tXwDUgaFIzzgimUkFELEWFhs8IMhQY",
	"U0bCgJzCNCUy2n6iKCaIyNpoQBGBSYgruJDqYyox0t4AgElhkJnQBSMwoxBOE1pWdEqYuRmFSkNYFaK7",
	"ShnyNARDmP20dDHljISm5jqvc2QJwdgb3XR9cXHhobvuSRX7lbX2fz3aP3h3cjAceyMvMVk6sDkhpa3f",
	"YenCx5z7s2BgMK6Gy+XKRLilFu7D+5xsHqXQIAW8dbNAkZaFYuRyVHsgoWSa2jwrOi9Im9ucHVwZHJcG",
	"Tb85msQF6Fe3yP9kl/nsa4Om0GWm8qK6NQC1nvLfsKlnKYizPEJD9m5D6ctuBlyW5lWmsg75KApBUZ4i",
	"o3LqiTOupuWoMCNT5boOokyM/f9qEICLEKy6xtBCfHaDWRMblg1yKTAwEgonwWt4sCnniqIQjCqaq2mW",
	"UIZhYwTAzHMKQRvFRTy4tidt3shofj3X7n4SpmmMeZ5y5hLi/6WlWHS8ajGA/ymahrDteb7n+Uwq8qvv",
	"vF89N7w5ZumWz2SWS0HCaL90pP1S+/agU6YinUu7/68XfjEejV6EbRl+/0vjygqRt8lsE/qkUl/sdkl4",
	"gxEcN75m66Wl/GosaAnatZwJLEwiFf+bos0Qs9su5p00cCgLsRlKxj+2KzmVEn5DMa/3mV5zRTkaltwf",
	"Bx+s2YNo4Bb85ixwUawDCoYukv9/BSq4W1btyp4NPRvWSsxOu5hDqSY8ikj0lOsp9xhFe1277KSqg88E",
	"zpCnOElprTUtF3iKRET2Oe6W27rrGq5g9C8DzPllMAsug8rtZVD6vQxqx2Uit8AkXAPXMCnieO46ADEJ",
	"y3fSwMUMUx6BoikpEoz0d6CpKtC3rgrxmJukmHhMZr7EnA+ZjCgmsfgH17og7Qe7e+Mt95nJzFa9w3Hw",
	"w/ejnfFesOPcxvSAavZnMu5kUIurpnafXGIyx9X8t03PX/7kYqRdfDFinRPj02r/wVSqpzzNXAv4KOSF",
	"qGX/XraflgSdF6TmXYpS1KZ0dBV+5Wl1zFNM9YOOYM/y1DLuRorrp5FYdWiBT5/7YnLtlXRgdl+KacqZ",
	"6c8LX5etN5qyNWZrkj0Yrzc916TdhpfaPfkbELSQBdSAEzmjV7fhbnUreQX5sKuL3Ia+GxZfnn7tQVZE",
	"fNoC/jnQ40bK+pKxZ1mPgL5kXI216oWg1I+Dyr4iNPQArjBn2IaWNX291vGMvUc3teNZXKYz2ji89N3V",
	"HpV9sdSTcvNJyUiZsrlGmseCi/juxGy17SIn7F9bnZRW9wBoq/F6g7Q17P8OUO+Qgh6sPVi/KVjL2T1e",
	"1x2vm0HXbrwu9Fk7ep33guwxYVT+Vql8Z0ZRO27b2p+3IfZxbdDW5mVnf/T2M8OKPumd3wC6308Lfl7Q",
	"kaFMP8MfCN0Nvj2wNrBp2vdMe1Q9HlWDfwMAAP//NdKzpaMzAAA=",
}

// decodeOpenAPISpec decodes and decompresses the embedded spec.
func decodeOpenAPISpec() ([]byte, error) {
	joined := strings.Join(openAPISpecJSON, "")
	raw, err := base64.StdEncoding.DecodeString(joined)
	if err != nil {
		return nil, fmt.Errorf("decoding base64: %w", err)
	}
	r, err := gzip.NewReader(bytes.NewReader(raw))
	if err != nil {
		return nil, fmt.Errorf("creating gzip reader: %w", err)
	}
	defer r.Close()
	var out bytes.Buffer
	if _, err := out.ReadFrom(r); err != nil {
		return nil, fmt.Errorf("decompressing: %w", err)
	}
	return out.Bytes(), nil
}

// decodeOpenAPISpecCached returns a closure that caches the decoded spec.
func decodeOpenAPISpecCached() func() ([]byte, error) {
	var cached []byte
	var cachedErr error
	var once sync.Once
	return func() ([]byte, error) {
		once.Do(func() {
			cached, cachedErr = decodeOpenAPISpec()
		})
		return cached, cachedErr
	}
}

var openAPISpec = decodeOpenAPISpecCached()

// GetOpenAPISpecJSON returns the raw OpenAPI spec as JSON bytes.
func GetOpenAPISpecJSON() ([]byte, error) {
	return openAPISpec()
}

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------
