// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1alpha1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+x9/XLcNvLgq+C4vyrb2fmQ5CSVqGorq0i2o4ttqfSR1K5Ht8aQPTNYkQANgCNPUqq6",
	"d7g3vCe5whcJkuAMZywr99s4+cMa4qvRaHQ3uhuN36OYZTmjQKWIDn+PRLyADOs/j6aCpYWEcywX6ncC",
	"IuYkl4TR6DC6gJyDUM0QpgjbumhGUkA5lotRNIhyznLgkoDuLw/2c7WAqrWqgiRD2PTDKJILQGIlJGQj",
	"9JZJQHKBJcJ0heAjEZLQual6R9IUTQGxJfA7TqQEqiCAjzjLU4gOo/ES83HK5mOc56OUzaNBJFe5KhGS",
	"EzqP7u/LL2z6b4hldD+IjvL8Sn8Lga1qIzbTMOI8T0mMVakelxZZdPjOIFdAdNMcbRB9HKpKwyXmFGcK",
	"Q+/caMeukQHA9XvMqAQqFSw4Tc9m0eG736P/4jCLDqO/jKtlHNs1HL8kKbhG94P1dS8gxZIszWKryhw+",
	"FIRDouDSK3fTQk8Dvhd0+QvmZqlrCw9VAU4Souri9LxWpbEUgwa2X9Al4YxmQCVaYk7wNAV0C6vhEqeF",
	"IhvCxQARquCCBCWF6gbxgkqSwQipxbqFFcI0QaYF4HiBskJIRTNTkHcAFO3rCgffPEfxAnMcS+BiFLWm",
	"3UEnDg3nnC1JAvwyh7j/WgXwqFahjkhcUeOGvnS1+0GkSKtjz1UDIlWrxMb+//3f/6eOA5QyOh8gITGX",
	"6I7IBcIoBSmBI8YRLbIp8IHGXcyoxIQiytDdgkgQOY5h1Gur/R4xCj0QdZrhOXShexOVn9KU0O7WN/c3",
	"69f2UmJZiDBHMGWKH2AkCJ2ndRxbXpbAkhiUOBZxziHHlidcKhSbPy8KSs1fLzhnPBpE1/SWsjsaDSLF",
	"IFKQkPTnK/UZ+GO2Cj0gWmUVVK0iB2aroIK7VeRNpI7oX1haGMqttk8d3ScwIxQEwpp6E7TULVAhIEHT",
	"lZZJdZZc30rhjXFNyYcCzH6wjN3vV9E+oSF+36Zvn3/qwW4+keYNSloEG8JbkwXVp25mJNqzf02E1PTr",
	"ka2trOZIJGSiB+9prGG11zHneLWRf5pmhj7W77IHWfK3rbUOrKdazhlwoDGENCFbpDQXs8fzlK0gQWfH",
	"p0OFo5RgKhFRq6g4ptpeMxxLNMXxrRJUa8cO0ZIPzwaWJS6LLMN81ZN1pamPRNHNtn4CnMrFKhpEJzDn",
	"OIEkwKq2Zk91aKsxOqt4g3fWCXCmeoUS3PtBdKwIZqaqwSWZK2Z3AR8KELKNts6qiHvKMeL240wtPRJk",
	"TiFBcdUWzTjLNJaPj9pUi3PyC3ChR2wCcHR+astQYtmhJiXzDRJkdqUhbyIqsKxImqk9Y6hmhC6Bq4ZI",
	"LFiRalG+BK6mErM5Jb+VvQlH5imWalqESuAUp0azMnpAhleIg+oXFdTrQVcRI/SGcUCEztghWkiZi8Px",
	"eE7k6PY7MSJMsZWsoESuxkqf4GRaSMbFOIElpGNB5kPMY6VdxLLgMMY5GWpgqV7YUZb8hYNgBY9BBLfy",
	"LaFJG5c/E5ogotbL1LSKYokyt08vXlxeITeAQavBoLfoFTIVIgidATc1y5UGmuSMUKl/xClRiq0ophmR",
	"wtGLwvMIHWNKmdbLijzBEpIROqXoGGeQHmMBnx2VCntiqFAWRmYGEidY4k1y4Uzj6A1IrFoJK5jWtejc",
	"XVbTi0QpInbrxjRv8ldvv1lS8SZpIQ+x3PXgtsjtV47zHJQsYAVNEFZSjA9jDmqN0fHlxQBlLIEUEsWC",
	"b4spcAoSBCJMry3OycjjIWK03B+tBaHNWeBjTrhRxiBmNBEh0abbmyNVyTSWOCUJkSvN0TQBVwOrYWaM",
	"Z1hGhxGh8vlBRTWKU8yBK2zBR8nxugNhqWy0KK6uTLROiqpjhKWhdRBOtCv0GtuBw7FmuArPOcuLVH+a",
	"rvTXo/NTJPQGVrjX9dXMFWMjWVZIdfoMnAsNHQUlhTpwTbGAb78eAo1ZAgk6f/Gm+vvn48u/7O8pcEbo",
	"DZbxwnJyRW2jUn4QSBNEKMI+PawTQoZJ1ZZkupIQ2sdaLPG3QRXplCaGyDRMvKQJ08ZwfM05PxQ4JTMC",
	"idagg/yiIAHee3168gjr5AEh8DykAF/r7xrrahpaGIBWiW9hhUwrb/72KECEKOoSvaYtbyRgNeXNuukj",
	"IKbBCR0114hjO9bXocRXBIXznLMlTscJUILT8QyTtOCARKmRlrP07AuiA++IzCrToGhzPK9qeI/aLts6",
	"2qBCHGJK1S9x3mt3Kfaq2VwAGcdlmdG81coyf6eN0M9KO0WxV5EDOtKog2SAToAS9a/C0EtMUgNUr+Na",
	"OXjwmOZTgzeFIA2UHXVPsFq+BCQmqdAChFFAWG056ZY7LjjXCpFUa+qUV0XUFx5Lqy9tioW84pgKPdIV",
	"6TJ7qXpIkgzMSCVosmwLiVHTFFyWDCVDmDK5AF5bbaWPDVVfYcVIKH7RhuKnIsMUccCJpiZbDxGzJ5Sa",
	"6bCDp6yQFuISvCBDY1O93ZNXQMHI6fDsR06TGc3Lmoap1LFxh4XmfEpmJajIzbC+XP/266Bc54BF8KSC",
	"nk45gdkzZGpUqoMb84noNdOeSp/r1Sl5rqeezYz5tLEDdA8lBIMQyZUIqNZ/7WbZbOWo4WigiZLN0BVX",
	"J62XOBUwQPb06h/OVXk0iHSFrY/jDehsX42vruvG59pJuobNNj1a70lFdcQ/2HizcZzOHOHdn4br6Vkq",
	"lqcK4xiEINMUmj8c3zjHXOiqlysa6z9+UbqsqsHSlBXylJ5zNucg1AJfqxOXNczmELuqb4pUkjyFszsK",
	"XGhIliSGE1CHLSLU0UE16ofsF5SzNM2ASiszvRl2ytU+dUr0dNYo8XYBORNEMr4KIk3hqrOghVm/sMTy",
	"yxRAOvzpHyF8Gzx6WDcffNybL31XwBDhjMybBtF+ZtdXRAaab/Ix/Fzq5pcQc5A7OCh2GPUnKfNQM42D",
	"vHCr8oZRtdBt31Rdmmam2mbXZ2UIYcg22qxY+r0HreLrHZXtmZhZckZffMwVLYXVEM4ogrICMtJMCyLV",
	"d1Kk2sRDMhCjCVWTtDWIQO+/Qvb/94doiN4Qqs6Wh+j9V+9RZs9re8Nvvh+hIfqJFbxVdPBcFZ3glULa",
	"G0blol5jf/h8X9UIFu0feI1/Bbht9v7taEIvizxnXB0C1EJiyRQQQ1XxsDxSKt3YmLWewmg+GuhuCEUL",
	"BXLZHyyBr/S3Z2rc98P3h+gC03nVam/43XuNuP0DdPRGrf136OiNqT14f4i0I8FV3h/sH9jaQmoddf9A",
	"LlCmcWjajN8foksJeQXW2LUxwDRbXBr/Wn0u31UoUVLzO6/JhL4wgQAKc2hv+N1g/9vhwXO7pEFF47gQ",
	"kmWGsZzSGVtnrGjqOtqWYyyyCYp1R8huMLsAwSGbh1GvE0INMepjnFYL61b5lophAG8DZ77XDdT5YiVI",
	"jFOvvy826C826C826HGlgPQ/e9g2O1iXbzr3cctx3vbqhi1IjcOm79he78HWJ5lkFZb+JuTDKu/qRK/I",
	"7G5B4oW2TOiWqJejXA2j40oCfPRtOYqrg9w5tzw+hnv3DqT91iwc4nE/6PaVVyc0W6V0Q+tN1oBrN9d5",
	"8/DaYZkpPcJqvTyElpPvRVd1j2hIqglTwdHPQjtnG/ECAYdxnUyJFaVrydSXdsYY4jifNhH48QkPYi5Y",
	"7y5v4nsjVo0e3oXIY8+6VZ3xDb7UfpqReRttHGgCHJJOMXxhKzjB29nvJptvfZy1kxQs7dQwbLGvaFhT",
	"hv4cM0ohtqf+crHb8xZGWT89CTMiW4xOT3yDUmOEMGGYlm880dGg91LXK0dxjNqxNgW3dQ78rRaIGGOq",
	"paUwtlxCiSQ4Jb8Zo2MZNgo8IxSngxJmyVyzAQIZdy0XTs5ouooOJS+gQZqNWQ08BHYvpX9ubiPCdWb1",
	"TuxIKqmftktrdWsNJeZzkP3Epg/KlW4XNsWZLvtNyeunzcZLV4/ZLEKN0JpaBnLBkvqW8g1U1xS0GUcb",
	"o2LJ+OoCRA2+dSagdRB7Pa+rVh+1xMKpkoOcyNXxAuLbLobUXbe5e+ssi7gWKFZNUA5c7Qjjsd5RBgyD",
	"MqA68TTHNBB9AuvvnvxuvL+zpw023i2QWVGdi6u8psKd/n176C/AtTd2KzoMTaAaaV0dH4bueiV03VUq",
	"uNto7bSYW+Wki0RbezdvnOD1KIk6dcjV7kSjCGFrFacib63eVEBvUG5U7RJXbflIMqUJZrmbe6PzpW5Z",
	"6aj93Fo77SobV2yWyKnWMs8+Bc87b8w2ML23ZqcAKFfB233h7bnTVmxsi44pde2sDXu4vX2rbfeazCBe",
	"xSnspMymrvUDHAOaRq+q84eSAY257sb+Q510kZd/fSiEsTafN84iu8Z1X0f9y5aE1oC6SSqN4hoUgfIQ",
	"aBuq1YjuTIRD5vxSZIqmVnEz+iA6uyyPAZ26RxZ0yl/VOjGR2sZYwtH1xevNByfTbzdhnImdttDZZe8p",
	"/FI/+LlpBPeFLjkh885gtUSXNfsypnYkFvjgm28P8d5oNHrWFzX1QbsRVfoPt0JXaW3dJOjjvOjHDupw",
	"OKGVEHH7Ke0zyBhf7d5DMygnL6KyUwtdX9Sud+6JmnfPINvYstsXAH7F3G70Y04kiXG681WAEKD+TYN2",
	"aTV4qNQDKFTsgAyV+aEMnh24gy01mBJe40upbE39ruDk1qG70yWchhO5FXxoDEPdgJjyHWAI+rBDwwuW",
	"hgysOljLYSOWZFmZdqxNoz8sdYtVMIa4LrK2tlXoIKyecFj5ZmzfhmsFzE8KtNoetF5zuyI2HLs/Dhp+",
	"8xAWzD3rpMPUZgp1XClRjLbu8W/ED2AZL86xlMBp0JbsVlZXRLmtWZtMy/xsfL4OjoISqUX0wFxJZVz/",
	"q7REUcxm5OMAmfs2C0jToZCrFNA8ZVM3mIZfj47nmFAhXdhhukIpwwmYITRMGf74GuhcLqLDg2++HUS2",
	"i+gw+l/v9obf4+FvR8N/Hk4mw3+NJvq/d5PJzf+YTIaTyVeTyQ83f3369371nv3wdDIZvTMVQ8X/FZLm",
	"m6/XGb/dOUtJ3FP4XHstDLned8qV9YaltikprNcL72afZZ7Its2wPguT1Ph8YlngtIoO/VRea1Utn+VW",
	"R4ot+EvbSRfYY7jtati694arpn98cbkGGo/GmebcNgqPweBbH72fGlPsy5teDLvyo2jDij2y7mR+cBaT",
	"SwDaJzbYkoUJhQXqYust/+tvMSnPdDsdQ7cULGWbmmjZVtfUwmAb4mwRpOHSLm6mRwdV/ZJdJdtwqqTD",
	"LuTtjBpU9Z0YhTemj0af/Eoy1mtTwVthzSM1nwK6dfPdva8erS4wT+4wBx3/YsLACJ1bkYlqESkP75W1",
	"MLiQ+YfwywZQs5tZZqs70GET35mOzAxfd76AKWM2ZvWc3QGH5Gw2q9kAf8VEVXjJ+HHpmDyaSeAXICTj",
	"quNzXIgtDTe1eXkQtso8oAOl9WNQrcifWqC4NttAedOUVCvsgZPQkBZN1eLWeE2/GL2z3Pl2zd7wLgzC",
	"x5yJ6i4VngOVowl9geOFvgYWM85B5Iwm5mJIpZCbTWIj0WKc4ylJiVyNJnRztJ+ZRG2PxSxNTT6bMmSr",
	"U9FRQHbGBijZdjTXuXNMleCW9KOwOvrwaihdwoSbWjy1YhGrnhUFhTz4PzIm0enJNl2ZYMo+cqUVv6kE",
	"qWOJBtvhWZ6VfPPS8c2e4DVjvXyEllhoQzGoL183F2vp5Bvc2bmuqU2iGaZ4bu4WaS5tJJbOmRSnRaJK",
	"7hZA3XcXgDkFlLA7as9DSqrYK2oBD5qtd2liqTdqO2YyZe1S6u/a/n4D2pKd7K8Gpgf1X/jC0nT/kMKy",
	"NtndhGW7iy08GBXCSvdFfsVOsL4XeVbIs5n927vmsYuJsAakN0Sg1B812Lhx36Re6lsBibjdeJFi67sL",
	"g//PLl8EOYo9F2tWYjrQzISIW3MteptsfwnhoMNVynR/zrSluq/3uX4ua/LSnRT+PcgZLlJ1UNtT2nob",
	"ogx/JFmRVUkOcJqyOz/M1ISqSYZim7HKJJUrG1T80l0eTxDWsfVMbeyl9SKDmqPte7pSJ2512iwokSNU",
	"XeAoP+qLvofovTB3IYRJ0zBA7zPzwVxvUB8W5oO+yKHXorJQPf3h8N3+8PubyST56tkPk0nyTmSLm6Ah",
	"6QWNmZIFfWKlwNY11KhD3fTyYYkbMf4+M8hTTJQ2ZJIh9L4jZ4Y6t43d7x9tJ/eD9jW6NvitKmuy9Nhb",
	"6WrBTfzVWiPTl8sRXy5H/AkvR7Q21Hb3JNrNHzYhT8fNWpz2YA2uapWxIKzLlYzCs5NajqFzlXbGxGJ3",
	"g3dNboy7BcgFcD8VBFpggaYAFLkOvDWfMpYCpsbOOYX0UxKuHrnEJ6YnfdDN83RVpbjruHnWWjw7z61W",
	"qFLV++lV3UvdVmg2DLppxT0vxaeu/VFH7IUW/1jaCzX+6t9hUVv4fgZo1+LHrts89UtBqm4PPdLrdeBP",
	"KaCODbZcgh1cRQHElws0CtJa+AAdrGakjlfRjNyq+0S4GCLtPAkEnwgeXoJQMig/r40wF/d9mgps4Lov",
	"rv8dtc/BL1xOEesuMfm5PRZCROlgWQBFSqx6S0hEiMF18BiF1V7spcsC0FFxOzpsddK18Y0A2omdeQ6/",
	"TZmMfIpqpzMabZ2kqJ2SB8JTfty0Q36K8yAeYlNo1mhGQrGo8br2+sCCJHyU6On11cvhd88Q481cbt4g",
	"+l4QSTsxrOq588tmOvCOY0EDl5p+9xUmVVpeWmrPe85ZkYdnrWbwRCBdY+AdaYFojQS7tMs2/zdwEqPT",
	"kxE6MSdtrS9MIs6YnERhrZQlsHboHLgNrdF5EEfoH6zQyroBxlhiM6Vaz3BGUoI5YrHEaZWfHOvT6W/A",
	"mcsQsPft11/r5cOGn8cksw3MxaZQm68P9p6p04IsSDIWIOfqH0ni2xWa2gM6KiOnR+h0htRpoMTYwBhi",
	"65PRZ0w1T8UDK4Qp8MKXWAsBfC222J1OxPfgC9VFc9uZvbZ5h6BG0Zsq116oCD5aUO65DjNROMVL63L1",
	"nMgLBUZoCbif/hmjV0TWQ7RsJr5tLGTOLmbvM87I3F05rFL1dFymdsWbVb2qq1qmyHZ0kVZpLmBJur1L",
	"3JYqoAvhZTReC2/r7mkJfGvUQZetb90TB/5sG3GMvfNs25UPDdyRcqdFPOrU35N6KPrp6uq8J/2ovR9+",
	"m0V9dRRjtKwnwjyTYt2dknmnCye9OMiC08rPpUERsATumTe9t1U+ifp4m/oc8WB72XBFY7SGLk2UX2jy",
	"vJTE1xevbc5MloFAeCbteVoJcB3Yj06lvq5r/GCAPhSgDdMcZ6DfvhBFvEBYHKJJNFY0OJZs7IxDP+ja",
	"f9O1u/hnJ4WXy/f4RO0oMjTy2vc1dnnOJPRuQcvn0XGnoZVav8w3YS8kBPJAoBzHt73cB113NjrRcl6k",
	"aRVEWbkVTmdvmTw3Z4WWg8GFGtSF7hO/zZMR+lWdgtQZSpUdpXd4JZ4Y5cFMlAiUF2mqRLvOiGQetqm1",
	"eqtKao30ky44Nfk4dFLU7tukZsxo0JyM7rWnoV7hp+xH/Wj0pT7Z/hxK+zxYURJHzzcyLjXT2OKKTrtt",
	"IJbVv29kGZaxz2945SEg+GtktHFSHtVt8RDFZsBMKmkOcyIkX43QlTqUKxV7CiaqpbbTVEOTA7X0P54d",
	"n5adDRTbThmdq3+tCsR4VvoiVF3TkfA9in145rqHLtY/6PP52JUJtVoT2O4zJCtgd7m+UanN64/JFqCe",
	"vKwryeDh9vM0xxjJbFbqNn/pNePyTBGIGP68orATcYNobSLHnvmXtgdzEAk9Wt/zRgUlMg0DtzFYQeWO",
	"mmLNDm0G8LRB3XPNRldNox9CKpiDHegHxLp70cUbuwqvfNX9wMPQzSZro21dLVKIdN7oG3l/gqSbntew",
	"HWNZlintpUyeYx5wTFOUAxdEJ9Kvbm9qjWWBlzCwZGf1cqFbGGh1qi1u6xq2E7C1UspkdfNjR7N2Vdmk",
	"w25dAWitvEu2X2ZfWOPjMZcwtGv6DguX17+/YyeBFHYZyz6VqZtvM958TXbxIyTgQ6HZks0OV3PM41Ls",
	"Iy/zeBk6ZtLuGK8JOm8+Z+De/7wAnAwZTVc9k5F/slfjDdbJM2y8wS2sRPWEpPVxNFI9MT7HlPxmIvBj",
	"LGHOuPr5VMQsN18FpBDLZ46Yg1TUj3fawJBgQvg7GjIZHvmBEVgidqffUtCRJ+b7QEmDifazj9VYk8im",
	"we1K3qdbdQfAUMRy/KEAh0Q9LNF5VspQImPgeCK8SJXqLnsVANPPPHmOZbzwgoBK/SNMAzOdQ73BPFjH",
	"TrKRu8bOZTP0+GconCT6zkieGrHCIWPLwOOv94MO498R+p+XZ2/ROdOYKN/RbbXWFBiG0UTFKNUgSZTS",
	"bqEZtQQCy9dZ1ZpaWO192LWPASNuq27/FvBRoO2DPgIseDwmNIGPo3+LfuTkJN9RClxe2LjkvPtmQXtK",
	"i3peq4YbWRsvVN9hn27RxW9dfKMSrdIxeTVvT13DS+DqxFUIa0Eo02dOYca4HZjQ+Qi91Hv8cH244hPx",
	"pB6H+CR7Uo9DfLJ40hmHOJkkf+0OPcyBx0BlZ3KOqlxhzczIOJk5mc+VOhDCpBFFRqleQp+rg7X1vrSN",
	"wnHUrkdvmWrzqEuTm03EVRusHXxpS1s043hPMAmDvvjQz3bTCUvVcWcVb8TOOgYUb9LuIrqaKlFTzQjF",
	"9kOG89w6SI/Przu9yOG89iZQuzP0oSOI2yntXe26Vfr7krmtzPtZNV1bCeNerw10zGaTar4Org1BIB2Y",
	"uL9Zc3JoL+DamyjhuHFc8zg1FHfHaNclRdCVEFe1RuiMpivzipD+mgNHbm/qQBLDwLZOlFBx/FCqBCVR",
	"CJ2fKjkdjCksGbR7XdwFueumCu5H4Lll4HcX411zSBz4SxGYcYihbXjPhhj1QBacWj1FAR7j1EUMJYw+",
	"cY4oZIyNnpr8Je7688Zdx8GgjMtiPjfv3WmHoF2c2MUxaPyZQKgB2kPEBkAYQ0yPlyC/BHs/aLB3x6Nj",
	"fdRQ/wKcwqM77HRlh+946CvD8YJQ6BzqbrFqDKAW2togJzp/YsHVudMm4UCnFiBDAkQgyHKpLQNc/6Ss",
	"Hp63xCTVLxyiI3RhXhuLU8zti47WxS5ctG8CaFoozgNCU67SoTlJABG54TLeuvvjFfLQmX6y6xBNostC",
	"v6I0idS5zJvpZycbkUM8xDQZdqZK7BFzX757ptlEz5fOrkgG/2TOheD8pa+ZURbbCUvRb0qQl/YBLqww",
	"1Eg9PXp75B7lObp4cTR+fXZ8dHV69naA7jQxqI/1Wz0KYYTq2DyOWAyYGj7sWtbe+swxlyQuUsyRIBKq",
	"5/7VYZMDHpgXacxpEh3paCo8fgt3//oH47cD9KJQAmp8jjlxaklBcTYl84IVAj0fxgvMcaxjENxcGxFk",
	"6OkkevXmahIN0CS6vjqeRM+CVHjduivbdFdWUs++bmTYNS4kUxslLi/2aoWMJqErwVLp5HObTcJemFeQ",
	"syIU3boxxXfjhSazmbh8xXEM/n29tUqrq6eUMo+41rUpibBF5qGwsHsvha92gsZ6YpBhkkaHkQSc/X2W",
	"kvlCxjIdERY5c50+p77UJehYbVSWoivAWTSICq6auq1da90yOr6rd3HzNNTsmRWONrpa37wDxeWM9URf",
	"94bMxqTOUgCpWRMkc+fnMaZMuQDC0R3jt4oUhElVkJIYqIDKqxUd5TheADoY7bUmc3d3N8K6eMT4fGzb",
	"ivHr0+MXby9fDA9Ge6OFzFKzYFKbYRpIOjo/jQbR0ilz0XIfp/kC79sr+xTnJDqMno/2RvvWZKUJTnG6",
	"8XJ/7D+DbeLknczWthoWfLrfeCtxz+eTS3Z+mpSNO1tG5UPQPzLzgooXYez5hcf/thLU0OnOD5kbkq3o",
	"WvICjG02Z2opVMcHe/uPBUgI0Ylayq/39h4MhvKuWGvAH3GCSnjUoPuPMOg1xYVcaFO/nerzRxj1JeNT",
	"kiRAzZDfP8KQNqsmo7OUGAn/zaNM9dIwumtaanfGXIvn2njVyQKiG1VtM6cY/6443b2O9QUZMnDjpHyR",
	"3YRYd26DNsN4BXIdt6iiDbWRaL3TZzPDUsfQuTl/EdWDDYS2rLx8LchnFwNvgZq2woKSDwWcGtOJ5i3G",
	"QFTjLnt/DHc5+/lPtse/foQh3zL5khU0+e+2u61eY7fy2D1l1LmnX4G0ocj26aTEvY3YJfhfgXTvLNn3",
	"FbfcvPb1RbNB64OLpsH0YfbvffsGbJnqUGc2QY0nn8phdWxzNa6ufNF4HmrduJ+TSVjsd3KEA7NRmnSN",
	"vHC6P4ppPNIORuUWfhzFoFIJvI1rNtTaXVqZU3Is43CEmos+825bnmzaqrpZ7ZrrblvVF6oawofaljfb",
	"nBKGeui/brdYtUiIXmeEx9ugX84C/xF6AvpjFAXUpSmUDGcQ5UVA5F/bfGvbcpMLE0TzwPykypX26Axl",
	"t538hX/8GVSGDQK8StPQ38xGUSj71nr7Wjul1+ch8PY4j2xP6wDgix3tP9iO9odZ0DpFZ2tbb9r1m0xm",
	"6ni95cZ/BTK067eSs93jPahd7POeb3uxhC/Grz+HUhvcmTqkVUe16D1hfHJjc9/PtGunPLdbTb/R3lBH",
	"dUyA3QlW6LcNR/Ueujea31kb+Pub+/8XAAD//2cZAf91pgAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
