// Code generated by oapi-codegen; DO NOT EDIT.

package v1alpha1

import (
	"bytes"
	"context"
	"encoding"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"reflect"
	"sort"
	"strconv"
	"strings"
	"time"

	apiv1alpha1 "github.com/flightctl/flightctl/api/core/v1alpha1"
	"github.com/google/uuid"
)

type createCatalogJSONRequestBody = apiv1alpha1.Catalog

type createCatalogItemJSONRequestBody = apiv1alpha1.CatalogItem

type patchCatalogItemApplicationJsonPatchJsonRequestBody = any

type replaceCatalogItemJSONRequestBody = apiv1alpha1.CatalogItem

type patchCatalogApplicationJsonPatchJsonRequestBody = any

type replaceCatalogJSONRequestBody = apiv1alpha1.Catalog

type patchCatalogStatusApplicationJsonPatchJsonRequestBody = any

type replaceCatalogStatusJSONRequestBody = apiv1alpha1.Catalog

// RequestEditorFn is the function signature for the RequestEditor callback function.
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// HttpRequestDoer performs HTTP requests.
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the OpenAPI spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction.
type ClientOption func(*Client) error

// NewClient creates a new Client with reasonable defaults.
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	client := Client{
		Server: server,
	}
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// Ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// Create httpClient if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientInterface is the interface specification for the client.
type ClientInterface interface {
	// ListAllCatalogItems makes a GET request to /catalogitems
	ListAllCatalogItems(ctx context.Context, params *ListAllCatalogItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListCatalogs makes a GET request to /catalogs
	ListCatalogs(ctx context.Context, params *ListCatalogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreateCatalogWithBody makes a POST request to /catalogs
	CreateCatalogWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateCatalog(ctx context.Context, body createCatalogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ListCatalogItems makes a GET request to /catalogs/{catalog}/items
	ListCatalogItems(ctx context.Context, catalog string, params *ListCatalogItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error)
	// CreateCatalogItemWithBody makes a POST request to /catalogs/{catalog}/items
	CreateCatalogItemWithBody(ctx context.Context, catalog string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	CreateCatalogItem(ctx context.Context, catalog string, body createCatalogItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteCatalogItem makes a DELETE request to /catalogs/{catalog}/items/{name}
	DeleteCatalogItem(ctx context.Context, catalog string, name string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetCatalogItem makes a GET request to /catalogs/{catalog}/items/{name}
	GetCatalogItem(ctx context.Context, catalog string, name string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PatchCatalogItemWithBody makes a PATCH request to /catalogs/{catalog}/items/{name}
	PatchCatalogItemWithBody(ctx context.Context, catalog string, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PatchCatalogItem(ctx context.Context, catalog string, name string, body patchCatalogItemApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ReplaceCatalogItemWithBody makes a PUT request to /catalogs/{catalog}/items/{name}
	ReplaceCatalogItemWithBody(ctx context.Context, catalog string, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	ReplaceCatalogItem(ctx context.Context, catalog string, name string, body replaceCatalogItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// DeleteCatalog makes a DELETE request to /catalogs/{name}
	DeleteCatalog(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetCatalog makes a GET request to /catalogs/{name}
	GetCatalog(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PatchCatalogWithBody makes a PATCH request to /catalogs/{name}
	PatchCatalogWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PatchCatalog(ctx context.Context, name string, body patchCatalogApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ReplaceCatalogWithBody makes a PUT request to /catalogs/{name}
	ReplaceCatalogWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	ReplaceCatalog(ctx context.Context, name string, body replaceCatalogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// GetCatalogStatus makes a GET request to /catalogs/{name}/status
	GetCatalogStatus(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error)
	// PatchCatalogStatusWithBody makes a PATCH request to /catalogs/{name}/status
	PatchCatalogStatusWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	PatchCatalogStatus(ctx context.Context, name string, body patchCatalogStatusApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
	// ReplaceCatalogStatusWithBody makes a PUT request to /catalogs/{name}/status
	ReplaceCatalogStatusWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)
	ReplaceCatalogStatus(ctx context.Context, name string, body replaceCatalogStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListAllCatalogItemsParams defines parameters for ListAllCatalogItems.
type ListAllCatalogItemsParams struct {
	// continue (optional)
	Continue *string `form:"continue" json:"continue"`
	// labelSelector (optional)
	LabelSelector *string `form:"labelSelector" json:"labelSelector"`
	// fieldSelector (optional)
	FieldSelector *string `form:"fieldSelector" json:"fieldSelector"`
	// limit (optional)
	Limit *int32 `form:"limit" json:"limit"`
}

// ListCatalogsParams defines parameters for ListCatalogs.
type ListCatalogsParams struct {
	// continue (optional)
	Continue *string `form:"continue" json:"continue"`
	// labelSelector (optional)
	LabelSelector *string `form:"labelSelector" json:"labelSelector"`
	// fieldSelector (optional)
	FieldSelector *string `form:"fieldSelector" json:"fieldSelector"`
	// limit (optional)
	Limit *int32 `form:"limit" json:"limit"`
}

// ListCatalogItemsParams defines parameters for ListCatalogItems.
type ListCatalogItemsParams struct {
	// continue (optional)
	Continue *string `form:"continue" json:"continue"`
	// labelSelector (optional)
	LabelSelector *string `form:"labelSelector" json:"labelSelector"`
	// limit (optional)
	Limit *int32 `form:"limit" json:"limit"`
}

// ListAllCatalogItems makes a GET request to /catalogitems

func (c *Client) ListAllCatalogItems(ctx context.Context, params *ListAllCatalogItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListAllCatalogItemsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListCatalogs makes a GET request to /catalogs

func (c *Client) ListCatalogs(ctx context.Context, params *ListCatalogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCatalogsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCatalogWithBody makes a POST request to /catalogs

func (c *Client) CreateCatalogWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCatalogRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCatalog makes a POST request to /catalogs with application/json body
func (c *Client) CreateCatalog(ctx context.Context, body createCatalogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCatalogRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListCatalogItems makes a GET request to /catalogs/{catalog}/items

func (c *Client) ListCatalogItems(ctx context.Context, catalog string, params *ListCatalogItemsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListCatalogItemsRequest(c.Server, catalog, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCatalogItemWithBody makes a POST request to /catalogs/{catalog}/items

func (c *Client) CreateCatalogItemWithBody(ctx context.Context, catalog string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCatalogItemRequestWithBody(c.Server, catalog, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateCatalogItem makes a POST request to /catalogs/{catalog}/items with application/json body
func (c *Client) CreateCatalogItem(ctx context.Context, catalog string, body createCatalogItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateCatalogItemRequest(c.Server, catalog, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteCatalogItem makes a DELETE request to /catalogs/{catalog}/items/{name}

func (c *Client) DeleteCatalogItem(ctx context.Context, catalog string, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCatalogItemRequest(c.Server, catalog, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCatalogItem makes a GET request to /catalogs/{catalog}/items/{name}

func (c *Client) GetCatalogItem(ctx context.Context, catalog string, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCatalogItemRequest(c.Server, catalog, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchCatalogItemWithBody makes a PATCH request to /catalogs/{catalog}/items/{name}

func (c *Client) PatchCatalogItemWithBody(ctx context.Context, catalog string, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCatalogItemRequestWithBody(c.Server, catalog, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchCatalogItem makes a PATCH request to /catalogs/{catalog}/items/{name} with application/json-patch+json body
func (c *Client) PatchCatalogItem(ctx context.Context, catalog string, name string, body patchCatalogItemApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCatalogItemRequest(c.Server, catalog, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceCatalogItemWithBody makes a PUT request to /catalogs/{catalog}/items/{name}

func (c *Client) ReplaceCatalogItemWithBody(ctx context.Context, catalog string, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceCatalogItemRequestWithBody(c.Server, catalog, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceCatalogItem makes a PUT request to /catalogs/{catalog}/items/{name} with application/json body
func (c *Client) ReplaceCatalogItem(ctx context.Context, catalog string, name string, body replaceCatalogItemJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceCatalogItemRequest(c.Server, catalog, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// DeleteCatalog makes a DELETE request to /catalogs/{name}

func (c *Client) DeleteCatalog(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteCatalogRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCatalog makes a GET request to /catalogs/{name}

func (c *Client) GetCatalog(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCatalogRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchCatalogWithBody makes a PATCH request to /catalogs/{name}

func (c *Client) PatchCatalogWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCatalogRequestWithBody(c.Server, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchCatalog makes a PATCH request to /catalogs/{name} with application/json-patch+json body
func (c *Client) PatchCatalog(ctx context.Context, name string, body patchCatalogApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCatalogRequest(c.Server, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceCatalogWithBody makes a PUT request to /catalogs/{name}

func (c *Client) ReplaceCatalogWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceCatalogRequestWithBody(c.Server, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceCatalog makes a PUT request to /catalogs/{name} with application/json body
func (c *Client) ReplaceCatalog(ctx context.Context, name string, body replaceCatalogJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceCatalogRequest(c.Server, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetCatalogStatus makes a GET request to /catalogs/{name}/status

func (c *Client) GetCatalogStatus(ctx context.Context, name string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCatalogStatusRequest(c.Server, name)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchCatalogStatusWithBody makes a PATCH request to /catalogs/{name}/status

func (c *Client) PatchCatalogStatusWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCatalogStatusRequestWithBody(c.Server, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// PatchCatalogStatus makes a PATCH request to /catalogs/{name}/status with application/json-patch+json body
func (c *Client) PatchCatalogStatus(ctx context.Context, name string, body patchCatalogStatusApplicationJsonPatchJsonRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchCatalogStatusRequest(c.Server, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceCatalogStatusWithBody makes a PUT request to /catalogs/{name}/status

func (c *Client) ReplaceCatalogStatusWithBody(ctx context.Context, name string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceCatalogStatusRequestWithBody(c.Server, name, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ReplaceCatalogStatus makes a PUT request to /catalogs/{name}/status with application/json body
func (c *Client) ReplaceCatalogStatus(ctx context.Context, name string, body replaceCatalogStatusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewReplaceCatalogStatusRequest(c.Server, name, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListAllCatalogItemsRequest creates a GET request for /catalogitems
func NewListAllCatalogItemsRequest(server string, params *ListAllCatalogItemsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogitems")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Continue != nil {
			if queryFrag, err := StyleParameter("continue", *params.Continue, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.LabelSelector != nil {
			if queryFrag, err := StyleParameter("labelSelector", *params.LabelSelector, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.FieldSelector != nil {
			if queryFrag, err := StyleParameter("fieldSelector", *params.FieldSelector, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Limit != nil {
			if queryFrag, err := StyleParameter("limit", *params.Limit, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListCatalogsRequest creates a GET request for /catalogs
func NewListCatalogsRequest(server string, params *ListCatalogsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Continue != nil {
			if queryFrag, err := StyleParameter("continue", *params.Continue, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.LabelSelector != nil {
			if queryFrag, err := StyleParameter("labelSelector", *params.LabelSelector, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.FieldSelector != nil {
			if queryFrag, err := StyleParameter("fieldSelector", *params.FieldSelector, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Limit != nil {
			if queryFrag, err := StyleParameter("limit", *params.Limit, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCatalogRequest creates a POST request for /catalogs with application/json body
func NewCreateCatalogRequest(server string, body createCatalogJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCatalogRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateCatalogRequestWithBody creates a POST request for /catalogs with any body
func NewCreateCatalogRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewListCatalogItemsRequest creates a GET request for /catalogs/{catalog}/items
func NewListCatalogItemsRequest(server string, catalog string, params *ListCatalogItemsParams) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("catalog", catalog, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/items", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := reqURL.Query()
		if params.Continue != nil {
			if queryFrag, err := StyleParameter("continue", *params.Continue, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.LabelSelector != nil {
			if queryFrag, err := StyleParameter("labelSelector", *params.LabelSelector, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "string", Format: "", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		if params.Limit != nil {
			if queryFrag, err := StyleParameter("limit", *params.Limit, ParameterOptions{Style: "form", ParamLocation: ParamLocationQuery, Explode: true, Required: false, Type: "integer", Format: "int32", AllowReserved: false}); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}
		}
		reqURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateCatalogItemRequest creates a POST request for /catalogs/{catalog}/items with application/json body
func NewCreateCatalogItemRequest(server string, catalog string, body createCatalogItemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateCatalogItemRequestWithBody(server, catalog, "application/json", bodyReader)
}

// NewCreateCatalogItemRequestWithBody creates a POST request for /catalogs/{catalog}/items with any body
func NewCreateCatalogItemRequestWithBody(server string, catalog string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("catalog", catalog, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/items", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCatalogItemRequest creates a DELETE request for /catalogs/{catalog}/items/{name}
func NewDeleteCatalogItemRequest(server string, catalog string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("catalog", catalog, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/items/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCatalogItemRequest creates a GET request for /catalogs/{catalog}/items/{name}
func NewGetCatalogItemRequest(server string, catalog string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("catalog", catalog, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/items/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchCatalogItemRequest creates a PATCH request for /catalogs/{catalog}/items/{name} with application/json-patch+json body
func NewPatchCatalogItemRequest(server string, catalog string, name string, body patchCatalogItemApplicationJsonPatchJsonRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchCatalogItemRequestWithBody(server, catalog, name, "application/json-patch+json", bodyReader)
}

// NewPatchCatalogItemRequestWithBody creates a PATCH request for /catalogs/{catalog}/items/{name} with any body
func NewPatchCatalogItemRequestWithBody(server string, catalog string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("catalog", catalog, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/items/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplaceCatalogItemRequest creates a PUT request for /catalogs/{catalog}/items/{name} with application/json body
func NewReplaceCatalogItemRequest(server string, catalog string, name string, body replaceCatalogItemJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceCatalogItemRequestWithBody(server, catalog, name, "application/json", bodyReader)
}

// NewReplaceCatalogItemRequestWithBody creates a PUT request for /catalogs/{catalog}/items/{name} with any body
func NewReplaceCatalogItemRequestWithBody(server string, catalog string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("catalog", catalog, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	var pathParam1 string
	pathParam1, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/items/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteCatalogRequest creates a DELETE request for /catalogs/{name}
func NewDeleteCatalogRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetCatalogRequest creates a GET request for /catalogs/{name}
func NewGetCatalogRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchCatalogRequest creates a PATCH request for /catalogs/{name} with application/json-patch+json body
func NewPatchCatalogRequest(server string, name string, body patchCatalogApplicationJsonPatchJsonRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchCatalogRequestWithBody(server, name, "application/json-patch+json", bodyReader)
}

// NewPatchCatalogRequestWithBody creates a PATCH request for /catalogs/{name} with any body
func NewPatchCatalogRequestWithBody(server string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplaceCatalogRequest creates a PUT request for /catalogs/{name} with application/json body
func NewReplaceCatalogRequest(server string, name string, body replaceCatalogJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceCatalogRequestWithBody(server, name, "application/json", bodyReader)
}

// NewReplaceCatalogRequestWithBody creates a PUT request for /catalogs/{name} with any body
func NewReplaceCatalogRequestWithBody(server string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewGetCatalogStatusRequest creates a GET request for /catalogs/{name}/status
func NewGetCatalogStatusRequest(server string, name string) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", reqURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchCatalogStatusRequest creates a PATCH request for /catalogs/{name}/status with application/json-patch+json body
func NewPatchCatalogStatusRequest(server string, name string, body patchCatalogStatusApplicationJsonPatchJsonRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchCatalogStatusRequestWithBody(server, name, "application/json-patch+json", bodyReader)
}

// NewPatchCatalogStatusRequestWithBody creates a PATCH request for /catalogs/{name}/status with any body
func NewPatchCatalogStatusRequestWithBody(server string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewReplaceCatalogStatusRequest creates a PUT request for /catalogs/{name}/status with application/json body
func NewReplaceCatalogStatusRequest(server string, name string, body replaceCatalogStatusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewReplaceCatalogStatusRequestWithBody(server, name, "application/json", bodyReader)
}

// NewReplaceCatalogStatusRequestWithBody creates a PUT request for /catalogs/{name}/status with any body
func NewReplaceCatalogStatusRequestWithBody(server string, name string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string
	pathParam0, err = StyleParameter("name", name, ParameterOptions{Style: "simple", ParamLocation: ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", AllowReserved: false})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/catalogs/%s/status", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	reqURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", reqURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

const DateFormat = "2006-01-02"

type Date struct {
	time.Time
}

func (d Date) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.Format(DateFormat))
}

func (d *Date) UnmarshalJSON(data []byte) error {
	var dateStr string
	err := json.Unmarshal(data, &dateStr)
	if err != nil {
		return err
	}
	parsed, err := time.Parse(DateFormat, dateStr)
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

func (d Date) String() string {
	return d.Format(DateFormat)
}

func (d *Date) UnmarshalText(data []byte) error {
	parsed, err := time.Parse(DateFormat, string(data))
	if err != nil {
		return err
	}
	d.Time = parsed
	return nil
}

// MarshalText implements encoding.TextMarshaler for Date.
func (d Date) MarshalText() ([]byte, error) {
	return []byte(d.Format(DateFormat)), nil
}

// Format returns the date formatted according to layout.
func (d Date) Format(layout string) string {
	return d.Time.Format(layout)
}

type UUID = uuid.UUID

// ---------------------------------------------------------------------------
// Deep object internals
// ---------------------------------------------------------------------------

// ---------------------------------------------------------------------------
// Exploded object binding
// ---------------------------------------------------------------------------

// ParamLocation indicates where a parameter is located in an HTTP request.
type ParamLocation int

const (
	ParamLocationUndefined ParamLocation = iota
	ParamLocationQuery
	ParamLocationPath
	ParamLocationHeader
	ParamLocationCookie
)

// primitiveToString converts a primitive value to a string representation.
// It handles basic Go types, time.Time, Date, and types that implement
// json.Marshaler or fmt.Stringer.
func primitiveToString(value any) (string, error) {
	// Check for known types first (time, date, uuid)
	if res, ok := marshalKnownTypes(value); ok {
		return res, nil
	}

	// Dereference pointers for optional values
	v := reflect.Indirect(reflect.ValueOf(value))
	t := v.Type()
	kind := t.Kind()

	switch kind {
	case reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64, reflect.Int:
		return strconv.FormatInt(v.Int(), 10), nil
	case reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uint:
		return strconv.FormatUint(v.Uint(), 10), nil
	case reflect.Float64:
		return strconv.FormatFloat(v.Float(), 'f', -1, 64), nil
	case reflect.Float32:
		return strconv.FormatFloat(v.Float(), 'f', -1, 32), nil
	case reflect.Bool:
		if v.Bool() {
			return "true", nil
		}
		return "false", nil
	case reflect.String:
		return v.String(), nil
	case reflect.Struct:
		// Check if it's a UUID
		if u, ok := value.(uuid.UUID); ok {
			return u.String(), nil
		}
		// Check if it implements json.Marshaler
		if m, ok := value.(json.Marshaler); ok {
			buf, err := m.MarshalJSON()
			if err != nil {
				return "", fmt.Errorf("failed to marshal to JSON: %w", err)
			}
			e := json.NewDecoder(bytes.NewReader(buf))
			e.UseNumber()
			var i2 any
			if err = e.Decode(&i2); err != nil {
				return "", fmt.Errorf("failed to decode JSON: %w", err)
			}
			return primitiveToString(i2)
		}
		fallthrough
	default:
		if s, ok := value.(fmt.Stringer); ok {
			return s.String(), nil
		}
		return "", fmt.Errorf("unsupported type %s", reflect.TypeOf(value).String())
	}
}

// marshalKnownTypes checks for special types (time.Time, Date, UUID) and marshals them.
func marshalKnownTypes(value any) (string, bool) {
	v := reflect.Indirect(reflect.ValueOf(value))
	t := v.Type()

	if t.ConvertibleTo(reflect.TypeOf(time.Time{})) {
		tt := v.Convert(reflect.TypeOf(time.Time{}))
		timeVal := tt.Interface().(time.Time)
		return timeVal.Format(time.RFC3339Nano), true
	}

	if t.ConvertibleTo(reflect.TypeOf(Date{})) {
		d := v.Convert(reflect.TypeOf(Date{}))
		dateVal := d.Interface().(Date)
		return dateVal.Format(DateFormat), true
	}

	if t.ConvertibleTo(reflect.TypeOf(uuid.UUID{})) {
		u := v.Convert(reflect.TypeOf(uuid.UUID{}))
		uuidVal := u.Interface().(uuid.UUID)
		return uuidVal.String(), true
	}

	return "", false
}

// escapeParameterName escapes a parameter name for use in query strings and
// paths. This ensures characters like [] in parameter names (e.g. user_ids[])
// are properly percent-encoded per RFC 3986.
func escapeParameterName(name string, paramLocation ParamLocation) string {
	// Parameter names should always be encoded regardless of allowReserved,
	// which only applies to values per the OpenAPI spec.
	return escapeParameterString(name, paramLocation, false)
}

// escapeParameterString escapes a parameter value based on its location.
// Query and path parameters need URL escaping; headers and cookies do not.
// When allowReserved is true and the location is query, RFC 3986 reserved
// characters are left unencoded per the OpenAPI allowReserved specification.
func escapeParameterString(value string, paramLocation ParamLocation, allowReserved bool) string {
	switch paramLocation {
	case ParamLocationQuery:
		if allowReserved {
			return escapeQueryAllowReserved(value)
		}
		return url.QueryEscape(value)
	case ParamLocationPath:
		return url.PathEscape(value)
	default:
		return value
	}
}

// escapeQueryAllowReserved percent-encodes a query parameter value while
// leaving RFC 3986 reserved characters (:/?#[]@!$&'()*+,;=) unencoded, as
// specified by OpenAPI's allowReserved parameter option.
func escapeQueryAllowReserved(value string) string {
	const reserved = `:/?#[]@!$&'()*+,;=`

	var buf strings.Builder
	for _, b := range []byte(value) {
		if isUnreserved(b) || strings.IndexByte(reserved, b) >= 0 {
			buf.WriteByte(b)
		} else {
			fmt.Fprintf(&buf, "%%%02X", b)
		}
	}
	return buf.String()
}

// isUnreserved reports whether the byte is an RFC 3986 unreserved character:
// ALPHA / DIGIT / "-" / "." / "_" / "~"
func isUnreserved(c byte) bool {
	return (c >= 'A' && c <= 'Z') ||
		(c >= 'a' && c <= 'z') ||
		(c >= '0' && c <= '9') ||
		c == '-' || c == '.' || c == '_' || c == '~'
}

// sortedKeys returns the keys of a map in sorted order.
func sortedKeys(m map[string]string) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	return keys
}

// isByteSlice reports whether t is []byte (or equivalently []uint8).
func isByteSlice(t reflect.Type) bool {
	return t.Kind() == reflect.Slice && t.Elem().Kind() == reflect.Uint8
}

// ParameterOptions carries OpenAPI parameter metadata to bind and style
// functions so they can handle style dispatch, explode, required,
// type-aware coercions, and location-aware escaping from a single
// uniform call site. All fields have sensible zero-value defaults.
type ParameterOptions struct {
	Style         string        // OpenAPI style: "simple", "form", "label", "matrix", "deepObject", "pipeDelimited", "spaceDelimited"
	ParamLocation ParamLocation // Where the parameter appears: query, path, header, cookie
	Explode       bool
	Required      bool
	Type          string // OpenAPI type: "string", "integer", "array", "object"
	Format        string // OpenAPI format: "int32", "date-time", etc.
	AllowReserved bool   // When true, reserved characters in query values are not percent-encoded
}

// StyleParameter serializes a Go value into an OpenAPI-styled parameter string.
// This is the entry point for client-side parameter serialization. The Style
// field in opts selects the serialization format. If Style is empty, "simple"
// is assumed.
func StyleParameter(paramName string, value any, opts ParameterOptions) (string, error) {
	style := opts.Style
	if style == "" {
		style = "simple"
	}

	t := reflect.TypeOf(value)
	v := reflect.ValueOf(value)

	// Dereference pointers; error on nil.
	if t.Kind() == reflect.Ptr {
		if v.IsNil() {
			return "", fmt.Errorf("value is a nil pointer")
		}
		v = reflect.Indirect(v)
		t = v.Type()
	}

	// If the value implements encoding.TextMarshaler, use it — but not for
	// time.Time or Date which have their own formatting logic.
	if tu, ok := value.(encoding.TextMarshaler); ok {
		it := reflect.Indirect(reflect.ValueOf(value)).Type()
		if !it.ConvertibleTo(reflect.TypeOf(time.Time{})) && !it.ConvertibleTo(reflect.TypeOf(Date{})) {
			b, err := tu.MarshalText()
			if err != nil {
				return "", fmt.Errorf("error marshaling '%s' as text: %w", value, err)
			}
			return stylePrimitive(style, opts.Explode, paramName, opts.ParamLocation, opts.AllowReserved, string(b))
		}
	}

	switch t.Kind() {
	case reflect.Slice:
		if opts.Format == "byte" && isByteSlice(t) {
			encoded := base64.StdEncoding.EncodeToString(v.Bytes())
			return stylePrimitive(style, opts.Explode, paramName, opts.ParamLocation, opts.AllowReserved, encoded)
		}
		n := v.Len()
		sliceVal := make([]any, n)
		for i := 0; i < n; i++ {
			sliceVal[i] = v.Index(i).Interface()
		}
		return styleSlice(style, opts.Explode, paramName, opts.ParamLocation, opts.AllowReserved, sliceVal)
	case reflect.Struct:
		return styleStruct(style, opts.Explode, paramName, opts.ParamLocation, opts.AllowReserved, value)
	case reflect.Map:
		return styleMap(style, opts.Explode, paramName, opts.ParamLocation, opts.AllowReserved, value)
	default:
		return stylePrimitive(style, opts.Explode, paramName, opts.ParamLocation, opts.AllowReserved, value)
	}
}

// ---------------------------------------------------------------------------
// Internal style helpers
// ---------------------------------------------------------------------------

func styleSlice(style string, explode bool, paramName string, paramLocation ParamLocation, allowReserved bool, values []any) (string, error) {
	if style == "deepObject" {
		if !explode {
			return "", errors.New("deepObjects must be exploded")
		}
		return MarshalDeepObject(values, paramName)
	}

	var prefix string
	var separator string

	escapedName := escapeParameterName(paramName, paramLocation)

	switch style {
	case "simple":
		separator = ","
	case "label":
		prefix = "."
		if explode {
			separator = "."
		} else {
			separator = ","
		}
	case "matrix":
		prefix = fmt.Sprintf(";%s=", escapedName)
		if explode {
			separator = prefix
		} else {
			separator = ","
		}
	case "form":
		prefix = fmt.Sprintf("%s=", escapedName)
		if explode {
			separator = "&" + prefix
		} else {
			separator = ","
		}
	case "spaceDelimited":
		prefix = fmt.Sprintf("%s=", escapedName)
		if explode {
			separator = "&" + prefix
		} else {
			separator = " "
		}
	case "pipeDelimited":
		prefix = fmt.Sprintf("%s=", escapedName)
		if explode {
			separator = "&" + prefix
		} else {
			separator = "|"
		}
	default:
		return "", fmt.Errorf("unsupported style '%s'", style)
	}

	parts := make([]string, len(values))
	for i, v := range values {
		part, err := primitiveToString(v)
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		parts[i] = escapeParameterString(part, paramLocation, allowReserved)
	}
	return prefix + strings.Join(parts, separator), nil
}

func styleStruct(style string, explode bool, paramName string, paramLocation ParamLocation, allowReserved bool, value any) (string, error) {
	if timeVal, ok := marshalKnownTypes(value); ok {
		return stylePrimitive(style, explode, paramName, paramLocation, allowReserved, timeVal)
	}

	if style == "deepObject" {
		if !explode {
			return "", errors.New("deepObjects must be exploded")
		}
		return MarshalDeepObject(value, paramName)
	}

	// If input implements json.Marshaler (e.g. objects with additional properties
	// or anyOf), marshal to JSON and re-style the generic structure.
	if m, ok := value.(json.Marshaler); ok {
		buf, err := m.MarshalJSON()
		if err != nil {
			return "", fmt.Errorf("failed to marshal input to JSON: %w", err)
		}
		e := json.NewDecoder(bytes.NewReader(buf))
		e.UseNumber()
		var i2 any
		err = e.Decode(&i2)
		if err != nil {
			return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
		}
		return StyleParameter(paramName, i2, ParameterOptions{
			Style:         style,
			ParamLocation: paramLocation,
			Explode:       explode,
			AllowReserved: allowReserved,
		})
	}

	// Build a dictionary of the struct's fields.
	v := reflect.ValueOf(value)
	t := reflect.TypeOf(value)
	fieldDict := make(map[string]string)

	for i := 0; i < t.NumField(); i++ {
		fieldT := t.Field(i)
		tag := fieldT.Tag.Get("json")
		fieldName := fieldT.Name
		if tag != "" {
			tagParts := strings.Split(tag, ",")
			if tagParts[0] != "" {
				fieldName = tagParts[0]
			}
		}
		f := v.Field(i)

		// Skip nil optional fields.
		if f.Type().Kind() == reflect.Ptr && f.IsNil() {
			continue
		}
		str, err := primitiveToString(f.Interface())
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName] = str
	}

	return processFieldDict(style, explode, paramName, paramLocation, allowReserved, fieldDict)
}

func styleMap(style string, explode bool, paramName string, paramLocation ParamLocation, allowReserved bool, value any) (string, error) {
	if style == "deepObject" {
		if !explode {
			return "", errors.New("deepObjects must be exploded")
		}
		return MarshalDeepObject(value, paramName)
	}
	v := reflect.ValueOf(value)

	fieldDict := make(map[string]string)
	for _, fieldName := range v.MapKeys() {
		str, err := primitiveToString(v.MapIndex(fieldName).Interface())
		if err != nil {
			return "", fmt.Errorf("error formatting '%s': %w", paramName, err)
		}
		fieldDict[fieldName.String()] = str
	}
	return processFieldDict(style, explode, paramName, paramLocation, allowReserved, fieldDict)
}

func processFieldDict(style string, explode bool, paramName string, paramLocation ParamLocation, allowReserved bool, fieldDict map[string]string) (string, error) {
	var parts []string

	if style != "deepObject" {
		if explode {
			for _, k := range sortedKeys(fieldDict) {
				v := escapeParameterString(fieldDict[k], paramLocation, allowReserved)
				parts = append(parts, k+"="+v)
			}
		} else {
			for _, k := range sortedKeys(fieldDict) {
				v := escapeParameterString(fieldDict[k], paramLocation, allowReserved)
				parts = append(parts, k)
				parts = append(parts, v)
			}
		}
	}

	escapedName := escapeParameterName(paramName, paramLocation)

	var prefix string
	var separator string

	switch style {
	case "simple":
		separator = ","
	case "label":
		prefix = "."
		if explode {
			separator = prefix
		} else {
			separator = ","
		}
	case "matrix":
		if explode {
			separator = ";"
			prefix = ";"
		} else {
			separator = ","
			prefix = fmt.Sprintf(";%s=", escapedName)
		}
	case "form":
		if explode {
			separator = "&"
		} else {
			prefix = fmt.Sprintf("%s=", escapedName)
			separator = ","
		}
	case "deepObject":
		if !explode {
			return "", fmt.Errorf("deepObject parameters must be exploded")
		}
		for _, k := range sortedKeys(fieldDict) {
			v := fieldDict[k]
			part := fmt.Sprintf("%s[%s]=%s", escapedName, k, v)
			parts = append(parts, part)
		}
		separator = "&"
	default:
		return "", fmt.Errorf("unsupported style '%s'", style)
	}

	return prefix + strings.Join(parts, separator), nil
}

func stylePrimitive(style string, explode bool, paramName string, paramLocation ParamLocation, allowReserved bool, value any) (string, error) {
	strVal, err := primitiveToString(value)
	if err != nil {
		return "", err
	}

	escapedName := escapeParameterName(paramName, paramLocation)

	var prefix string
	switch style {
	case "simple":
	case "label":
		prefix = "."
	case "matrix":
		prefix = fmt.Sprintf(";%s=", escapedName)
	case "form":
		prefix = fmt.Sprintf("%s=", escapedName)
	default:
		return "", fmt.Errorf("unsupported style '%s'", style)
	}
	return prefix + escapeParameterString(strVal, paramLocation, allowReserved), nil
}

// ---------------------------------------------------------------------------
// Deep object marshaling
// ---------------------------------------------------------------------------

// MarshalDeepObject marshals an object to deepObject style query parameters.
func MarshalDeepObject(i any, paramName string) (string, error) {
	buf, err := json.Marshal(i)
	if err != nil {
		return "", fmt.Errorf("failed to marshal input to JSON: %w", err)
	}
	var i2 any
	err = json.Unmarshal(buf, &i2)
	if err != nil {
		return "", fmt.Errorf("failed to unmarshal JSON: %w", err)
	}
	fields, err := marshalDeepObjectRecursive(i2, nil)
	if err != nil {
		return "", fmt.Errorf("error traversing JSON structure: %w", err)
	}

	for idx := range fields {
		fields[idx] = paramName + fields[idx]
	}
	return strings.Join(fields, "&"), nil
}

func marshalDeepObjectRecursive(in any, path []string) ([]string, error) {
	var result []string

	switch t := in.(type) {
	case []any:
		for i, iface := range t {
			newPath := append(path, strconv.Itoa(i))
			fields, err := marshalDeepObjectRecursive(iface, newPath)
			if err != nil {
				return nil, fmt.Errorf("error traversing array: %w", err)
			}
			result = append(result, fields...)
		}
	case map[string]any:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, k := range keys {
			newPath := append(path, k)
			fields, err := marshalDeepObjectRecursive(t[k], newPath)
			if err != nil {
				return nil, fmt.Errorf("error traversing map: %w", err)
			}
			result = append(result, fields...)
		}
	default:
		prefix := "[" + strings.Join(path, "][") + "]"
		result = []string{
			prefix + fmt.Sprintf("=%v", t),
		}
	}
	return result, nil
}
