// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package imagebuilder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8XXPbOJJ/BcW9qk22ZDnJzl3d+ekcJ5l1zWTijT2zD5t5gMiWhA0JMAAoRzPl/37V",
	"DZAESVCinDjJ3ujJFtEEuhv93QB/T1JVlEqCtCY5+z0x6RoKTv8+FzITcnWzLQF/ZmBSLUorlEzOkps1",
	"MLstgaklWzhAtlSa2TUwUfAVsEUl8myezBKQVZGc/TMBrvNtMktybiH5dZZYmjgxVgu5SmbJxxOEPNlw",
	"LXkBBl8JUHjp3w4e/UgT3c2SCyUz4RDr49kMsVRJy4U0LAPLRW4IXSWBcVNCapEQRD6ttAZpmbHcgnso",
	"DDu/umRvwahKp4A0lVqVoK0A4lTOjb3RXBpa6UYUIwxDOGZFAW6lBjXbvAsZW2pVEF6IQWWYVYxLZdeg",
	"ceGl0gW3yVmScQsnOFfS5+TdLCnAGL6KYPG3quCSaeAZX+TAPBxDnqbc4ibW3OELVVmPcYPePLaYWhjQ",
	"G8i+Bwmax7cBqZ8XYHnGLZ+vGkhm19z2uHHLDTNg2YIbyFhVumUbwoW0//Vdi4eQFlagEREN3MQWP2eP",
	"FlrA8jFzEI2gNmv+2Uyi1O0ILvAfGpbJWfKn01Z7Tr3qnDYid+3A7+qZJr5GCndH9HyohIYMNYFmaDCY",
	"xUSuYUC7/62WqcW/ILVJqCzXDTVddrnnjT7U4DMSSrVkN7qCGXvFcwMz9rN8L9WtDPUcx5NZQgDJLPEQ",
	"EzW+h52fq/e0nrr3uFkppHLEfHnT1UqdkOyCF5BfcAMhNedlqdUGsmSW3Fy9/gW0WAr6FQy8AOmeveIi",
	"j4GmKRgjFjn0f9Q25YprQ6DXW5nSP7/wXODftyrPVWUv5ZVWKw0GN//nMiNlRfgS0hr0dZVbUebw5laC",
	"NoTXRqTwAlJVFMIYoSS+NG0jXkqt8rwAad/ChwqMDegdjHXJvUDLuESDAtdihWsOpxiFaXg5CtEweRSi",
	"i85bKJURVultlPXI8dGBwf6Eg81evcoBbL0L9CO2a243gr1zD8IddE+m7uPdLCGv6F3iUMpptHHPqZJL",
	"saq84T1hUCwgMyxtuYhK0DjwoZtDyJ94zLnh09pgQCMcnam1Zxz6M1q5sxiZ5IzIrPGNWmA7NRgZBh4D",
	"sR8xsQ2VMeP58mOptH1Fvmh/YOR8FlFM7wX0WhViuCmy98ks+ZCq22fJLBFGTdXSHj6/vH7xQzJE8+8X",
	"b/7xLPL88voNidEl4vQcA7YhQe0Y01BqMOi1GHfxHdNO42j/eB1jgR4TIV6KX0CbaIxwfnXpx1gGSyHB",
	"EL827hlkzHnKJiZrsHECrZaMS+a2as6uMSTRhpm1qvIMEduAtkxDqlZS/NbMRvGVpdjMIh0YTmjJc7bh",
	"Obo5LjNW8C3TgPOySgYzEIiZs9dKo+os1RlbW1uas9PTlbDz9/9t5kKhqy8qKez2FLmjxaKySpvTDDaQ",
	"nxqxOuE6XQsLqa00nPJSnBCyEoky8yL7U605JqoR74WMbNoPQmZM4DY5SIdryzJ8hFS/fXl9E6gmstVx",
	"MNjrlpnICCGXoB0kRapO5bNSCekDuVxQ/FwtCmFNLSDI5zm74FIqyxbAKjSDkM3ZZeh3H5qVyD1zgiyL",
	"M7OOUPfFam+IR6/BcgoLS0j3vdFqEdr76cFk8J6PJntWK9AoLwwBGR63mCVrJx51HwMQhrOhWzUjTqUO",
	"rJvcLxM4YSEkt0rjCgUvS7+YM8sjdHccm88ZR0AxDawh7xqDs3WeyhGOWYqEN8vk7J+72d1Z9m62G7iz",
	"cNeMvgBjkeiooYuCBbxFDmbBSMhVO2ZZ6XHcO6NLkoGHVpUtq2CigRroJmLaP1kbXbV2BIfQBb65uETz",
	"WlZm3SfAO8Chg+erEZ/KVxPx7ylIQMws4JJbardm/CiM3bV9OO6sbI7/qSXrOMvAbB+94MN6QWGhiKSy",
	"P+7Zlua1aSa4jUATrjXfHv3vV/K/uK/O+x7mDd1+71b6qzU3I0a0xKHaCgVVTlZqhQlkGNJ/qKCi5JAg",
	"nBdDQ+j+Q5pysGiGli6dnRbv99D8e71I7/nzds3eyFWDQm/gosWoN+Lz7a6DewvLaxLaXfaxAQqcG2de",
	"2H3ehzLMZUxDR3xcPfN+1xSZE+1cZYBxw9pF7pFlti/X+93iNjnT7JKzWyr3M3vAaWRBl9f96OzeEUQ4",
	"bdwe48jNBF++d6bPGYv49LQ2vnvWnhpHNLTu2UGfJYzuXwkpc4OLevfcXqZtGMhlv7vS3cNFG8tPc2lB",
	"4Jx1Y9Zp74eBLiY1jZhOTGocfJ/XfpouTrOGuj2MHqlr9yHCcka/8+Pq3x27FAnjAm8XF84QohbSXhQ/",
	"EPjaNWTndkR76gaS8z0N/PT2UFP1jnDpwnOhhRma08mhU9uYi0ROoLXLCXtFS3zcdqaWAanOVY4bnLew",
	"BA0yHdmNZZXnXn10DRnZFfYI5qv5jH2o+BajHqVXpzSApubM8tXjKAY5N/YaQE5p/TlyXKMLJHu0Bq7t",
	"Arh9fECPj0uxBGNfiBWYEVHJaCxGY/12lJSyDoGmKbGLmFxJQ08XXA89leK7MaV3Rc0RfXeDncqlrKux",
	"de3SqiYzwkSH0lXiEqVFmViSrFhfzj3mc8eq5rGqGdgAp2L3KGv6Fx+grulm3l+EG8BNqMI54wGZNxGf",
	"FEeH8z9cCByW4HrYH1yGW2AGjPF7zY4BCeahSnJh82rnfjqQTs65txPX3cJls8jOYnG/GegYd10tl+Lj",
	"EMM39A/PmSEAOthTliCz2lj7umbLXWE84vtZ6jGexLwpFQ7OjJCrHGrOOVdj/MmYQZHDe6LPWuYYoNyt",
	"dgyGL0Ic4iC96kdkim4RZADQr4WEADvzjiFgP/0I0o4e753IRvrxEzOFRoyCXbxP2jA9YI+uuCN6v7++",
	"HR4Fdy1gEwhPULlDAuOhvk2Oj6PMOzxYPtw67Gh3tACRfkcTYx8bHt9UwyO2L9M7Hj6tOrY8/l+3PNwu",
	"74gI1AY0z/NY78OHUruaH7dc2DoUeKgIYTQ2oIF/NBj0R8bihfFIYUeMsCM62Fm6D0Gm1O7bWGDX0Yqg",
	"GbG3etN2coZVtB3vNlB1CfcTT17EENp3ACOOSJT9NxNbOr1LDC27I32eAb8OFt0Wt8tw2nGIYK0elePd",
	"hRZgenthLOQ8tEcwTMSbaM+MFEq9B/NAO1K2Q12ZzxzR5gp56V5+OvRuB7QwOvo9sYdRE7/HIk9IJg7t",
	"Yrz8xDSiMfhftuPQov1lWw6e2L1ZS4SiK9AnPoSvL/Fonr73x5LvJ7f9yyQtUYc0HjxRn9Z5kPDRvgWr",
	"t2MCgwB+TcU0QoaLP3JnvXO+hebkhJCrAxA4NA07uEHhMf1cHYq+i4prdQ9q35kJ1lbR/ii9/MP6959w",
	"jmOHSx85y3G/0wHhCdJhLsctjF7eCO5KGMYtWwptLFsoFTHw97o0Eb+lGaU+SlmdrkRTVBwJgpE6XXG3",
	"Ac1W2jVYkbaZKysqY9mab2DGhEzziniCoYKhVH3DtVCVaZweoWHm7LyVHUwkcQKmZL6tr7L93rY8ZqxG",
	"7C7mIjF/rSJcfM23mFsasLXfqAxo+s1ZLgphmXL3XGRVLEDjquQA0C5WWkLmig3+BiZFZv5GJN2q1GzN",
	"DSswRyUO8Q0XOV/kMGe4gS7HxhS65B8qaOoWC8KDKsvCGBqgK6Rhz7OXRiPn6R6ny7QpDvPmW8DG2UUy",
	"7EgbhhU1Ji27LxybcG/oLogRxqJnp7kQLZ+Jl8pdtqpZ5intyjjSna65XEHG0DsjC+yaS8bZEm5ZIWSF",
	"7KI9LbkxmNkjS+odr4tKSwF0AMxxm92uQbLKOBsiDKu31rPyVuQ5oigyzOFTntec8px2e+m0TYMplTQw",
	"Y5XMwRi2VZXDR0MKomGlVe9BNifdIAw2Rsxk4awcBqkXqpJjbraRKFMtDG6stF64PJ7E+Nu1SNeMayD2",
	"O/Wpr1/VG12TMmeXy/bNWljqaz0Zy/kCctwOx1UDOaRWaTPDl/py3tBRI2VY5a5okpw6RuI0NdNzWFpW",
	"SVIemTFVCGshY1lF9SQDWvBc/Ebi0UWU9tEFpewRCJL0BaS8MsAEDSPp6bqSGIQh/vUosUAYXws0Huhx",
	"S48GzzongX2aHCHCfAolda1L5RnVubhkm6fzp//JMkV44yztGk7KhbQgcRurtiozlBuk7C+YfhR05/Av",
	"TtvEb77Fk6oc94+QuKAaWlM5xXU1kKUcm9uq2vJhykw/4CNP7aTb2rFYKeg/D5tnzRjS1HUYVJ5CbTfI",
	"46jTcDrgZd/QG95qkb32sKkGbmO31qRUrtzsfmYuw+D5VcTPBorcywoaYHe9fdvYPtE5h9oyhPDx17uN",
	"5UW5J2z1dVSM7h0pB2RoGeRwn7W8wNPrh6y32vG1gHPmrFnaWJNOFZk3lQsWfEmgbaljcOK+3zBnV6qs",
	"MJTJGn5vjYVizt4Cz04wFpj4cQGyfJ+y/a95SabaFcffw7YOXfKq9vopl6HnVnrFJSorwmFwsFIafz4y",
	"qSrdU2eAHzcuOCZFctqlINdBiX7g4VaCju1SUMXnlqlbaeoWjXuOwRp7R0XpU1zrXbKrudZz3JEFZR3m",
	"eCbSss5Tt1VTMqZ/NkFLxwcCnU7RtOxtzycSqNvhIgsfH2Bqm/I89xuaKflnW0O4ACzYqWOP7GF7ZKnK",
	"IoJ/Xa1WQJ7ibzc3V/XmIGzbAnZ5xIw9wQjVu+C+nfjrs6idODbHPmtzbOQ7NudsXRVcnjRfsgmGm3JE",
	"8B0TypC8pxgxPmPfjil4uhYSRpe6XW97C+BG+wD8HX0SpNJo+hw+PnAVps3doCjt1seaFKoSx1HScLIg",
	"4ztHr2WUZGnOtS8NSSfGnlgS40WFlgdc0Ks2oLXIMA7e802bXV+BaZnH3lDqfMbeJdcVfTbjXYIBYEDp",
	"g4sNuv8TLrMTz9K95x9iPdLmUzpkJiZ9PAfZBWmlhd1eo4n0dy6Aa9DnlV2PliS7L50Gb6B71avLbOqr",
	"DvgOUUH+1sUJnlKOiEF6npwlFnjxv8tcrNY2tflcqKQOA8jvv6IRSte1ytkN8CKZJZXGV+v96rw9CGao",
	"YMmoX0XVDophyX52556/kzdkUD1EwSUdOwwvz7UBO75fX5drjmL76lf4XQkzf4cblYsUpCsEe+LOS56u",
	"gT2bPxnQc3t7O+c0PFd6derfNac/Xl68/On65cmz+ZP52hY51Q2FzXG6Hp+6RJ9fXSazZFO77GTzdAGW",
	"P6UdLUHyUiRnyV/nT+ZP0dVzuyZhQXE+3Tx1FwqIVnq8AjtymGPs6mqjkSg7BNpCGlpR8wIsaEOt12GA",
	"7TJ3V+JBtUltm09T8u4LJnWe5OJnoV0NwB0mwbk+VEBFT78FNHrtZ0c1o1giEh/fzT4rVpQbj2JFo/fD",
	"ChWm4B9FURWd2oapcttW8ToVl6aaMsYjUQjbwWJvYBHhFkbD/kRps9nIOFqsrlY4LJvIwEXHY3g1Zc5d",
	"DPqVInWij0T32ZMntRUCV6niZZn7rvLpv7xXbeebdgiAzqKRmevVAX5ABfvuM67ZnD8frPWcZ8x/Ucot",
	"+vQLLPqz5JVdU6JH982/e/Y/X2DVG6XYay63Nb3uPL7lK9P0RBbubuvdLClV7JzgBVUcdtzl7VosB945",
	"9uBD0+cq2z6ARDmy26jA6gruBrL89MFWjnEr+6MJ85MvIcwXSi5z4TL4b0597maxGOD0dzTBd06r6HTZ",
	"QL9e0PPJ+uXAO/q1MySYcHm+cRsYzbReQ3L/8clQs76+B9nlPb6O7H/3BVb9SVn2SlXyW/Ud0UD3e2qT",
	"TJPr78Eehfoo1N+wRXeHh6akdbED+iN53Us/6TGxOyZ2/66JXXDL6JjZfUOGzBms6aldz2ztzO38LaIH",
	"TO7qe0pfIbsLlz6md3/o9K7RoZFo4PAEb6+WBRleo2WHR8ORZf4twuFx3TvGw1/djezN8vYKd53mHSX7",
	"KNnfkHGnDjAdviApdC3G0wSFwr8x/OqHF2vDlBzt5nlhDPLKYV4QmSmWQIZTecTvfr37vwAAAP//3e6X",
	"yehpAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
