// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package imagebuilder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	externalRef0 "github.com/flightctl/flightctl/api/v1beta1"
	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+w8XXPbNrZ/BcO9M013ZDnJdu/c66frOknX06bxxm77sOkDRB5J2JAAA4By1I7/+51z",
	"AJIgCUqUEyfpVk+2iEPgfOF8Avw9SVVRKgnSmuTs98Skayg4/futkJmQq5ttCfgzA5NqUVqhZHKW3KyB",
	"2W0JTC3ZwgGypdLMroGJgq+ALSqRZ/NkloCsiuTsXwlwnW+TWZJzC8mvs8TSxImxWshVMkvenyDkyYZr",
	"yQsw+EqAwnP/dvDoB5robpZcKJkJh1gfz2aIpUpaLqRhGVguckPoKgmMmxJSi4Qg8mmlNUjLjOUW3ENh",
	"2PnVJXsNRlU6BaSp1KoEbQUQp3Ju7I3m0tBKN6IYYRjCMSsKcCs1qNnmXcjYUquC8EIMKsOsYlwquwaN",
	"Cy+VLrhNzpKMWzjBuZI+J+9mSQHG8FUEi39UBZdMA8/4Igfm4RjyNOUWhVhzhy9UZT3GDXrz2GJqYUBv",
	"IPsOJGgeFwNSPy/A8oxbPl81kMyuue1x45YbZsCyBTeQsap0yzaEC2n/+5sWDyEtrEAjIhq4iS1+zh4t",
	"tIDl18xBNIrarPmVmUSpkwgu8F8alslZ8pfTdvec+q1z2qjctQO/q2ea+BptuDui510lNGS4E2iGBoNZ",
	"TOUaBrTyb3eZWvwbUpuEm+W6oabLLve82Q81+IyUUi3Zja5gxl7w3MCM/STfSnUrw32O48ksIYBklniI",
	"iTu+h52fq/e0nrr3uFkppHLEfHnT1WqdkOyCF5BfcAMhNedlqdUGsmSW3Fy9/Bm0WAr6FQw8A+meveAi",
	"j4GmKRgjFjn0f9Q25YprQ6DXW5nSPz/zXODf1yrPVWUv5ZVWKw0Ghf9TmdFmRfgS0hr0ZZVbUebw6laC",
	"NoTXRqTwDFJVFMIYoSS+NE0Qz6VWeV6AtK/hXQXGBvQOxrrkXqBlXKJBgWuxwjWHU4zCNLwchWiYPArR",
	"Rec1lMoIq/Q2ynrk+OjAQD7hYCOrFzmAraVAP2JSc9IIZOcehBJ0T6bK8W6WkFf0LnGo5TTauOdUyaVY",
	"Vd7wnjAoFpAZlrZcxE3QOPChm0PIH3nMueHT2mBAoxydqbVnHPozWrmzGJnkjMis8Y1aYDs1GBkGHgO1",
	"HzGxDZUx4/n8fam0fUG+aH9g5HwWUUzvBfRaFWK4KbK3ySx5l6rbp8ksEUZN3aU9fH5++ez7ZIjmPy9e",
	"/fI08vzy+hWp0SXi9C0GbEOC2jGmodRg0Gsx7uI7pt2OI/nxOsYCPaZCvBQ/gzbRGOH86tKPsQyWQoIh",
	"fm3cM8iY85RNTNZg4xRaLRmXzIlqzq4xJNGGmbWq8gwR24C2TEOqVlL81sxG8ZWl2MwiHRhOaMlztuE5",
	"ujkuM1bwLdOA87JKBjMQiJmzl0rj1lmqM7a2tjRnp6crYedv/8fMhUJXX1RS2O0pckeLRWWVNqcZbCA/",
	"NWJ1wnW6FhZSW2k45aU4IWQlEmXmRfaXeueY6I54K2REaN8LmTGBYnKQDteWZfgIqX79/Pom2JrIVsfB",
	"QNYtM5ERQi5BO0iKVN2Wz0olpA/kckHxc7UohDW1giCf5+yCS6ksWwCr0AxCNmeXod99aFYi98wJsizO",
	"zDpC3RervSIevQTLKSwsId33RruL0N5PDyaD93w02bNawY7yyhCQ4XGLWbJ24lH3MQBhOBu6VTPiVOrA",
	"usn9MoETFkJyqzSuUPCy9Is5szxCd8ex+ZxxBBTTwBryrjE4W+epHOGYpUh4tUzO/rWb3Z1l72a7gTsL",
	"d83oMzAWiY4auihYwFvkYBaMhFy1Y5aVHse9M7okGXhoVdmyCiYabAPdREz7J2ujq9aO4BC6wFcXl2he",
	"y8qs+wR4Bzh08Hw14lP5aiL+vQ0SEDMLuOSW2r0zfhDG7hIfjjsrm+N/ask6zjIw20cv+LBeUFgoIqns",
	"D3vE0rw2zQS3EWjCtebbo//9TP4X5eq872He0Ml796a/WnMzYkRLHKqtUFDlZKVWmECGIf27CipKDgnC",
	"eTE0hO4/pCkHi2Zo6dLZafF+D81/1ov0nn/brtkbuWpQ6A1ctBj1Rny+3XVwr2F5TUq7yz42QIFz48wr",
	"u8/7UIe5jO3QER9Xz7zfNUXmRDtXGWDcsHaRe2SZ7cu1vFvcJmeaXXJ2a+V+Zg84jSzo8rofnd07ggin",
	"jdtjHLmZ4Mv3zvQxYxGfntbGd8/aU+OIhtY9EvRZwqj8SkiZG1zU0nOyTNswkMt+d6Urw0Uby09zaUHg",
	"nHVj1mnvh4EuJjWNmk5Mahx8n9d+mi5Os4a6PYweqWv3IcJyRr/z4+rfHbsUCeMCbxdXzhCiVtJeFD9Q",
	"+No1ZOd2ZPfUDSTnexr46e2hpuod4dKF50ILMzSnk0OntjEXiZxAa5cT9oqW+LjtTC0DUp2rHDc4r2EJ",
	"GmQ6Io1lled+++gaMiIV9gjmq/mMvav4FqMepVenNICm5szy1ddRDHJu7DWAnNL6c+S4RhdI9mgNXNsF",
	"cPv1AT0+LsUSjH0mVmBGVCWjsRiN9dtRUso6BJq2iV3E5EoaerrieuipFN/t3PS/CLu+4eat8S2AIQZ+",
	"ACOAVAO30As7MMdRBMzzfNsMupIp41YVIsWRObtcOib6IWEw/tuIDLKZM9sUrrNbkedMbUBrkQHDWLyN",
	"QVr9I8tD+GQ7jY3olGin5ysBppNe9KB9ixwNb/YIwpRKxkLpeqTvj4ds6AsllMiO/PoPwKt2lYiTaihs",
	"y+2ybiHoQI19Oo9MohoLLUy5fCaWpGDW9yCORYhjKf5Yih9s3XvU4v2LD1CMdzPvrxwP4CaUjp3xgMyb",
	"iA9K/sL5Hy5vC+vGPewPrh0vuHFJZ82OAQnmoerIYcd1pzwdSKdQsrd93BXhsllkZ4ej38F2jLuulkvx",
	"fojhK+98mSEAOo1WliCz2lj7YnzLXWE84vtZ6jGexLwpZTnOjJCrHGrOOVdj/HGuQWXOe6KPWpsboNwt",
	"0Q2GL0Ic4iC9kl1kim7lbgDQL+CFADuT5SFgP2cOcuUe753KRg6RTExvGzUKpHifXHd6lhldcUfKef/9",
	"dnjq1rWATfY2Ycsdks0N99vkpC7KvMMzvMOtw44eXQsQadLtzyKOAfLn6NLF5DK9TVdnZMc+3X9yn85J",
	"eUdEoDageZ7HGnY+lNrVsbvlwtahwENFCKOxAQ380mDQHxmLF8YjhR0xwo7oYGe/KQSZ0nBqY4Fd54HC",
	"qs2+ak3bfhyWfne820DVfYcPPC4UQ2jfqaE4IlH230zsQ/Zu3rTsjjQnB/w6WHVb3C7DacchgrV6VI63",
	"xFqA6T2xsZDz0MbWMBFvoj0zUt33HswD7UjZDnVlPnNEmyvkpXv5ydC7HdB36+zviY23mvg9FnlCMnFo",
	"6+35B6YRjcH/tG2yFu1P2yfzxO7NWiIUXYE+8SF8ffNM8/StP0t/P73t34BqiTqkW+aJ+rB2mYT39jVY",
	"vR1TGATwayqmETJc/JG7oJDzLTTHfYRcHYDAoWnYwV01j+nHaqv1XVR8V/eg9h30YW0V7c9yAOWwQycf",
	"cPhoh0sfOYB0vyMt4bHnYS7HLYzeOAou+BjGLVsKbSxbKBUx8Pe66RO/WhylPkpZna5EU1QcCYKROl1x",
	"V1jNVto1WJG2mSsrKmPZmm9gxoRM84p4gqGCoVR9w7VQlWmcHqFh5uy81R1MJHECpmS+re9f/t62PGas",
	"Ruwu5iIxf60iXHzJt5hbGrC136gMaPrNWS4KYZlyl7NkVSxA46rkANAuVlpC5ooN/towRWb+Gq/vfa+5",
	"YQXmqMQhvuEi54sc5gwF6HJsTKFL/q6Cpm6xIDyosiyMoQG69xz2PHtpNHKeLh+7TJviMG++BWycXSTD",
	"jrRhWFFj0rL7wrEJZUMXmIwwFj07zYVo+Uy8VO6GYM0yT2lXx5HudM3lCjKG3hlZYNdcMs6WcMsKIStk",
	"F8m05MZgZo8sqSVeF5WWAujUouM2u12DZJVxNkQYVovWs5JOGiyAiQxz+JTnNac8p50s3W7Tvvk+Y5XM",
	"wRi2VZXDR0MKomGlVW9BNsczIQw2Rsxk4awcBqkXqpJjbrbRKFMtDApWWq9cHk9i/O1apGvGNRD73fap",
	"7wzWgq5JoRMZzZu1stR30TKW8wXkKA7HVQM5pFZpQ6c1+nre0FEjZVjl7hWTnjpG4jQ103NYWlZJ2jwy",
	"Y6oQ1kLGsorqSQa04Ln4jdSjiyjJ0QWl7BEI0vQFpLwywAQNI+npupIYhCH+9SixQBhfCzQe6OuWHg2e",
	"dU4D+zQ5QoT5EErqWpfKM6pzcck2T+ZP/s4yRXjjLO0aTsuFtCBRjFVblRnqDVL2V0w/Croo+1e328Rv",
	"vsWTqhzlR0hcUA2tqZziuhrIUo7NbVVt+TBlph/wnqd20icGYrFS0H8eNs+aMaSp6zCoPIW73SCPo07D",
	"7QGv+4be8FaL7LWHdadmIuVrKZUrN7ufmcsweH4V8bPBRu5lBQ2w+ybDtrF9onN4umUI4eO/SWAsL8o9",
	"Yauvo2J07w8ATY+pM8jhPmt5hafXD1lvteMTF+fMWbO0sSadKjJvKhcs+PxF21LH4MR9dGTOrlRZ5XQU",
	"qub31lgo5uw18OwEY4GJX8Qgy/ch4n/JSzLVrjj+FrZ16JJXtddPuQw9t9IrLnGzIhwGByul8ecjk6rS",
	"PXUG+OvGBce0SE67yeY6KNGvktxK0DEpBVV8bpm6laZu0bjnGKyxN1SUPsW13iS7mms9xx1ZUNZhjmci",
	"Les8dVs1JWP6lQlaOj4Q6HSKpmVve77rQd0OF1n4+ABT25TnuRdopuRXtoZwAVggqWOP7GF7ZKnKIop/",
	"Xa1WQJ7iHzc3V7VwELZtAbs8YsYeY4TqXXDfTvztadROHJtjH7U5NvLxpXO2rgouT5rPLwXDTTki+PgO",
	"ZUjeU4wYn7EPHhU8XQsJo0vdrre9BVDQPgB/Q9+xqTSaPoePD1yFaXM3KEq79bEmharEcdQ0nCzI+M7R",
	"axklWZpz7UtD0qmxJ5bUeFGh5QEX9Aanpvd8iGnXp4ta5rFXlDqfsTfJdUXfenmTYAAYUPrgaoPu/4TL",
	"7MSzdO/5h1iPtPn+E5mJSV98QnZBWmlht9doIv1FIeAa9Hll16Mlye5Lp8Eb6F716jKb+qoDvkNUkL91",
	"cYKnlCNikJ4nZ4kFXvzfMhertU1tPhcqqcMA8vsvaITSda1ydgO8SGZJpfHVWl6dtwfBDBUsGfWrqNpB",
	"MSzZz+7c8zfyhgyqhyi4pGOH4Y3PNmDH9+s7ns1RbF/9Cj+GYuZvUFC5SMGfivfEnZc8XQN7On88oOf2",
	"9nbOaXiu9OrUv2tOf7i8eP7j9fOTp/PH87UtcqobCpvjdD0+dYk+v7pMZsmmdtnJ5skCLH9CEi1B8lIk",
	"Z8nf5o/nT9DVc7smZUF1Pt08cbdgiFZ6vAI7cphj7L51syNRdwi0hTS0ouYFWNCGWq/DANtl7q7Eg9sm",
	"tW0+Tcm7L5jUeZKLn4V2NQB3mATnelcBFT29CGj02s+O24xiiUh8fDf7qFhRbjyKFY3eDyvcMAV/L4qq",
	"6NQ2TJXbtorXqbg01ZQxHolC2A4WewOLCLdkc52DNcJGxtFidbXCYdlEBi46HsOrKXPuYtCvFKkTfaS6",
	"Tx8/rq0QuEoVL8vcd5VP/+29ajvftEMAdBaNzFyvDvA9brBvPuKazfnzwVrf8ozVd6Bo0SefYNGfJK/s",
	"mhI9ukjzzdP//QSr3ijFXnK5rel15/EtX5mmJ7Jwt3DuZkmpYucEL2I3wcIL6F2L5cA7xx58aPqtyrYP",
	"oFGO7DYqsLqCu4EuP3mwlWPcyv5syvz4UyjzhZLLXLgM/ovbPnezWAxweivs+sRy85b08IAdNvWuJTqo",
	"5mA5fZyVp3U2tHtnNtcQH3yLDm6efrYtO7x6edzDf749PEv+/knkellX1lxhh9F5pINNyO8Yxd05s0EH",
	"VAcG5Bk9n+yiHXjHRe/MKiZ8NKaJPDEhagNPyf1Hl8Od/vmD0F0B6OfZet98glV/VJa9UJX8UsPPaK78",
	"HXVap+n1d2CPSn1U6i84KHTnD6dUhmJ3fEZKQ8/9pMfa0LE29EetDQUXFY/FoS/IkDmDNb061DNbO5NQ",
	"fxHxAZPP5uMznz7bDJc+Zpd/6gpRs4dGooHDE7y9uyzI8Jpddng0HFnmDxEOj++9Yzz82d3I3ixvr3LX",
	"ad5Rs4+a/QUZdzpEQue3SAvdKYXTBJXCvzH8cJBXa8OUHD0Q4JUxyCuHeUFkplgCGU7lEb/79e7/AwAA",
	"///vA6MX4HAAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
