// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package imagebuilder

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW8bN/L/KgRboO0ferDT4I+rXp2jJHdGk9YXK/cmzgGj3ZGWzS65IWfl6AJ99wMf",
	"9knaldZp4gSoX8VZDjnDefzNUB95pLJcSZRk+OwjN1GCGbg/nwgZC7lebHO0/43RRFrkJJTkM75IkNE2",
	"R6ZWbOkJ2UppRgkykcEa2bIQaTzhI46yyPjsDUfQ6ZaPeAqE/O2IkzuYG9JCrvmIfxhbyvEGtIQMjd3S",
	"EOFZ2N349MIdtBvxuZKx8ILty1ktMY25RmPvyYAZAioMi6pVtWLANBpV6Ait1LlWOWoS6HSRgqGFBmkc",
	"9UJkPSqxdIxEhk4R9fFU7UWnk5XSGRCf8RgIx3YD31fIbsQzNAbWHawuWFJkIMcaIYZliixQViaoOE+6",
	"ztUIpktZF2ypBa6YXx94mFfl4WHXXsVqdXhG6RELXdh7P4fU2H9fy3dS3cpD39iVHw5UHjzwmITuvu8L",
	"oTG2PN1qJXXNSi3/wIgsq0vrvk+s9x4yrNfa/rQMn94XaMgpDqxQBEKi9gFx6FSQi3+jNp1+e3F1GdZY",
	"jCsh0Tg1bvw3jJkPVK9eYWppoHJnyfydJuwatd3ITKKKNLaCbVAT0xiptRT/rU4zjJRjY0PUEBOSUEtI",
	"2QbSAkcMZMwy2DKN9lxWyMYJjsRM2EulkQm5UjOWEOVmNp2uBU3e/c1MhJpGKssKKWg7tdrRYlmQ0mYa",
	"4wbTqRHrMegoEYQRFRqnkIuxE1baS5lJFn9Xhqjp9MV3QnYY7VchYyZ82FtKL2utMvvJ3vrVs+tFlQO8",
	"Wr0GG7aulWkVIeQKtadcaZW5U1DGuRKSvNunAiUxUywzQaZ0EKvnCZuDlIrYElmR2zQQT9ilZHPIMJ2D",
	"wS+uSqs9M7Yq61ZmhgQxEFiFfq9xxWf8u2ldLabBZ6a/Ox29RAKXDnKMTu2oo+jaUreSyMB9nn4/uBsR",
	"FZyhcY0g2/GQD+XlWOQHEmZPEyuBpiqAkZIrsS60j8EyfVaFsB39EWrqqFeWYCUiIGSFwdidEs7vtBJR",
	"2pEXRYZjUuNUbOqaUJ7CnrviM2O5siVpgy7O16jZSqWpusWYLbfMTLNp4qQGslmAz/h/3pyPf3l7cxP/",
	"3xuTJW+/50fy9DEzNoHFbnfUHJcyL+iYMRxBwxT2oiGAPQw5YQVH9Bv01XOLRMoS1jy20xRuZQHrHrQE",
	"68EnaVwLQ3o7TLCSus5dofSUie0Ev70gajEfNTTUuOHxIHohzFGj2XWfkFP7l1qxVl1tZPiHgvllC6Yg",
	"zDqw24sTZqm2DcvWdWLgoDVsH0r1VyrV1q6+UN+tcHp7Hw/63ws6kas9xV6yjtGQkIcVk/pQ8x0ytvIM",
	"v1yeJcXywiT7Qluf6SyOA2rDCZmH52o6maavEjA9187tUilSo59nuVYRGtPs4t4XWKB1GEfhe3mrFf+X",
	"9cIUyUq0ApFiPLD13xPzXyWTve9Pap57K1eVCHsL81qivZXnQcCWlq4DoO3zarvO/OKyBCDew6Paq0Hu",
	"T0XaTr2sYeewlFriVJvDS4w0bKeHVLsRV1XADtsYAnzfBT376rjjLnfdMyzYp2h21y45F1q77FwNFUA2",
	"qlMHVGhk1G4Xb1KUnr6XeA4CuHTm+IJ6Arkc/fhoqeiHz3yqUUaHluZBCzVNKXhbFYPKcz0066jOqLXS",
	"hwI8s5+rYZNYNa7qg7sfFw9LsacMMBhinzooBUPXiHLIGM9f8BYMM4iS/ZggaFoi0E93GOWBFCs09FSs",
	"0fQ4T+zWOm7Ayt2dV8nLND4sjH3WH1T8qoLnTHSboMYD0YRhhpTuMb0h0MPDJVAP1WpX61ghnE5Ma1es",
	"xCW0YbBUBZV9iEaTK2k6MIeFbUIWXZNYyVQO7wtb89+h9D07KSaMKZCBVJSgZi/88X46aJsCjaQFbvzl",
	"JX4gZtBZXqMpUjI9aCXzTd0lYTZXhezRqiyyJWp/WtjBXEpgQvpuRXhXqpQsJP3/45plmAd0a7gx7jng",
	"Xq+1tEwJEIM0ZbnFmIaw0U6wrDDEEtjgiN0mIkqYkFFaxGjcDs/XWL3qQBtpBOoap1qMDlXqhNinN0iv",
	"WmQHam1foSZ2JllufUVHvRFRM5XUCnHyhFcBQ5DlJ3w9NCo2n/ir3KE6xJjip/ASaWq7F7f9LvzWKNGP",
	"s7peC4z1aBlVHtdq06CCQaw+pUxuMRqLH1w9xwm7UnlhW+i40vfWEGYT9gohHiuZbge5q03rS0z/jPlf",
	"Qm5lDN3nO9waF6++WfeOHIF0nWCIdKXXYDt6RxcB4Vpp+98fTaRy/9VgihH9VDpzpxfJYR2NH1B0mUrd",
	"StRdVmq0yUBM3UpTTkD895FNCzeu65taXjeceU33JCG/q38QU2XEoETHVsTWLeoRnevMfzCNiUkY3rQG",
	"McNy/vXxFyg3TtBIhZZhnGAReQRpGgwaK/kDlRQ+YTcs9dlHUD3IMu4w/z8Xi6v6rTKup5lWJCgfvJpx",
	"8fOjzriIkUCkJzGh19jTQPx5pzSTP/fC2ViuxqhO2s80EDn2KppBlAiJtTB7D6RHBBn2Otoy52CPn0PR",
	"1b83FtuPlJH75F66a4nb7r0S2PXsadOQWyozoE9+p2zwya/X9vwJH/4M3PgxQt/efjU+rWOjS5FhmeVa",
	"bYSDJVVlYSGsKhjZp1YnlOkW3K8d+vSgJq7pCIOHrJarXQl40xcHMEZFwtXgW0HJKePKgROzTzn90FQ7",
	"N+ZYqRKLQ+Sgr0W3KZ9xQsj+vkrFOqGI0olQvBTQSfTcrbC5kqRVyhYIGR/xQtut5bS2tfsAFbjuibn2",
	"CXUJBp27ts+e3MiFLa0lRQYS1mhaE7Qa+bqnvTC/cjghTM32fzlgJjeSj3gqIpQ+4MPlLnKIEmSPJmcH",
	"97m9vZ2AW54ovZ6GvWb64nL+7LfrZ+NHk7NJQlnqvEZQao/b01P70hdXl3zEN2Xt45vzJRKcO+SRo4Rc",
	"8Bn/eXI2Ofdvhonz3SnkYro5n7p7uLu6z2uknkeHvheHKkNexoG0pjSOo4YMCbXhszddSNUiMJtelD2X",
	"tIioaoV8HNjqj3HVcHggKjTzkNJFpD3rfYF6W/uXW70Op/NR+P1UB9DcjT6rVC4b90rlVj9NKhswGXwQ",
	"WZG1GknXltYCNTrJVt/cqSORCWpJcRKxdGjLwsqQditjW8U5ZixTGispqwceDzP75Kq6+mMKeusgr7uf",
	"c91HZ2dlFkLfgEOep2HWO/0jIIj6vGFDGfdi6tLcXkP9qw2wx5+RZ/XLiQNeTyBmr/yMwjM9vwemryUU",
	"lLiOyT0TPn70yz1wXSjFXoLclvf1vyQhWLunhzpZuaeAXHUN7OaudW+PoVtYt52xPHnjSdQP0dHQExVv",
	"v4BH+WvXg3rSBe4OfPn8i3Hu0lb8V3Pms/tw5rmSq1R4RPvNhc9u1IUBph9tCt75qHJvcQfx9dR9Hxxf",
	"nrwVX0chwT5S7WHiyoZFM3XVkP55tR1ZX7+CHKseX8f3H98D198UseeqkN9q7egEuv9AGuzXrxDiB69+",
	"8OpvCxF1/c7ntftl1B0cO08h+oYz9tcHZ/cdUH8hXHb/UfwABY9CwWk9KD+WXeq54cFvgO6Sa8J9HjLO",
	"Q8Z5wA33Fv+7EfcDOR9sfmA95db5w4aD35OUYWyYkr2z4RB0DWa7t7v/BQAA//+0iGT22ToAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
