// Package imagebuilder provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package imagebuilder

import (
	"time"
)

// Defines values for BindingType.
const (
	BindingTypeEarly BindingType = "early"
	BindingTypeLate  BindingType = "late"
)

// Defines values for ConditionStatus.
const (
	False   ConditionStatus = "False"
	True    ConditionStatus = "True"
	Unknown ConditionStatus = "Unknown"
)

// Defines values for ImageBuildPhase.
const (
	ImageBuildPhaseBuilding ImageBuildPhase = "building"
	ImageBuildPhaseComplete ImageBuildPhase = "complete"
	ImageBuildPhaseFailed   ImageBuildPhase = "failed"
	ImageBuildPhasePushing  ImageBuildPhase = "pushing"
	ImageBuildPhaseQueued   ImageBuildPhase = "queued"
)

// BindingType The type of binding for the image build.
type BindingType string

// Condition Condition represents a status condition of a resource.
type Condition struct {
	// LastTransitionTime The last time the condition transitioned.
	LastTransitionTime *time.Time `json:"lastTransitionTime,omitempty"`

	// Message A human-readable message for the condition.
	Message *string `json:"message,omitempty"`

	// Reason A brief reason for the condition.
	Reason *string `json:"reason,omitempty"`

	// Status Status of the condition.
	Status ConditionStatus `json:"status"`

	// Type Type of condition.
	Type string `json:"type"`
}

// ConditionStatus Status of the condition.
type ConditionStatus string

// ImageBuild ImageBuild represents a build request for a container image.
type ImageBuild struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
	ApiVersion string `json:"apiVersion"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind string `json:"kind"`

	// Metadata ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
	Metadata ObjectMeta `json:"metadata"`

	// Spec ImageBuildSpec describes the specification for an image build.
	Spec ImageBuildSpec `json:"spec"`

	// Status ImageBuildStatus represents the current status of an ImageBuild.
	Status *ImageBuildStatus `json:"status,omitempty"`
}

// ImageBuildBinding ImageBuildBinding specifies binding configuration for the build.
type ImageBuildBinding struct {
	// Cert Certificate used for binding.
	Cert *string `json:"cert,omitempty"`

	// Ttl Time-to-live for the binding. Format: positive integer followed by s/m/h.
	Ttl *string `json:"ttl,omitempty"`

	// Type The type of binding for the image build.
	Type *BindingType `json:"type,omitempty"`
}

// ImageBuildInput ImageBuildInput specifies the source image for the build.
type ImageBuildInput struct {
	// ImageName The name of the source image.
	ImageName string `json:"imageName"`

	// ImageTag The tag of the source image.
	ImageTag string `json:"imageTag"`

	// RegistryName The name of the registry resource containing the source image.
	RegistryName string `json:"registryName"`
}

// ImageBuildList ImageBuildList is a list of ImageBuild resources.
type ImageBuildList struct {
	// ApiVersion APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources.
	ApiVersion string `json:"apiVersion"`

	// Items List of ImageBuild resources.
	Items []ImageBuild `json:"items"`

	// Kind Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds.
	Kind string `json:"kind"`

	// Metadata ListMeta is metadata about a list response.
	Metadata ListMeta `json:"metadata"`
}

// ImageBuildOutput ImageBuildOutput specifies the destination for the built image.
type ImageBuildOutput struct {
	// ImageName The name of the output image.
	ImageName string `json:"imageName"`

	// RegistryName The name of the registry resource to push the built image to.
	RegistryName string `json:"registryName"`

	// Tag The tag of the output image.
	Tag string `json:"tag"`
}

// ImageBuildPhase The phase of the image build process.
type ImageBuildPhase string

// ImageBuildSpec ImageBuildSpec describes the specification for an image build.
type ImageBuildSpec struct {
	// Binding ImageBuildBinding specifies binding configuration for the build.
	Binding *ImageBuildBinding `json:"binding,omitempty"`

	// Input ImageBuildInput specifies the source image for the build.
	Input ImageBuildInput `json:"input"`

	// Output ImageBuildOutput specifies the destination for the built image.
	Output ImageBuildOutput `json:"output"`
}

// ImageBuildStatus ImageBuildStatus represents the current status of an ImageBuild.
type ImageBuildStatus struct {
	// Architecture The architecture of the built image.
	Architecture *string `json:"architecture,omitempty"`

	// CompletedAt The time the build completed.
	CompletedAt *time.Time `json:"completedAt,omitempty"`

	// Conditions Current conditions of the ImageBuild.
	Conditions *[]Condition `json:"conditions,omitempty"`

	// Error Error message if the build failed.
	Error *string `json:"error,omitempty"`

	// ImageName The name of the built image.
	ImageName *string `json:"imageName,omitempty"`

	// ImageTag The tag of the built image.
	ImageTag *string `json:"imageTag,omitempty"`

	// LastSeen The last time the build was seen (heartbeat).
	LastSeen *time.Time `json:"lastSeen,omitempty"`

	// ManifestDigest The digest of the built image manifest.
	ManifestDigest *string `json:"manifestDigest,omitempty"`

	// Phase The phase of the image build process.
	Phase *ImageBuildPhase `json:"phase,omitempty"`

	// RegistryName The registry name where the built image is stored.
	RegistryName *string `json:"registryName,omitempty"`

	// StartedAt The time the build started.
	StartedAt *time.Time `json:"startedAt,omitempty"`
}

// ListMeta ListMeta is metadata about a list response.
type ListMeta struct {
	// Continue An opaque token used to issue another List request and retrieve the next set of results.
	Continue *string `json:"continue,omitempty"`

	// RemainingItemCount The number of remaining items in the list.
	RemainingItemCount *int64 `json:"remainingItemCount,omitempty"`
}

// ObjectMeta ObjectMeta is metadata that all persisted resources must have, which includes all objects users must create.
type ObjectMeta struct {
	// Annotations Properties set by the service.
	Annotations *map[string]string `json:"annotations,omitempty"`

	// CreationTimestamp The time the object was created.
	CreationTimestamp *time.Time `json:"creationTimestamp,omitempty"`

	// DeletionTimestamp The time the object will be deleted.
	DeletionTimestamp *time.Time `json:"deletionTimestamp,omitempty"`

	// Generation A sequence number representing a specific generation of the desired state. Populated by the system. Read-only.
	Generation *int64 `json:"generation,omitempty"`

	// Labels Map of string keys and values that can be used to organize and categorize (scope and select) objects.
	Labels *map[string]string `json:"labels,omitempty"`

	// Name The name of the object.
	Name *string `json:"name,omitempty"`

	// Owner A resource that owns this resource, in "kind/name" format.
	Owner *string `json:"owner,omitempty"`

	// ResourceVersion An opaque string that identifies the server's internal version of an object.
	ResourceVersion *string `json:"resourceVersion,omitempty"`
}

// Status Status is a return value for calls that don't return other objects.
type Status struct {
	// ApiVersion APIVersion defines the versioned schema.
	ApiVersion *string `json:"apiVersion,omitempty"`

	// Code HTTP status code for the operation.
	Code *int32 `json:"code,omitempty"`

	// Details StatusDetails provides additional details about a status.
	Details *StatusDetails `json:"details,omitempty"`

	// Kind Kind is a string value representing the REST resource.
	Kind *string `json:"kind,omitempty"`

	// Message A human-readable description of the status.
	Message *string `json:"message,omitempty"`

	// Metadata ListMeta is metadata about a list response.
	Metadata *ListMeta `json:"metadata,omitempty"`

	// Reason A machine-readable reason for the status.
	Reason *string `json:"reason,omitempty"`

	// Status Status of the operation.
	Status *string `json:"status,omitempty"`
}

// StatusCause StatusCause represents a cause of a status.
type StatusCause struct {
	// Field The field that caused the status.
	Field *string `json:"field,omitempty"`

	// Message A human-readable message for the cause.
	Message *string `json:"message,omitempty"`

	// Type The type of cause.
	Type *string `json:"type,omitempty"`
}

// StatusDetails StatusDetails provides additional details about a status.
type StatusDetails struct {
	// Causes The causes of the status.
	Causes *[]StatusCause `json:"causes,omitempty"`

	// Kind The kind of resource associated with the status.
	Kind *string `json:"kind,omitempty"`

	// Name The name of the resource associated with the status.
	Name *string `json:"name,omitempty"`
}

// ListImageBuildsParams defines parameters for ListImageBuilds.
type ListImageBuildsParams struct {
	// LabelSelector A selector to restrict the list of returned objects by their labels.
	LabelSelector *string `form:"labelSelector,omitempty" json:"labelSelector,omitempty"`

	// FieldSelector A selector to restrict the list of returned objects by their fields.
	FieldSelector *string `form:"fieldSelector,omitempty" json:"fieldSelector,omitempty"`

	// Limit The maximum number of results returned in the list response.
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Continue An optional parameter to query more results from the server.
	Continue *string `form:"continue,omitempty" json:"continue,omitempty"`
}

// CreateImageBuildJSONRequestBody defines body for CreateImageBuild for application/json ContentType.
type CreateImageBuildJSONRequestBody = ImageBuild

// ReplaceImageBuildJSONRequestBody defines body for ReplaceImageBuild for application/json ContentType.
type ReplaceImageBuildJSONRequestBody = ImageBuild

// ReplaceImageBuildStatusJSONRequestBody defines body for ReplaceImageBuildStatus for application/json ContentType.
type ReplaceImageBuildStatusJSONRequestBody = ImageBuild
