{{- if .Values.certManager.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: flightctl-api-cert
  namespace: {{ .Release.Namespace }}
spec:
  secretName: flightctl-api-tls
  issuerRef:
    name: flightctl-issuer
    kind: ClusterIssuer
  commonName: flightctl-api
  dnsNames:
    - flightctl-api
    - flightctl-api.$(NAMESPACE)
    - flightctl-api.$(NAMESPACE).svc
    - flightctl-api.$(NAMESPACE).svc.cluster.local
  duration: 2160h # 90 days
  renewBefore: 360h # 15 days
{{- end }} 