{{- $userPassword := (include "flightctl.generatePassword" .) -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-db-app-secret
  namespace: {{ .Release.Namespace }}
  labels:
    flightctl.service: flightctl-db-app
    security.level: application
type: Opaque
data:
  user: {{ .Values.db.user | b64enc }}
  userPassword: {{ if .Values.db.userPassword }}{{ .Values.db.userPassword | b64enc }}{{ else }}{{ $userPassword }}{{ end }}
{{- if .Values.global.internalNamespace }}
---
apiVersion: v1
kind: Secret
metadata:
  name: flightctl-db-app-secret
  namespace: {{ .Values.global.internalNamespace }}
  labels:
    flightctl.service: flightctl-db-app
    security.level: application
type: Opaque
data:
  user: {{ .Values.db.user | b64enc }}
  userPassword: {{ if .Values.db.userPassword }}{{ .Values.db.userPassword | b64enc }}{{ else }}{{ $userPassword }}{{ end }}
{{- end }}