global:
  nodePorts:
    registry: ""
    gitserver: ""
    prometheus: ""
    jaegerUi: ""
  imagePullPolicy: IfNotPresent
  imagePullSecretName: ""
  internalNamespace: ""
  registryIP: ""  # IP address for registry certificate
registry:
  image: quay.io/flightctl/e2eregistry:2
  route: true
  hostName: ""
gitserver:
  image: localhost/git-server:latest
jaeger:
  enabled: false
  image:
    image: jaegertracing/all-in-one
    tag: "1.35"
    pullPolicy: ""
  storageType: memory
  maxTraces: 50000
  otlpEnabled: true
  logLevel: info
  resources:
    requests:
      memory: "128Mi"
      cpu: "50m"
    limits:
      memory: "512Mi"
      cpu: "200m"

## @section Certificate Management
## @description Certificate management using cert-manager (required)
## @descriptionEnd

certManager:
  enabled: true
