name: "Smoke tests"

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'release-*'
  pull_request:

permissions:
  contents: read
  pull-requests: read

env:
  # Enable BuildKit for cache mounts
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:
  # This line defines a job with the ID `check-links` that is stored within the `jobs` key.
  smoke:
    runs-on: "ubuntu-24.04"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            notdocs:
              - '!.spelling'
              - '!README.md'
              - '!docs/**'

      - name: Setup all dependencies
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        uses: ./.github/actions/setup-dependencies

      - name: Cache Go modules
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache DNF packages
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/dnf
            /var/lib/dnf
          key: ${{ runner.os }}-dnf-smoke
          restore-keys: |
            ${{ runner.os }}-dnf-

      - name: Cache bootc-image-builder
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        uses: actions/cache@v4
        with:
          path: |
            bin/dnf-cache
            bin/osbuild-cache
          key: ${{ runner.os }}-bootc-cache-smoke-${{ hashFiles('test/scripts/agent-images/Containerfile-e2e-base.local') }}
          restore-keys: |
            ${{ runner.os }}-bootc-cache-smoke-

      - name: Create cluster
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: make cluster

      - name: Deploy
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: DISABLE_FIPS="true" GITHUB_ACTIONS=false make deploy

      - name: Check
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: |
          kubectl get pods --all-namespaces

      - name: Apply device
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: bin/flightctl apply -f examples/device.yaml

      - name: Apply fleet
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: bin/flightctl apply -f examples/fleet.yaml

      - name: Apply enrollmentrequest
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: bin/flightctl apply -f examples/enrollmentrequest.yaml

      - name: Apply repository
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: bin/flightctl apply -f examples/repository-flightctl.yaml

      - name: Apply resourcesync
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: bin/flightctl apply -f examples/resourcesync.yaml

      - name: Build the simulator
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: DISABLE_FIPS="true" make build-devicesimulator

      - name: Simulator run
        if: ${{ steps.filter.outputs.notdocs == 'true' }}
        run: bin/devicesimulator --config bin/agent/etc/flightctl/config.yaml --count 1 --stop-after 1m

      - name: Collect and Upload Logs
        if: always() && steps.filter.outputs.notdocs == 'true'
        uses: ./.github/actions/collect-logs
        with:
          namespace-external: 'flightctl-external'
          namespace-internal: 'flightctl-internal'
          log-directory: 'smoke-logs'
