name: Push E2E containers

on:
  push:
    branches:
      - main

env:
  QUAY_ORG: quay.io/flightctl
  # Enable BuildKit for cache mounts
  DOCKER_BUILDKIT: 1
  BUILDKIT_PROGRESS: plain

jobs:



  publish-flightctl-e2e-containers:
    strategy:
      matrix:
        image: 
          - {name: 'git-server', containerfile: 'test/scripts/agent-images/Containerfile.git-server'},
          - {name: 'sleep-app', containerfile: 'test/scripts/agent-images/Containerfile.sleep-app'}
        
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: |
            image=moby/buildkit:v0.12.4

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Cache DNF packages
        uses: actions/cache@v4
        with:
          path: |
            /var/cache/dnf
            /var/lib/dnf
          key: ${{ runner.os }}-dnf-${{ matrix.image }}
          restore-keys: |
            ${{ runner.os }}-dnf-

      - name: Build
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ matrix.image.name }}
          tags: cache
          labels: |
            org.flightctl.flightctl-${{ matrix.image.name }}.github.repository=${{ github.repository }}
            org.flightctl.flightctl-${{ matrix.image.name }}.github.actor=${{ github.actor }}
            org.flightctl.flightctl-${{ matrix.image.name }}.github.run_id=${{ github.run_id }}
            org.flightctl.flightctl-${{ matrix.image.name }}.github.sha=${{ github.sha }}
            org.flightctl.flightctl-${{ matrix.image.name }}.github.ref_name=${{ github.ref_name }}
          extra-args: |
            --ulimit nofile=10000:10000
            --mount=type=cache,target=/opt/app-root/src/go/pkg/mod
            --mount=type=cache,target=/opt/app-root/src/.cache/go-build
            --mount=type=cache,target=/var/cache/dnf
            --mount=type=cache,target=/var/lib/dnf
          containerfiles: ${{ matrix.image.containerfile }}
          context: .

      - name: Push to Quay.io
        id: push
        uses: redhat-actions/push-to-registry@v2.7
        with:
          image: ${{ matrix.image.name }}
          tags: cache
          registry: ${{ env.QUAY_ORG }}
          username: ${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_USERNAME }}
          password: ${{ secrets.QUAY_FLIGHTCTL_INFRA_ROBOT_PASSWORD }}
